// SPDX-License-Identifier: GPL-3.0-or-later
//
// Export every function in the current program as decompiled C, one file per
// function, plus a JSON manifest. Run as a Ghidra headless -postScript.
//
// Output is REGENERABLE and must never be hand-edited: hand-written
// replacements live in patched/ and shadow these at link time via weak-symbol
// aliasing. Each emitted file records the source address and a content hash so a
// later regeneration can tell what actually changed.
//
// Usage (headless):
//   analyzeHeadless <proj_dir> <proj> -process default.xbe \
//       -scriptPath tools/ghidra -postScript ExportDecompiledC.java <outdir>
//
//@category TSFP
//@author tsfp-decomp

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileOptions;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionManager;

public class ExportDecompiledC extends GhidraScript {

    /** Decompiler timeout per function, seconds. Long enough for the worst cases. */
    private static final int TIMEOUT_SECONDS = 120;

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length < 1) {
            println("ERROR: expected an output directory argument");
            return;
        }
        Path outDir = Path.of(args[0]);
        Path srcDir = outDir.resolve("src");
        Files.createDirectories(srcDir);

        DecompInterface decompiler = new DecompInterface();
        decompiler.setOptions(new DecompileOptions());
        if (!decompiler.openProgram(currentProgram)) {
            println("ERROR: could not open program in the decompiler: "
                    + decompiler.getLastMessage());
            return;
        }

        FunctionManager functions = currentProgram.getFunctionManager();
        int total = functions.getFunctionCount();
        println("exporting " + total + " functions to " + outDir);

        List<String> manifest = new ArrayList<>();
        int done = 0;
        int failed = 0;

        for (Function function : functions.getFunctions(true)) {
            if (monitor.isCancelled()) {
                break;
            }
            String address = function.getEntryPoint().toString();
            String name = function.getName();

            DecompileResults results =
                    decompiler.decompileFunction(function, TIMEOUT_SECONDS, monitor);
            String body;
            boolean ok = results != null && results.decompileCompleted();
            if (ok) {
                body = results.getDecompiledFunction().getC();
            } else {
                failed++;
                String reason = results == null ? "no result" : results.getErrorMessage();
                body = "/* DECOMPILATION FAILED: " + escape(reason) + " */\n";
            }

            String header = "/* SPDX-License-Identifier: GPL-3.0-or-later\n"
                    + " *\n"
                    + " * GENERATED by tools/ghidra/ExportDecompiledC.java. Do not edit.\n"
                    + " * Hand-written replacements belong in patched/ and shadow this at\n"
                    + " * link time via weak-symbol aliasing.\n"
                    + " *\n"
                    + " * function : " + name + "\n"
                    + " * address  : " + address + "\n"
                    + " * size     : " + function.getBody().getNumAddresses() + "\n"
                    + " */\n\n";
            String contents = header + body;
            String digest = sha256(contents);

            Path target = srcDir.resolve("sub_" + address + ".c");
            Files.writeString(target, contents, StandardCharsets.UTF_8);

            manifest.add("  {"
                    + "\"address\": \"" + address + "\", "
                    + "\"name\": \"" + escape(name) + "\", "
                    + "\"size\": " + function.getBody().getNumAddresses() + ", "
                    + "\"signature\": \"" + escape(function.getSignature().getPrototypeString())
                    + "\", "
                    + "\"thunk\": " + function.isThunk() + ", "
                    + "\"decompiled\": " + ok + ", "
                    + "\"file\": \"src/" + target.getFileName() + "\", "
                    + "\"sha256\": \"" + digest + "\"}");

            done++;
            if (done % 500 == 0) {
                println("  " + done + "/" + total + " (" + failed + " failed)");
            }
        }

        decompiler.dispose();
        writeManifest(outDir.resolve("manifest.json"), manifest);
        println("done: " + done + " exported, " + failed + " failed to decompile");
    }

    private void writeManifest(Path path, List<String> entries) throws IOException {
        try (PrintWriter writer = new PrintWriter(
                Files.newBufferedWriter(path, StandardCharsets.UTF_8))) {
            writer.println("{");
            writer.println("  \"program\": \"" + escape(currentProgram.getName()) + "\",");
            writer.println("  \"language\": \""
                    + escape(currentProgram.getLanguageID().getIdAsString()) + "\",");
            writer.println("  \"image_base\": \"" + currentProgram.getImageBase() + "\",");
            writer.println("  \"function_count\": " + entries.size() + ",");
            writer.println("  \"functions\": [");
            writer.println(String.join(",\n", entries));
            writer.println("  ]");
            writer.println("}");
        }
    }

    private static String escape(String value) {
        if (value == null) {
            return "";
        }
        return value.replace("\\", "\\\\").replace("\"", "\\\"")
                .replace("\n", " ").replace("\r", " ").replace("\t", " ");
    }

    private static String sha256(String value) throws Exception {
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        byte[] hash = digest.digest(value.getBytes(StandardCharsets.UTF_8));
        StringBuilder out = new StringBuilder(hash.length * 2);
        for (byte b : hash) {
            out.append(Character.forDigit((b >> 4) & 0xF, 16));
            out.append(Character.forDigit(b & 0xF, 16));
        }
        return out.toString();
    }

    @SuppressWarnings("unused")
    private static List<String> sorted(List<String> input) {
        List<String> copy = new ArrayList<>(input);
        Collections.sort(copy);
        return copy;
    }

    @SuppressWarnings("unused")
    private static File unused() {
        return null;
    }
}
