/* SPDX-License-Identifier: GPL-3.0-or-later */
/* T1781 synthesized EXACT roots (47):
 * 0x00012020, 0x00017A80, 0x00022950, 0x00024E40, 0x00038F30, 0x00038F50, 0x00038F80,
 * 0x0003ECA0, 0x0003F5E0, 0x000427B0, 0x00042C30, 0x000431C0, 0x00055EC0, 0x00058270,
 * 0x00059F10, 0x00059F50, 0x000696D0, 0x000697D0, 0x00069930, 0x0006B3D0, 0x00071E60,
 * 0x000802C0, 0x00080AD0, 0x00081C20, 0x000873F0, 0x000877C0, 0x00087840, 0x000879A0,
 * 0x000879C0, 0x000879E0, 0x00087A40, 0x0009A390, 0x0009A4C0, 0x0009A570, 0x0009C520,
 * 0x0009C550, 0x0009E610, 0x000B0590, 0x000C2E30, 0x000C4560, 0x000D0CA0, 0x000D6920,
 * 0x000D7550, 0x000DC270, 0x000DCA40, 0x000DCA70, 0x000E0250
 * Generated by docs/data/t1781-synth/assemble.py from the frozen drafts in
 * docs/data/t1781-synth/drafts. Do not edit by hand, rerun the tool with --check. */
#include "game_replace.h"
extern __thread uint32_t g_ebx, g_edi, g_ebp;
extern __thread int g_df;
/* Volatile byte reads retain original dead loads and do not assume alignment. */
static inline uint32_t synth_read32(uint32_t a)
{
    volatile const uint8_t *p = (volatile const uint8_t *)game_host_ptr(a);
    uint32_t v = p[0]; v |= (uint32_t)p[1] << 8;
    v |= (uint32_t)p[2] << 16; v |= (uint32_t)p[3] << 24;
    return v;
}
static inline void synth_push(uint32_t v)
{
    g_esp -= 4u; guest_write32(g_esp, v);
}
static inline uint32_t synth_pop(void)
{
    uint32_t v = synth_read32(g_esp); g_esp += 4u; return v;
}
static inline void synth_fill(void)
{
    const uint32_t step = g_df != 0 ? (uint32_t)-4 : 4u;
    while (g_ecx != 0u) {
        guest_write32(g_edi, g_eax); g_edi += step; --g_ecx;
    }
}
static inline void synth_copy(void)
{
    const uint32_t step = g_df != 0 ? (uint32_t)-4 : 4u;
    while (g_ecx != 0u) {
        uint32_t v = synth_read32(g_esi); guest_write32(g_edi, v);
        g_esi += step; g_edi += step; --g_ecx;
    }
}
static inline uint8_t synth_read8(uint32_t a)
{
    return *(volatile const uint8_t *)game_host_ptr(a);
}
static inline uint16_t synth_read16(uint32_t a)
{
    volatile const uint8_t *p = (volatile const uint8_t *)game_host_ptr(a);
    uint16_t v = p[0]; return (uint16_t)(v | ((uint16_t)p[1] << 8));
}
static inline void synth_write16(uint32_t a, uint16_t v)
{
    memcpy(game_host_ptr(a), &v, sizeof v);
}

/* 0x00012020 game_stream_push_dword3 */
GAME_REPLACE_EXACT(00012020, cdecl, 1, u32, game_stream_push_dword3)
{
    g_edx = synth_read32(0x55F974u);
    g_eax = synth_read32(g_esp + 4u);
    g_ecx = synth_read32(g_eax);
    guest_write32(g_edx, g_ecx);
    g_ecx = synth_read32(0x55F974u) + 4u;
    guest_write32(0x55F974u, g_ecx);
    g_edx = synth_read32(g_eax + 4u);
    guest_write32(g_ecx, g_edx);
    g_ecx = synth_read32(0x55F974u) + 4u;
    guest_write32(0x55F974u, g_ecx);
    g_eax = synth_read32(g_eax + 8u);
    guest_write32(g_ecx, g_eax);
    guest_write32(0x55F974u, synth_read32(0x55F974u) + 4u);
}

/* 0x00017A80 game_selected_buffer_pair_initialize_current_records */
GAME_REPLACE_EXACT(00017A80, cdecl, 3, u32, game_selected_buffer_pair_initialize_current_records)
{
    synth_push(g_esi);
    g_esi = synth_read32(0x54E564u);
    g_eax = synth_read32(4u * g_esi + 0x54EEA4u);
    g_edx = 0u;
    guest_write32(0x54EF0Cu, g_edx);
    if ((int32_t)g_eax >= 0x44) { g_eax = 0u; g_esi = synth_pop(); return; }
    g_ecx = g_eax;
    g_eax = (g_ecx + 8u * g_ecx) << 4;
    g_ecx *= 0x1Cu;
    synth_push(g_edi);
    g_edi = synth_read32(4u * g_esi + 0x54EEC8u);
    g_eax += g_edi;
    g_edi = synth_read32(4u * g_esi + 0x54EEE8u);
    g_esi = synth_read32(g_esp + 12u); guest_write32(g_ecx + g_edi, g_esi);
    g_esi = synth_read32(g_esp + 16u); g_ecx += g_edi;
    guest_write32(g_ecx + 4u, g_esi);
    g_esi = synth_read32(g_esp + 20u); guest_write32(g_ecx + 8u, g_esi);
    guest_write32(g_ecx + 12u, UINT32_MAX);
    guest_write32(g_ecx + 16u, g_edx); guest_write32(g_ecx + 20u, g_edx);
    guest_write32(g_ecx + 24u, g_edx);
    g_edi = synth_pop();
    for (uint32_t offset = 12u; offset <= 0x8Cu; offset += 16u)
        guest_write32(g_eax + offset, g_edx);
    g_eax = 1u; g_esi = synth_pop();
}

/* 0x00022950 game_global_563158_equals_word_at_global_56311c_plus4 */
GAME_REPLACE_EXACT(00022950, cdecl, 0, u32, game_global_563158_equals_word_at_global_56311c_plus4)
{
    g_ecx = synth_read32(0x56311Cu); g_edx = synth_read32(0x563158u);
    synth_push(g_esi); g_esi = synth_read32(g_ecx + 4u);
    g_eax = (g_edx == g_esi); g_esi = synth_pop();
}

/* 0x00024E40 game_memory_unit_slot_get_field_0x4 */
GAME_REPLACE_EXACT(00024E40, cdecl, 1, u32, game_memory_unit_slot_get_field_0x4)
{
    g_eax = synth_read32(g_esp + 4u);
    g_eax = synth_read32(48u * g_eax + 0x5655B4u);
}

/* 0x00038F30 game_messenger_slot_clear */
GAME_REPLACE_EXACT(00038F30, cdecl, 1, u32, game_messenger_slot_clear)
{
    g_edx = synth_read32(0x68C6FCu); synth_push(g_edi);
    g_edi = synth_read32(g_esp + 8u) * 0x1A0u + g_edx;
    g_ecx = 0x68u; g_eax = 0u; synth_fill(); g_edi = synth_pop();
}

/* 0x00038F50 game_messenger_slot_copy_out */
GAME_REPLACE_EXACT(00038F50, cdecl, 2, u32, game_messenger_slot_copy_out)
{
    g_ecx = synth_read32(0x68C6FCu); synth_push(g_esi);
    g_esi = synth_read32(g_esp + 12u) * 0x1A0u; synth_push(g_edi);
    g_edi = synth_read32(g_esp + 12u); g_esi += g_ecx;
    g_ecx = 0x68u; synth_copy(); g_edi = synth_pop(); g_esi = synth_pop();
}

/* 0x00038F80 game_slot_count_active_bit0 */
GAME_REPLACE_EXACT(00038F80, cdecl, 0, u32, game_slot_count_active_bit0)
{
    g_ecx = synth_read32(0x68C6FCu); synth_push(g_esi);
    g_eax = 0u; g_ecx += 0x31Fu; g_esi = 4u;
    g_edx = (g_edx & 0xFFFFFF00u) | 1u;
    do {
        if (synth_read8(g_ecx - 0x1A0u) & (uint8_t)g_edx) ++g_eax;
        if (synth_read8(g_ecx) & (uint8_t)g_edx) ++g_eax;
        if (synth_read8(g_ecx + 0x1A0u) & (uint8_t)g_edx) ++g_eax;
        if (synth_read8(g_ecx + 0x340u) & (uint8_t)g_edx) ++g_eax;
        if (synth_read8(g_ecx + 0x4E0u) & (uint8_t)g_edx) ++g_eax;
        g_ecx += 0x820u; --g_esi;
    } while (g_esi != 0u);
    g_esi = synth_pop();
}

/* 0x0003ECA0 game_pool_6b83c8_allocate_locked_block_from_cursor */
GAME_REPLACE_EXACT(0003ECA0, cdecl, 1, u32, game_pool_6b83c8_allocate_locked_block_from_cursor)
{
    g_eax = synth_read32(g_esp + 4u); g_ecx = synth_read32(0x6B83CCu);
    g_edx = synth_read32(g_ecx + 4u); g_eax = (g_eax + 0x5Fu) & 0xFFFFFFC0u;
    synth_push(g_esi); g_esi = g_eax + 0x20u;
    if (g_esi > g_edx) { g_eax = 0u; g_esi = synth_pop(); return; }
    guest_write32(g_ecx + 4u, g_eax); guest_write32(g_ecx, 2u);
    synth_push(g_ebx); g_esi = 0u;
    guest_write32(g_ecx + 12u, g_esi); guest_write32(g_ecx + 16u, g_esi);
    guest_write32(g_ecx + 8u, g_esi);
    guest_write32(0x6B83D0u, synth_read32(0x6B83D0u) + g_eax);
    guest_write32(0x6B83C0u, synth_read32(0x6B83C0u) - g_eax);
    g_ebx = synth_read32(0x6B83C4u); synth_push(g_edi); g_edi = g_ecx;
    g_ecx = synth_read32(0x6B83CCu) + g_eax; g_ebx -= g_eax;
    guest_write32(0x6B83C4u, g_ebx); g_edx -= g_eax;
    guest_write32(0x6B83CCu, g_ecx); g_eax = g_edi + 0x20u;
    g_edi = synth_pop(); g_ebx = synth_pop();
    guest_write32(g_ecx, g_esi); guest_write32(g_ecx + 8u, g_esi);
    guest_write32(g_ecx + 12u, g_esi); guest_write32(g_ecx + 16u, g_esi);
    guest_write32(g_ecx + 4u, g_edx); g_esi = synth_pop();
}

/* 0x0003F5E0 game_table_6b83e4_entry_get_field_0x28 */
GAME_REPLACE_EXACT(0003F5E0, cdecl, 2, u32, game_table_6b83e4_entry_get_field_0x28)
{
    g_eax = synth_read32(g_esp + 8u); g_ecx = synth_read32(g_esp + 4u);
    g_edx = 48u * g_eax; g_ecx <<= 4;
    g_eax = synth_read32(g_ecx + 0x6B83E4u);
    g_eax = synth_read32(g_eax + g_edx + 0x28u);
}

/* 0x000427B0 game_input_pad_current_button_state_by_pad_index_zero_when_6b9888_set */
GAME_REPLACE_EXACT(000427B0, cdecl, 1, u32, game_input_pad_current_button_state_by_pad_index_zero_when_6b9888_set)
{
    g_eax = synth_read32(0x6B9888u);
    if (g_eax != 0u) { g_eax = 0u; return; }
    g_eax = synth_read32(0x76B0FCu);
    if (g_eax != 0u) {
        g_eax = synth_read32(g_esp + 4u) * 0x3Cu;
        g_eax = synth_read32(g_eax + 0x6B94D8u); return;
    }
    g_ecx = synth_read32(g_esp + 4u);
    g_edx = synth_read32(4u * g_ecx + 0x6B93C0u) * 0x3Cu;
    g_eax = synth_read32(g_edx + 0x6B93E0u);
}

/* 0x00042C30 game_input_pad_get_field_0x10_direct */
GAME_REPLACE_EXACT(00042C30, cdecl, 1, u32, game_input_pad_get_field_0x10_direct)
{
    g_eax = synth_read32(0x6B9888u);
    if (g_eax != 0u) { g_eax = 0u; return; }
    g_eax = synth_read32(g_esp + 4u) * 0x3Cu;
    g_eax = synth_read32(g_eax + 0x6B93E0u);
}

/* 0x000431C0 game_input_pad_map_is_bit_set */
GAME_REPLACE_EXACT(000431C0, cdecl, 1, u32, game_input_pad_map_is_bit_set)
{
    g_ecx = synth_read32(g_esp + 4u);
    g_ecx = synth_read32(4u * g_ecx + 0x6B93C0u);
    g_edx = synth_read16(0x7E7240u);
    g_eax = ((1u << (g_ecx & 31u)) & g_edx) != 0u;
}

/* 0x00055EC0 game_global_7e71c8_swap_with_6d6058 */
GAME_REPLACE_EXACT(00055EC0, cdecl, 0, u32, game_global_7e71c8_swap_with_6d6058)
{
    g_eax = synth_read32(0x7E71C8u); g_esp -= 0x44u;
    synth_push(g_esi); synth_push(g_edi);
    g_ecx = 0x11u; g_esi = g_eax; g_edi = g_esp + 8u; synth_copy();
    g_ecx = 0x11u; g_esi = 0x6D6058u; g_edi = g_eax; synth_copy();
    g_ecx = 0x11u; g_esi = g_esp + 8u; g_edi = 0x6D6058u; synth_copy();
    g_edi = synth_pop(); g_esi = synth_pop(); g_esp += 0x44u;
}

/* 0x00058270 game_table_7e3954_get_by_mapped_index */
GAME_REPLACE_EXACT(00058270, cdecl, 1, u32, game_table_7e3954_get_by_mapped_index)
{
    g_eax = synth_read32(g_esp + 4u);
    g_eax = (g_eax & 0xFFFF0000u) | synth_read16(2u * g_eax + 0x7E03C0u);
    if ((int16_t)g_eax < 0) { g_eax = 0u; return; }
    g_edx = synth_read32(0x7E3954u); g_ecx = (uint32_t)(int32_t)(int16_t)g_eax;
    g_eax = synth_read32(g_edx + 4u * g_ecx);
}

/* 0x00059F10 game_anim_obj_0xd8_flag_mask_test */
GAME_REPLACE_EXACT(00059F10, cdecl, 3, u32, game_anim_obj_0xd8_flag_mask_test)
{
    g_eax = synth_read32(g_esp + 4u); g_ecx = synth_read32(g_eax + 4u);
    g_ecx = synth_read32(g_ecx + 0xD8u); g_edx = synth_read32(0x7E3954u);
    if (synth_read32(g_edx + 4u * g_ecx) == 0u) { g_eax = 0u; return; }
    g_eax = synth_read32(8u * g_ecx + 0x7DE660u); g_edx = synth_read32(g_esp + 8u);
    g_ecx = synth_read32(8u * g_ecx + 0x7DE664u); g_eax &= g_edx;
    g_ecx &= synth_read32(g_esp + 12u); g_eax = (g_eax | g_ecx) != 0u;
}

/* 0x00059F50 game_anim_obj_0x130_flag_mask_test */
GAME_REPLACE_EXACT(00059F50, cdecl, 3, u32, game_anim_obj_0x130_flag_mask_test)
{
    g_eax = synth_read32(g_esp + 4u); g_ecx = synth_read32(g_eax + 4u);
    g_ecx = synth_read32(g_ecx + 0x130u); g_edx = synth_read32(0x7E3954u);
    if (synth_read32(g_edx + 4u * g_ecx) == 0u) { g_eax = 0u; return; }
    g_eax = synth_read32(8u * g_ecx + 0x7DE660u); g_edx = synth_read32(g_esp + 8u);
    g_ecx = synth_read32(8u * g_ecx + 0x7DE664u); g_eax &= g_edx;
    g_ecx &= synth_read32(g_esp + 12u); g_eax = (g_eax | g_ecx) != 0u;
}

/* 0x000696D0 game_slot_7bedc0_is_active */
GAME_REPLACE_EXACT(000696D0, cdecl, 1, u32, game_slot_7bedc0_is_active)
{
    g_eax = synth_read32(g_esp + 4u) * 0x1F54u;
    g_edx = synth_read32(g_eax + 0x7BEDC0u); g_ecx = (g_edx != 0u); g_eax = g_ecx;
}

/* 0x000697D0 game_table_7bedc0_entry_set_fields_0x24_0x28_and_clear_0x34_by_index */
GAME_REPLACE_EXACT(000697D0, cdecl, 3, u32, game_table_7bedc0_entry_set_fields_0x24_0x28_and_clear_0x34_by_index)
{
    g_eax = synth_read32(g_esp + 4u);
    if ((int32_t)g_eax >= 0 && (int32_t)g_eax < 16) {
        g_eax *= 0x1F54u; g_ecx = synth_read32(g_eax + 0x7BEDC0u);
        g_eax += 0x7BEDC0u; if (g_ecx == 0u) g_eax = 0u;
    } else g_eax = 0u;
    g_ecx = synth_read32(g_eax); guest_write32(g_ecx + 0x34u, 0u);
    g_edx = synth_read32(g_eax); g_ecx = synth_read32(g_esp + 8u);
    guest_write32(g_edx + 0x24u, g_ecx);
    g_edx = synth_read32(g_eax); g_eax = synth_read32(g_esp + 12u);
    guest_write32(g_edx + 0x28u, g_eax);
}

/* 0x00069930 game_profile_stats_entry_ptr_stride_0x18_at_0x490_by_slot_and_index */
GAME_REPLACE_EXACT(00069930, cdecl, 2, u32, game_profile_stats_entry_ptr_stride_0x18_at_0x490_by_slot_and_index)
{
    if (synth_read32(0x7DE458u) & 0x800000u) {
        g_eax = synth_read32(g_esp + 8u); g_ecx = 0x6F11C0u;
    } else {
        g_eax = synth_read32(g_esp + 4u) * 0x1F54u;
        g_ecx = synth_read32(g_eax + 0x7BEDC0u);
        g_ecx = g_ecx ? g_eax + 0x7C0050u : 0x6F11C0u;
        g_eax = synth_read32(g_esp + 8u);
    }
    g_eax = g_ecx + 24u * g_eax + 0x490u;
}

/* 0x0006B3D0 game_find_id_in_three_lists_74c36c */
GAME_REPLACE_EXACT(0006B3D0, cdecl, 1, u32, game_find_id_in_three_lists_74c36c)
{
    synth_push(g_esi); g_esi = synth_read32(0x74C36Cu);
    g_edx = synth_read32(g_esi + 0x10u); g_eax = 0u;
    synth_push(g_edi); g_edi = synth_read32(g_esp + 12u);
    if ((int32_t)g_edx > 0) {
        g_ecx = synth_read32(g_esi + 12u);
        do {
            if (synth_read32(g_ecx) == g_edi) goto match12;
            ++g_eax; g_ecx += 0x60u;
        } while ((int32_t)g_eax < (int32_t)g_edx);
    }
    g_edx = synth_read32(g_esi + 0x88u); g_eax = 0u;
    if ((int32_t)g_edx > 0) {
        g_ecx = synth_read32(g_esi + 0x84u);
        do {
            if (synth_read32(g_ecx) == g_edi) goto match12;
            ++g_eax; g_ecx += 0x8Cu;
        } while ((int32_t)g_eax < (int32_t)g_edx);
    }
    g_edx = synth_read32(g_esi + 0xE0u); g_eax = 0u;
    if ((int32_t)g_edx > 0) {
        g_ecx = synth_read32(g_esi + 0xDCu);
        do {
            if (synth_read32(g_ecx) == g_edi) goto match8;
            ++g_eax; g_ecx += 0x40u;
        } while ((int32_t)g_eax < (int32_t)g_edx);
    }
    g_edi = synth_pop(); g_esi = synth_pop(); g_eax = 0u; return;
match12:
    g_eax = synth_read32(g_ecx + 12u); goto resolve;
match8:
    g_eax = synth_read32(g_ecx + 8u);
resolve:
    g_eax = (uint32_t)(int32_t)(int16_t)synth_read16(2u * g_eax + 0x78B860u);
    g_edx = synth_read32(0x791D4Cu); g_ecx = 48u * g_eax;
    g_eax = synth_read32(g_ecx + g_edx + 0x28u);
    g_edi = synth_pop(); g_eax >>= 25; g_esi = synth_pop(); g_eax &= 1u;
}

/* 0x00071E60 game_global_7bb1e8_swap_fields_0x1e0_0x1e4 */
GAME_REPLACE_EXACT(00071E60, cdecl, 0, u32, game_global_7bb1e8_swap_fields_0x1e0_0x1e4)
{
    g_eax = synth_read32(0x7BB1E8u); g_edx = synth_read32(g_eax + 0x1E4u);
    g_ecx = synth_read32(g_eax + 0x1E0u); guest_write32(g_eax + 0x1E0u, g_edx);
    g_eax = synth_read32(0x7BB1E8u); guest_write32(g_eax + 0x1E4u, g_ecx);
}

/* 0x000802C0 game_list_701cb8_find_by_field_0x90 */
GAME_REPLACE_EXACT(000802C0, cdecl, 1, u32, game_list_701cb8_find_by_field_0x90)
{
    g_eax = synth_read32(0x701CB8u); g_ecx = synth_read32(g_esp + 4u);
    while (g_ecx != synth_read32(g_eax + 0x90u)) g_eax = synth_read32(g_eax + 0x94u);
}

/* 0x00080AD0 game_g701cc4_set_fields_0x74_0x78_0x7c */
GAME_REPLACE_EXACT(00080AD0, cdecl, 3, u32, game_g701cc4_set_fields_0x74_0x78_0x7c)
{
    g_eax = synth_read32(0x701CC4u); g_ecx = synth_read32(g_esp + 4u);
    g_edx = synth_read32(g_esp + 8u); guest_write32(g_eax + 0x74u, g_ecx);
    g_ecx = synth_read32(g_esp + 12u); guest_write32(g_eax + 0x78u, g_edx);
    guest_write32(g_eax + 0x7Cu, g_ecx);
}

/* 0x00081C20 game_record_4b85c8_get_word_0x26_by_slot */
GAME_REPLACE_EXACT(00081C20, cdecl, 1, u32, game_record_4b85c8_get_word_0x26_by_slot)
{
    g_eax = synth_read32(g_esp + 4u); g_ecx = synth_read32(4u * g_eax + 0x7BA040u);
    g_edx = synth_read32(0x4B85C8u); g_ecx *= 0x34u; g_eax = synth_read32(g_edx);
    g_eax = synth_read16(g_ecx + g_eax + 0x26u);
}

/* 0x000873F0 game_room_708788_get_bounds_by_index */
GAME_REPLACE_EXACT(000873F0, cdecl, 3, u32, game_room_708788_get_bounds_by_index)
{
    g_eax = synth_read32(g_esp + 4u); g_ecx = synth_read32(0x708788u); g_eax *= 0xB4u;
    g_edx = synth_read32(g_eax + g_ecx + 0x10u); g_ecx = synth_read32(g_esp + 8u);
    guest_write32(g_ecx, g_edx); g_edx = synth_read32(0x708788u);
    g_edx = synth_read32(g_eax + g_edx + 0x14u); guest_write32(g_ecx + 4u, g_edx);
    g_edx = synth_read32(0x708788u); g_edx = synth_read32(g_eax + g_edx + 0x18u);
    guest_write32(g_ecx + 8u, g_edx); g_ecx = synth_read32(0x708788u);
    g_edx = synth_read32(g_eax + g_ecx + 0x1Cu); g_ecx = synth_read32(g_esp + 12u);
    guest_write32(g_ecx, g_edx); g_edx = synth_read32(0x708788u);
    g_edx = synth_read32(g_eax + g_edx + 0x20u); guest_write32(g_ecx + 4u, g_edx);
    g_edx = synth_read32(0x708788u); g_eax = synth_read32(g_eax + g_edx + 0x24u);
    guest_write32(g_ecx + 8u, g_eax);
}

/* 0x000877C0 game_level_room_sub_entry_ptr_from_packed_handle_room_in_high_half_index_low_half */
GAME_REPLACE_EXACT(000877C0, cdecl, 2, u32, game_level_room_sub_entry_ptr_from_packed_handle_room_in_high_half_index_low_half)
{
    g_eax = synth_read32(g_esp + 4u); g_ecx = synth_read32(0x7B9784u);
    g_edx = synth_read32(g_ecx + 4u * g_eax); g_eax = synth_read32(g_edx + 4u);
    g_ecx = synth_read32(g_eax + 4u); g_eax = synth_read32(g_esp + 8u); g_edx = g_eax;
    synth_push(g_esi); g_esi = synth_read32(g_ecx);
    g_edx = ((uint32_t)((int32_t)g_edx >> 16) - g_esi) * 0xC8u;
    g_ecx = synth_read32(g_edx + g_ecx + 0x78u); g_eax &= 0xFFFFu;
    g_eax = g_ecx + 24u * g_eax; g_esi = synth_pop();
}

/* 0x00087840 game_object_field_0x1f0_or_room_entry_field_0x7c_by_flag */
GAME_REPLACE_EXACT(00087840, cdecl, 2, u32, game_object_field_0x1f0_or_room_entry_field_0x7c_by_flag)
{
    g_eax = synth_read32(g_esp + 8u); const int flag = g_eax != 0u;
    g_eax = synth_read32(g_esp + 4u);
    if (flag) {
        g_ecx = synth_read32(0x7B9784u); g_edx = synth_read32(g_ecx + 4u * g_eax);
        g_eax = synth_read32(g_edx + 0x1F0u); return;
    }
    g_ecx = synth_read32(0x708788u); g_eax *= 0xB4u;
    g_eax = synth_read32(g_eax + g_ecx); g_edx = synth_read32(g_eax) * 0xC8u;
    g_eax -= g_edx; g_eax = synth_read32(g_eax + 0x7Cu);
}

/* 0x000879A0 game_table_70878c_entry_has_word_0x16_set */
GAME_REPLACE_EXACT(000879A0, cdecl, 1, u32, game_table_70878c_entry_has_word_0x16_set)
{
    g_eax = synth_read32(g_esp + 4u); g_ecx = synth_read32(0x70878Cu);
    g_edx = synth_read32(g_ecx + 4u * g_eax);
    g_eax = synth_read16(g_edx + 0x16u) != 0xFFFFu;
}

/* 0x000879C0 game_table_70878c_entry_set_word_0x16_ffff */
GAME_REPLACE_EXACT(000879C0, cdecl, 1, u32, game_table_70878c_entry_set_word_0x16_ffff)
{
    g_eax = synth_read32(g_esp + 4u); g_ecx = synth_read32(0x70878Cu);
    g_eax = synth_read32(g_ecx + 4u * g_eax);
    if (g_eax != 0u) synth_write16(g_eax + 0x16u, 0xFFFFu);
}

/* 0x000879E0 game_table_70878c_entry_set_word_0x16_zero */
GAME_REPLACE_EXACT(000879E0, cdecl, 1, u32, game_table_70878c_entry_set_word_0x16_zero)
{
    g_eax = synth_read32(g_esp + 4u); g_ecx = synth_read32(0x70878Cu);
    g_eax = synth_read32(g_ecx + 4u * g_eax);
    if (g_eax != 0u) synth_write16(g_eax + 0x16u, 0u);
}

/* 0x00087A40 game_table_708778_set_bit_0x20_clear_bit_0x22 */
GAME_REPLACE_EXACT(00087A40, cdecl, 2, u32, game_table_708778_set_bit_0x20_clear_bit_0x22)
{
    g_eax = synth_read32(g_esp + 4u); g_ecx = synth_read32(0x708778u);
    g_eax *= 5u; g_edx = g_ecx + 8u * g_eax; g_ecx = synth_read32(g_esp + 8u);
    g_eax = 1u << (g_ecx & 31u);
    synth_write16(g_edx + 0x20u, (uint16_t)(synth_read16(g_edx + 0x20u) | (uint16_t)g_eax));
    g_eax = ~g_eax;
    synth_write16(g_edx + 0x22u, (uint16_t)(synth_read16(g_edx + 0x22u) & (uint16_t)g_eax));
}

/* 0x0009A390 game_list_7b6770_get_items_end_ptr_and_field4 */
GAME_REPLACE_EXACT(0009A390, cdecl, 2, u32, game_list_7b6770_get_items_end_ptr_and_field4)
{
    g_ecx = synth_read32(g_esp + 4u); g_eax = synth_read32(0x7B6770u);
    g_eax = synth_read32(g_eax + 4u * g_ecx); g_edx = synth_read32(g_eax);
    g_eax += 4u * g_edx + 0x18u; g_edx = synth_read32(g_esp + 8u);
    guest_write32(g_edx, g_eax); g_eax = synth_read32(0x7B6770u);
    g_ecx = synth_read32(g_eax + 4u * g_ecx); g_eax = synth_read32(g_ecx + 4u);
}

/* 0x0009A4C0 game_entry_id_get_key */
GAME_REPLACE_EXACT(0009A4C0, cdecl, 1, u32, game_entry_id_get_key)
{
    g_eax = synth_read32(g_esp + 4u); if (g_eax == UINT32_MAX) return;
    if ((int32_t)g_eax >= 0x209E && (int32_t)g_eax < 0x20B2) { g_eax = 0xFFFFFFFEu; return; }
    if ((int32_t)g_eax >= 0x1F40 && (int32_t)g_eax < 0x209E) {
        g_ecx = synth_read32(0x715F34u); g_eax = (g_eax - 0x1F40u) << 5;
        g_eax = synth_read32(g_eax + g_ecx); return;
    }
    g_edx = synth_read32(0x715F2Cu); g_eax <<= 5; g_eax = synth_read32(g_eax + g_edx);
}

/* 0x0009A570 game_table_715f30_entry_set_flag_0x10000 */
GAME_REPLACE_EXACT(0009A570, cdecl, 1, u32, game_table_715f30_entry_set_flag_0x10000)
{
    g_eax = synth_read32(g_esp + 4u); g_ecx = synth_read32(0x715F30u);
    g_eax = g_ecx + 20u * g_eax; guest_write32(g_eax, synth_read32(g_eax) | 0x10000u);
}

/* 0x0009C520 game_list_7b6770_get_vec3_0xc */
GAME_REPLACE_EXACT(0009C520, cdecl, 2, u32, game_list_7b6770_get_vec3_0xc)
{
    g_ecx = synth_read32(0x7B6770u); g_eax = synth_read32(g_esp + 4u);
    g_eax = synth_read32(g_ecx + 4u * g_eax); g_edx = synth_read32(g_eax + 12u);
    g_ecx = synth_read32(g_esp + 8u); guest_write32(g_ecx, g_edx);
    g_edx = synth_read32(g_eax + 16u); guest_write32(g_ecx + 4u, g_edx);
    g_eax = synth_read32(g_eax + 20u); guest_write32(g_ecx + 8u, g_eax);
}

/* 0x0009C550 game_list_7b6770_get_items_ptr_and_first_dword */
GAME_REPLACE_EXACT(0009C550, cdecl, 2, u32, game_list_7b6770_get_items_ptr_and_first_dword)
{
    g_ecx = synth_read32(0x7B6770u); g_eax = synth_read32(g_esp + 4u);
    g_eax = synth_read32(g_ecx + 4u * g_eax); g_ecx = synth_read32(g_esp + 8u);
    g_edx = g_eax + 0x18u; guest_write32(g_ecx, g_edx); g_eax = synth_read32(g_eax);
}

/* 0x0009E610 game_table_791d4c_get_field_0x10 */
GAME_REPLACE_EXACT(0009E610, cdecl, 1, u32, game_table_791d4c_get_field_0x10)
{
    g_eax = synth_read32(g_esp + 4u); g_ecx = synth_read32(0x791D4Cu);
    g_eax = synth_read32(48u * g_eax + g_ecx + 16u);
}

/* 0x000B0590 game_table_732a04_clear */
GAME_REPLACE_EXACT(000B0590, cdecl, 0, u32, game_table_732a04_clear)
{
    synth_push(g_edi); g_edi = synth_read32(0x732A04u); g_ecx = 0x9A8u; g_eax = 0u;
    guest_write32(0x732A08u, 0u); synth_fill(); g_edi = synth_pop();
}

/* 0x000C2E30 game_table_732e70_clear */
GAME_REPLACE_EXACT(000C2E30, cdecl, 0, u32, game_table_732e70_clear)
{
    synth_push(g_edi); g_edi = synth_read32(0x732E70u); g_ecx = 0x528u; g_eax = 0u;
    guest_write32(0x732E74u, 0u); synth_fill(); g_edi = synth_pop();
}

/* 0x000C4560 game_player_slot_summary_fill_by_index */
GAME_REPLACE_EXACT(000C4560, cdecl, 2, u32, game_player_slot_summary_fill_by_index)
{
    g_edx = synth_read32(g_esp + 4u);
    if (g_edx == UINT32_MAX) {
        g_eax = synth_read32(g_esp + 8u); g_ecx = 0u; g_edx = g_eax;
        for (uint32_t offset = 0u; offset < 32u; offset += 4u) guest_write32(g_edx + offset, g_ecx);
        guest_write32(g_eax, UINT32_MAX); return;
    }
    g_ecx = synth_read32(0x7356D8u); g_eax = g_edx * 0xEA0u + g_ecx;
    g_ecx = synth_read32(g_esp + 8u); guest_write32(g_ecx, g_edx);
    g_edx = synth_read32(g_eax); g_edx = synth_read32(g_edx + 0x34u);
    guest_write32(g_ecx + 4u, g_edx);
    g_edx = synth_read32(g_eax + 0xBFCu); guest_write32(g_ecx + 8u, g_edx);
    g_edx = synth_read32(g_eax + 0xC00u); guest_write32(g_ecx + 12u, g_edx);
    g_edx = synth_read32(g_eax + 0xC1Cu); guest_write32(g_ecx + 16u, g_edx);
    g_edx = synth_read32(g_eax + 0xC20u); guest_write32(g_ecx + 20u, g_edx);
    g_edx = synth_read32(g_eax + 0xBF8u); guest_write32(g_ecx + 24u, g_edx);
    g_eax = synth_read32(g_eax + 0xC04u); guest_write32(g_ecx + 28u, g_eax);
}

/* 0x000D0CA0 game_player_sync_owner_object_position_from_player_position_0xa8_unless_state_0x400 */
GAME_REPLACE_EXACT(000D0CA0, cdecl, 0, u32, game_player_sync_owner_object_position_from_player_position_0xa8_unless_state_0x400)
{
    g_ecx = synth_read32(0x7B0C7Cu); const int skip = synth_read32(g_ecx + 0x114u) == 0x400u;
    g_eax = synth_read32(g_ecx + 0x14u); if (skip) return;
    g_ecx = synth_read32(g_ecx + 0xA8u); guest_write32(g_eax + 0x64u, g_ecx);
    g_edx = synth_read32(0x7B0C7Cu); g_ecx = synth_read32(g_edx + 0xACu);
    guest_write32(g_eax + 0x68u, g_ecx); g_edx = synth_read32(0x7B0C7Cu);
    g_ecx = synth_read32(g_edx + 0xB0u); guest_write32(g_eax + 0x6Cu, g_ecx);
}

/* 0x000D6920 game_player_records_clear_all_and_reset_count */
GAME_REPLACE_EXACT(000D6920, cdecl, 0, u32, game_player_records_clear_all_and_reset_count)
{
    g_eax = synth_read32(0x79094Cu); g_ecx = g_eax != 0x65u;
    synth_push(g_edi); g_edi = synth_read32(0x7356D8u); g_eax = 0u;
    g_ecx = (((((g_ecx - 1u) & 0xFFFFFFE4u) + 0x20u) * 0xEA0u + 15u) & 0xFFFFFFF0u) >> 2;
    synth_fill(); guest_write32(0x7B0C44u, g_eax); g_edi = synth_pop();
}

/* 0x000D7550 game_object_set_field_0x84_and_0xa58_from_table */
GAME_REPLACE_EXACT(000D7550, cdecl, 2, u32, game_object_set_field_0x84_and_0xa58_from_table)
{
    g_eax = synth_read32(g_esp + 8u); g_ecx = synth_read32(g_esp + 4u);
    guest_write32(g_ecx + 0x84u, g_eax); g_eax *= 5u;
    g_edx = synth_read32(4u * g_eax + 0x4D1E28u); guest_write32(g_ecx + 0xA58u, g_edx);
}

/* 0x000DC270 game_table_4deb54_get_field */
GAME_REPLACE_EXACT(000DC270, cdecl, 1, u32, game_table_4deb54_get_field)
{
    g_eax = synth_read32(g_esp + 4u);
    if (g_eax == UINT32_MAX) g_eax = 0u;
    else { g_eax <<= 6; g_eax = synth_read32(g_eax + 0x4DEB54u); }
}

/* 0x000DCA40 game_table_4deb28_copy_vec3_0x4 */
GAME_REPLACE_EXACT(000DCA40, cdecl, 2, u32, game_table_4deb28_copy_vec3_0x4)
{
    g_eax = synth_read32(g_esp + 4u); g_ecx = synth_read32(g_esp + 8u); g_eax <<= 6;
    g_edx = synth_read32(g_eax + 0x4DEB2Cu); guest_write32(g_ecx, g_edx);
    g_edx = synth_read32(g_eax + 0x4DEB30u); guest_write32(g_ecx + 4u, g_edx);
    g_eax = synth_read32(g_eax + 0x4DEB34u); guest_write32(g_ecx + 8u, g_eax);
}

/* 0x000DCA70 game_table_737bd4_collect_entries_with_type_flag_8 */
GAME_REPLACE_EXACT(000DCA70, cdecl, 0, u32, game_table_737bd4_collect_entries_with_type_flag_8)
{
    g_eax = synth_read32(0x737BD4u); synth_push(g_ebx); synth_push(g_esi); g_esi = 0u;
    synth_push(g_edi); guest_write32(0x736674u, g_esi); g_eax += 0x458u;
    g_edi = 4u; g_ebx = (g_ebx & 0xFFFFFF00u) | 8u;
    do {
        g_ecx = synth_read32(g_eax - 0x458u); g_edx = g_eax - 0x458u;
        if (g_ecx != UINT32_MAX) {
            g_ecx <<= 6;
            if (synth_read8(g_ecx + 0x4DEB54u) & (uint8_t)g_ebx) {
                guest_write32(4u * g_esi + 0x738B78u, g_edx); ++g_esi;
            }
        }
        g_ecx = synth_read32(g_eax - 0x22Cu); g_edx = g_eax - 0x22Cu;
        if (g_ecx != UINT32_MAX) {
            g_ecx <<= 6;
            if (synth_read8(g_ecx + 0x4DEB54u) & (uint8_t)g_ebx) {
                guest_write32(4u * g_esi + 0x738B78u, g_edx); ++g_esi;
            }
        }
        g_ecx = synth_read32(g_eax);
        if (g_ecx != UINT32_MAX) {
            g_ecx <<= 6;
            if (synth_read8(g_ecx + 0x4DEB54u) & (uint8_t)g_ebx) {
                guest_write32(4u * g_esi + 0x738B78u, g_eax); ++g_esi;
            }
        }
        g_ecx = synth_read32(g_eax + 0x22Cu); g_edx = g_eax + 0x22Cu;
        if (g_ecx != UINT32_MAX) {
            g_ecx <<= 6;
            if (synth_read8(g_ecx + 0x4DEB54u) & (uint8_t)g_ebx) {
                guest_write32(4u * g_esi + 0x738B78u, g_edx); ++g_esi;
            }
        }
        g_ecx = synth_read32(g_eax + 0x458u); g_edx = g_eax + 0x458u;
        if (g_ecx != UINT32_MAX) {
            g_ecx <<= 6;
            if (synth_read8(g_ecx + 0x4DEB54u) & (uint8_t)g_ebx) {
                guest_write32(4u * g_esi + 0x738B78u, g_edx); ++g_esi;
            }
        }
        g_eax += 0xADCu; --g_edi;
    } while (g_edi != 0u);
    g_edi = synth_pop(); guest_write32(0x736674u, g_esi); g_esi = synth_pop();
    guest_write32(0x4DFB1Cu, 0u); g_ebx = synth_pop();
}

/* 0x000E0250 game_table_737bd4_clear_matching_owner_0x104 */
GAME_REPLACE_EXACT(000E0250, cdecl, 1, u32, game_table_737bd4_clear_matching_owner_0x104)
{
    g_ecx = synth_read32(0x737E44u); g_edx = synth_read32(0x736680u); ++g_ecx;
    if ((int32_t)g_edx >= (int32_t)g_ecx) return;
    g_eax = g_edx * 0x22Cu; synth_push(g_esi); g_esi = synth_read32(0x737BD4u);
    g_eax += g_esi + 0x104u; g_esi = synth_read32(g_esp + 8u); g_ecx -= g_edx;
    do {
        if (synth_read32(g_eax - 0x104u) == 0x10u) {
            g_edx = synth_read32(g_eax);
            if (g_edx != 0u && g_edx == g_esi) guest_write32(g_eax, 0u);
        }
        g_eax += 0x22Cu; --g_ecx;
    } while (g_ecx != 0u);
    g_esi = synth_pop();
}
