# ruff: noqa: E501  (the old/new strings are exact one-line C anchors)
"""Mutations for the Clear emission (T440): the commands Clear writes at the original's cursor
positions (src/gpu/d3d8_frame.c), the viewport words SetRenderTarget now seeds for it
(src/gpu/d3d8_bind.c) and the CLEAR_SURFACE accounting (src/gpu/d3d8_gpu.c).

WHAT THIS SET IS FOR. Clear used to write nothing, so a wrong packet could not show. Now every word
of the 28-byte packet, the surface format rewrite around it, the clip, the depth and colour conversion
and the per-site reservation are claims about what the original does, and the failure mode is a word
that is plausible and wrong (a far edge off by one, a stencil that never arrives). Each mutation
breaks one of them and `why` says what a survivor would hide.

TARGETS. The ctest binary with the literals the original produced (`test_d3d8_frame`, `test_d3d8_bind`,
`test_d3d8_gpu`) and the pytest suites that replay the ORIGINAL code through the same states
(`tests/test_d3d8_clear_oracle.py`, 283 cases, `tests/test_d3d8_bind_oracle.py`) and ctest `d3d8_clear_decode`, which decodes the emitted stream with gpu_pgraph (T267).

CONVENTION. `&& false` rather than a bare `false`, because `-Wunused-parameter -Werror` turns the
latter into NOT-A-MUTANT, which reads like evidence.
"""

MUTATIONS: list[dict] = [
    {
        "id": "d3d-clear-rect-horizontal-far-edge",
        "file": "src/gpu/d3d8_frame.c",
        "old": "((scaled_right << 16u) - 0x10000u) | scaled_left",
        "new": "((scaled_right << 16u)) | scaled_left",
        "targets": [
            "test_d3d8_frame",
            'pytest:tests/test_d3d8_clear_oracle.py -k "measured_shapes"',
        ],
        "why": "the clear rectangle is inclusive of its far edge, so the original stores far - 1 in the high half. Without it every clear covers one column too many and nothing but the packed word shows it.",
    },
    {
        "id": "d3d-clear-rect-vertical-far-edge",
        "file": "src/gpu/d3d8_frame.c",
        "old": "((scaled_bottom << 16u) - 0x10000u) | scaled_top",
        "new": "((scaled_bottom << 16u)) | scaled_top",
        "targets": [
            "test_d3d8_frame",
            'pytest:tests/test_d3d8_clear_oracle.py -k "measured_shapes"',
        ],
        "why": "the same far edge on the vertical word, which is a separate expression.",
    },
    {
        "id": "d3d-clear-rect-header-count",
        "file": "src/gpu/d3d8_frame.c",
        "old": "#define HEADER_CLEAR_RECT 0x00081D98u",
        "new": "#define HEADER_CLEAR_RECT 0x00041D98u",
        "targets": [
            "test_d3d8_frame",
            'pytest:tests/test_d3d8_clear_oracle.py -k "measured_shapes"',
        ],
        "why": "a one-dword rectangle header would leave the vertical word to be decoded as a method, so the stream looks well formed and means something else.",
    },
    {
        "id": "d3d-clear-values-header-count",
        "file": "src/gpu/d3d8_frame.c",
        "old": "#define HEADER_CLEAR_VALUES 0x000C1D8Cu",
        "new": "#define HEADER_CLEAR_VALUES 0x00081D8Cu",
        "targets": [
            "test_d3d8_frame",
            'pytest:tests/test_d3d8_clear_oracle.py -k "measured_shapes"',
        ],
        "why": "a count 2 run drops CLEAR_SURFACE itself, the one command a replay acts on, while the zstencil and colour values still decode.",
    },
    {
        "id": "d3d-clear-surface-format-header",
        "file": "src/gpu/d3d8_frame.c",
        "old": "#define HEADER_SURFACE_FORMAT 0x00040208u",
        "new": "#define HEADER_SURFACE_FORMAT 0x00040204u",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "the surface format rewrite around a clear goes to method 0x208, any other method is silently a different register.",
    },
    {
        "id": "d3d-clear-flags-unmasked-in-packet",
        "file": "src/gpu/d3d8_frame.c",
        "old": "        packet->flags = flags;",
        "new": "        packet->flags = call->flags;",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "without a depth buffer the original clears bits 0 and 1 of the flags it sends, so a clear never asks the GPU for a depth or stencil buffer that is not bound.",
    },
    {
        "id": "d3d-clear-stencil-dropped",
        "file": "src/gpu/d3d8_frame.c",
        "old": "packet->zstencil = depth_value | call->stencil;",
        "new": "packet->zstencil = depth_value;",
        "targets": [
            "test_d3d8_frame",
            'pytest:tests/test_d3d8_clear_oracle.py -k "measured_shapes"',
        ],
        "why": "the stencil argument reaches the GPU only through the low bits of the zstencil value.",
    },
    {
        "id": "d3d-clear-depth24-shift-dropped",
        "file": "src/gpu/d3d8_frame.c",
        "old": "load_guest(DEPTH_SCALE_24)), 0xFFFFFF) << 8u;",
        "new": "load_guest(DEPTH_SCALE_24)), 0xFFFFFF);",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "the 24-bit depth sits above the stencil byte, unshifted it is written into the stencil field.",
    },
    {
        "id": "d3d-clear-depth16-clamp",
        "file": "src/gpu/d3d8_frame.c",
        "old": "load_guest(DEPTH_SCALE_16)), 0xFFFF);",
        "new": "load_guest(DEPTH_SCALE_16)), 0x7FFF);",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "a depth above 1.0 must clamp at the top of the 16-bit range, the clamp limit is a constant of its own.",
    },
    {
        "id": "d3d-clear-depth-negative-clamp",
        "file": "src/gpu/d3d8_frame.c",
        "old": "return value < 0 ? 0u : (uint32_t)value;",
        "new": "return (uint32_t)value;",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "a negative depth clamps to zero, otherwise the wrapped value is written.",
    },
    {
        "id": "d3d-clear-depth-f24-bias",
        "file": "src/gpu/d3d8_frame.c",
        "old": "+ 0xF8000000u) &",
        "new": "+ 0xF0000000u) &",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "the float depth formats rebuild the value from the high dword of a double with an exponent bias that only the F24 path has.",
    },
    {
        "id": "d3d-clear-depth-f16-bias",
        "file": "src/gpu/d3d8_frame.c",
        "old": ">> 8u) - 0x8000u) &",
        "new": ">> 8u) - 0x4000u) &",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "the same for the F16 path, which has its own bias.",
    },
    {
        "id": "d3d-clear-depth-float-zero-test",
        "file": "src/gpu/d3d8_frame.c",
        "old": "    case 1u: /* 24-bit float depth, zero stays zero */\n        if (float_equals(depth_bits, load_guest(FLOAT_ZERO))) {",
        "new": "    case 1u: /* 24-bit float depth, zero stays zero */\n        if (float_equals(depth_bits, load_guest(FLOAT_ZERO)) && false) {",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "the original skips the multiply when the depth equals the zero constant, a zero depth through the multiply is a different word.",
    },
    {
        "id": "d3d-clear-depth-format-limit",
        "file": "src/gpu/d3d8_frame.c",
        "old": "    if (index > 7u) {",
        "new": "    if (index > 8u) {",
        "targets": ["test_d3d8_frame"],
        "why": "the jump table has eight entries and the original jumps into padding for a ninth, the refusal must start exactly there.",
    },
    {
        "id": "d3d-clear-colour-565-green-mask",
        "file": "src/gpu/d3d8_frame.c",
        "old": "const uint32_t green = class_byte == 0u ? 0xF800u : 0xFC00u;",
        "new": "const uint32_t green = 0xF800u;",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "5-6-5 keeps six green bits, 5-5-5 five.",
    },
    {
        "id": "d3d-clear-colour-shift-swapped",
        "file": "src/gpu/d3d8_frame.c",
        "old": "const uint32_t shift = class_byte == 0u ? 3u : 2u;",
        "new": "const uint32_t shift = class_byte == 0u ? 2u : 3u;",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "the two packings shift the red and green halves by different amounts.",
    },
    {
        "id": "d3d-clear-colour-class-none-converts",
        "file": "src/gpu/d3d8_frame.c",
        "old": "    if (class_byte == 2u) {\n        return color;\n    }",
        "new": "    if (class_byte == 5u) {\n        return color;\n    }",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "a 32-bit target keeps the colour as given, converting it would corrupt every opaque clear.",
    },
    {
        "id": "d3d-clear-format-rewrite-test",
        "file": "src/gpu/d3d8_frame.c",
        "old": "if ((d3d8_guest_load8(FORMAT_INFO_TABLE + format) & 1u) != 0u) {",
        "new": "if ((d3d8_guest_load8(FORMAT_INFO_TABLE + format) & 2u) != 0u) {",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "bit 0 of the format table decides whether the surface format is rewritten around the clear.",
    },
    {
        "id": "d3d-clear-format-rewrite-bits",
        "file": "src/gpu/d3d8_frame.c",
        "old": "plan->format_word = (word & 0xFFFFFDFFu) | 0x100u;",
        "new": "plan->format_word = (word & 0xFFFFFDFFu) | 0x200u;",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "the rewrite clears bit 9 and sets bit 8.",
    },
    {
        "id": "d3d-clear-format-restore-dropped",
        "file": "src/gpu/d3d8_frame.c",
        "old": "plan->restore_format = plan->restore_word != 0u;",
        "new": "plan->restore_format = false;",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "without the restore the surface format stays rewritten and every later draw runs with it.",
    },
    {
        "id": "d3d-clear-early-return-dropped",
        "file": "src/gpu/d3d8_frame.c",
        "old": "        if (flags == 0u) {\n            /* 0x003D5F90",
        "new": "        if (flags == 0u && false) {\n            /* 0x003D5F90",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "a depth or stencil clear with no depth buffer returns at once, the rest would write a packet that clears nothing.",
    },
    {
        "id": "d3d-clear-no-depth-flag-mask",
        "file": "src/gpu/d3d8_frame.c",
        "old": "flags &= 0xFFFFFFFCu;",
        "new": "flags &= 0xFFFFFFFEu;",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "both depth and stencil bits drop when there is no depth buffer.",
    },
    {
        "id": "d3d-clear-clip-left-direction",
        "file": "src/gpu/d3d8_frame.c",
        "old": "const int32_t left = (int32_t)rects[index][0] > x0 ?",
        "new": "const int32_t left = (int32_t)rects[index][0] < x0 ?",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "the left edge is the larger of the rectangle and the viewport.",
    },
    {
        "id": "d3d-clear-clip-right-direction",
        "file": "src/gpu/d3d8_frame.c",
        "old": "const int32_t right = (int32_t)rects[index][2] < x1 ?",
        "new": "const int32_t right = (int32_t)rects[index][2] > x1 ?",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "the right edge is the smaller of the rectangle and the viewport.",
    },
    {
        "id": "d3d-clear-clip-empty-width",
        "file": "src/gpu/d3d8_frame.c",
        "old": "if (left >= right || top >= bottom) {",
        "new": "if (left > right || top >= bottom) {",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "an empty rectangle writes no packet.",
    },
    {
        "id": "d3d-clear-clip-empty-height",
        "file": "src/gpu/d3d8_frame.c",
        "old": "if (left >= right || top >= bottom) {",
        "new": "if (left >= right || top > bottom) {",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "the same on the vertical edge.",
    },
    {
        "id": "d3d-clear-viewport-far-edge",
        "file": "src/gpu/d3d8_frame.c",
        "old": "const int32_t x1 = (int32_t)((uint32_t)x0 + device_word(DEV_VIEWPORT + 8u));",
        "new": "const int32_t x1 = (int32_t)device_word(DEV_VIEWPORT + 8u);",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "the viewport words are an origin and a size, the clip needs origin + size.",
    },
    {
        "id": "d3d-clear-viewport-count-zero",
        "file": "src/gpu/d3d8_frame.c",
        "old": "    if (call->count == 0u) {\n        rects[0][0]",
        "new": "    if (call->count == 1u) {\n        rects[0][0]",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "Count 0 means the whole viewport, a count of one reads the caller's rectangle.",
    },
    {
        "id": "d3d-clear-preamble-dropped",
        "file": "src/gpu/d3d8_frame.c",
        "old": "    const uint32_t cursor = d3d8_pushbuffer_begin();\n    for (uint32_t index = 0u; index < count; index++) {",
        "new": "    const uint32_t cursor = d3d8_device_load32(D3D8_DEV_CURSOR);\n    for (uint32_t index = 0u; index < count; index++) {",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "every packet opens with its own reservation preamble, without it a roll-over never happens at a Clear site.",
    },
    {
        "id": "d3d-clear-publish-short",
        "file": "src/gpu/d3d8_frame.c",
        "old": "d3d8_pushbuffer_end(cursor + count * 4u);",
        "new": "d3d8_pushbuffer_end(cursor + count * 4u - 4u);",
        "targets": ["test_d3d8_frame", "pytest:tests/test_d3d8_clear_oracle.py"],
        "why": "the cursor must advance by the whole packet.",
    },
    {
        "id": "d3d-clear-nonblack-mask",
        "file": "src/gpu/d3d8_frame.c",
        "old": "if ((call->flags & 0xF0u) != 0u && call->color != 0u) {",
        "new": "if ((call->flags & 0xF1u) != 0u && call->color != 0u) {",
        "targets": ["test_d3d8_frame"],
        "why": "a depth-only clear is not a colour clear, whatever the colour argument holds.",
    },
    {
        "id": "d3d-clear-alias-check-dropped",
        "file": "src/gpu/d3d8_frame.c",
        "old": "overlaps(start, site_bytes[site], D3D_REGION_BASE, D3D_REGION_BYTES) ||",
        "new": "(overlaps(start, site_bytes[site], D3D_REGION_BASE, D3D_REGION_BYTES) && false) ||",
        "targets": ["test_d3d8_frame"],
        "why": "a command span on the device or the library tables would be overwritten by the clear that reads them.",
    },
    {
        "id": "d3d-clear-device-check-dropped",
        "file": "src/gpu/d3d8_frame.c",
        "old": "if (load_guest(D3D8_DEVICE_POINTER_SLOT) != D3D8_DEVICE_BASE) {",
        "new": "if (load_guest(D3D8_DEVICE_POINTER_SLOT) != D3D8_DEVICE_BASE && false) {",
        "targets": ["test_d3d8_frame"],
        "why": "the port reproduces the one device the title makes.",
    },
    {
        "id": "d3d-clear-rect-cap-boundary",
        "file": "src/gpu/d3d8_frame.c",
        "old": "    if (count > MAX_RECTANGLES) {",
        "new": "    if (count >= MAX_RECTANGLES) {",
        "targets": ["test_d3d8_frame"],
        "why": "the plan holds exactly MAX_RECTANGLES, an off-by-one refuses a legal call.",
    },
    {
        "id": "d3d-clear-decode-rect-order",
        "file": "src/gpu/d3d8_frame.c",
        "old": "const uint32_t words[7] = {HEADER_CLEAR_RECT,    packet->rect_horizontal,\n                                   packet->rect_vertical, HEADER_CLEAR_VALUES,",
        "new": "const uint32_t words[7] = {HEADER_CLEAR_RECT,    packet->rect_vertical,\n                                   packet->rect_horizontal, HEADER_CLEAR_VALUES,",
        "targets": ["test_d3d8_clear_decode"],
        "why": "the decoder keys the horizontal and vertical halves by method, so swapped words decode as a transposed rectangle and a replay clears the wrong region.",
    },
    {
        "id": "d3d-clear-decode-values-order",
        "file": "src/gpu/d3d8_frame.c",
        "old": "                                   packet->zstencil,      packet->color,\n                                   packet->flags};",
        "new": "                                   packet->color,      packet->zstencil,\n                                   packet->flags};",
        "targets": ["test_d3d8_clear_decode"],
        "why": "the count 3 run is zstencil then colour then CLEAR_SURFACE, the decoder's event takes whatever stood in 0x1D8C and 0x1D90.",
    },
    {
        "id": "d3d-clear-decode-flags-last",
        "file": "src/gpu/d3d8_frame.c",
        "old": "                                   packet->zstencil,      packet->color,\n                                   packet->flags};",
        "new": "                                   packet->zstencil,      packet->flags,\n                                   packet->color};",
        "targets": ["test_d3d8_clear_decode"],
        "why": "CLEAR_SURFACE must be the last word of the run, it is the event that makes the decoder record the clear.",
    },
    {
        "id": "d3d-clear-viewport-width-from-size",
        "file": "src/gpu/d3d8_bind.c",
        "old": "(size_word & 0xFFFu) + 1u",
        "new": "(size_word & 0xFFFu)",
        "targets": ["test_d3d8_bind", "pytest:tests/test_d3d8_bind_oracle.py"],
        "why": "a linear target's Size word stores width - 1.",
    },
    {
        "id": "d3d-clear-viewport-height-exponent",
        "file": "src/gpu/d3d8_bind.c",
        "old": "1u << ((format_word >> 24) & 0xFu);",
        "new": "1u << ((format_word >> 20) & 0xFu);",
        "targets": ["test_d3d8_bind", "pytest:tests/test_d3d8_bind_oracle.py"],
        "why": "a swizzled target's height is the second exponent, bits 24 to 27.",
    },
    {
        "id": "d3d-clear-viewport-scale-dropped",
        "file": "src/gpu/d3d8_scaled_viewport.c",
        "old": "    d3d8_device_store32(DEV_SCALE_X, plan->scale_x);\n",
        "new": "",
        "targets": ["test_d3d8_bind", 'pytest:tests/test_d3d8_bind_oracle.py -k "narrowed"'],
        "why": "the scale store only shows when the scale was not already the recomputed one, which a created device never has (T536: re-derived, the reset to FLOAT_ONE became the store of the recomputed scale_x when T449 added the sample modes. T533: the store moved with the recompute into the piece SetRenderTarget shares with states 0x9A and 0x9B).",
    },
    {
        "id": "d3d-clear-viewport-origin-dropped",
        "file": "src/gpu/d3d8_bind.c",
        "old": "    d3d8_device_store32(DEV_VIEWPORT, 0u);\n",
        "new": "",
        "targets": ["test_d3d8_bind", 'pytest:tests/test_d3d8_bind_oracle.py -k "narrowed"'],
        "why": "SetRenderTarget puts a narrowed viewport back to the whole target.",
    },
    {
        "id": "d3d-clear-depth-range-dropped",
        "file": "src/gpu/d3d8_bind.c",
        "old": "    d3d8_device_store32(DEV_DEPTH_RANGE + 4u, FLOAT_ONE);\n",
        "new": "",
        "targets": ["test_d3d8_bind", 'pytest:tests/test_d3d8_bind_oracle.py -k "narrowed"'],
        "why": "the depth range is part of the viewport reset.",
    },
    {
        "id": "d3d-clear-viewport-multisample-refusal",
        "file": "src/gpu/d3d8_bind.c",
        "old": "(first_back_buffer && mode > 2u) ||",
        "new": "(first_back_buffer && mode > 2u && false) ||",
        "targets": ["test_d3d8_bind"],
        "why": "T536 re-derived: T449 made the sample modes computed, so the refusal is now only the modes it did not measure (back buffer above 2, offscreen above 4). A first back buffer sample mode beyond the measured ones must still stop.",
    },
    {
        "id": "d3d-clear-viewport-supersample-refusal",
        "file": "src/gpu/d3d8_bind.c",
        "old": "(!first_back_buffer && mode > 4u)",
        "new": "(!first_back_buffer && mode > 4u && false)",
        "targets": ["test_d3d8_bind"],
        "why": "T536, added with the re-derived refusal above: an offscreen supersample kind beyond the measured ones (above 4) must still stop.",
    },
    {
        "id": "d3d-clear-gpu-clear-method",
        "file": "src/gpu/d3d8_gpu.c",
        "old": "#define METHOD_CLEAR_SURFACE 0x1D94u",
        "new": "#define METHOD_CLEAR_SURFACE 0x1D90u",
        "targets": ["test_d3d8_gpu", "test_d3d8_frame_profile"],
        "why": "the counter counts CLEAR_SURFACE, not the colour clear value beside it.",
    },
    {
        "id": "d3d-clear-gpu-clear-counted-when-not",
        "file": "src/gpu/d3d8_gpu.c",
        "old": "    if (method == METHOD_CLEAR_SURFACE) {",
        "new": "    if (method != METHOD_CLEAR_SURFACE) {",
        "targets": ["test_d3d8_gpu"],
        "why": "every other method must stay uncounted.",
    },
]
