# ruff: noqa: E501  (the anchors are verbatim C source lines)
"""Mutations for the XMV device calls (T421): the second DirectSoundCreate and device Release in
src/audio/dsound_device.c, the SynchPlayback route in src/audio/dsound_movie_stream.c and the thunk layer
route in src/host/xdk_thunk.c. Reached through test_dsound_device_movie_calls, test_synch_dispatch and
test_dsound_synch_routes. The `tsfp_host` main.c wiring is not a ctest binary, it is covered by the
boot test tests/test_xmv_native_boot.py (`movie device   calls ..., SynchPlayback route ...` line).
"""

DEVICE = ["test_dsound_device_movie_calls"]
ROUTES = ["test_dsound_synch_routes"]
DISPATCH = ["test_synch_dispatch"]

MUTATIONS: list[dict] = [
    {
        "id": "t421-create-movie-caller-any",
        "file": "src/audio/dsound_device.c",
        "old": "!(caller == MOVIE_CREATE_CALLER && dsound_device_movie_calls_enabled())",
        "new": "!(caller != 0u && dsound_device_movie_calls_enabled())",
        "targets": DEVICE,
        "why": "any caller would get the second DirectSoundCreate, only the measured XMV return address was pinned.",
    },
    {
        "id": "t421-create-ignores-the-enable",
        "file": "src/audio/dsound_device.c",
        "old": "!(caller == MOVIE_CREATE_CALLER && dsound_device_movie_calls_enabled())",
        "new": "!(caller == MOVIE_CREATE_CALLER && true)",
        "targets": DEVICE,
        "why": "the XMV Create would be admitted with --headless-movie-audio off, changing every default and XMV boot.",
    },
    {
        "id": "t421-create-builds-the-first-device",
        "file": "src/audio/dsound_device.c",
        "old": "    if (movie && owned_address == 0u)\n",
        "new": "    if (movie && owned_address == 0u && false)\n",
        "targets": DEVICE,
        "why": "a movie caller could create the device itself, with the startup's omitted internals never built.",
    },
    {
        "id": "t421-create-movie-reference-uncounted",
        "file": "src/audio/dsound_device.c",
        "old": "        if (movie) movie_references++;\n",
        "new": "        if (movie && false) movie_references++;\n",
        "targets": DEVICE,
        "why": "the Release would then refuse every movie reference as the startup one.",
    },
    {
        "id": "t421-create-startup-counted-as-movie",
        "file": "src/audio/dsound_device.c",
        "old": "        if (movie) movie_references++;\n",
        "new": "        movie_references++;\n",
        "targets": DEVICE,
        "why": "the startup reference could then be released by the XMV caller, destroying the device.",
    },
    {
        "id": "t421-release-without-an-outstanding-reference",
        "file": "src/audio/dsound_device.c",
        "old": "    if (movie_references == 0u)\n        refuse_locked_at(RELEASE_ENTRY",
        "new": "    if (movie_references == 0u && false)\n        refuse_locked_at(RELEASE_ENTRY",
        "targets": DEVICE,
        "why": "a Release of the startup reference is the original device destructor, which tears down omitted children.",
    },
    {
        "id": "t421-release-destructor-threshold-low",
        "file": "src/audio/dsound_device.c",
        "old": "#define DESTROY_REFERENCES 6u",
        "new": "#define DESTROY_REFERENCES 5u",
        "targets": DEVICE,
        "why": "the measured destroy happens when the Release would leave 5, one off lets exactly that Release through.",
    },
    {
        "id": "t421-release-destructor-guard-removed",
        "file": "src/audio/dsound_device.c",
        "old": "    if (shadow_reference - 1u < DESTROY_REFERENCES)\n",
        "new": "    if (shadow_reference - 1u < DESTROY_REFERENCES && false)\n",
        "targets": DEVICE,
        "why": "a device without children would be released below the count the original destroys at.",
    },
    {
        "id": "t421-release-returns-the-old-count",
        "file": "src/audio/dsound_device.c",
        "old": "    const uint32_t result = shadow_reference;\n    pthread_mutex_unlock(&lock);\n    return result;",
        "new": "    const uint32_t result = shadow_reference + 1u;\n    pthread_mutex_unlock(&lock);\n    return result;",
        "targets": DEVICE + ROUTES,
        "why": "the original Release returns the NEW count (oracle pin), the guest's cmp after it would see the old one.",
    },
    {
        "id": "t421-release-guest-word-unchanged",
        "file": "src/audio/dsound_device.c",
        "old": '    if (!kernel_guest_write_u32(owned_address + 4u, shadow_reference - 1u))\n        refuse_locked_at(RELEASE_ENTRY, "device reference is not writable");',
        "new": '    if (!kernel_guest_write_u32(owned_address + 4u, shadow_reference))\n        refuse_locked_at(RELEASE_ENTRY, "device reference is not writable");',
        "targets": DEVICE + ROUTES,
        "why": "the shadow and the guest word would disagree and the next validation would stop on its own state.",
    },
    {
        "id": "t421-release-interface-unchecked",
        "file": "src/audio/dsound_device.c",
        "old": "    if (shadow_reference == UINT32_MAX || !validate_owned(interface))\n        refuse_locked_at(RELEASE_ENTRY",
        "new": "    if (shadow_reference == UINT32_MAX || (!validate_owned(interface) && false))\n        refuse_locked_at(RELEASE_ENTRY",
        "targets": DEVICE + ROUTES,
        "why": "a stream or foreign pointer would be treated as the device and its reference word written.",
    },
    {
        "id": "t421-release-caller-unchecked",
        "file": "src/audio/dsound_device.c",
        "old": "        caller != MOVIE_RELEASE_CALLER)\n        refuse_at(RELEASE_ENTRY",
        "new": "        caller == 0u)\n        refuse_at(RELEASE_ENTRY",
        "targets": DEVICE,
        "why": "the stream destructors also call 0x406A8A, their Release is not the movie one.",
    },
    {
        "id": "t421-release-ignores-the-enable",
        "file": "src/audio/dsound_device.c",
        "old": '    if (!movie_calls_enabled) refuse_locked_at(RELEASE_ENTRY, "movie device calls are disabled");',
        "new": '    if (!movie_calls_enabled && false) refuse_locked_at(RELEASE_ENTRY, "movie device calls are disabled");',
        "targets": DEVICE,
        "why": "the Release would answer with the movie policy off.",
    },
    {
        "id": "t421-reset-keeps-the-movie-references",
        "file": "src/audio/dsound_device.c",
        "old": "    movie_references = 0u;\n    announced = false;",
        "new": "    announced = false;",
        "targets": DEVICE,
        "why": "an old device's outstanding count would be charged to the next device.",
    },
    {
        "id": "t421-synch-caller-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "    if (caller != SYNCH_RETURN) refuse(SYNCH,",
        "new": "    if (caller != SYNCH_RETURN && false) refuse(SYNCH,",
        "targets": ROUTES,
        "why": "only the XMV call at 0x445716 is measured, another site could not be trusted to want the Pause(2) streams started.",
    },
    {
        "id": "t421-synch-policy-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "    if (error != NULL) refuse(SYNCH, error);",
        "new": "    if (error != NULL && false) refuse(SYNCH, error);",
        "targets": ROUTES,
        "why": "with the policy off or the global audio state set the original answers differently (E_FAIL).",
    },
    {
        "id": "t421-synch-never-starts-the-streams",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "    (void)userdata;\n    dsound_movie_stream_synch_playback();\n    *result = 0u;",
        "new": "    (void)userdata;\n    *result = 0u;",
        "targets": ROUTES,
        "why": "the call would return 0 and leave every Pause(2) stream held forever, so no packet would complete.",
    },
    {
        "id": "t421-synch-result-nonzero",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "    dsound_movie_stream_synch_playback();\n    *result = 0u;",
        "new": "    dsound_movie_stream_synch_playback();\n    *result = 1u;",
        "targets": ROUTES,
        "why": "GetNextFrame returns the SynchPlayback result on failure, the original returns 0 here.",
    },
    {
        "id": "t421-synch-device-argument-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "    if (!dsound_device_with_owned_interface(interface, synch_owned_device, NULL, result))\n        refuse(SYNCH,",
        "new": "    if (!dsound_device_with_owned_interface(interface, synch_owned_device, NULL, result) && false)\n        refuse(SYNCH,",
        "targets": ROUTES,
        "why": "a wrong argument would stop being refused (the result stays unset, the answer is a leftover).",
    },
    {
        "id": "t421-thunk-synch-pops-the-wrong-bytes",
        "file": "src/host/xdk_thunk.c",
        "old": "    g_esp = entry_esp + 8u;\n}\n\nrecomp_func_t recomp_lookup_manual",
        "new": "    g_esp = entry_esp + 4u;\n}\n\nrecomp_func_t recomp_lookup_manual",
        "targets": DISPATCH + ROUTES,
        "why": "SynchPlayback is stdcall with one argument, anything else desynchronises the guest stack silently.",
    },
    {
        "id": "t421-thunk-synch-result-dropped",
        "file": "src/host/xdk_thunk.c",
        "old": "    g_eax = result;\n    g_esp = entry_esp + 8u;",
        "new": "    g_eax = 0u;\n    g_esp = entry_esp + 8u;",
        "targets": DISPATCH,
        "why": "the handler's result would never reach the guest.",
    },
    {
        "id": "t421-thunk-synch-trace-result-unpatched",
        "file": "src/host/xdk_thunk.c",
        "old": "    thunk_trace_patch_result(slot, result);\n    g_eax = result;\n    g_esp = entry_esp + 8u;",
        "new": "    (void)slot;\n    g_eax = result;\n    g_esp = entry_esp + 8u;",
        "targets": DISPATCH,
        "why": "the call trace would show an unanswered call for a call that was answered.",
    },
    {
        "id": "t421-thunk-synch-call-uncounted",
        "file": "src/host/xdk_thunk.c",
        "old": "    bump(&synch_calls);\n",
        "new": "",
        "targets": DISPATCH + ROUTES,
        "why": "the report's SynchPlayback count would stay zero while calls were answered.",
    },
    {
        "id": "t421-thunk-synch-setter-skips-the-capability",
        "file": "src/host/xdk_thunk.c",
        "old": "    if (valid && handler != NULL) valid = xdk_thunk_synch_stop_ready();",
        "new": "    if (valid && handler != NULL) valid = true;",
        "targets": DISPATCH,
        "why": "a lift without the stop boundary would enable a route its direct call never reaches.",
    },
    {
        "id": "t421-thunk-synch-lookup-claims-more-than-one-address",
        "file": "src/host/xdk_thunk.c",
        "old": "    if (xbox_va == SYNCH_ADDRESS) {",
        "new": "    if (xbox_va >= SYNCH_ADDRESS && xbox_va < SYNCH_ADDRESS + 2u) {",
        "targets": DISPATCH,
        "why": "the route must answer 0x407A4C and nothing around it.",
    },
    {
        "id": "t421-thunk-synch-lookup-after-explicit-stops",
        "file": "src/host/xdk_thunk.c",
        "old": "    if (find_stop(xbox_va)) {\n        pending_stop_address = xbox_va;\n        return stop_override_dispatch;\n    }\n    if (xbox_va == SYNCH_ADDRESS) {",
        "new": "    if (xbox_va == SYNCH_ADDRESS) {\n        pthread_mutex_lock(&virtual_lock);\n        const bool early = synch_handler != NULL;\n        pthread_mutex_unlock(&virtual_lock);\n        if (early) return synch_dispatch;\n    }\n    if (find_stop(xbox_va)) {\n        pending_stop_address = xbox_va;\n        return stop_override_dispatch;\n    }\n    if (xbox_va == SYNCH_ADDRESS) {",
        "targets": DISPATCH,
        "why": "an explicit stop override must keep priority over the route, as it does for the movie methods.",
    },
]
