# ruff: noqa: E501  (the anchors are verbatim C source lines)
"""Mutations for the opt-in passive completion model (T681, option (a) of T608), in the T452 style.

Covered: `src/audio/dsound_completion.c` (the packet queue, the virtual clock accounting, the measured status
words, the named refusals, Play and the buffer status), the completion branches of `dsound_stream.c` and
`dsound_buffer.c` (a started stream's volume, Pause(0), the sound update's volume and frequency clamp, the
played-buffer refusals), the thunk layer completion route in `src/host/xdk_thunk.c` and the option parser.

Kill suites: `test_dsound_completion` (the model, its timing on a stated clock and every refusal),
`test_movie_method_dispatch` (the route), `test_host_options`, and the Unicorn oracle
`tests/test_dsound_completion_oracle.py` for the measured words (needs the user's XBE).

EQUIVALENT MUTANTS CONSIDERED AND LEFT OUT, so nobody re-adds them:
  - `dsound_completion_reset` dropping a `memset`: the states are keyed by address AND the lease serial, a
    recycled address with a new serial resets itself, so a stale state is never read.
  - `stream_find` / `buffer_find` serial mismatch branch: the same keying, the rebuilt entry equals a fresh one.
  - `dsound_completion_method_owned` dropping `dsound_completion_enabled()`: the thunk only installs the route
    when the model is enabled, and the snapshot of a stream the model never sees is still valid.
  - refusal and announce strings, and the `stats.observations` counter (reporting only).
  - `ticks_for` with a zero byte rate (`UINT64_MAX` against 0): the scope validators admit only non-zero average rates.
  - `Process` dropping `words[0]==0u` (a null packet buffer) and a status output of 0 (`output==0u`): `kernel_guest_range_readable`
    and `kernel_guest_read_u32` refuse address 0 themselves, only the refusal text could differ.
  - `dsound_completion_note_pause` dropping the `enabled` gate: the observer is installed only with the model on and the states it
    creates are read only by an enabled model.
  - `Play` dropping the `data_sets`, `volume_sets` or `pause_sets` test: the buffer module admits SetVolume only after SetBufferData and
    Pause only after SetVolume, so a recorded `frequency_sets` implies all three. Dropping `frequency_sets` is covered by the
    `snap.frequency==0u` test that follows it (the same refusal).
  - the completion `dsound_stream_get_startup_status` relaxation was dropped: with the model on, GetStatus is
    answered by the completion route, the startup status path is unreachable.

T733 (Stop, the free buffer call sites, `started` by lease serial): the Play caller gate (`PLAY_CALLER`) and the update caller pairing
of SetVolume are GONE under the model, so their mutants were retired with them: the call site is not a property of the original
(`0x407A80`, `0x407AA4`, `0x407AF8` never read their return address), the odd caller loops of `tests/c/test_dsound_completion.c` pin that.
EQUIVALENT T733 MUTANTS CONSIDERED AND LEFT OUT:
  - `Stop` of a looping buffer testing `b->looping` alone (dropping `b->playing`): a looping state is only ever playing (a loop never
    finishes, Play sets both), so the two conditions are the same on every reachable state.
  - the `stopped` flag staying set after a buffer finished: `stopped` is read only together with `playing`, and Play clears it.
  - the `Stop` announce (`announced_stop`), its refusal and log texts (reporting only).

Every `old` is checked to occur exactly once by `tests/test_mutation_anchors.py`.
"""

A = "src/audio/"
COM = A + "dsound_completion.c"
STR = A + "dsound_stream.c"
BUF = A + "dsound_buffer.c"
THUNK = "src/host/xdk_thunk.c"
OPTS = "src/host/host_options.c"
T_COM = ["test_dsound_completion"]
ORACLE = "pytest:tests/test_dsound_completion_oracle.py"


def m(mutation_id: str, path: str, old: str, new: str, targets: list[str], why: str) -> dict:
    return {
        "id": f"t681-{mutation_id}",
        "file": path,
        "old": old,
        "new": new,
        "targets": list(targets),
        "why": why,
    }


MUTATIONS: list[dict] = [
    # ---------------------------------------------------------------- the virtual clock and the queue
    m(
        "paused-consumes-time",
        COM,
        "    if(!s->running)return true;",
        "    if(!s->running && false)return true;",
        T_COM,
        "a paused stream would consume clock time and complete packets while paused.",
    ),
    m(
        "take-more-than-elapsed",
        COM,
        "const unsigned __int128 take=available<head->remaining_q32?available:head->remaining_q32;",
        "const unsigned __int128 take=available>head->remaining_q32?available:head->remaining_q32;",
        T_COM,
        "a packet would be charged more time than has passed.",
    ),
    m(
        "complete-without-remaining-check",
        COM,
        "        if(head->remaining_q32!=0u)break;\n",
        "        if(head->remaining!=0u && false)break;\n",
        T_COM,
        "every observation would complete the head packet whatever time is left.",
    ),
    m(
        "round-down",
        COM,
        "(units*clock_frequency+per_second-1u)/per_second",
        "(units*clock_frequency)/per_second",
        T_COM,
        "a packet could complete before size/average of clock time has passed.",
    ),
    m(
        "completed-size-wrong",
        COM,
        "(void)kernel_guest_write_u32(head.completed,head.size);",
        "(void)kernel_guest_write_u32(head.completed,0u);",
        T_COM,
        "the completed size word would not report the packet size.",
    ),
    m(
        "completed-word-skipped",
        COM,
        "if(head.completed!=0u)(void)kernel_guest_write_u32(head.completed,head.size);",
        "if(false)(void)kernel_guest_write_u32(head.completed,head.size);",
        T_COM,
        "the completed size would never be written.",
    ),
    m(
        "status-word-pending-at-completion",
        COM,
        "(void)kernel_guest_write_u32(head.status,0u);",
        "(void)kernel_guest_write_u32(head.status,PENDING_STATUS);",
        T_COM,
        "a completed packet would still read as pending.",
    ),
    m(
        "status-word-skipped",
        COM,
        "if(head.status!=0u)(void)kernel_guest_write_u32(head.status,0u);",
        "if(false)(void)kernel_guest_write_u32(head.status,0u);",
        T_COM,
        "the completion status would never be written.",
    ),
    m(
        "completion-order",
        COM,
        "for(uint32_t i=1u;i<s->queued;i++)s->queue[i-1u]=s->queue[i];",
        "for(uint32_t i=1u;i<s->queued;i++)s->queue[i]=s->queue[i-1u];",
        T_COM,
        "packets would not complete in the order they were attached.",
    ),
    # ---------------------------------------------------------------- the measured words
    m(
        "status-free-bit-off-by-one",
        COM,
        "uint32_t value=s->queued<max_packets?1u:0u;",
        "uint32_t value=s->queued<=max_packets?1u:0u;",
        T_COM + [ORACLE],
        "the free-packet bit would stay set with the list full (measured 0x10000 and 0x20000 at three packets).",
    ),
    m(
        "status-paused-bits-swapped",
        COM,
        "value|=s->running?0x10000u:0x20000u;",
        "value|=s->running?0x20000u:0x10000u;",
        T_COM + [ORACLE],
        "the playing and paused bits would be swapped.",
    ),
    m(
        "status-bits-without-packets",
        COM,
        "    if(s->queued!=0u)value|=s->running",
        "    if(true)value|=s->running",
        T_COM + [ORACLE],
        "an empty stream would report playing or paused (measured 1).",
    ),
    m(
        "pending-status-constant",
        COM,
        "#define PENDING_STATUS 0x8000000Au",
        "#define PENDING_STATUS 0x80000009u",
        T_COM + [ORACLE],
        "the attached packet status word is the measured 0x8000000A.",
    ),
    m(
        "full-result-constant",
        COM,
        "#define PACKET_LIST_FULL 0x88780032u",
        "#define PACKET_LIST_FULL 0x88780033u",
        T_COM + [ORACLE],
        "the list-full HRESULT is the measured 0x88780032.",
    ),
    m(
        "full-at-one-more",
        COM,
        "if(s->queued>=max){pthread_mutex_unlock(&lock);return PACKET_LIST_FULL;}",
        "if(s->queued>max){pthread_mutex_unlock(&lock);return PACKET_LIST_FULL;}",
        T_COM + [ORACLE],
        "a fourth packet would be taken (measured: refused at three).",
    ),
    m(
        "full-list-reads-the-packet",
        COM,
        "if(s->queued>=max){pthread_mutex_unlock(&lock);return PACKET_LIST_FULL;}",
        "if(s->queued>=max){pthread_mutex_unlock(&lock);(void)kernel_guest_write_u32(packet_address+8u,0u);return PACKET_LIST_FULL;}",
        T_COM,
        "the refused packet's memory would be touched (measured: untouched, never read).",
    ),
    m(
        "info-latency",
        COM,
        "uint32_t words[4]={5u,block,0u,2u*block};",
        "uint32_t words[4]={5u,block,0u,block};",
        T_COM + [ORACLE],
        "the XMEDIAINFO latency word is the measured 144.",
    ),
    m(
        "info-flags",
        COM,
        "uint32_t words[4]={5u,block,0u,2u*block};",
        "uint32_t words[4]={4u,block,0u,2u*block};",
        T_COM + [ORACLE],
        "the XMEDIAINFO flags are the measured 5.",
    ),
    m(
        "info-any-block",
        COM,
        "if(!((block==72u && info_channels==2u) || (block==36u && info_channels==1u)) || le16(info_format)!=0x69u || le16(info_format+14)!=4u)\n        refuse(STREAM_GET_INFO",
        "if(false && (!((block==72u && info_channels==2u) || (block==36u && info_channels==1u)) || le16(info_format)!=0x69u || le16(info_format+14)!=4u))\n        refuse(STREAM_GET_INFO",
        T_COM + ["t1091_anchor_repair"],
        "a stream outside the measured stereo72/mono36 ADPCM formats would get the measured answer.",
    ),
    # ---------------------------------------------------------------- named refusals
    m(
        "output-packet-accepted",
        COM,
        "if(output_packet!=0u)refuse(STREAM_PROCESS",
        "if(false && output_packet!=0u)refuse(STREAM_PROCESS",
        T_COM,
        "an output packet (codec output) would be accepted and ignored.",
    ),
    m(
        "event-accepted",
        COM,
        "if(words[4]!=0u)refuse(STREAM_PROCESS",
        "if(false)refuse(STREAM_PROCESS",
        T_COM,
        "a completion event the model never signals would be accepted.",
    ),
    m(
        "timestamp-accepted",
        COM,
        "if(words[5]!=0u)refuse(STREAM_PROCESS",
        "if(false)refuse(STREAM_PROCESS",
        T_COM,
        "a timestamp the model never stores would be accepted.",
    ),
    m(
        "empty-packet-accepted",
        COM,
        "if(words[1]==0u || words[0]==0u ||",
        "if(words[0]==0u ||",
        T_COM,
        "a zero size packet would stay pending for ever.",
    ),
    m(
        "same-completion-words",
        COM,
        "(words[2]!=0u && words[2]==words[3]))",
        "false)",
        T_COM,
        "the completed and status words could alias each other.",
    ),
    m(
        "header-alias-words",
        COM,
        "!((uint64_t)address<(uint64_t)stream_address+40u && (uint64_t)stream_address<(uint64_t)address+4u) &&",
        "(stream_address==0u || true) &&",
        T_COM,
        "a completion word could alias the public stream header.",
    ),
    m(
        "status-needs-startup-volume",
        COM,
        "if(!snap.volume_seen)refuse(STREAM_GET_STATUS",
        "if(false)refuse(STREAM_GET_STATUS",
        T_COM,
        "a stream that never started would have a status.",
    ),
    m(
        "enabled-gate-status",
        COM,
        "if(!dsound_completion_enabled() || !stream_snapshot(stream,&snap))refuse(STREAM_GET_STATUS",
        "if(!stream_snapshot(stream,&snap))refuse(STREAM_GET_STATUS",
        T_COM,
        "the stream status would answer with the policy off.",
    ),
    m(
        "register-with-policy-off",
        COM,
        "    if(!dsound_completion_enabled())return 0u;\n    size_t count=0u;",
        "    size_t count=0u;",
        T_COM,
        "a flags-off registry would gain the Play and buffer status rows.",
    ),
    m(
        "do-work-skipped",
        COM,
        "stream_advance(&streams[i],now);\n            if(dowork_delivery)stream_deliver_done(&streams[i]);",
        "if(false)stream_advance(&streams[i],now);\n            if(dowork_delivery)stream_deliver_done(&streams[i]);",
        T_COM,
        "DoWork would not complete the stream packets on time.",
    ),
    m(
        "do-work-buffers-skipped",
        COM,
        "for(unsigned i=0u;i<BUFFER_STATES;i++)if(buffers[i].used)buffer_advance(&buffers[i],now);",
        "for(unsigned i=0u;i<BUFFER_STATES;i++)if(false)buffer_advance(&buffers[i],now);",
        T_COM + [ORACLE],
        "DoWork would not finish the played buffers on time.",
    ),
    m(
        "pause-note-inverted",
        COM,
        "s->running=(mode==0u);",
        "s->running=(mode!=0u);",
        T_COM,
        "Pause(0) would pause and Pause(1) would resume.",
    ),
    # ---------------------------------------------------------------- Play and the buffer status
    m(
        "play-flags-limit",
        COM,
        "if(flags>3u){char text[96];",
        "if(flags>4u){char text[96];",
        T_COM,
        "an unmeasured Play flags value would be admitted.",
    ),
    m(
        "play-flags-limit-low",
        COM,
        "if(flags>3u){char text[96];",
        "if(flags>2u){char text[96];",
        T_COM + [ORACLE],
        "Play flags 3 (FROMSTARTONLY looping) would be refused.",
    ),
    m(
        "play-flags-looping-bit",
        COM,
        "b->looping=(flags&1u)!=0u;",
        "b->looping=flags==1u;",
        T_COM + [ORACLE],
        "flags 3 would not loop.",
    ),
    m(
        "t722-status-paused-bit",
        COM,
        "value=(b->paused?2u:1u)|(b->looping?4u:0u);",
        "value=(b->paused?1u:1u)|(b->looping?4u:0u);",
        T_COM,
        "a paused buffer would report 1, the measured status is 2 (looping 6).",
    ),
    m(
        "t722-paused-consumes-time",
        COM,
        "if(!b->playing || b->paused)return;",
        "if(!b->playing)return;",
        T_COM,
        "a paused buffer would finish while paused.",
    ),
    m(
        "t722-pause-mode-limit",
        COM,
        "bool admitted=b!=NULL && mode<=2u;",
        "bool admitted=b!=NULL && mode<=3u;",
        T_COM,
        "an unmeasured Pause mode 3 would be admitted.",
    ),
    m(
        "t722-resume-pauses",
        COM,
        "if(mode==0u)b->paused=false;",
        "if(mode==0u)b->paused=true;",
        T_COM,
        "Pause(0) would pause a playing buffer instead of resuming.",
    ),
    m(
        "t722-pause-finished-admitted",
        COM,
        "else if(b->playing && !b->stopped)b->paused=true;\n        else admitted=false;",
        "else b->paused=true;",
        T_COM,
        "Pause(1) of a finished buffer (not measured) would be admitted.",
    ),
    m(
        "t722-frequency-no-rescale",
        COM,
        "b->remaining=(uint64_t)((remaining_scaled+new_hertz-1u)/new_hertz);",
        "b->remaining=(uint64_t)((remaining_scaled+old_hertz-1u)/old_hertz);",
        T_COM,
        "a rate change would not change the time left.",
    ),
    m(
        "t722-frequency-rescale-rounds-down",
        COM,
        "b->remaining=(uint64_t)((remaining_scaled+new_hertz-1u)/new_hertz);",
        "b->remaining=(uint64_t)(remaining_scaled/new_hertz);",
        T_COM,
        "the time left would round down and a buffer could end early.",
    ),
    m(
        "t722-start-volume-any-off",
        A + "dsound_buffer.c",
        "        if(!completion){\n            if(r->argument!=VOLUME_STARTUP && r->argument!=VOLUME_UPDATE){r->error=",
        "        if(true){\n            if(r->argument!=VOLUME_STARTUP && r->argument!=VOLUME_UPDATE){r->error=",
        T_COM,
        "the second sound's start volume 0 (and every volume of the sound update) would be refused again with the model on.",
    ),
    m(
        "t722-played-pause-argument-unchecked",
        A + "dsound_buffer.c",
        'if(r->argument!=0u){r->error="only Pause(0) (resume) on a never started buffer is supported";goto done;}',
        'if(false){r->error="only Pause(0) (resume) on a never started buffer is supported";goto done;}',
        T_COM,
        "Pause(1) of a buffer nothing played (measured result 1) would be admitted.",
    ),
    m(
        "t722-pause-hook-inverted",
        A + "dsound_buffer.c",
        "if(pause_hook==NULL || !pause_hook(r->address,n->value.lease.serial,r->argument)){",
        "if(pause_hook==NULL || pause_hook(r->address,n->value.lease.serial,r->argument)){",
        T_COM,
        "the model's Pause verdict would be inverted.",
    ),
    m(
        "t722-frequency-hook-inverted",
        A + "dsound_buffer.c",
        "(frequency_hook==NULL || !frequency_hook(r->address,n->value.lease.serial,n->value.frequency,r->argument))){",
        "(frequency_hook==NULL || frequency_hook(r->address,n->value.lease.serial,n->value.frequency,r->argument))){",
        T_COM,
        "the model's SetFrequency verdict would be inverted.",
    ),
    m(
        "t722-frequency-hook-old-rate",
        A + "dsound_buffer.c",
        "frequency_hook(r->address,n->value.lease.serial,n->value.frequency,r->argument)",
        "frequency_hook(r->address,n->value.lease.serial,r->argument,r->argument)",
        T_COM,
        "the time left would be rescaled from the wrong old rate.",
    ),
    m(
        "t722-refusal-text-argument",
        A + "dsound_buffer.c",
        "r.error,address,argument,count);",
        "r.error,address,address,count);",
        T_COM,
        "the refusal would not carry the argument.",
    ),
    m(
        "t722-setvolume-text-address",
        A + "dsound_buffer.c",
        "actual,args[0],(int32_t)args[1]);",
        "args[0],args[0],(int32_t)args[1]);",
        T_COM,
        "the SetVolume refusal would not carry the return address.",
    ),
    m(
        "play-samples-per-block",
        COM,
        "#define BUFFER_BLOCK_SAMPLES 64u",
        "#define BUFFER_BLOCK_SAMPLES 63u",
        T_COM,
        "the ADPCM block holds 64 samples.",
    ),
    m(
        "play-loop-inverted",
        COM,
        "b->looping=(flags&1u)!=0u;",
        "b->looping=(flags&1u)==0u;",
        T_COM + [ORACLE],
        "flags 1 (looping) would end and flags 0 would loop.",
    ),
    m(
        "play-status-loop-word",
        COM,
        "if(b->playing)value=(b->paused?2u:1u)|(b->looping?4u:0u);",
        "if(b->playing)value=(b->paused?2u:1u)|(b->looping?0u:4u);",
        T_COM + [ORACLE],
        "the measured status is 1 playing and 5 looping.",
    ),
    m(
        "play-finish-off-by-one",
        COM,
        "if(elapsed>=b->remaining){b->remaining=0u;b->position=b->duration;b->playing=false;stats.buffer_finished++;}",
        "if(elapsed>b->remaining){b->remaining=0u;b->position=b->duration;b->playing=false;stats.buffer_finished++;}",
        T_COM,
        "the buffer would stay playing one tick too long.",
    ),
    m(
        "play-loop-finishes",
        COM,
        "if(b->looping) {",
        "if(false) {",
        T_COM,
        "a looping buffer would finish.",
    ),
    m(
        "play-reserved-arguments",
        COM,
        "if(args[1]!=0u || args[2]!=0u){",
        "if(args[1]!=0u){",
        T_COM,
        "the second reserved Play argument would be ignored.",
    ),
    m(
        "play-tiny-data",
        COM,
        "snap.frequency==0u || snap.data_length<BUFFER_BLOCK)",
        "snap.frequency==0u)",
        T_COM,
        "less than one block of data would play for no time.",
    ),
    # ---------------------------------------------------------------- the stream branches of dsound_stream.c
    m(
        "stream-volume-model-off",
        STR,
        "const bool update = completion && (spatial || stereo)",
        "const bool update = (spatial || stereo)",
        T_COM,
        "the update volume would be admitted with the model off.",
    ),
    m(
        "stream-volume-unstarted",
        STR,
        "&& n->value.discontinuity_seen && n->value.volume_seen;",
        "&& n->value.volume_seen;",
        T_COM,
        "an unstarted stream would take the update volume.",
    ),
    m(
        "stream-volume-recorded",
        STR,
        "n->value.volume = update ? (int32_t)r->argument : -10000;",
        "n->value.volume = -10000;",
        T_COM,
        "the recorded volume would stay -10000 (the model takes the value).",
    ),
    m(
        "stream-resume-model-off",
        STR,
        "const bool resume_ok = completion && n->value.discontinuity_seen",
        "const bool resume_ok = n->value.discontinuity_seen",
        T_COM,
        "Pause(0) would be admitted with the model off.",
    ),
    m(
        "stream-resume-unstarted",
        STR,
        "const bool resume_ok = completion && n->value.discontinuity_seen &&",
        "const bool resume_ok = completion &&",
        T_COM,
        "Pause(0) would be admitted on an unstarted stream.",
    ),
    m(
        "stream-resume-mode-2",
        STR,
        "(r->argument == 0u || r->argument == 1u);",
        "(r->argument == 0u || r->argument <= 2u);",
        T_COM,
        "Pause mode 2 would be admitted.",
    ),
    m(
        "stream-pause-note-dropped",
        STR,
        "if (pause_note != NULL) pause_note(r->address, r->argument);",
        "",
        T_COM,
        "the model would never hear a Pause.",
    ),
    # ---------------------------------------------------------------- the buffer branches of dsound_buffer.c
    m(
        "buffer-volume-model-off",
        BUF,
        "        if(!completion){\n            if(r->argument!=VOLUME_STARTUP && r->argument!=VOLUME_UPDATE){r->error=",
        "        if(false){\n            if(r->argument!=VOLUME_STARTUP && r->argument!=VOLUME_UPDATE){r->error=",
        T_COM + ["test_dsound_buffer"],
        "any volume would be admitted with the model off.",
    ),
    m(
        "buffer-volume-update-caller-pairing",
        BUF,
        "(!completion && args[1]!=VOLUME_UPDATE)",
        "(args[1]!=VOLUME_UPDATE && false)",
        T_COM + ["test_dsound_buffer"],
        "the update caller would take any value with the model off.",
    ),
    m(
        "buffer-volume-start-caller-pairing",
        BUF,
        ": (!completion && args[1]!=VOLUME_STARTUP)))",
        ": (false)))",
        T_COM + ["test_dsound_buffer"],
        "the start caller would take any volume.",
    ),
    m(
        "buffer-frequency-low-bound",
        BUF,
        "r->argument>=FREQUENCY_MIN &&",
        "r->argument>FREQUENCY_MIN &&",
        T_COM,
        "the lowest frequency of the title's clamp would be refused.",
    ),
    m(
        "buffer-frequency-high-bound",
        BUF,
        "r->argument<=FREQUENCY_MAX)",
        "r->argument<FREQUENCY_MAX)",
        T_COM,
        "the highest frequency of the title's clamp would be refused.",
    ),
    m(
        "buffer-frequency-model-off",
        BUF,
        "!(completion && r->argument>=FREQUENCY_MIN",
        "!(r->argument>=FREQUENCY_MIN",
        T_COM,
        "any clamped frequency would be admitted with the model off.",
    ),
    m(
        "buffer-frequency-after-play",
        BUF,
        "        if(started_query!=NULL && started_query(r->address,n->value.lease.serial) &&\n           (frequency_hook==NULL ||",
        "        if(false &&\n           (frequency_hook==NULL ||",
        T_COM,
        "SetFrequency would be admitted on a played buffer the completion model does not know (T722: refused unless the hook accepts).",
    ),
    m(
        "buffer-pause-after-play",
        BUF,
        "            if(pause_hook==NULL || !pause_hook(r->address,n->value.lease.serial,r->argument)){",
        "            if(false){",
        T_COM,
        "Pause would be admitted on a played buffer the completion model does not know (T722: refused unless the hook accepts).",
    ),
    # ---------------------------------------------------------------- T733: Stop, the free call sites, started by lease serial
    m(
        "t733-stop-pause-kept",
        COM,
        "if(b->playing){b->paused=false;b->stopped=true;}",
        "if(b->playing){b->stopped=true;}",
        T_COM + [ORACLE],
        "a paused buffer would stay paused through Stop (measured: status 2 becomes 1 and the voice resumes).",
    ),
    m(
        "t733-stop-not-stopped",
        COM,
        "if(b->playing){b->paused=false;b->stopped=true;}",
        "if(b->playing){b->paused=false;}",
        T_COM,
        "Pause(1) after Stop would pause again (measured: the original answers the mode and changes nothing).",
    ),
    m(
        "t733-stop-ends-play",
        COM,
        "if(b->playing){b->paused=false;b->stopped=true;}",
        "if(b->playing){b->paused=false;b->stopped=true;b->playing=false;}",
        T_COM + [ORACLE],
        "Stop would silence the buffer at once (measured: status stays 1, the voice drains its data).",
    ),
    m(
        "t733-stop-clears-time-left",
        COM,
        "if(b->playing){b->paused=false;b->stopped=true;}",
        "if(b->playing){b->paused=false;b->stopped=true;b->remaining=0u;}",
        T_COM,
        "Stop would finish the buffer at the next observation instead of letting it drain its data.",
    ),
    m(
        "t733-stop-looping-admitted",
        COM,
        "if(b->playing && b->looping){",
        "if(false){",
        T_COM,
        "Stop of a looping buffer would be admitted with a play position the model does not track.",
    ),
    m(
        "t733-stop-policy-off",
        COM,
        "if(!dsound_completion_enabled() || !dsound_buffer_get_snapshot(buffer,&snap))refuse(BUFFER_STOP",
        "if(!dsound_buffer_get_snapshot(buffer,&snap))refuse(BUFFER_STOP",
        T_COM,
        "Stop would be answered with the policy off.",
    ),
    m(
        "t733-stop-start-not-needed",
        COM,
        "snap.frequency_sets==0u || !ordinary_or_spatial(&snap))\n        refuse(BUFFER_STOP",
        "!ordinary_or_spatial(&snap))\n        refuse(BUFFER_STOP",
        T_COM,
        "Stop would be admitted on a buffer whose start (SetFrequency) is not recorded.",
    ),
    m(
        "t733-stop-spatial",
        COM,
        "snap.frequency_sets==0u || !ordinary_or_spatial(&snap))\n        refuse(BUFFER_STOP",
        "snap.frequency_sets==0u)\n        refuse(BUFFER_STOP",
        T_COM + ["t1091_anchor_repair"],
        "Stop would admit a spatial buffer outside the measured whole-cache scope or unsupported flags.",
    ),
    m(
        "t733-stop-uncounted",
        COM,
        "    stats.buffer_stops++;\n",
        "",
        T_COM,
        "the Stops would not be counted.",
    ),
    m(
        "t733-stop-unregistered",
        COM,
        "    count+=dsound_hle_register(BUFFER_STOP,stop_handler)?1u:0u;return count;",
        "    (void)stop_handler;return count;",
        T_COM,
        "the passive Stop handler would never be registered (the boot would stop at 0x407AA4 again).",
    ),
    m(
        "t733-stop-argument-count",
        COM,
        "entry==BUFFER_STOP?1u:2u;",
        "entry==BUFFER_STOP?2u:2u;",
        T_COM,
        "Stop (RET 4) would read a second argument it does not have.",
    ),
    m(
        "t733-play-clears-stopped",
        COM,
        "b->playing=true;b->stopped=false;",
        "b->playing=true;",
        T_COM,
        "a Play after a Stop would leave the buffer unpausable (measured: Play restarts, Pause(1) pauses).",
    ),
    m(
        "t733-started-ignores-serial",
        COM,
        "buffers[i].address==buffer && buffers[i].serial==serial)started=true;",
        "buffers[i].address==buffer && (buffers[i].serial==serial || true))started=true;",
        T_COM,
        "a recycled address with a new lease would count as a played buffer.",
    ),
    m(
        "t733-started-ignores-address",
        COM,
        "buffers[i].used && buffers[i].address==buffer && buffers[i].serial==serial)started=true;",
        "buffers[i].used && (buffers[i].address==buffer || true) && buffers[i].serial==serial)started=true;",
        T_COM,
        "any played buffer with that serial would count.",
    ),
    m(
        "t733-started-asks-without-serial",
        BUF,
        "if(started_query!=NULL && started_query(r->address,n->value.lease.serial)){",
        "if(started_query!=NULL && started_query(r->address,0u)){",
        T_COM,
        "Pause would ask about a lease serial that is not the buffer's.",
    ),
    m(
        "t733-caller-free-model-off",
        BUF,
        "const bool caller_free=completion_on && (entry==SET_DATA",
        "const bool caller_free=(completion_on || true) && (entry==SET_DATA",
        T_COM + ["test_dsound_buffer"],
        "the four buffer methods would lose their measured callers with the model off.",
    ),
    m(
        "t733-caller-free-set-data",
        BUF,
        "(entry==SET_DATA || entry==SET_VOLUME || entry==PAUSE || entry==SET_FREQUENCY);",
        "(entry==SET_VOLUME || entry==PAUSE || entry==SET_FREQUENCY);",
        T_COM,
        "SetBufferData would keep its measured caller under the model.",
    ),
    m(
        "t733-caller-free-set-volume",
        BUF,
        "(entry==SET_DATA || entry==SET_VOLUME || entry==PAUSE || entry==SET_FREQUENCY);",
        "(entry==SET_DATA || entry==PAUSE || entry==SET_FREQUENCY);",
        T_COM,
        "SetVolume would keep its measured callers under the model.",
    ),
    m(
        "t733-caller-free-pause",
        BUF,
        "(entry==SET_DATA || entry==SET_VOLUME || entry==PAUSE || entry==SET_FREQUENCY);",
        "(entry==SET_DATA || entry==SET_VOLUME || entry==SET_FREQUENCY);",
        T_COM,
        "Pause would keep its measured caller under the model.",
    ),
    m(
        "t733-caller-free-set-frequency",
        BUF,
        "(entry==SET_DATA || entry==SET_VOLUME || entry==PAUSE || entry==SET_FREQUENCY);",
        "(entry==SET_DATA || entry==SET_VOLUME || entry==PAUSE);",
        T_COM,
        "SetFrequency would keep its measured caller under the model.",
    ),
    m(
        "t733-caller-free-create",
        BUF,
        "(entry==SET_DATA || entry==SET_VOLUME || entry==PAUSE || entry==SET_FREQUENCY);",
        "(entry==SET_DATA || entry==SET_VOLUME || entry==PAUSE || entry==SET_FREQUENCY || entry==CREATE);",
        T_COM,
        "CreateSoundBuffer would lose its measured callers under the model.",
    ),
    m(
        "t733-caller-free-i3dl2",
        BUF,
        "(entry==SET_DATA || entry==SET_VOLUME || entry==PAUSE || entry==SET_FREQUENCY);",
        "(entry==SET_DATA || entry==SET_VOLUME || entry==PAUSE || entry==SET_FREQUENCY || entry==I3DL2);",
        T_COM,
        "the startup I3DL2 cache would lose its measured caller under the model.",
    ),
    m(
        "t733-caller-free-min-distance",
        BUF,
        "(entry==SET_DATA || entry==SET_VOLUME || entry==PAUSE || entry==SET_FREQUENCY);",
        "(entry==SET_DATA || entry==SET_VOLUME || entry==PAUSE || entry==SET_FREQUENCY || entry==MINIMUM);",
        T_COM,
        "the startup minimum distance cache would lose its measured caller under the model.",
    ),
    m(
        "t733-caller-free-rolloff",
        BUF,
        "(entry==SET_DATA || entry==SET_VOLUME || entry==PAUSE || entry==SET_FREQUENCY);",
        "(entry==SET_DATA || entry==SET_VOLUME || entry==PAUSE || entry==SET_FREQUENCY || entry==ROLLOFF);",
        T_COM,
        "the startup rolloff cache would lose its measured caller under the model.",
    ),
    # ---------------------------------------------------------------- the thunk route and the option
    m(
        "route-owner-ignored",
        THUNK,
        "completion_owns != NULL && completion_answer != NULL && completion_owns(entry_esp)",
        "completion_owns != NULL && completion_answer != NULL && true",
        ["test_movie_method_dispatch"],
        "the completion handler would answer streams it does not own.",
    ),
    m(
        "route-pop-bytes",
        THUNK,
        "            g_esp = entry_esp + pop_bytes + 4u;",
        "            g_esp = entry_esp + pop_bytes;",
        ["test_movie_method_dispatch"],
        "the stdcall return address would not be popped.",
    ),
    m(
        "route-uncounted",
        THUNK,
        "            bump(&completion_calls);\n",
        "",
        ["test_movie_method_dispatch"],
        "the routed calls would not be counted.",
    ),
    m(
        "route-decline-not-honoured",
        THUNK,
        "        if (completion_answer(address, entry_esp, &result, &pop_bytes)) {",
        "        if (completion_answer(address, entry_esp, &result, &pop_bytes) || true) {",
        ["test_movie_method_dispatch"],
        "a declined call would be popped as answered.",
    ),
    m(
        "route-info-without-completion",
        THUNK,
        "if (xbox_va == STREAM_INFO_ADDRESS ? completion : (movie || completion)) {",
        "if (xbox_va == STREAM_INFO_ADDRESS ? true : (movie || completion)) {",
        ["test_movie_method_dispatch"],
        "GetInfo would be routed in a boot without the completion model.",
    ),
    m(
        "route-setter-not-stored",
        THUNK,
        "    if (valid) { completion_owner = owns; completion_handler = handler; }",
        "    if (valid && false) { completion_owner = owns; completion_handler = handler; }",
        ["test_movie_method_dispatch"],
        "the completion handlers would never be installed.",
    ),
    m(
        "option-flag",
        OPTS,
        "            out->passive_audio_completion = true;",
        "            out->passive_audio_completion = false;",
        ["test_host_options"],
        "the flag would parse and do nothing.",
    ),
    m(
        "option-needs-streams",
        OPTS,
        "         (out->headless_streams && out->headless_buffers && out->headless_listener)) &&",
        "         (out->headless_buffers && out->headless_listener)) &&",
        ["test_host_options"],
        "the model would be accepted without the passive streams.",
    ),
    m(
        "option-needs-buffers",
        OPTS,
        "         (out->headless_streams && out->headless_buffers && out->headless_listener)) &&",
        "         (out->headless_streams && out->headless_listener)) &&",
        ["test_host_options"],
        "the model would be accepted without the passive buffers.",
    ),
    m(
        "option-needs-listener",
        OPTS,
        "         (out->headless_streams && out->headless_buffers && out->headless_listener)) &&",
        "         (out->headless_streams && out->headless_buffers)) &&",
        ["test_host_options"],
        "the model would be accepted without the listener (DoWork).",
    ),
    # ---------------------------------------------------------------- T756: virtual looping play position and Stop drain
    m(
        "t756-loop-position-no-wrap",
        COM,
        "const uint64_t step=elapsed%b->duration;",
        "const uint64_t step=elapsed;",
        T_COM,
        "elapsed time spanning multiple loop durations would leave the play position outside the buffer.",
    ),
    m(
        "t756-loop-position-paused-advances",
        COM,
        "if(!b->playing || b->paused)return;",
        "if(!b->playing)return;",
        T_COM,
        "a paused looping buffer would consume virtual time and Stop would drain from a false play position.",
    ),
    m(
        "t756-loop-position-frequency-not-rescaled",
        COM,
        "b->position=(uint64_t)(scaled/new_hertz);",
        "b->position=(uint64_t)(scaled/old_hertz);",
        T_COM,
        "SetFrequency would leave the virtual cursor in old-rate ticks and compute the wrong Stop tail.",
    ),
    m(
        "t756-loop-play-does-not-reset-position",
        COM,
        "b->duration=ticks_for(samples,snap.frequency);b->position=0u;b->remaining=b->duration;",
        "b->duration=ticks_for(samples,snap.frequency);b->position=b->position;b->remaining=b->duration;",
        T_COM,
        "restarting Play would continue from the previous loop cursor instead of the measured restart-at-start behavior.",
    ),
    m(
        "t756-loop-stop-drains-full-duration",
        COM,
        "b->remaining=b->duration-b->position;",
        "b->remaining=b->duration;",
        T_COM,
        "Stop would drain a full buffer instead of the tail remaining at the virtual play position.",
    ),
    # ---------------------------------------------------------------- T855: delivery at DirectSoundDoWork (opt-in mode)
    m(
        "t855-deliver-at-deadline",
        COM,
        "    if(!dowork_delivery)while(state->done!=0u){packet_deliver(state);state->done--;}",
        "    while(state->done!=0u){packet_deliver(state);state->done--;}",
        T_COM,
        "the DoWork mode would deliver the words at the deadline like the default model.",
    ),
    m(
        "t855-dowork-never-delivers",
        COM,
        "            if(dowork_delivery)stream_deliver_done(&streams[i]);",
        "            if(false)stream_deliver_done(&streams[i]);",
        T_COM,
        "finished packets would stay queued forever and the list would stay full.",
    ),
    m(
        "t855-dowork-delivers-one",
        COM,
        "    while(s->done!=0u){packet_deliver(s);s->done--;}",
        "    if(s->done!=0u){packet_deliver(s);s->done--;}",
        T_COM,
        "one DoWork would deliver a single finished packet and leave the others for a later frame.",
    ),
    m(
        "t855-dowork-delivery-setter-ignored",
        COM,
        "pthread_mutex_lock(&lock);dowork_delivery=value;pthread_mutex_unlock(&lock);",
        "pthread_mutex_lock(&lock);dowork_delivery=!value;pthread_mutex_unlock(&lock);",
        T_COM,
        "the mode could not be switched on.",
    ),
    m(
        "t855-dowork-done-packet-restarts-clock",
        COM,
        "        packet *head=&s->queue[s->done];",
        "        packet *head=&s->queue[0];",
        T_COM,
        "a finished packet waiting for DoWork would be charged again and the next packet would never start counting.",
    ),
    m(
        "t855-option-without-model",
        OPTS,
        "(!out->passive_audio_completion_at_dowork || out->passive_audio_completion) &&",
        "true &&",
        ["test_host_options"],
        "DoWork delivery would be accepted with the completion model off.",
    ),
    m(
        "t855-option-not-parsed",
        OPTS,
        "            out->passive_audio_completion_at_dowork = true;",
        "            out->passive_audio_completion_at_dowork = false;",
        ["test_host_options"],
        "the flag would be accepted and ignored.",
    ),
]
