# ruff: noqa: E501  (the anchors are verbatim C source lines)
"""Mutations for the XMV movie PCM stream model (T392): src/audio/dsound_movie_stream.c, its hooks in
dsound_stream.c and dsound_listener.c, the thunk layer route in xdk_thunk.c, recomp_guest_call.c and the
--headless-movie-audio option guard. Reached through test_dsound_movie_stream, test_dsound_movie_stream_routes,
test_movie_method_dispatch and test_host_options. `tsfp_host` main.c wiring is not a ctest binary, it is
covered by tests/test_xmv_native_boot.py and the recorded boot measurement instead.
"""

MUTATIONS: list[dict] = [
    {
        "id": "movie-scope-flags-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (word32(desc) != 0u || word32(desc + 4u)",
        "new": "if (false || word32(desc + 4u)",
        "targets": ["test_dsound_movie_stream"],
        "why": "a stream created with other flags would be admitted as the measured movie stream, flag bits change what the original builds.",
    },
    {
        "id": "movie-scope-packets-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "word32(desc + 4u) != DSOUND_MOVIE_MAX_PACKETS ||",
        "new": "(word32(desc + 4u) != DSOUND_MOVIE_MAX_PACKETS && false) ||",
        "targets": ["test_dsound_movie_stream"],
        "why": "the two-packet limit is the original's measured Process rejection, another descriptor would break that pin.",
    },
    {
        "id": "movie-scope-callback-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "word32(desc + 12u) != DSOUND_MOVIE_CALLBACK ||",
        "new": "(word32(desc + 12u) != DSOUND_MOVIE_CALLBACK && false) ||",
        "targets": ["test_dsound_movie_stream"],
        "why": "the model runs this guest callback, so an unmeasured callback address must never be admitted.",
    },
    {
        "id": "movie-scope-context-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "word32(desc + 16u) == 0u ||",
        "new": "(word32(desc + 16u) == 0u && false) ||",
        "targets": ["test_dsound_movie_stream"],
        "why": "a NULL stream context is not the decoder the callback is written for.",
    },
    {
        "id": "movie-scope-mixbins-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "word32(desc + 20u) != 0u)",
        "new": "(word32(desc + 20u) != 0u && false))",
        "targets": ["test_dsound_movie_stream"],
        "why": "mixbins change the original voice routing, the measured movie stream has none.",
    },
    {
        "id": "movie-scope-tag-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "word16(wave) != 1u ||",
        "new": "(word16(wave) != 1u && false) ||",
        "targets": ["test_dsound_movie_stream"],
        "why": "XADPCM would be admitted as PCM and the byte rate rule would be wrong by a factor.",
    },
    {
        "id": "movie-scope-channels-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "word16(wave + 2u) != 2u ||",
        "new": "(word16(wave + 2u) != 2u && false) ||",
        "targets": ["test_dsound_movie_stream"],
        "why": "mono would be admitted, the completion rate rule is only derived for the measured average.",
    },
    {
        "id": "movie-scope-rate-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "word32(wave + 4u) != FORMAT_RATE ||",
        "new": "(word32(wave + 4u) != FORMAT_RATE && false) ||",
        "targets": ["test_dsound_movie_stream"],
        "why": "another sample rate would be admitted with the 44100 pin.",
    },
    {
        "id": "movie-scope-average-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "word32(wave + 8u) != FORMAT_AVERAGE ||",
        "new": "(word32(wave + 8u) != FORMAT_AVERAGE && false) ||",
        "targets": ["test_dsound_movie_stream"],
        "why": "the completion rule divides by this constant, so a different average would change every deadline silently.",
    },
    {
        "id": "movie-scope-block-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "word16(wave + 12u) != FORMAT_BLOCK ||",
        "new": "(word16(wave + 12u) != FORMAT_BLOCK && false) ||",
        "targets": ["test_dsound_movie_stream"],
        "why": "the packet size granularity is this block.",
    },
    {
        "id": "movie-scope-bits-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "word16(wave + 14u) != 16u ||",
        "new": "(word16(wave + 14u) != 16u && false) ||",
        "targets": ["test_dsound_movie_stream"],
        "why": "8 bit PCM would be admitted with the 16 bit pins.",
    },
    {
        "id": "movie-scope-cbsize-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "word16(wave + 16u) != 0u)",
        "new": "(word16(wave + 16u) != 0u && false))",
        "targets": ["test_dsound_movie_stream"],
        "why": "extra format bytes are not the measured WAVEFORMATEX.",
    },
    {
        "id": "movie-policy-disabled-ignored",
        "file": "src/audio/dsound_movie_stream.c",
        "old": 'if (!enabled) return "explicit headless-movie-audio policy is disabled";',
        "new": 'if (!enabled && false) return "explicit headless-movie-audio policy is disabled";',
        "targets": ["test_dsound_movie_stream"],
        "why": "the default boot must never create a movie stream without the flag.",
    },
    {
        "id": "movie-policy-irql-ignored",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (irql_provider == NULL || !irql_provider(&irql) || irql != 0u) return",
        "new": "if (irql_provider == NULL || !irql_provider(&irql) || (irql != 0u && false)) return",
        "targets": ["test_dsound_movie_stream"],
        "why": "the model assumes passive level, as every startup audio module does.",
    },
    {
        "id": "movie-policy-global-state-ignored",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (!kernel_guest_read_u32(GLOBAL_STATE, &state) || state != 0u) return",
        "new": "if (!kernel_guest_read_u32(GLOBAL_STATE, &state) || (state != 0u && false)) return",
        "targets": ["test_dsound_movie_stream"],
        "why": "a nonzero original global audio state makes every original wrapper fail, the model must not answer over it.",
    },
    {
        "id": "movie-header-not-validated",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "memcmp(actual, node->header, sizeof(actual)) == 0 &&",
        "new": "true &&",
        "targets": ["test_dsound_movie_stream"],
        "why": "a guest overwrite of the stream header must be noticed before the model keeps answering.",
    },
    {
        "id": "movie-status-pause-bits-swapped",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "n->paused ? 0x20000u : 0x10000u",
        "new": "n->paused ? 0x10000u : 0x20000u",
        "targets": ["test_dsound_movie_stream"],
        "why": "GetStatus bits are pinned against the original in the oracle, CloseDecoder polls bit 0x10000.",
    },
    {
        "id": "movie-status-accept-bit-inverted",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "n->queued < DSOUND_MOVIE_MAX_PACKETS ? 1u : 0u",
        "new": "n->queued < DSOUND_MOVIE_MAX_PACKETS ? 0u : 1u",
        "targets": ["test_dsound_movie_stream"],
        "why": "the accept bit tells the title whether another packet fits.",
    },
    {
        "id": "movie-ticks-not-rounded-up",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "return (numerator + FORMAT_AVERAGE - 1u) / FORMAT_AVERAGE;",
        "new": "return numerator / FORMAT_AVERAGE;",
        "targets": ["test_dsound_movie_stream"],
        "why": "a packet must never complete before all its bytes have played, so the deadline rounds up.",
    },
    {
        "id": "movie-pause-forgets-remainder",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "n->queue[0].remaining = n->queue[0].deadline > now ? n->queue[0].deadline - now : 0u;",
        "new": "n->queue[0].remaining = n->queue[0].deadline > now ? 0u : 0u;",
        "targets": ["test_dsound_movie_stream"],
        "why": "pausing mid packet would let the rest complete instantly on resume.",
    },
    {
        "id": "movie-resume-ignores-remainder",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (n->paused && n->queued != 0u) n->queue[0].deadline = now + n->queue[0].remaining;",
        "new": "if (n->paused && n->queued != 0u) n->queue[0].deadline = now;",
        "targets": ["test_dsound_movie_stream"],
        "why": "resume must restart the frozen remainder, not complete at once.",
    },
    {
        "id": "movie-chain-restarts-at-now",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "n->queue[0].deadline = (played ? done.deadline : now) + n->queue[0].ticks;",
        "new": "n->queue[0].deadline = now + n->queue[0].ticks;",
        "targets": ["test_dsound_movie_stream"],
        "why": "playback is continuous, the next packet starts where the last one ended, never at the late work call.",
    },
    {
        "id": "movie-completes-one-tick-late",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "(!n->paused && n->queue[0].deadline <= now)",
        "new": "(!n->paused && n->queue[0].deadline < now)",
        "targets": ["test_dsound_movie_stream"],
        "why": "the deadline is inclusive, the packet completes on the first work call at or after it.",
    },
    {
        "id": "movie-queue-limit-off-by-one",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (n->queued >= DSOUND_MOVIE_MAX_PACKETS) return DSOUND_MOVIE_TOO_MANY_PACKETS;",
        "new": "if (n->queued > DSOUND_MOVIE_MAX_PACKETS) return DSOUND_MOVIE_TOO_MANY_PACKETS;",
        "targets": ["test_dsound_movie_stream"],
        "why": "the original rejects the third packet with 0x88780032, a third in the queue overflows the array.",
    },
    {
        "id": "movie-process-pending-status-wrong",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "kernel_guest_write_u32(p.status, DSOUND_MOVIE_PENDING_STATUS)",
        "new": "kernel_guest_write_u32(p.status, 0u)",
        "targets": ["test_dsound_movie_stream"],
        "why": "XMV waits for the status to leave 0x8000000A, writing success at Process would complete the packet unplayed.",
    },
    {
        "id": "movie-process-block-multiple-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "(p.size % FORMAT_BLOCK) != 0u ||",
        "new": "((p.size % FORMAT_BLOCK) != 0u && false) ||",
        "targets": ["test_dsound_movie_stream"],
        "why": "partial blocks are not measured, the original truncates or drops them.",
    },
    {
        "id": "movie-process-null-output-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (r->arg[1] != 0u) {",
        "new": "if (r->arg[1] != 0u && false) {",
        "targets": ["test_dsound_movie_stream"],
        "why": "the output packet is ignored by the model, a nonzero one is outside the measured XMV call.",
    },
    {
        "id": "movie-process-idle-deadline-from-zero",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "p.deadline = now_ticks() + p.ticks;",
        "new": "p.deadline = p.ticks;",
        "targets": ["test_dsound_movie_stream"],
        "why": "an idle stream restarts its clock at the attach tick, no credit for the idle gap.",
    },
    {
        "id": "movie-process-alias-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (words_overlap(n->queue[i].completed, p.completed) || words_overlap(n->queue[i].status, p.status) ||",
        "new": "if ((words_overlap(n->queue[i].completed, p.completed) && false) || words_overlap(n->queue[i].status, p.status) ||",
        "targets": ["test_dsound_movie_stream"],
        "why": "two packets sharing a completion word make completion order unobservable.",
    },
    {
        "id": "movie-probe-alignment-required",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "return address != 0u && (uint64_t)address + 4u <= UINT64_C(0x100000000) &&",
        "new": "return address != 0u && (address & 3u) == 0u && (uint64_t)address + 4u <= UINT64_C(0x100000000) &&",
        "targets": ["test_dsound_movie_stream"],
        "why": "T394: the retained decoder keeps its completion words at odd addresses and the original stores dwords through them, so requiring alignment stops the first real movie at its first audio packet.",
    },
    {
        "id": "movie-words-overlap-pair-allowed",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "return a < b ? b - a < 4u : a - b < 4u;",
        "new": "return a == b;",
        "targets": ["test_dsound_movie_stream"],
        "why": "T394: an unaligned completion pair that overlaps by a byte or more makes the two stores clobber each other, only equality was refused before.",
    },
    {
        "id": "movie-words-overlap-off-by-one",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "return a < b ? b - a < 4u : a - b < 4u;",
        "new": "return a < b ? b - a < 3u : a - b < 3u;",
        "targets": ["test_dsound_movie_stream"],
        "why": "T394: words three bytes apart still overlap by one byte.",
    },
    {
        "id": "movie-words-overlap-too-wide",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "return a < b ? b - a < 4u : a - b < 4u;",
        "new": "return a < b ? b - a < 5u : a - b < 5u;",
        "targets": ["test_dsound_movie_stream"],
        "why": "T394: words exactly four bytes apart are adjacent and legal, the real decoder lays them eight apart.",
    },
    {
        "id": "movie-attached-overlap-status-only",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "words_overlap(n->queue[i].completed, p.status) || words_overlap(n->queue[i].status, p.completed)) {",
        "new": "false) {",
        "targets": ["test_dsound_movie_stream"],
        "why": "T394: a new packet's status word over an attached packet's completed word (or the reverse) is as bad as sharing the same word.",
    },
    {
        "id": "movie-flush-does-not-resume-paused",
        "file": "src/audio/dsound_movie_stream.c",
        "old": '    TRACE_EVENT("flush tick %llu queued %u", (unsigned long long)now_ticks(), n->queued);\n    if (n->paused) resume_stream(n, now_ticks());',
        "new": '    TRACE_EVENT("flush tick %llu queued %u", (unsigned long long)now_ticks(), n->queued);',
        "targets": ["test_dsound_movie_stream"],
        "why": "T394: the original Flush leaves a Pause(2) stream running (oracle), a stream left paused would starve the next movie.",
    },
    {
        "id": "movie-flush-aborts-nothing",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "    const uint32_t result = access_node(&r);\n    (void)drain(FLUSH, true, stream);",
        "new": "    const uint32_t result = access_node(&r);",
        "targets": ["test_dsound_movie_stream"],
        "why": "T394: the synchronous Flush completes every pending packet before it returns, the callbacks included.",
    },
    {
        "id": "movie-flush-keeps-the-passed-packet",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "    const uint32_t result = access_node(&r);\n    (void)drain(FLUSH, true, stream);",
        "new": "    const uint32_t result = access_node(&r);\n    (void)drain(WORK, false, stream);",
        "targets": ["test_dsound_movie_stream"],
        "why": "T394: Flush is not a DoWork, it aborts a packet whose deadline passed but that no DoWork observed.",
    },
    {
        "id": "movie-flush-route-pop-wrong",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "    case ADD_REF: case RELEASE: case DISCONTINUITY: case FLUSH: count = 1u; break;",
        "new": "    case ADD_REF: case RELEASE: case DISCONTINUITY: case FLUSH: count = 2u; break;",
        "targets": ["test_dsound_movie_stream"],
        "why": "T394: Flush is ret 4, a wrong pop corrupts the title's stack.",
    },
    {
        "id": "movie-flush-route-missing",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "    case FLUSH: *result = dsound_movie_stream_flush(args[0]); break;\n",
        "new": "",
        "targets": ["test_dsound_movie_stream"],
        "why": "T394: the routed Flush must reach the model, not fall through to Process.",
    },
    {
        "id": "movie-thunk-flush-not-routed",
        "file": "src/host/xdk_thunk.c",
        "old": '    {0x00407388u, "StreamFlush"},\n',
        "new": "",
        "targets": [
            "test_movie_method_dispatch",
            "pytest:tests/test_movie_loop_boot.py -k both_logo",
        ],
        "why": "T394: without the thunk row the title's Flush at the end of a movie is the compiled stop again.",
    },
    {
        "id": "movie-flush-does-not-resume",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (n->paused) resume_stream(n, now);  /* an async flush lets a paused stream drain (oracle) */",
        "new": "",
        "targets": ["test_dsound_movie_stream"],
        "why": "the original resumes a sync-paused stream on an async flush (oracle), otherwise Close would wait forever.",
    },
    {
        "id": "movie-flush-tick-not-recorded",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "n->flush_tick = now;",
        "new": "n->flush_tick = 0u;",
        "targets": ["test_dsound_movie_stream"],
        "why": "packets that finished before the flush must complete normally, not abort.",
    },
    {
        "id": "movie-flush-argument-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (r->arg[0] != 0u || r->arg[1] != 0u || r->arg[2] != 1u) {",
        "new": "if (r->arg[2] != 1u) {",
        "targets": ["test_dsound_movie_stream"],
        "why": "a timed flush is a different original path, only time 0 is measured.",
    },
    {
        "id": "movie-flush-empty-sets-pending",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (n->queued == 0u) return 0u;  /* nothing to flush, the original changes nothing (oracle) */",
        "new": "",
        "targets": ["test_dsound_movie_stream"],
        "why": "an empty flush would leave flush_pending set and abort the next packet attached.",
    },
    {
        "id": "movie-deliver-size-not-written",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "kernel_guest_write_u32(done->completed, done->size)",
        "new": "kernel_guest_write_u32(done->completed, 0u)",
        "targets": ["test_dsound_movie_stream"],
        "why": "the completed size is the packet size on completion and abort (oracle).",
    },
    {
        "id": "movie-callback-arguments-swapped",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "runner(callback, context, done->context, status)",
        "new": "runner(callback, done->context, context, status)",
        "targets": ["test_dsound_movie_stream"],
        "why": "the XMV callback reads its decoder from the first argument and the packet context from the second.",
    },
    {
        "id": "movie-abort-status-always-success",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "*status = played ? 0u : DSOUND_MOVIE_ABORT_STATUS;",
        "new": "*status = 0u;",
        "targets": ["test_dsound_movie_stream"],
        "why": "flushed packets must report 0x80004004, success would hide data the decoder never played.",
    },
    {
        "id": "movie-final-release-off-by-one",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (n->header[2] == 1u) { r->destroy = true; return 0u; }",
        "new": "if (n->header[2] == 2u) { r->destroy = true; return 0u; }",
        "targets": ["test_dsound_movie_stream"],
        "why": "destroying on the second to last reference frees a stream the title still holds.",
    },
    {
        "id": "movie-final-release-skips-abort",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "(void)drain(RELEASE, true, stream);",
        "new": "",
        "targets": ["test_dsound_movie_stream"],
        "why": "pending packets must be aborted before the stream is freed (oracle), or the decoder waits on status forever.",
    },
    {
        "id": "movie-add-ref-not-incremented",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "write_refs(n, n->header[2] + 1u)",
        "new": "write_refs(n, n->header[2])",
        "targets": ["test_dsound_movie_stream"],
        "why": "AddRef must raise the guest reference word the original raises.",
    },
    {
        "id": "movie-pause-mode-three-accepted",
        "file": "src/audio/dsound_movie_stream.c",
        "old": 'if (mode == 3u) { r->error = "Pause mode 3 has no measured XMV use"; return 0u; }',
        "new": "",
        "targets": ["test_dsound_movie_stream"],
        "why": "mode 3 has an unmeasured effect.",
    },
    {
        "id": "movie-pause-high-modes-succeed",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (mode >= 4u) return E_FAIL_STATUS;  /* the original fails modes 4 and up (oracle) */",
        "new": "",
        "targets": ["test_dsound_movie_stream"],
        "why": "the original fails modes 4 and up with E_FAIL.",
    },
    {
        "id": "movie-synch-resumes-plain-pause",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (n->paused && n->pause_mode == 2u) resume_stream(n, now);",
        "new": "if (n->paused) resume_stream(n, now);",
        "targets": ["test_dsound_movie_stream"],
        "why": "SynchPlayback only starts the Pause(2) streams.",
    },
    {
        "id": "movie-create-caller-unchecked",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (!dsound_movie_stream_create_caller_ok(return_address)) return false;",
        "new": "",
        "targets": ["test_dsound_movie_stream"],
        "why": "Create is admitted from the one EnableAudioStream site only, the startup caller keeps the startup policy.",
    },
    {
        "id": "movie-caller-range-open",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "return (address >= XMV_LOW && address <= XMV_HIGH) || (address >= TITLE_LOW && address < TITLE_HIGH);",
        "new": "return (address >= XMV_LOW && address <= XMV_HIGH) || (address >= TITLE_LOW && address < TITLE_HIGH) || address != 0u;",
        "targets": ["test_dsound_movie_stream"],
        "why": "the startup callers must stay fatal on a movie stream.",
    },
    {
        "id": "movie-work-without-streams",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "|| dsound_movie_stream_count() == 0u)",
        "new": ")",
        "targets": ["test_dsound_movie_stream"],
        "why": "DoWork with no movie stream is the old owner's call, the movie route must not swallow it.",
    },
    {
        "id": "movie-method-not-owned-claimed",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "kernel_guest_read_u32(stack_pointer + 4u, &stream) && dsound_movie_stream_owns(stream);",
        "new": "kernel_guest_read_u32(stack_pointer + 4u, &stream);",
        "targets": ["test_dsound_movie_stream"],
        "why": "a startup stream passed to a movie method must not be claimed by the movie model.",
    },
    {
        "id": "movie-method-pop-bytes-wrong",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "*pop_bytes = 4u * count;",
        "new": "*pop_bytes = 4u;",
        "targets": ["test_dsound_movie_stream"],
        "why": "a wrong pop desyncs the guest stack for every later call.",
    },
    {
        "id": "movie-reset-keeps-streams",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "const uint32_t address = nodes != NULL ? nodes->stream_address : 0u;",
        "new": "const uint32_t address = nodes != NULL ? 0u : 0u;",
        "targets": ["test_dsound_movie_stream"],
        "why": "shutdown must free the movie streams and give the device references back.",
    },
    {
        "id": "movie-reset-ignores-refusal",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (!destroy_node(address, &identity)) return false;",
        "new": "if (!destroy_node(address, &identity)) break;",
        "targets": ["test_dsound_movie_stream"],
        "why": "a refused cleanup must be reported as not cleaned, not as a clean shutdown.",
    },
    {
        "id": "movie-stream-handler-hook-removed",
        "file": "src/audio/dsound_stream.c",
        "old": "if(route(entry,frame,actual,&extension))return extension;",
        "new": "(void)extension;",
        "targets": ["test_dsound_movie_stream_routes"],
        "why": "without the hook the movie Create, Pause, FlushEx and SetVolume still hit the startup refusal.",
    },
    {
        "id": "movie-stream-reset-skips-movies",
        "file": "src/audio/dsound_stream.c",
        "old": "const bool movies=extension==NULL || extension();",
        "new": "const bool movies=(extension==NULL && false) || true;",
        "targets": ["test_dsound_movie_stream"],
        "why": "the host shutdown path calls the startup reset, movie streams would keep device references.",
    },
    {
        "id": "movie-stream-reset-ignores-movie-refusal",
        "file": "src/audio/dsound_stream.c",
        "old": "return movies && result;",
        "new": "return (movies || true) && result;",
        "targets": ["test_dsound_movie_stream"],
        "why": "a refused movie cleanup must make the shutdown report not cleaned.",
    },
    {
        "id": "movie-stream-tables-check-removed",
        "file": "src/audio/dsound_stream.c",
        "old": "return kernel_guest_read_bytes(SECONDARY,table,sizeof(table)) && safe_tables(table);",
        "new": "return kernel_guest_read_bytes(SECONDARY,table,sizeof(table)) || safe_tables(table);",
        "targets": ["test_dsound_movie_stream"],
        "why": "the movie stream must not be created over an original vtable with an unprotected method.",
    },
    {
        "id": "movie-listener-work-hook-removed",
        "file": "src/audio/dsound_listener.c",
        "old": "if(work_route!=NULL && have &&",
        "new": "if(false && work_route!=NULL && have &&",
        "targets": ["test_dsound_movie_stream_routes"],
        "why": "without the hook DoWork from the movie loop is refused and no packet ever completes.",
    },
    {
        "id": "movie-thunk-claims-without-ownership",
        "file": "src/host/xdk_thunk.c",
        "old": "if (owns != NULL && handler != NULL && owns(entry_esp)) {",
        "new": "if (owns != NULL && handler != NULL) {",
        "targets": ["test_movie_method_dispatch"],
        "why": "a startup stream would be answered by the movie model instead of the startup route or stop.",
    },
    {
        "id": "movie-thunk-pop-forgets-return-address",
        "file": "src/host/xdk_thunk.c",
        "old": "g_esp = entry_esp + 4u + pop_bytes;",
        "new": "g_esp = entry_esp + pop_bytes;",
        "targets": ["test_movie_method_dispatch"],
        "why": "a stdcall method pops its return address and arguments, anything else desyncs the guest stack.",
    },
    {
        "id": "movie-thunk-route-without-handler",
        "file": "src/host/xdk_thunk.c",
        "old": "const bool movie = movie_handler != NULL && movie_owner != NULL;",
        "new": "const bool movie = true;",
        "targets": ["test_movie_method_dispatch"],
        "why": "the default build must keep the old lookup, a NULL handler route would crash or stop.",
    },
    {
        "id": "movie-thunk-pair-unchecked",
        "file": "src/host/xdk_thunk.c",
        "old": "(owns == NULL) == (handler == NULL);",
        "new": "true;",
        "targets": ["test_movie_method_dispatch"],
        "why": "a half registered pair would call a NULL function.",
    },
    {
        "id": "movie-thunk-stops-not-required",
        "file": "src/host/xdk_thunk.c",
        "old": "if (valid && handler != NULL) valid = xdk_thunk_stream_stops_ready();",
        "new": "if (valid && handler != NULL) valid = true;",
        "targets": ["test_movie_method_dispatch"],
        "why": "the other stream methods must stay stopped, enabling without the compiled stops exposes omitted original state.",
    },
    {
        "id": "movie-thunk-startup-fallback-removed",
        "file": "src/host/xdk_thunk.c",
        "old": "const recomp_func_t startup = virtual_lookup(address);\n    if (startup != NULL) {\n        startup();",
        "new": "const recomp_func_t startup = NULL;\n    if (startup != NULL) {\n        startup();",
        "targets": ["test_movie_method_dispatch"],
        "why": "startup GetStatus and Discontinuity must keep their route when the movie model does not own the stream.",
    },
    {
        "id": "movie-thunk-result-not-traced",
        "file": "src/host/xdk_thunk.c",
        "old": "bump(&movie_calls);\n        thunk_trace_patch_result(slot, result);",
        "new": "bump(&movie_calls);\n        (void)slot;",
        "targets": ["test_movie_method_dispatch"],
        "why": "the call list would show the movie call with an unknown result.",
    },
    {
        "id": "movie-thunk-call-not-counted",
        "file": "src/host/xdk_thunk.c",
        "old": "bump(&movie_calls);\n        thunk_trace_patch_result(slot, result);",
        "new": "thunk_trace_patch_result(slot, result);",
        "targets": ["test_movie_method_dispatch"],
        "why": "the report would hide routed movie calls.",
    },
    {
        "id": "movie-option-needs-no-xmv",
        "file": "src/host/host_options.c",
        "old": "(!out->headless_movie_audio || (out->native_xmv && out->headless_streams)) &&",
        "new": "(!out->headless_movie_audio || (out->headless_streams)) &&",
        "targets": ["test_host_options"],
        "why": "the movie stream needs the retained XMV exports that call it.",
    },
    {
        "id": "movie-option-needs-no-streams",
        "file": "src/host/host_options.c",
        "old": "(!out->headless_movie_audio || (out->native_xmv && out->headless_streams)) &&",
        "new": "(!out->headless_movie_audio || (out->native_xmv)) &&",
        "targets": ["test_host_options"],
        "why": "the movie stream needs the startup stream policy and device.",
    },
    {
        "id": "movie-guest-call-unbalanced-accepted",
        "file": "src/host/recomp_guest_call.c",
        "old": "const bool balanced = g_esp == top;",
        "new": "const bool balanced = true;",
        "targets": ["test_dsound_movie_stream_routes"],
        "why": "a callee that did not pop its frame means the argument count is wrong and the guest stack is off.",
    },
    {
        "id": "movie-guest-call-eax-not-restored",
        "file": "src/host/recomp_guest_call.c",
        "old": "    g_eax = saved[0];\n",
        "new": "",
        "targets": ["test_dsound_movie_stream_routes"],
        "why": "the XDK dispatcher sets EAX itself, but a restore that is missing leaks the callback result into the caller registers.",
    },
    {
        "id": "movie-guest-call-ecx-not-restored",
        "file": "src/host/recomp_guest_call.c",
        "old": "    g_ecx = saved[1];\n",
        "new": "",
        "targets": ["test_dsound_movie_stream_routes"],
        "why": "ECX carries the guest this pointer for thiscall exports, the callback must not change it.",
    },
    {
        "id": "movie-guest-call-edx-not-restored",
        "file": "src/host/recomp_guest_call.c",
        "old": "    g_edx = saved[2];\n",
        "new": "",
        "targets": ["test_dsound_movie_stream_routes"],
        "why": "EDX is the second fastcall register.",
    },
    {
        "id": "movie-volume-not-forwarded",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (!dsound_audio_runtime_set_stream_volume(n->stream_address, n->volume)) {",
        "new": "if (false) {",
        "targets": ["test_dsound_movie_stream"],
        "why": "T818: SetVolume reaches the mixer gain of the movie stream when the audio runtime is on.",
    },
    {
        "id": "movie-stream-lifetime-gain-not-reset",
        "file": "src/audio/dsound_movie_stream.c",
        "old": "if (dsound_audio_runtime_active())\n        (void)dsound_audio_runtime_reset_stream_volume(stream_address);",
        "new": "if (false)\n        (void)dsound_audio_runtime_reset_stream_volume(stream_address);",
        "targets": ["test_dsound_movie_stream"],
        "why": "Final release must restore unity on its persistent mixer key after cutting queued movie audio.",
    },
]
