# ruff: noqa: E501  (the old/new strings are exact one-line C anchors)
"""Mutations for the pushbuffer refill's fence insertion and the subchannel-aware recorder (T391, T487, T546).

WHAT THIS SET IS FOR. T391 ported what the original refill 0x003D69E0 does besides moving the limit:
  - 0x003D6530's GET shadow (device+0x5C, +0x60) and the refusal of the path it cannot model (GET outside the
    ring), and (T486) the wait for the GPU when GET lies in the area about to be reused: the walk over the second
    fence history that names the fence, and the refusal of a fence the GPU has not passed,
  - the fence insertion 0x003D67B0 writes at every fence (eight dwords at the cursor, the cursor 0x20 on, the
    histories) and the refill's tail (a fence with flags 3 and a kick, or with device flag 0x800 the flag 0x1000
    and a kick),
  - the recorder keeping the header's subchannel (bits 13-15), so the fence's subchannel-5 0x310 is not the 3D
    class's SET_DITHER_ENABLE, and the decoder counting and not replaying it (a refusal for anything else on
    another subchannel), consuming the fence packet's own zero colour clear values with it,
  - the frame profile hashing and diffing the packet as bookkeeping, and the vertex constants emitter (0x003D57D0)
    rolling the ring over at its entry and running past the limit between chunks as the original does, and
    (T487) refilling BETWEEN two chunks (`d3d8_pushbuffer_sim_split_site` plans the split, `refill_at` makes it,
    the emitter writes the first run before the refill and the rest after it).
(T546) the scissor `0x003D4470` (one check at its entry, the packet after the refill), the fog packet after the
vertex-program helper (`0x003D5C50`'s sized reservation, its packet under it, the fog packet's own preamble after it),
and the indexed draw `0x003D5050` (the cascade, the 0x209-dword reservation under device flag 0x800, the groups with the
0x204-dword reservation between them, the end fence) planned over one simulation that carries the device flags and lists
every span it writes. Targets `tests/test_d3d8_scissor_refill_oracle.py`, `tests/test_d3d8_fog_refill_oracle.py` and
`tests/test_d3d8_indexed_refill_oracle.py`. The plan-equals-emission consistency fatals are not mutated: they are
equivalent unless the plan is wrong, which the other mutants cover.
The failure mode is a refill that looks right (the boot advances, the limit is the same) while the cursor, the
history entry, the semaphore or one word of the packet is off, which only the original-vs-native comparison and
the hand-derived unit checks see.

TARGETS. Each names the ctest binary (it also guards compilation, a pytest target alone cannot) and the pytest
suite that replays the ORIGINAL code through the same state:
`tests/test_d3d8_refill_oracle.py` (the whole D3D region, the whole ring, the control block and the second history
dword for dword, 44 refill cases and the refusals), `tests/test_d3d8_vertex_constants_oracle.py` and
`tests/test_d3d8_vertex_constants_refill_oracle.py` (the emitter over a refilling ring, the limit swept across
the chunk boundaries, 29 cases).

CONVENTION. `if (cond && false)` rather than `if (false)`, because `-Wunused-parameter -Werror` turns the latter
into NOT-A-MUTANT, which reads like evidence.
"""

PUSH = "src/gpu/d3d8_pushbuffer.c"
GPU = "src/gpu/d3d8_gpu.c"
PGRAPH = "src/gpu/gpu_pgraph.c"
FEED = "src/gpu/d3d8_gpu_pgraph.c"
PROFILE = "src/gpu/d3d8_frame_profile.c"
VERTEX = "src/gpu/d3d8_vertex_constants.c"
PIXEL_CONSTANTS = "src/gpu/d3d8_pixel_constants.c"
PIXEL_BIND = "src/gpu/d3d8_pixel_bind.c"
SHADER = "src/gpu/d3d8_shader.c"
SCISSOR = "src/gpu/d3d8_scissor.c"
FOG = "src/gpu/d3d8_texture_dirty.c"
INDEXED = "src/gpu/d3d8_indexed.c"

T_PUSH = ["test_d3d8_pushbuffer"]
T_GPU = ["test_d3d8_gpu"]
T_PGRAPH = ["test_gpu_pgraph"]
T_FEED = ["test_d3d8_gpu_pgraph"]
T_PROFILE = ["test_d3d8_frame_profile"]
T_VERTEX = ["test_d3d8_vertex_constants"]
T_PIXEL_CONSTANTS = ["test_d3d8_pixel_constants"]
T_PIXEL_BIND = ["test_d3d8_pixel_bind"]
T_SCISSOR = ["test_d3d8_scissor"]
T_FOG = ["test_d3d8_texture_dirty"]
T_INDEXED = ["test_d3d8_indexed"]
ORACLE = "pytest:tests/test_d3d8_refill_oracle.py"
ORACLE_VERTEX = "pytest:tests/test_d3d8_vertex_constants_oracle.py"
ORACLE_VERTEX_REFILL = "pytest:tests/test_d3d8_vertex_constants_refill_oracle.py"
ORACLE_FOUR = "pytest:tests/test_d3d8_four_vertex_constants_oracle.py"
ORACLE_FOUR_REFILL = "pytest:tests/test_d3d8_four_vertex_constants_refill_oracle.py"
ORACLE_PIXEL_REFILL = "pytest:tests/test_d3d8_pixel_refill_oracle.py"
ORACLE_SCISSOR_REFILL = "pytest:tests/test_d3d8_scissor_refill_oracle.py"
ORACLE_FOG_REFILL = "pytest:tests/test_d3d8_fog_refill_oracle.py"
ORACLE_INDEXED_REFILL = "pytest:tests/test_d3d8_indexed_refill_oracle.py"


def _mutation(identifier: str, file: str, old: str, new: str, targets: list[str], why: str) -> dict:
    return {
        "id": f"gpu-refill-{identifier}",
        "file": file,
        "old": old,
        "new": new,
        "targets": targets,
        "why": why,
    }


MUTATIONS: list[dict] = [
    # --- the refill: GET shadow, the generation, the two refusals --------------------------------------
    _mutation(
        "get-shadow-not-stored",
        PUSH,
        "        d3d8_device_store32(D3D8_DEV_GET_SHADOW, plan.get_shadow);",
        "        (void)plan.get_shadow;",
        [*T_PUSH, ORACLE],
        "device+0x5C is the GET the library believes the GPU is at: unwritten, the next wait reads a stale one.",
    ),
    _mutation(
        "get-generation-not-stored",
        PUSH,
        "        d3d8_device_store32(D3D8_DEV_GET_GENERATION, plan.get_generation);",
        "        (void)plan.get_generation;",
        [*T_PUSH, ORACLE],
        "device+0x60 is the wrap generation GET belongs to: without it a wrapped GET compares as the previous lap.",
    ),
    _mutation(
        "get-generation-ignores-wrap",
        PUSH,
        "(cursor < get ? 1u : 0u)};",
        "0u};",
        [*T_PUSH, ORACLE],
        "a GET ahead of the cursor is on the previous lap: the generation is one behind the wrap count.",
    ),
    _mutation(
        "get-generation-equal-counts-as-ahead",
        PUSH,
        "(cursor < get ? 1u : 0u)};",
        "(cursor <= get ? 1u : 0u)};",
        [*T_PUSH, ORACLE],
        "GET exactly at the cursor (the steady state after a kick) is NOT ahead: the original's `sbb` test is strict.",
    ),
    _mutation(
        "get-ring-end-inclusive",
        PUSH,
        "if (gpu_attached && (get < base || get >= end)) {",
        "if (gpu_attached && (get < base || get > end)) {",
        [*T_PUSH, ORACLE],
        "the ring is [base, end): a GET at the end reads the GPU's own registers in the original, which is refused.",
    ),
    _mutation(
        "get-ring-base-exclusive",
        PUSH,
        "if (gpu_attached && (get < base || get >= end)) {",
        "if (gpu_attached && (get <= base || get >= end)) {",
        [*T_PUSH, ORACLE],
        "a GET at the very first byte of the ring (the state after create) is inside it and models fine.",
    ),
    _mutation(
        "get-outside-ring-not-refused",
        PUSH,
        "if (gpu_attached && (get < base || get >= end)) {",
        "if (gpu_attached && (get < base || get >= end) && false) {",
        [*T_PUSH, ORACLE],
        "the original reads the GPU's register file on that path; computing a shadow from a garbage GET hides it.",
    ),
    _mutation(
        "wait-not-refused",
        PUSH,
        "if (gpu_attached && plan.cursor < effective && effective <= candidate) {",
        "if (gpu_attached && plan.cursor < effective && effective <= candidate && false) {",
        [*T_PUSH, ORACLE],
        "the original waits on its fence history here: skipping the wait would reuse ring the GPU is still reading.",
    ),
    _mutation(
        "wait-end-exclusive",
        PUSH,
        "plan.cursor < effective && effective <= candidate) {",
        "plan.cursor < effective && effective < candidate) {",
        [*T_PUSH, ORACLE],
        "the segment end belongs to the area about to be reused (`ja` skips only a GET PAST it).",
    ),
    _mutation(
        "wait-start-inclusive",
        PUSH,
        "plan.cursor < effective && effective <= candidate) {",
        "plan.cursor <= effective && effective <= candidate) {",
        [*T_PUSH, ORACLE],
        "a GET exactly at the new cursor has consumed everything before it (`jae` skips): no wait in the steady state.",
    ),
    _mutation(
        "wrap-get-ahead-not-base",
        PUSH,
        "        if (get > cursor) {\n            effective = base + 4u;",
        "        if (false && get > cursor) {\n            effective = base + 4u;",
        [*T_PUSH, ORACLE],
        "after a wrap a GET ahead of the old cursor is read as the start of the ring (0x003D6A67), so the area is waited on.",
    ),
    _mutation(
        "wrap-get-at-base-not-bumped",
        PUSH,
        "        if (effective == base) {",
        "        if (effective == base + 1u) {",
        [*T_PUSH, ORACLE],
        "a GET at the ring base reads as base + 4 (0x003D6A78), inside the area: the wait, not a free wrap.",
    ),
    _mutation(
        "wait-checked-without-gpu",
        PUSH,
        "    const bool gpu_attached = refill_tail_fn != NULL;",
        "    const bool gpu_attached = true;",
        [*T_PUSH],
        "without the GPU module there is no DMA state: the refill is the arithmetic alone (the unit tests of the ring).",
    ),
    _mutation(
        "get-shadow-written-without-gpu",
        PUSH,
        "    if (refill_tail_fn != NULL) {\n        d3d8_device_store32(D3D8_DEV_GET_SHADOW, plan.get_shadow);",
        "    if (true) {\n        d3d8_device_store32(D3D8_DEV_GET_SHADOW, plan.get_shadow);",
        [*T_PUSH],
        "the shadow is the GPU module's: written without it, the ring-only tests see device words they never set.",
    ),
    # --- the refill's tail and where the previews put the cursor ---------------------------------------
    _mutation(
        "tail-not-run",
        PUSH,
        "    if (refill_tail_fn != NULL) {\n        refill_tail_fn();",
        "    if (refill_tail_fn != NULL && false) {\n        refill_tail_fn();",
        [*T_PUSH, *T_GPU, ORACLE],
        "a refill without its fence and kick leaves the cursor 0x20 short and the GPU never handed the old segment.",
    ),
    _mutation(
        "tail-installed-as-null",
        GPU,
        "    d3d8_pushbuffer_set_refill_tail(refill_tail);",
        "    (void)refill_tail;\n    d3d8_pushbuffer_set_refill_tail(NULL);",
        [*T_GPU, ORACLE],
        "attach is how the GPU module puts the tail on the ring: forgetting it silently drops every refill fence.",
    ),
    _mutation(
        "preview-begin-ignores-fence-bytes",
        PUSH,
        "    const refill_plan plan = plan_refill(&state, *cursor, kickoff >> 1, kickoff, flags);\n    *cursor = plan.cursor + refill_fence_bytes_for(flags);",
        "    const refill_plan plan = plan_refill(&state, *cursor, kickoff >> 1, kickoff, flags);\n    *cursor = plan.cursor;",
        [*T_PUSH],
        "the cascade plans its sites over the preview: it must land where the real refill, fence packet included, does.",
    ),
    _mutation(
        "preview-reserve-ignores-fence-bytes",
        PUSH,
        "    const refill_plan plan = plan_refill(&state, *cursor, half, kickoff, flags);\n    *cursor = plan.cursor + refill_fence_bytes_for(flags);",
        "    const refill_plan plan = plan_refill(&state, *cursor, half, kickoff, flags);\n    *cursor = plan.cursor;",
        [*T_PUSH],
        "the sized reservation's preview shifts by the fence packet too.",
    ),
    _mutation(
        "fence-bytes-ignores-flag-0x800",
        PUSH,
        "    if (refill_tail_fn == NULL || (flags & D3D8_PUSHBUFFER_FLAG_REFILL_WITHOUT_FENCE) != 0u) {",
        "    if (refill_tail_fn == NULL || (flags & D3D8_PUSHBUFFER_FLAG_REFILL_WITHOUT_FENCE) == 0u) {",
        [*T_PUSH],
        "with device flag 0x800 the refill writes no fence packet, so its preview must not move the cursor.",
    ),
    _mutation(
        "drain-leaves-put",
        PUSH,
        "    segment_start = cursor;\n    put_address = cursor;",
        "    segment_start = cursor;",
        [*T_PUSH],
        "the kick puts the GPU at the cursor: a put that never moves makes every later refill wait on the first lap.",
    ),
    _mutation(
        "create-put-not-base",
        PUSH,
        "    put_address = base;",
        "    put_address = 0u;",
        [*T_PUSH],
        "a fresh ring has the GPU at its base: any other GET is outside the ring and the first refill is refused.",
    ),
    # --- the fence packet 0x003D67B0 -------------------------------------------------------------------
    _mutation(
        "fence-packet-not-written",
        GPU,
        "    write_fence_packet(cursor, fence);\n    d3d8_pushbuffer_end(cursor + D3D8_PUSHBUFFER_FENCE_PACKET_BYTES);",
        "    if (flags > 3u) write_fence_packet(cursor, fence);\n    d3d8_pushbuffer_end(cursor + D3D8_PUSHBUFFER_FENCE_PACKET_BYTES);",
        [*T_GPU, ORACLE],
        "the packet is the SEMAPHORE_RELEASE the GPU's completion hangs on: a gap of zeros in the ring instead.",
    ),
    _mutation(
        "fence-cursor-not-advanced",
        GPU,
        "    d3d8_pushbuffer_end(cursor + D3D8_PUSHBUFFER_FENCE_PACKET_BYTES);",
        "    d3d8_pushbuffer_end(cursor);",
        [*T_GPU, ORACLE],
        "the next emitter would overwrite the packet.",
    ),
    _mutation(
        "fence-notify-on-the-3d-subchannel",
        GPU,
        "FENCE_HEADER(D3D8_GPU_SUBCHANNEL_SOFTWARE, D3D8_GPU_METHOD_FENCE_NOTIFY));",
        "FENCE_HEADER(D3D8_GPU_SUBCHANNEL_3D, D3D8_GPU_METHOD_FENCE_NOTIFY));",
        [*T_GPU, ORACLE],
        "on the 3D subchannel the same words would be SET_DITHER_ENABLE: a replay would change the dither state.",
    ),
    _mutation(
        "fence-notify-wrong-method",
        GPU,
        "D3D8_GPU_SUBCHANNEL_SOFTWARE, D3D8_GPU_METHOD_FENCE_NOTIFY));",
        "D3D8_GPU_SUBCHANNEL_SOFTWARE, D3D8_GPU_METHOD_FENCE_NOTIFY + 4u));",
        [*T_GPU, ORACLE],
        "the method is 0x310 exactly.",
    ),
    _mutation(
        "fence-notify-cursor-shift",
        GPU,
        "(((cursor << 3) | (fence & 0x1Fu)) << 2)",
        "(((cursor << 2) | (fence & 0x1Fu)) << 2)",
        [*T_GPU, ORACLE],
        "the notification carries cursor * 32: a different shift marks another ring position.",
    ),
    _mutation(
        "fence-notify-fence-mask",
        GPU,
        "(((cursor << 3) | (fence & 0x1Fu)) << 2)",
        "(((cursor << 3) | (fence & 0x3Fu)) << 2)",
        [*T_GPU, ORACLE],
        "only the fence's low five bits are folded in.",
    ),
    _mutation(
        "fence-notify-outer-shift",
        GPU,
        "(((cursor << 3) | (fence & 0x1Fu)) << 2) | (wraps & 3u)",
        "(((cursor << 3) | (fence & 0x1Fu)) << 3) | (wraps & 3u)",
        [*T_GPU, ORACLE],
        "the word is shifted left by two to make room for the wrap count.",
    ),
    _mutation(
        "fence-notify-wrap-mask",
        GPU,
        "| (wraps & 3u));",
        "| (wraps & 7u));",
        [*T_GPU, ORACLE],
        "the wrap count is folded in modulo four.",
    ),
    _mutation(
        "fence-notify-wrap-count-unread",
        GPU,
        "    const uint32_t wraps = d3d8_device_load32(D3D8_DEV_WRAP_COUNT);",
        "    const uint32_t wraps = 0u;",
        [*T_GPU, ORACLE],
        "the wrap count read AFTER a refill's wrap is what the packet carries.",
    ),
    _mutation(
        "fence-semaphore-value",
        GPU,
        "    d3d8_guest_store32(cursor + 12u, fence);",
        "    d3d8_guest_store32(cursor + 12u, fence + 1u);",
        [*T_GPU, ORACLE],
        "SEMAPHORE_RELEASE writes the fence's own value: one more completes a fence that never ran.",
    ),
    _mutation(
        "fence-clear-value-method",
        GPU,
        "    d3d8_guest_store32(cursor + 16u, FENCE_HEADER(D3D8_GPU_SUBCHANNEL_3D, METHOD_COLOR_CLEAR_VALUE));",
        "    d3d8_guest_store32(cursor + 16u, FENCE_HEADER(D3D8_GPU_SUBCHANNEL_3D, METHOD_COLOR_CLEAR_VALUE + 4u));",
        [*T_GPU, ORACLE],
        "the first colour clear value write is 0x1D90.",
    ),
    _mutation(
        "fence-last-dword",
        GPU,
        "    d3d8_guest_store32(cursor + 28u, 0u);",
        "    d3d8_guest_store32(cursor + 28u, 1u);",
        [*T_GPU, ORACLE],
        "the packet resets the clear colour to 0: a one leaves the next Clear a non-black colour.",
    ),
    # --- the refill's tail -----------------------------------------------------------------------------
    _mutation(
        "tail-flag-0x1000-not-set",
        GPU,
        "        d3d8_device_store32(D3D8_DEV_FLAGS, flags | DEV_FLAGS_REFILLED);",
        "        d3d8_device_store32(D3D8_DEV_FLAGS, flags);",
        [*T_GPU, ORACLE],
        "with device flag 0x800 the refill marks 0x1000 (0x003D6AEA).",
    ),
    _mutation(
        "tail-fence-without-second-history",
        GPU,
        "        (void)d3d8_gpu_fence_insert(3u);\n    }\n    d3d8_gpu_kick();",
        "        (void)d3d8_gpu_fence_insert(2u);\n    }\n    d3d8_gpu_kick();",
        [*T_GPU, ORACLE],
        "the refill's fence is inserted with flags 3: the second history entry is what the next wait searches.",
    ),
    _mutation(
        "tail-kick-missing",
        GPU,
        "        (void)d3d8_gpu_fence_insert(3u);\n    }\n    d3d8_gpu_kick();",
        "        (void)d3d8_gpu_fence_insert(3u);\n    }",
        [*T_GPU, ORACLE],
        "flags 3 does not kick: the tail's kick hands the fence packet over and raises the semaphore.",
    ),
    _mutation(
        "tail-0x800-no-kick",
        GPU,
        "        d3d8_device_store32(D3D8_DEV_FLAGS, flags | DEV_FLAGS_REFILLED);\n    } else {",
        "        d3d8_device_store32(D3D8_DEV_FLAGS, flags | DEV_FLAGS_REFILLED);\n        return;\n    } else {",
        [*T_GPU, ORACLE],
        "the 0x800 branch also kicks (0x003D6AF4): without it the GPU is never handed the old segment.",
    ),
    # --- the recorder keeps the subchannel -------------------------------------------------------------
    _mutation(
        "record-subchannel-dropped",
        GPU,
        "    stream[stream_length].subchannel = subchannel;",
        "    stream[stream_length].subchannel = 0u;",
        [*T_GPU, *T_FEED],
        "the fence's 0x310 on subchannel 5 would be recorded as the 3D class's 0x310 and replayed.",
    ),
    _mutation(
        "record-subchannel-bit-position",
        GPU,
        "const uint32_t subchannel = (header >> 13) & 7u;",
        "const uint32_t subchannel = (header >> 12) & 7u;",
        [*T_GPU, *T_FEED],
        "the subchannel is header bits 13-15 (measured from every header in the original's ring).",
    ),
    _mutation(
        "record-subchannel-width",
        GPU,
        "const uint32_t subchannel = (header >> 13) & 7u;",
        "const uint32_t subchannel = (header >> 13) & 3u;",
        [*T_GPU],
        "three bits: subchannels 4 to 7 would alias 0 to 3.",
    ),
    _mutation(
        "record-other-subchannel-uncounted",
        GPU,
        "        stats.commands_other_subchannel++;",
        "        (void)0;",
        [*T_GPU, *T_FEED, *T_PROFILE],
        "the count is how the traffic that is never replayed stays visible.",
    ),
    _mutation(
        "record-other-subchannel-clear-counted",
        GPU,
        "        return; /* never a CLEAR_SURFACE, whatever its method number */",
        "        (void)0;",
        [*T_GPU],
        "0x1D94 on another subchannel is not a clear.",
    ),
    # --- the decoder -----------------------------------------------------------------------------------
    _mutation(
        "decode-other-subchannel-accepts-all",
        PGRAPH,
        "    if (!fence_notify || pgraph->in_bracket) {",
        "    if (false && (!fence_notify || pgraph->in_bracket)) {",
        [*T_PGRAPH, *T_FEED],
        "nothing measured says what another subchannel's command does: replaying it as 3D would be wrong.",
    ),
    _mutation(
        "decode-fence-notify-in-bracket",
        PGRAPH,
        "    if (!fence_notify || pgraph->in_bracket) {",
        "    if (!fence_notify) {",
        [*T_PGRAPH, *T_FEED],
        "a fence inside a BEGIN_END bracket is not measured and is refused.",
    ),
    _mutation(
        "decode-fence-notify-either-half",
        PGRAPH,
        "subchannel == GPU_PGRAPH_SUBCHANNEL_SOFTWARE && method == GPU_PGRAPH_SOFTWARE_FENCE_NOTIFY;",
        "subchannel == GPU_PGRAPH_SUBCHANNEL_SOFTWARE || method == GPU_PGRAPH_SOFTWARE_FENCE_NOTIFY;",
        [*T_PGRAPH],
        "only the pair (subchannel 5, method 0x310) is the fence's notification.",
    ),
    _mutation(
        "decode-software-method-uncounted",
        PGRAPH,
        "    pgraph->stats.software_methods++;\n    pgraph->fence_tail = FENCE_TAIL_COMMANDS;",
        "    (void)0;\n    pgraph->fence_tail = FENCE_TAIL_COMMANDS;",
        [*T_PGRAPH, *T_FEED],
        "the counter is the evidence the packet was seen and not replayed.",
    ),
    _mutation(
        "decode-software-method-no-pair",
        PGRAPH,
        "    pgraph->fence_tail = FENCE_TAIL_COMMANDS;\n    pgraph->stats.pairs++;",
        "    pgraph->fence_tail = FENCE_TAIL_COMMANDS;",
        [*T_PGRAPH, *T_FEED],
        "one pair per recorded command keeps the pair index equal to the stream index the swap replay records.",
    ),
    _mutation(
        "decode-fence-tail-not-armed",
        PGRAPH,
        "    pgraph->fence_tail = FENCE_TAIL_COMMANDS;",
        "    pgraph->fence_tail = 0u;",
        [*T_PGRAPH, *T_FEED],
        "without the tail the packet's colour clear values are refused in strict mode: every frame with a fence.",
    ),
    _mutation(
        "decode-fence-tail-any-value",
        PGRAPH,
        "(step == 0u || commands[i].data == 0u)",
        "true",
        [*T_PGRAPH],
        "only the fence's ZERO clear colour is the packet's: a real clear colour write must still be refused.",
    ),
    _mutation(
        "decode-fence-tail-method-table",
        PGRAPH,
        "{GPU_PGRAPH_SEMAPHORE_RELEASE, 0x1D90u, 0x1D90u};",
        "{GPU_PGRAPH_SEMAPHORE_RELEASE, 0x1D90u, 0x1D94u};",
        [*T_PGRAPH, *T_FEED],
        "the packet ends with two colour clear values, not a CLEAR_SURFACE.",
    ),
    _mutation(
        "decode-fence-tail-never-disarmed",
        PGRAPH,
        "            } else {\n                pgraph->fence_tail = 0u;",
        "            } else {\n                (void)0;",
        [*T_PGRAPH],
        "a command that is not the packet's next one ends the packet: a later 0x1D90 must be judged on its own.",
    ),
    _mutation(
        "decode-fence-tail-consumed-with-clear-group",
        PGRAPH,
        "(pgraph->output_groups & GPU_PGRAPH_OUTPUT_CLEAR) == 0u) {\n                    pgraph->stats.fence_clear_values++;",
        "(pgraph->output_groups & GPU_PGRAPH_OUTPUT_CLEAR) != 0u) {\n                    pgraph->stats.fence_clear_values++;",
        [*T_PGRAPH],
        "with the clear group on the packet's clear colour is a real write (the library resets it at every fence).",
    ),
    _mutation(
        "decode-semaphore-unhandled",
        PGRAPH,
        "    if (method == GPU_PGRAPH_SEMAPHORE_RELEASE) {",
        "    if (method == GPU_PGRAPH_SEMAPHORE_RELEASE && false) {",
        [*T_PGRAPH, *T_FEED],
        "SEMAPHORE_RELEASE is in every fence packet: unhandled, a strict decode refuses every frame.",
    ),
    _mutation(
        "decode-semaphore-in-bracket",
        PGRAPH,
        "    if (method == GPU_PGRAPH_SEMAPHORE_RELEASE) {\n        if (pgraph->in_bracket) {",
        "    if (method == GPU_PGRAPH_SEMAPHORE_RELEASE) {\n        if (false) {",
        [*T_PGRAPH],
        "no measured emitter releases a semaphore inside a bracket.",
    ),
    _mutation(
        "decode-semaphore-uncounted",
        PGRAPH,
        "        pgraph->stats.semaphore_releases++;",
        "        (void)0;",
        [*T_PGRAPH, *T_FEED],
        "the counter is the evidence the release was seen.",
    ),
    _mutation(
        "decode-other-subchannel-3d-accepted",
        PGRAPH,
        "    if (pgraph == NULL || subchannel == GPU_PGRAPH_SUBCHANNEL_3D) {",
        "    if (pgraph == NULL) {",
        [*T_PGRAPH],
        "subchannel 0 belongs to gpu_pgraph_decode: accepting it here would count 3D traffic as a software method.",
    ),
    # --- the recording's reader ------------------------------------------------------------------------
    _mutation(
        "feed-subchannel-ignored",
        FEED,
        "            if (command.subchannel != D3D8_GPU_SUBCHANNEL_3D) {\n                break;",
        "            if (command.subchannel != D3D8_GPU_SUBCHANNEL_3D && false) {\n                break;",
        [*T_FEED],
        "the fence's 0x310 would be decoded as the 3D class's: the batch must stop at a command on another subchannel.",
    ),
    # --- the frame profile -----------------------------------------------------------------------------
    _mutation(
        "profile-full-keeps-notify-data",
        PROFILE,
        "            full_data = 0u;\n            masked = 0u;",
        "            masked = 0u;",
        [*T_PROFILE],
        "the notification holds the ring cursor, a host address: the full digest would differ between two boots.",
    ),
    _mutation(
        "profile-normalised-keeps-fence-value",
        PROFILE,
        "        } else if (command.method == METHOD_SEMAPHORE_RELEASE) {\n            masked = 0u;",
        "        } else if (command.method == METHOD_SEMAPHORE_RELEASE) {\n            masked = command.data;",
        [*T_PROFILE],
        "the fence value changes every frame: in the normalised digest a static screen reads as a new frame every present.",
    ),
    _mutation(
        "profile-subchannel-not-hashed",
        PROFILE,
        "            hash_word(&full, command.subchannel);",
        "            (void)0;",
        [*T_PROFILE],
        "a command on subchannel 5 must never hash equal to a 3D command of the same method.",
    ),
    _mutation(
        "profile-diff-counts-fence-data",
        PROFILE,
        "(bookkeeping || now.data == kept[index].data)) {",
        "(now.data == kept[index].data || (bookkeeping && false))) {",
        [*T_PROFILE],
        "the fence value and ring cursor differ in every frame pair: counted, the diff table is all noise.",
    ),
    _mutation(
        "profile-diff-ignores-subchannel",
        PROFILE,
        "if (now.method == kept[index].method && now.subchannel == kept[index].subchannel &&",
        "if (now.method == kept[index].method &&",
        [*T_PROFILE],
        "the same method and data on another subchannel is a different command.",
    ),
    # --- the refill's wait for the GPU (T486): the walk over the second history and its refusal ---------
    _mutation(
        "wait-fence-passed-not-checked",
        PUSH,
        "        if (!fence_reached_fn(fence, state->fence_counter, state_semaphore(state))) {",
        "        if (false && !fence_reached_fn(fence, state->fence_counter, state_semaphore(state))) {",
        [*T_PUSH, ORACLE],
        "a fence the GPU has not passed must be refused: the original spins or stalls the ring there, never overwrites.",
    ),
    _mutation(
        "wait-asks-about-the-wrong-fence",
        PUSH,
        "        if (!fence_reached_fn(fence, state->fence_counter, state_semaphore(state))) {",
        "        if (!fence_reached_fn(fence + 2u, state->fence_counter, state_semaphore(state))) {",
        [*T_PUSH, ORACLE],
        "the wait is on the fence the walk named: the next one is a different fence, passed or not.",
    ),
    _mutation(
        "wait-no-completion-test-not-refused",
        PUSH,
        "        if (fence_reached_fn == NULL) {",
        "        if (false && fence_reached_fn == NULL) {",
        [*T_PUSH],
        "a GPU-less ring with a tail but no completion test has no way to know a fence is passed: it must refuse, not call NULL.",
    ),
    _mutation(
        "wait-test-not-installed-by-the-gpu",
        GPU,
        "    d3d8_pushbuffer_set_fence_reached(fence_reached_at);",
        "    (void)fence_reached_at;",
        [*T_GPU, ORACLE],
        "without the completion test every refill that waits is refused: the wait cases of the original all complete.",
    ),
    _mutation(
        "wait-window-is-half-the-kickoff",
        PUSH,
        "(d3d8_guest_load32(D3D8_GLOBAL_PUSHBUFFER_SIZE) >> 1);",
        "(d3d8_guest_load32(D3D8_GLOBAL_KICKOFF_SIZE) >> 1);",
        [*T_PUSH, ORACLE],
        "0x003D6A8E loads the global at 0x003E6404, the RING size, not the kickoff size at 0x003E6400.",
    ),
    _mutation(
        "wait-window-end-exclusive",
        PUSH,
        "        if (position <= reach ||",
        "        if (position < reach ||",
        [*T_PUSH, ORACLE],
        "`cmp ecx, ebx; jbe`: a position exactly half the ring on stops the walk.",
    ),
    _mutation(
        "wait-walk-ignores-the-history-start",
        PUSH,
        "|| index == head ||",
        "|| false ||",
        [*T_PUSH, ORACLE],
        "`cmp eax, [esi+0x34]; je`: the walk ends where it began, or a history of one entry loops forever.",
    ),
    _mutation(
        "wait-walk-ignores-passed-fences",
        PUSH,
        "state_history(state, ring, index, 0u) <= completed) {",
        "0u * completed) {",
        [*T_PUSH, ORACLE],
        "`cmp [edx+eax*8], ecx; ja`: the walk goes on only while the entry before is a fence the GPU has not passed.",
    ),
    _mutation(
        "wait-walk-passed-is-strict",
        PUSH,
        "state_history(state, ring, index, 0u) <= completed) {",
        "state_history(state, ring, index, 0u) < completed) {",
        [*T_PUSH, ORACLE],
        "a fence EQUAL to the semaphore is passed: `ja` goes on only for an entry strictly above it.",
    ),
    _mutation(
        "wait-walk-forwards",
        PUSH,
        "        index = (index - 1u) & mask;",
        "        index = (index + 1u) & mask;",
        [*T_PUSH, ORACLE],
        "`dec eax; and eax, ebp`: the walk goes back in time, from the newest fence to the older ones.",
    ),
    _mutation(
        "wait-position-of-the-fence-itself",
        PUSH,
        "        uint32_t position = state_history(state, ring, index, 4u);",
        "        uint32_t position = state_history(state, ring, (index + 1u) & mask, 4u);",
        [*T_PUSH, ORACLE],
        "the position tested is the ENTRY BEFORE the fence's (0x003D6AAB reads it after the decrement): where the fence's segment began.",
    ),
    _mutation(
        "wait-walk-starts-one-entry-on",
        PUSH,
        "    uint32_t index = head;\n",
        "    uint32_t index = (head + 1u) & mask;\n",
        [*T_PUSH, ORACLE],
        "the walk starts at the history's cursor, the newest entry (`mov eax, [esi+0x34]`).",
    ),
    _mutation(
        "wait-low-position-not-shifted",
        PUSH,
        "            position += wrap_delta;",
        "            position += wrap_delta * 0u;",
        [*T_PUSH, ORACLE],
        "a position below the new cursor is on the previous lap: the wrap distance (device+0x44) is added (`add ecx, [esi+0x44]`).",
    ),
    _mutation(
        "wait-position-equal-to-the-cursor-shifted",
        PUSH,
        "        if (position < cursor) {",
        "        if (position <= cursor) {",
        [*T_PUSH, ORACLE],
        "`cmp ecx, edi; jae` skips the shift at equality: a position exactly at the cursor is not on the previous lap.",
    ),
    _mutation(
        "wait-shift-uses-the-stale-distance",
        PUSH,
        "plan.wrapped ? cursor - base : state->wrap_delta;",
        "state->wrap_delta;",
        [*T_PUSH, ORACLE],
        "the wait runs AFTER the wrap stored the new distance (0x003D6A5F): the walk reads that one, not the previous lap's.",
    ),
    _mutation(
        "wait-shift-always-uses-the-new-distance",
        PUSH,
        "plan.wrapped ? cursor - base : state->wrap_delta;",
        "cursor - base;",
        [*T_PUSH, ORACLE],
        "without a wrap the distance is what the last wrap stored at device+0x44, not the cursor's offset in the ring.",
    ),
    _mutation(
        "wait-completed-fence-ignored",
        PUSH,
        "    const uint32_t completed = state_semaphore(state);",
        "    const uint32_t completed = 0u;",
        [*T_PUSH, ORACLE],
        "the semaphore dword (`mov eax, [[esi+0x30]]`) is the last fence the GPU passed: the walk stops at it.",
    ),
    # --- the vertex constants emitter and the split site it plans over (T391, T487) ------------------
    _mutation(
        "vertex-constants-entry-not-previewed",
        PUSH,
        "    const bool entered = sim_enter(sim);",
        "    const bool entered = false;",
        [*T_PUSH, *T_VERTEX, ORACLE_VERTEX_REFILL],
        "at the limit the original rolls over at its entry (0x003D57DE): the packet must land at the new cursor.",
    ),
    _mutation(
        "vertex-constants-real-roll-skipped",
        VERTEX,
        "    if(plan.entered && d3d8_pushbuffer_begin()!=cursor)",
        "    if(false && plan.entered && d3d8_pushbuffer_begin()!=cursor)",
        [*T_VERTEX],
        "the preview alone moves nothing: the limit, the wrap count and the fence packet are the real roll-over's.",
    ),
    _mutation(
        "split-check-after-the-last-unit",
        PUSH,
        "        if (unit == units || position < sim->limit) continue;",
        "        if (position < sim->limit) continue;",
        [*T_PUSH, *T_VERTEX, ORACLE_VERTEX, ORACLE_VERTEX_REFILL],
        "the original never re-checks after the last FULL chunk (0x003D586A, `je 0x003D580D`, and 0x003D5875 `jb 0x003D57FB` before a partial one).",
    ),
    _mutation(
        "split-check-exclusive",
        PUSH,
        "        if (unit == units || position < sim->limit) continue;",
        "        if (unit == units || position <= sim->limit) continue;",
        [*T_PUSH, *T_VERTEX, ORACLE_VERTEX_REFILL],
        "`cmp edi, [limit]; jb` continues only BELOW the limit: a cursor exactly at it refills.",
    ),
    _mutation(
        "split-check-one-early",
        PUSH,
        "        if (unit == units || position < sim->limit) continue;",
        "        if (unit == units || position + 1u < sim->limit) continue;",
        [*T_PUSH, *T_VERTEX, ORACLE_VERTEX_REFILL],
        "a limit one byte above the cursor does not refill: the check is on the cursor, not the cursor plus a byte.",
    ),
    _mutation(
        "vertex-constants-chunk-size",
        VERTEX,
        "    d3d8_pushbuffer_sim_split_site(&sim,entry,8u,4u+16u*4u,count/16u,",
        "    d3d8_pushbuffer_sim_split_site(&sim,entry,8u,64u,count/16u,",
        [*T_VERTEX, ORACLE_VERTEX, ORACLE_VERTEX_REFILL],
        "a full chunk is 0x44 bytes: its header and sixteen dwords.",
    ),
    _mutation(
        "vertex-constants-tail-of-zero-count",
        VERTEX,
        "                                   count==0u?4u:(partial!=0u?4u+partial*4u:0u),&plan);",
        "                                   count==0u?0u:(partial!=0u?4u+partial*4u:0u),&plan);",
        [*T_VERTEX, ORACLE_VERTEX],
        "a zero count still writes its one header dword (0x003D57FB with eax 0).",
    ),
    _mutation(
        "split-head-bytes-not-counted",
        PUSH,
        "    uint32_t position = span_end(entry, sim->cursor, head_bytes);",
        "    uint32_t position = span_end(entry, sim->cursor, 0u);",
        [*T_PUSH, *T_VERTEX, ORACLE_VERTEX_REFILL],
        "the two head dwords (0x41EA4 and the first register) precede the first chunk and count against the limit.",
    ),
    _mutation(
        "split-unit-bytes-short",
        PUSH,
        "        position = span_end(entry, position, unit_bytes);",
        "        position = span_end(entry, position, unit_bytes - 4u);",
        [*T_PUSH, *T_VERTEX, ORACLE_VERTEX_REFILL],
        "every unit advances the cursor by its whole size before the check.",
    ),
    _mutation(
        "split-tail-not-counted",
        PUSH,
        "    position = span_end(entry, position, tail_bytes);",
        "    position = span_end(entry, position, 0u);",
        [*T_PUSH, *T_VERTEX, ORACLE_VERTEX, ORACLE_VERTEX_REFILL],
        "the last partial chunk is part of the second run: its bytes are in the final cursor.",
    ),
    # --- T526: the state a refill leaves for the next one, carried by the plan -----------------------------
    _mutation(
        "carried-put-not-advanced",
        PUSH,
        "    state->put = plan->cursor + fence_bytes;",
        "    state->put = state->put + 0u * fence_bytes;",
        [*T_PUSH, ORACLE_VERTEX_REFILL],
        "a refill's kick leaves GET at the end of its fence packet: the next refill's wait test reads that, not the GET of the original state.",
    ),
    _mutation(
        "carried-put-before-the-fence-packet",
        PUSH,
        "    state->put = plan->cursor + fence_bytes;",
        "    state->put = plan->cursor;",
        [*T_PUSH],
        "the kick comes after the fence packet: GET is the cursor past it (0x003D6B0F calls the kick after 0x003D67B0 returned).",
    ),
    _mutation(
        "carried-wrap-count-not-advanced",
        PUSH,
        "        state->wrap_count++;",
        "        state->wrap_count += 0u;",
        [*T_PUSH],
        "a wrapping refill adds one to the count the next refill's generation (`wrap count - (cursor < GET)`) is made from.",
    ),
    _mutation(
        "carried-wrap-distance-not-stored",
        PUSH,
        "        state->wrap_delta = cursor - d3d8_device_load32(D3D8_DEV_PB_BASE);",
        "        state->wrap_delta = state->wrap_delta + 0u * cursor;",
        [*T_PUSH],
        "a wrap stores how far the cursor had got (device+0x44): the next refill's wait shifts positions below its cursor by it.",
    ),
    _mutation(
        "carried-history-head-not-advanced",
        PUSH,
        "        state->history_cursor = d3d8_device_load32(D3D8_DEV_HISTORY_MASK) & (state->history_cursor + 1u);",
        "        state->history_cursor = d3d8_device_load32(D3D8_DEV_HISTORY_MASK) & state->history_cursor;",
        [*T_PUSH],
        "the fence insertion moves the second history's cursor one entry on (masked) before it writes the entry.",
    ),
    _mutation(
        "carried-history-entry-not-recorded",
        PUSH,
        "        state->history[state->fences++] = entry;",
        "        (void)entry;",
        [*T_PUSH],
        "the entry the refill's fence wrote is the newest one the next refill's walk starts from.",
    ),
    _mutation(
        "carried-history-entry-position",
        PUSH,
        "        const d3d8_pushbuffer_history_entry entry = {state->history_cursor, state->fence_counter, plan->cursor};",
        "        const d3d8_pushbuffer_history_entry entry = {state->history_cursor, state->fence_counter, cursor};",
        [*T_PUSH],
        "the entry's position is where the fence packet was written (the new segment), not where the refill was called.",
    ),
    _mutation(
        "carried-fence-counter-not-advanced",
        PUSH,
        "        state->fence_counter += 2u;",
        "        state->fence_counter += 0u;",
        [*T_PUSH],
        "every fence takes two off the counter (0x003D67B0 adds 2): the next refill's fence and its completion test see it.",
    ),
    _mutation(
        "carried-semaphore-not-raised",
        PUSH,
        "        state->semaphore_known = true;",
        "        state->semaphore_known = false;",
        [*T_PUSH],
        "the kick completes every fence at once under the instantaneous GPU: the semaphore dword holds the last one for the next wait.",
    ),
    _mutation(
        "carried-semaphore-value",
        PUSH,
        "        state->semaphore_value = state->fence_counter - 2u;",
        "        state->semaphore_value = state->fence_counter;",
        [*T_PUSH],
        "the semaphore is the last fence INSERTED (the counter less 2), which the GPU passes at the kick (0x003D6690).",
    ),
    _mutation(
        "carried-history-overlay-ignored",
        PUSH,
        "    for (uint32_t entry = state->fences; entry != 0u; entry--) {",
        "    for (uint32_t entry = 0u; entry != 0u; entry--) {",
        [*T_PUSH],
        "the walk reads the entries the plan's own fences wrote, which are not in guest memory yet.",
    ),
    _mutation(
        "carried-history-overlay-oldest-wins",
        PUSH,
        "    for (uint32_t entry = state->fences; entry != 0u; entry--) {\n        const d3d8_pushbuffer_history_entry *written = &state->history[entry - 1u];",
        "    for (uint32_t entry = 1u; entry <= state->fences; entry++) {\n        const d3d8_pushbuffer_history_entry *written = &state->history[entry - 1u];",
        [*T_PUSH],
        "the history is a ring: when its index comes round again the newest entry at an index is the one in memory.",
    ),
    _mutation(
        "carried-no-fence-without-the-tail",
        PUSH,
        "    if (refill_tail_fn == NULL) return;\n    const uint32_t fence_bytes = refill_fence_bytes_for(flags);",
        "    const uint32_t fence_bytes = refill_fence_bytes_for(flags);",
        [*T_PUSH],
        "without the GPU module no kick and no fence happen: the put and the history are not the plan's to move.",
    ),
    _mutation(
        "carried-state-not-loaded-from-the-device",
        PUSH,
        "    if (!sim->state.loaded) sim->state = refill_state_now();\n",
        "    if (!sim->state.loaded) { memset(&sim->state, 0, sizeof(sim->state)); sim->state.loaded = true; }\n",
        [*T_PUSH, ORACLE_VERTEX_REFILL],
        "the first refill of a plan starts from the device's put, wrap count, fence counter and history cursor.",
    ),
    _mutation(
        "carried-sim-uses-the-device-state-again",
        PUSH,
        "    const refill_plan plan = plan_refill(&sim->state, cursor, half, kickoff, flags);\n    refill_advance(&sim->state, &plan, cursor, flags);",
        "    const refill_state fresh = refill_state_now();\n    const refill_plan plan = plan_refill(&fresh, cursor, half, kickoff, flags);\n    refill_advance(&sim->state, &plan, cursor, flags);",
        [*T_PUSH, ORACLE_VERTEX_REFILL],
        "the second refill of a plan is planned from the state the first left, not the device's (nothing has been written yet).",
    ),
    _mutation(
        "refill-fence-would-refill-itself",
        PUSH,
        "    if (gpu_attached && refill_fence_bytes_for(flags) != 0u && plan.cursor >= plan.limit) {",
        "    if (gpu_attached && refill_fence_bytes_for(flags) != 0u && false) {",
        [*T_PUSH],
        "a segment shorter than the slack would roll the ring over again inside the refill's fence insertion (0x003D67B0 begins with the limit check): not modelled, refused.",
    ),
    # --- the split site: any number of runs --------------------------------------------------------------
    _mutation(
        "split-runs-not-capped",
        PUSH,
        "        if (plan->runs == D3D8_PUSHBUFFER_MAX_RUNS)",
        "        if (plan->runs == D3D8_PUSHBUFFER_MAX_RUNS && false)",
        [*T_PUSH],
        "a site with more refills than the plan holds is refused by name, not written past the run table.",
    ),
    _mutation(
        "split-run-length",
        PUSH,
        "        ended->bytes = position - ended->begin;",
        "        ended->bytes = position - ended->begin + 4u;",
        [*T_PUSH, *T_VERTEX, ORACLE_VERTEX_REFILL],
        "a run ends at the cursor the refill is called with (0x003D5880 stores EDI).",
    ),
    _mutation(
        "split-ignores-the-wrap",
        PUSH,
        "        position = span_end(entry, refill.cursor, ended->fence_bytes);",
        "        position = span_end(entry, position, ended->fence_bytes);",
        [*T_PUSH, *T_VERTEX, ORACLE_VERTEX_REFILL],
        "a wrapping refill restarts at the ring's base: the next run is not where the last one ended.",
    ),
    _mutation(
        "split-ignores-the-fence-packet",
        PUSH,
        "        position = span_end(entry, refill.cursor, ended->fence_bytes);",
        "        position = span_end(entry, refill.cursor, 0u);",
        [*T_PUSH, ORACLE_VERTEX_REFILL],
        "the refill's fence packet sits at the new cursor and the next chunk follows it (0x003D588B returns the cursor after).",
    ),
    _mutation(
        "split-fence-bytes-of-the-no-fence-flag",
        PUSH,
        "        ended->fence_bytes = sim->last_refill.fence_bytes;",
        "        ended->fence_bytes = D3D8_PUSHBUFFER_FENCE_PACKET_BYTES;",
        [*T_PUSH, ORACLE_VERTEX_REFILL],
        "with device flag 0x800 the refill kicks without a fence packet: the next run starts at the new cursor.",
    ),
    _mutation(
        "split-limit-not-moved",
        PUSH,
        "    sim->limit = plan.limit;\n",
        "    (void)plan.limit;\n",
        [*T_PUSH, ORACLE_VERTEX_REFILL],
        "the later checks of the same site compare with the limit the refill set, not the old one.",
    ),
    _mutation(
        "split-wrap-not-reported",
        PUSH,
        "        ended->wraps = refill.wrapped;",
        "        ended->wraps = false;",
        [*T_PUSH, *T_VERTEX],
        "a wrapping refill writes its jump word at the end of the run, which the caller must keep clear.",
    ),
    _mutation(
        "split-refill-wrong-cursor",
        PUSH,
        "        const refill_plan refill = sim_refill(sim, position, kickoff >> 1, kickoff);",
        "        const refill_plan refill = sim_refill(sim, plan->begin, kickoff >> 1, kickoff);",
        [*T_PUSH, *T_VERTEX, ORACLE_VERTEX_REFILL],
        "the refill is called with the cursor after the chunks written, not the packet's first byte.",
    ),
    _mutation(
        "split-refill-not-counted",
        PUSH,
        "    sim->refills++;\n    const d3d8_pushbuffer_refill_spans spans =",
        "    const d3d8_pushbuffer_refill_spans spans =",
        [*T_PUSH],
        "a planner that does not count the refill hides it from callers that refuse any refill.",
    ),
    _mutation(
        "sim-last-refill-not-recorded",
        PUSH,
        "    sim->last_refill = spans;",
        "    (void)spans;",
        [*T_PUSH, *T_PIXEL_CONSTANTS, *T_PIXEL_BIND, ORACLE_PIXEL_REFILL],
        "the jump word and the fence packet of the latest refill are what callers keep their inputs clear of.",
    ),
    _mutation(
        "sim-last-refill-fence-position",
        PUSH,
        "    const d3d8_pushbuffer_refill_spans spans = {cursor, plan.wrapped, plan.cursor, refill_fence_bytes_for(flags)};",
        "    const d3d8_pushbuffer_refill_spans spans = {cursor, plan.wrapped, cursor, refill_fence_bytes_for(flags)};",
        [*T_PUSH, ORACLE_PIXEL_REFILL],
        "the fence packet is at the new cursor (where a wrap restarts), not where the refill was called.",
    ),
    _mutation(
        "split-entry-flag-not-reported",
        PUSH,
        "    const d3d8_pushbuffer_split none = {entered, false, sim->cursor, 1u, {{sim->cursor, 0u, false, 0u}}};",
        "    const d3d8_pushbuffer_split none = {entered && false, false, sim->cursor, 1u, {{sim->cursor, 0u, false, 0u}}};",
        [*T_PUSH, *T_VERTEX, ORACLE_VERTEX_REFILL],
        "the entry roll-over is the real one's to make before the first write: the caller has to be told.",
    ),
    _mutation(
        "split-flag-not-reported",
        PUSH,
        "        plan->split = true;\n",
        "",
        [*T_PUSH, *T_VERTEX, ORACLE_VERTEX_REFILL],
        "a plan with more than one run says so, or the caller writes it as one.",
    ),
    _mutation(
        "refill-at-does-not-publish-the-cursor",
        PUSH,
        "uint32_t d3d8_pushbuffer_refill_at(uint32_t cursor)\n{\n    d3d8_pushbuffer_end(cursor);\n    roll_over();",
        "uint32_t d3d8_pushbuffer_refill_at(uint32_t cursor)\n{\n    (void)cursor;\n    roll_over();",
        [*T_PUSH, *T_VERTEX, ORACLE_VERTEX_REFILL],
        "0x003D5880 stores the cursor before the call: the refill hands [segment start, cursor) to the GPU.",
    ),
    _mutation(
        "refill-at-does-not-roll-over",
        PUSH,
        "uint32_t d3d8_pushbuffer_refill_at(uint32_t cursor)\n{\n    d3d8_pushbuffer_end(cursor);\n    roll_over();",
        "uint32_t d3d8_pushbuffer_refill_at(uint32_t cursor)\n{\n    d3d8_pushbuffer_end(cursor);",
        [*T_PUSH, *T_VERTEX, ORACLE_VERTEX_REFILL],
        "the call 0x003D6B20 is unconditional once the limit check has passed.",
    ),
    _mutation(
        "sim-site-start-after-the-entry",
        PUSH,
        "    (void)sim_enter(sim);\n    return d3d8_pushbuffer_sim_write(sim, entry, bytes);",
        "    const uint32_t start = sim->cursor;\n    (void)sim_enter(sim);\n    (void)d3d8_pushbuffer_sim_write(sim, entry, bytes);\n    return start;",
        [*T_PUSH],
        "the site's commands start after the roll-over's fence packet, which callers check their aliasing against.",
    ),
    _mutation(
        "sim-reserve-not-carried",
        PUSH,
        "    const refill_plan plan = sim_refill(sim, sim->cursor, half, kickoff);\n    sim->cursor = plan.cursor + sim->last_refill.fence_bytes;",
        "    const refill_plan plan = sim_refill(sim, sim->cursor, half, kickoff);\n    sim->cursor = plan.cursor;",
        [*T_PUSH],
        "the sized reservation's roll-over leaves the cursor past the fence packet as the unsized one does.",
    ),
    _mutation(
        "sim-enter-ignores-the-fence-packet",
        PUSH,
        "    const refill_plan plan = sim_refill(sim, sim->cursor, kickoff >> 1, kickoff);\n    sim->cursor = plan.cursor + sim->last_refill.fence_bytes;",
        "    const refill_plan plan = sim_refill(sim, sim->cursor, kickoff >> 1, kickoff);\n    sim->cursor = plan.cursor;",
        [*T_PUSH, ORACLE_VERTEX_REFILL],
        "the entry roll-over's fence packet moves the cursor the site's commands start at.",
    ),
    # --- the vertex constants emitter over the runs --------------------------------------------------------
    _mutation(
        "vertex-constants-split-not-performed",
        VERTEX,
        "        if(d3d8_pushbuffer_refill_at(planned->begin+planned->bytes)!=plan.run[run+1u].begin)",
        "        if(false && d3d8_pushbuffer_refill_at(planned->begin+planned->bytes)!=plan.run[run+1u].begin)",
        [*T_VERTEX, ORACLE_VERTEX_REFILL],
        "the refill between two runs is made, with the first one in the ring.",
    ),
    _mutation(
        "vertex-constants-run-from-the-start",
        VERTEX,
        "        if(!kernel_guest_write_bytes(planned->begin,(const uint8_t *)packet+written,planned->bytes))",
        "        if(!kernel_guest_write_bytes(planned->begin,(const uint8_t *)packet+0u*written,planned->bytes))",
        [*T_VERTEX, ORACLE_VERTEX_REFILL],
        "each run is the packet from where the one before it ended.",
    ),
    _mutation(
        "vertex-constants-run-written-after-its-refill",
        VERTEX,
        "        const d3d8_pushbuffer_run *planned=&plan.run[run];\n        if(!kernel_guest_write_bytes(planned->begin,",
        "        const d3d8_pushbuffer_run *planned=&plan.run[run];\n        if(run+1u!=plan.runs)(void)d3d8_pushbuffer_refill_at(planned->begin+planned->bytes);\n        if(!kernel_guest_write_bytes(planned->begin,",
        [*T_VERTEX, ORACLE_VERTEX_REFILL],
        "the refill hands [segment start, cursor) to the GPU: every run must be in the ring before its refill.",
    ),
    _mutation(
        "vertex-constants-jump-word-not-kept-clear",
        VERTEX,
        "        spans[span_count][0]=planned->begin+planned->bytes;spans[span_count++][1]=planned->wraps?4u:0u;",
        "        spans[span_count][0]=planned->begin+planned->bytes;spans[span_count++][1]=0u;",
        [*T_VERTEX],
        "a source at the end of a run is overwritten by the wrapping refill's jump word before the original reads it.",
    ),
    _mutation(
        "vertex-constants-later-runs-not-kept-clear",
        VERTEX,
        "        spans[span_count][0]=planned->begin;spans[span_count++][1]=planned->bytes;",
        "        spans[span_count][0]=planned->begin;spans[span_count++][1]=run==0u?planned->bytes:0u;",
        [*T_VERTEX],
        "every run is written over what the source or the constant cache holds, not only the first.",
    ),
    _mutation(
        "vertex-constants-planned-bytes-ignore-later-runs",
        VERTEX,
        "    for(uint32_t run=0u;run<plan.runs;run++)planned_bytes+=plan.run[run].bytes;",
        "    for(uint32_t run=0u;run<1u;run++)planned_bytes+=plan.run[run].bytes;",
        [*T_VERTEX, ORACLE_VERTEX_REFILL],
        "the runs together are the whole packet: a plan that loses bytes is refused before any write.",
    ),
    # --- T525: the pixel constant setter (one site per vector) and the pixel binders (one site, or two) ------
    _mutation(
        "pixel-constants-first-vector-only",
        PIXEL_CONSTANTS,
        "        const uint32_t start=d3d8_pushbuffer_sim_site(&sim,ENTRY,bytes);",
        "        const uint32_t start=vector==0u ? d3d8_pushbuffer_sim_site(&sim,ENTRY,bytes) : (sim.cursor+=bytes)-bytes;",
        [*T_PIXEL_CONSTANTS, ORACLE_PIXEL_REFILL],
        "0x003D95B5 checks the limit at EVERY vector, not once per call: a refill falls between vectors.",
    ),
    _mutation(
        "pixel-constants-stage-bytes",
        PIXEL_CONSTANTS,
        "                    bytes+=8u; selected|=1u<<(factor*8u+stage);",
        "                    bytes+=4u; selected|=1u<<(factor*8u+stage);",
        [*T_PIXEL_CONSTANTS, ORACLE_PIXEL_REFILL],
        "a selected stage is a command header and the packed colour: 8 bytes against the limit of the next vector.",
    ),
    _mutation(
        "pixel-constants-register-zero-bytes",
        PIXEL_CONSTANTS,
        "        if (index+vector==0u) bytes+=16u;\n        const uint32_t refills=sim.refills;",
        "        if (index+vector==0u) bytes+=12u;\n        const uint32_t refills=sim.refills;",
        [*T_PIXEL_CONSTANTS, ORACLE_PIXEL_REFILL],
        "register zero adds the raw RGB command: a header and three floats, 16 bytes (0x003D97A9).",
    ),
    _mutation(
        "pixel-constants-jump-word-not-kept-clear",
        PIXEL_CONSTANTS,
        "            spans[span_count][0]=sim.last_refill.at; spans[span_count++][1]=sim.last_refill.wraps ? 4u : 0u;",
        "            spans[span_count][0]=sim.last_refill.at; spans[span_count++][1]=0u;",
        [*T_PIXEL_CONSTANTS, ORACLE_PIXEL_REFILL],
        "a wrapping refill writes its jump word at the end of the previous vector: a source there is read after it.",
    ),
    _mutation(
        "pixel-constants-fence-packet-not-kept-clear",
        PIXEL_CONSTANTS,
        "            spans[span_count][0]=sim.last_refill.fence_begin; spans[span_count++][1]=sim.last_refill.fence_bytes;",
        "            spans[span_count][0]=sim.last_refill.fence_begin; spans[span_count++][1]=0u;",
        [*T_PIXEL_CONSTANTS, ORACLE_PIXEL_REFILL],
        "the refill's fence packet is written before the next vector reads its floats: a source there changes.",
    ),
    _mutation(
        "pixel-constants-only-the-first-refill-kept-clear",
        PIXEL_CONSTANTS,
        "        if (sim.refills!=refills) {\n            /* What the refill itself writes: the jump word",
        "        if (sim.refills!=refills && vector==0u) {\n            /* What the refill itself writes: the jump word",
        [*T_PIXEL_CONSTANTS, ORACLE_PIXEL_REFILL],
        "every vector's refill writes outside its commands, not only the first call's.",
    ),
    _mutation(
        "pixel-constants-site-not-recorded",
        PIXEL_CONSTANTS,
        "        plan->site[vector]=start;",
        "        plan->site[vector]=sim.cursor;",
        [*T_PIXEL_CONSTANTS, ORACLE_PIXEL_REFILL],
        "the plan says where each vector starts, which the real refill must reproduce.",
    ),
    _mutation(
        "pixel-constants-vector-span-not-kept-clear",
        PIXEL_CONSTANTS,
        "        spans[span_count][0]=start; spans[span_count++][1]=bytes;",
        "        spans[span_count][0]=start; spans[span_count++][1]=vector==0u ? bytes : 0u;",
        [*T_PIXEL_CONSTANTS, ORACLE_PIXEL_REFILL],
        "every vector's commands are written over what the float4 array or the usage table holds.",
    ),
    _mutation(
        "pixel-constants-ring-extent",
        PIXEL_CONSTANTS,
        "(uint64_t)start+bytes>ring[1]))",
        "(uint64_t)start+bytes>ring[1]+0x400u))",
        [*T_PIXEL_CONSTANTS],
        "a vector that would run past the ring's end is refused (the original lets it write beyond).",
    ),
    _mutation(
        "pixel-bind-ring-extent",
        PIXEL_BIND,
        "(uint64_t)start+site_bytes[site]>ring_end || start<ring_base",
        "(uint64_t)start+site_bytes[site]>ring_end+0x400u || start<ring_base",
        [*T_PIXEL_BIND],
        "a site that would run past the ring's end is refused (the original lets it write beyond).",
    ),
    _mutation(
        "pixel-bind-null-shader-one-site",
        PIXEL_BIND,
        "    else { site_bytes[sites++]=68u; site_bytes[sites++]=92u; }",
        "    else { site_bytes[sites++]=160u; }",
        [*T_PIXEL_BIND, ORACLE_PIXEL_REFILL],
        "the null shader checks the limit twice: before the factor restore and again before the rows (0x003D9374).",
    ),
    _mutation(
        "pixel-bind-factor-restore-bytes",
        PIXEL_BIND,
        "    else { site_bytes[sites++]=68u; site_bytes[sites++]=92u; }",
        "    else { site_bytes[sites++]=64u; site_bytes[sites++]=96u; }",
        [*T_PIXEL_BIND, ORACLE_PIXEL_REFILL],
        "0x003D7150 writes a header and sixteen factors, 68 bytes, before the second check.",
    ),
    _mutation(
        "pixel-bind-shader-bytes",
        PIXEL_BIND,
        "    if (argument) site_bytes[sites++]=240u+(inputs ? 12u : 0u)+(rows_needed ? 84u : 0u);",
        "    if (argument) site_bytes[sites++]=240u+(inputs ? 12u : 0u);",
        [*T_PIXEL_BIND, ORACLE_PIXEL_REFILL],
        "binding from the null shader writes the three programmable rows (84 bytes) first, under the same check.",
    ),
    _mutation(
        "pixel-bind-second-site-not-planned",
        PIXEL_BIND,
        "    for (unsigned site=0u;site<sites;site++) {\n        const uint32_t refills=sim.refills;",
        "    for (unsigned site=0u;site<1u;site++) {\n        const uint32_t refills=sim.refills;",
        [*T_PIXEL_BIND, ORACLE_PIXEL_REFILL],
        "the second site of the null shader is planned from what the first one's refill left.",
    ),
    _mutation(
        "pixel-bind-jump-word-not-kept-clear",
        PIXEL_BIND,
        "            spans[span_count][0]=sim.last_refill.at; spans[span_count++][1]=sim.last_refill.wraps ? 4u : 0u;",
        "            spans[span_count][0]=sim.last_refill.at; spans[span_count++][1]=0u;",
        [*T_PIXEL_BIND, ORACLE_PIXEL_REFILL],
        "a wrapping refill writes its jump word before the definition is read: a definition there changes.",
    ),
    _mutation(
        "pixel-bind-fence-packet-not-kept-clear",
        PIXEL_BIND,
        "            spans[span_count][0]=sim.last_refill.fence_begin; spans[span_count++][1]=sim.last_refill.fence_bytes;",
        "            spans[span_count][0]=sim.last_refill.fence_begin; spans[span_count++][1]=0u;",
        [*T_PIXEL_BIND, ORACLE_PIXEL_REFILL],
        "the refill's fence packet is written before the definition is read: a definition there changes.",
    ),
    _mutation(
        "pixel-bind-site-not-recorded",
        PIXEL_BIND,
        "        plan->site[site]=start;",
        "        plan->site[site]=sim.cursor;",
        [*T_PIXEL_BIND, ORACLE_PIXEL_REFILL],
        "the plan says where each site starts, which the real refill must reproduce.",
    ),
    _mutation(
        "pixel-bind-site-span-not-kept-clear",
        PIXEL_BIND,
        "        spans[span_count][0]=start; spans[span_count++][1]=site_bytes[site];",
        "        spans[span_count][0]=start; spans[span_count++][1]=site==0u ? site_bytes[site] : 0u;",
        [*T_PIXEL_BIND, ORACLE_PIXEL_REFILL],
        "the second site's commands are written over the definition or the wrapper like the first's.",
    ),
    # --- the scissors: one check at the entry, the packet after the refill (T546) ---------------------------------
    _mutation(
        "scissor-start-ignores-the-refill",
        SCISSOR,
        "    const uint32_t start=d3d8_pushbuffer_sim_site(&sim,ENTRY,36u);",
        "    const uint32_t start=d3d8_device_load32(D3D8_DEV_CURSOR);(void)d3d8_pushbuffer_sim_site(&sim,ENTRY,36u);",
        [*T_SCISSOR, ORACLE_SCISSOR_REFILL],
        "the packet follows the refill's fence packet, not the cursor the call was entered with.",
    ),
    _mutation(
        "scissor-refill-not-made",
        SCISSOR,
        "    if (d3d8_pushbuffer_begin()!=start)",
        "    if (d3d8_device_load32(D3D8_DEV_CURSOR)!=start && false)",
        [*T_SCISSOR, ORACLE_SCISSOR_REFILL],
        "a planned refill has to be performed: the limit, the jump word, the fence packet and the hand-off.",
    ),
    _mutation(
        "scissor-jump-word-not-kept-clear",
        SCISSOR,
        "        if ((spans->wraps && aliased(rectangles,spans->at,4u)) ||",
        "        if ((false && aliased(rectangles,spans->at,4u)) ||",
        [*T_SCISSOR, ORACLE_SCISSOR_REFILL],
        "the original reads the rectangle after the wrap wrote its jump word: a rectangle there is read changed.",
    ),
    _mutation(
        "scissor-fence-packet-not-kept-clear",
        SCISSOR,
        "            (spans->fence_bytes!=0u && aliased(rectangles,spans->fence_begin,spans->fence_bytes)))",
        "            (false && aliased(rectangles,spans->fence_begin,spans->fence_bytes)))",
        [*T_SCISSOR, ORACLE_SCISSOR_REFILL],
        "the refill's fence packet is written before the rectangle is read: a rectangle there is read changed.",
    ),
    _mutation(
        "scissor-packet-not-kept-clear-of-the-rectangle",
        SCISSOR,
        "        aliased(rectangles,start,36u))",
        "        false)",
        [*T_SCISSOR, ORACLE_SCISSOR_REFILL],
        "the packet's own 36 bytes over the rectangle change what is read for the later words.",
    ),
    _mutation(
        "scissor-cursor-published-short",
        SCISSOR,
        "    d3d8_pushbuffer_end(start+36u);",
        "    d3d8_pushbuffer_end(start+32u);",
        [*T_SCISSOR, ORACLE_SCISSOR_REFILL],
        "the cursor ends after the whole 36-byte packet.",
    ),
    # --- the fog packet after the vertex-program helper: two sites, a real begin() between them (T546) -------------
    _mutation(
        "fog-reservation-not-planned",
        FOG,
        "    (void)d3d8_pushbuffer_sim_reserve(sim, reserve_dwords);",
        "    (void)reserve_dwords;",
        [*T_FOG, ORACLE_FOG_REFILL],
        "the helper writes under the sized reservation 0x003D6B30(count + 30), which refills when the cursor is 200 bytes or more past the limit.",
    ),
    _mutation(
        "fog-reservation-not-made",
        FOG,
        "        cursor = d3d8_pushbuffer_reserve(reserve);",
        "        cursor = d3d8_device_load32(D3D8_DEV_CURSOR);",
        [*T_FOG, ORACLE_FOG_REFILL],
        "a planned reservation refill has to be performed before the helper writes.",
    ),
    _mutation(
        "fog-reservation-size",
        FOG,
        "    *reserve_out = count + 30u;",
        "    *reserve_out = count + 29u;",
        [*T_FOG, ORACLE_FOG_REFILL],
        "0x003D5C94 reserves `count + 0x1E` dwords: one fewer moves the boundary the original refills at by four bytes.",
    ),
    _mutation(
        "fog-helper-not-published",
        FOG,
        "        cursor += program * 4u;\n        d3d8_pushbuffer_end(cursor);",
        "        cursor += program * 4u;\n        (void)cursor;",
        [*T_FOG, ORACLE_FOG_REFILL],
        "the helper publishes its cursor (0x003D5D3A) before the fog packet's own check reads it.",
    ),
    _mutation(
        "fog-site-has-no-preamble",
        FOG,
        "    sites->fog = d3d8_pushbuffer_sim_site(sim, 0x003DDEA0u, fog_words * 4u);\n    check_refill_spans(sim, refills);",
        "    sites->fog = d3d8_pushbuffer_sim_write(sim, 0x003DDEA0u, fog_words * 4u);\n    check_refill_spans(sim, refills);",
        [*T_FOG, ORACLE_FOG_REFILL],
        "the fog packet has its own `cmp [cursor], [limit]` (0x003DDF80) after the helper: a refill falls between the two.",
    ),
    _mutation(
        "fog-no-helper-site-has-no-preamble",
        FOG,
        "        sites->fog = d3d8_pushbuffer_sim_site(sim, 0x003DDEA0u, fog_words * 4u);\n        fog_span",
        "        sites->fog = d3d8_pushbuffer_sim_write(sim, 0x003DDEA0u, fog_words * 4u);\n        fog_span",
        [*T_FOG, ORACLE_FOG_REFILL],
        "without the helper the single preamble (0x003DE017) still rolls the ring over before the packet.",
    ),
    _mutation(
        "fog-planned-on-a-fresh-simulation",
        FOG,
        "    plan_fog_sites(sim, program, reserve, total - program, &sites);",
        "    d3d8_pushbuffer_sim fresh = d3d8_pushbuffer_sim_start();\n    plan_fog_sites(&fresh, program, reserve, total - program, &sites);\n    (void)sim;",
        [*T_FOG, ORACLE_FOG_REFILL],
        "the fog site is planned from what the refills before it in the cascade left (GET, wrap, fences), not from the device.",
    ),
    _mutation(
        "fog-helper-overlap-not-checked",
        FOG,
        "    helper_output_span(sites->helper, program_words * 4u);",
        "    (void)helper_output_span;",
        [*T_FOG],
        "command storage over an input the port snapshots would change what the original reads while it writes.",
    ),
    # --- the indexed draw: one simulation for the cascade, the reservations and the groups (T546) -------------------
    _mutation(
        "indexed-deferred-not-planned",
        INDEXED,
        "    d3d8_draw_plan_deferred(&sim,base_vertex);",
        "    (void)base_vertex;",
        [*T_INDEXED, ORACLE_INDEXED_REFILL],
        "the draw's packet starts where the cascade and the stream work leave the cursor, refills included.",
    ),
    _mutation(
        "indexed-flag-not-planned",
        INDEXED,
        "    d3d8_pushbuffer_sim_set_flags(&sim,d3d8_pushbuffer_sim_flags(&sim)|FLAG_IN_DRAW);",
        "    (void)d3d8_pushbuffer_sim_flags(&sim);",
        [*T_INDEXED, ORACLE_INDEXED_REFILL],
        "device flag 0x800 is set before the first reservation, so a refill there inserts no fence packet.",
    ),
    _mutation(
        "indexed-first-reservation-not-planned",
        INDEXED,
        "    (void)d3d8_pushbuffer_sim_reserve(&sim,0x209u);",
        "    (void)sim.cursor;",
        [*T_INDEXED, ORACLE_INDEXED_REFILL],
        "the draw reserves 0x209 dwords before its header, which rolls the ring over when they do not fit.",
    ),
    _mutation(
        "indexed-first-reservation-size",
        INDEXED,
        "    (void)d3d8_pushbuffer_sim_reserve(&sim,0x209u);",
        "    (void)d3d8_pushbuffer_sim_reserve(&sim,0x208u);",
        [*T_INDEXED, ORACLE_INDEXED_REFILL],
        "0x003D5076 pushes 0x209: one dword fewer moves the refill boundary by four bytes.",
    ),
    _mutation(
        "indexed-first-reservation-not-made",
        INDEXED,
        "    if(d3d8_pushbuffer_reserve(0x209u)!=start)",
        "    if(d3d8_device_load32(D3D8_DEV_CURSOR)!=start)",
        [*T_INDEXED, ORACLE_INDEXED_REFILL],
        "a planned reservation refill has to be performed before the header is written.",
    ),
    _mutation(
        "indexed-group-reservation-not-made",
        INDEXED,
        "        return d3d8_pushbuffer_reserve(0x204u);",
        "        return d3d8_device_load32(D3D8_DEV_CURSOR);",
        [*T_INDEXED, ORACLE_INDEXED_REFILL],
        "the reservation between two groups (0x003D5209) rolls the ring over where the first group left too little.",
    ),
    _mutation(
        "indexed-group-cursor-not-published",
        INDEXED,
        "        d3d8_pushbuffer_end((uint32_t)position);",
        "        (void)position;",
        [*T_INDEXED, ORACLE_INDEXED_REFILL],
        "the group's end is published (0x003D5207) before the reservation reads the cursor.",
    ),
    _mutation(
        "indexed-group-reservation-size",
        INDEXED,
        "    (void)d3d8_pushbuffer_sim_reserve(plan,0x204u);",
        "    (void)d3d8_pushbuffer_sim_reserve(plan,0x203u);",
        [*T_INDEXED, ORACLE_INDEXED_REFILL],
        "0x003D51FC pushes 0x204: one dword fewer moves the refill boundary by four bytes.",
    ),
    _mutation(
        "indexed-flag-not-set-in-the-draw",
        INDEXED,
        "    d3d8_device_store32(D3D8_DEV_FLAGS,d3d8_device_load32(D3D8_DEV_FLAGS)|FLAG_IN_DRAW);",
        "    d3d8_device_store32(D3D8_DEV_FLAGS,d3d8_device_load32(D3D8_DEV_FLAGS));",
        [*T_INDEXED, ORACLE_INDEXED_REFILL],
        "a refill inside the draw runs under flag 0x800: no fence packet, flag 0x1000 left behind.",
    ),
    _mutation(
        "indexed-end-fence-not-inserted",
        INDEXED,
        "    if((finished&FLAG_REFILLED)!=0u)return d3d8_gpu_fence_insert(1u);",
        "    if((finished&FLAG_REFILLED)!=0u && false)return d3d8_gpu_fence_insert(1u);",
        [*T_INDEXED, ORACLE_INDEXED_REFILL],
        "a refill under flag 0x800 left 0x1000, which the draw answers with one fence at its end (0x003D529A).",
    ),
    _mutation(
        "indexed-flags-not-cleared",
        INDEXED,
        "    d3d8_device_store32(D3D8_DEV_FLAGS,finished&~FLAG_KICKOFF);",
        "    d3d8_device_store32(D3D8_DEV_FLAGS,finished&~FLAG_IN_DRAW);",
        [*T_INDEXED, ORACLE_INDEXED_REFILL],
        "the draw clears 0x800 and 0x1000 (0x003D5288 `and edx, 0xFFFFE7FF`).",
    ),
    _mutation(
        "indexed-index-data-not-kept-clear",
        INDEXED,
        "           (count!=0u && overlaps(begin,bytes,index_data,count*2u)))",
        "           (false && overlaps(begin,bytes,index_data,count*2u)))",
        [*T_INDEXED, ORACLE_INDEXED_REFILL],
        "the original reads the indices after every refill wrote its jump word and fence packet and the draw is laid out after them.",
    ),
    _mutation(
        "sim-span-not-merged",
        PUSH,
        "        if ((uint64_t)last->begin + last->bytes == begin) {",
        "        if ((uint64_t)last->begin + last->bytes == begin && false) {",
        [*T_PUSH],
        "spans that touch are one span: a plan of a refill per site would otherwise run out of them.",
    ),
    _mutation(
        "sim-jump-word-not-recorded",
        PUSH,
        "    if (plan.wrapped) sim_note(sim, 0x003D6B20u, cursor, 4u);",
        "    if (plan.wrapped) sim_note(sim, 0x003D6B20u, cursor, 0u);",
        [*T_PUSH, ORACLE_INDEXED_REFILL],
        "a wrapping refill writes its jump word at the old cursor: a caller checks it against what it reads.",
    ),
    _mutation(
        "sim-fence-packet-not-recorded",
        PUSH,
        "    sim_note(sim, 0x003D6B20u, plan.cursor, spans.fence_bytes);",
        "    sim_note(sim, 0x003D6B20u, plan.cursor, 0u);",
        [*T_PUSH, ORACLE_INDEXED_REFILL],
        "the refill's fence packet is written at the new cursor: a caller checks it against what it reads.",
    ),
    _mutation(
        "sim-flag-0x1000-not-left",
        PUSH,
        "        d3d8_pushbuffer_sim_set_flags(sim, flags | 0x1000u);",
        "        d3d8_pushbuffer_sim_set_flags(sim, flags);",
        [*T_PUSH],
        "a refill whose tail ran under flag 0x800 leaves 0x1000, which the indexed draw answers with a fence.",
    ),
    _mutation(
        "sim-refill-ignores-the-plan-flags",
        PUSH,
        "    const d3d8_pushbuffer_refill_spans spans = {cursor, plan.wrapped, plan.cursor, refill_fence_bytes_for(flags)};",
        "    const d3d8_pushbuffer_refill_spans spans = {cursor, plan.wrapped, plan.cursor, refill_fence_bytes_for(0u)};",
        [*T_PUSH, ORACLE_INDEXED_REFILL],
        "a refill under flag 0x800 inserts no fence packet.",
    ),
    _mutation(
        "sim-flags-not-carried",
        PUSH,
        "    sim->flags_set = true;\n    sim->flags = flags;",
        "    sim->flags_set = false;\n    sim->flags = flags;",
        [*T_PUSH, ORACLE_INDEXED_REFILL],
        "the plan's refills see the flags the plan was given, not the device's.",
    ),
    _mutation(
        "indexed-stream-work-not-planned",
        "src/gpu/d3d8_resource.c",
        "        d3d8_pushbuffer_sim_site(sim, 0x003D5050u, stream_bytes);",
        "        (void)stream_bytes;",
        [*T_INDEXED, ORACLE_INDEXED_REFILL],
        "the stream work after the cascade has its own preamble and its bytes move what follows it.",
    ),
    _mutation(
        "indexed-entry-kickoff-flag-dropped",
        INDEXED,
        "    d3d8_device_store32(D3D8_DEV_FLAGS,d3d8_device_load32(D3D8_DEV_FLAGS)|FLAG_IN_DRAW);",
        "    d3d8_device_store32(D3D8_DEV_FLAGS,(d3d8_device_load32(D3D8_DEV_FLAGS)&~FLAG_REFILLED)|FLAG_IN_DRAW);",
        [*T_INDEXED, ORACLE_INDEXED_REFILL],
        "0x003D5076 only ORs 0x800: flag 0x1000 left by an earlier refill is kept and answered with a fence at the end.",
    ),
    # --- T579: the fixed vertex constants emitter 0x003D5720, planned over `d3d8_pushbuffer_sim_checked_site` ------
    _mutation(
        "checked-site-boundary-exclusive",
        PUSH,
        "    while ((uint32_t)(sim->cursor + bytes) >= sim->limit) {",
        "    while ((uint32_t)(sim->cursor + bytes) > sim->limit) {",
        [*T_PUSH, ORACLE_FOUR_REFILL],
        "`add eax, 0x4c; cmp eax, [limit]; jae` refills at EQUALITY: a limit exactly 76 bytes on refills.",
    ),
    _mutation(
        "checked-site-packet-short",
        PUSH,
        "    while ((uint32_t)(sim->cursor + bytes) >= sim->limit) {",
        "    while ((uint32_t)(sim->cursor + bytes - 4u) >= sim->limit) {",
        [*T_PUSH, ORACLE_FOUR_REFILL],
        "the test is on the cursor plus the WHOLE 0x4c bytes: one dword fewer moves the boundary the original refills at.",
    ),
    _mutation(
        "checked-site-single-pass",
        PUSH,
        "    while ((uint32_t)(sim->cursor + bytes) >= sim->limit) {",
        "    if ((uint32_t)(sim->cursor + bytes) >= sim->limit) {",
        [*T_PUSH, ORACLE_FOUR_REFILL],
        "0x003D57BD jumps back to the top: the test is made again from the new cursor and limit, so a call refills until the packet fits.",
    ),
    _mutation(
        "checked-site-fence-packet-not-skipped",
        PUSH,
        "        sim->cursor = span_end(entry, refill.cursor, fence_bytes);",
        "        sim->cursor = span_end(entry, refill.cursor, 0u);",
        [*T_PUSH, ORACLE_FOUR_REFILL],
        "the refill's fence packet is written at the new cursor and the next test starts past it.",
    ),
    _mutation(
        "checked-site-packet-end-not-counted",
        PUSH,
        "    const uint32_t end = span_end(entry, sim->cursor, bytes);",
        "    const uint32_t end = span_end(entry, sim->cursor, 0u);",
        [*T_PUSH],
        "the packet's bytes are in the plan's final cursor.",
    ),
    _mutation(
        "checked-site-packet-not-at-the-last-run",
        PUSH,
        "    plan->begin = plan->run[plan->runs - 1u].begin;",
        "    plan->begin = plan->run[0].begin;",
        [*T_PUSH, ORACLE_FOUR_REFILL],
        "the packet lands after the LAST refill (the new segment's start, past a wrap), not at the cursor the call began with.",
    ),
    _mutation(
        "checked-site-packet-not-recorded",
        PUSH,
        "    sim_note(sim, entry, plan->begin, bytes);",
        "    sim_note(sim, entry, plan->begin, 0u);",
        [*T_PUSH],
        "the packet is one of the spans the plan writes.",
    ),
    _mutation(
        "four-constants-packet-short",
        VERTEX,
        "    d3d8_pushbuffer_sim_checked_site(&sim,entry,packet_bytes,&plan);",
        "    d3d8_pushbuffer_sim_checked_site(&sim,entry,packet_bytes-4u,&plan);",
        [*T_VERTEX, ORACLE_FOUR, ORACLE_FOUR_REFILL],
        "the packet is 0x4c bytes: the header pair, the 0x400B80 header and sixteen dwords.",
    ),
    _mutation(
        "four-constants-source-not-reloaded",
        VERTEX,
        "    if (plan.split && !kernel_guest_read_bytes(data,packet+3,source_bytes))",
        "    if (false && plan.split && !kernel_guest_read_bytes(data,packet+3,source_bytes))",
        [*T_VERTEX, ORACLE_FOUR_REFILL],
        "the eight MMX loads (0x003D5739) come AFTER the refills: a source a refill wrote is the bytes it left.",
    ),
    _mutation(
        "four-constants-last-refill-skipped",
        VERTEX,
        "    for (uint32_t run=0u;run+1u<plan.runs;run++) {",
        "    for (uint32_t run=0u;run+2u<plan.runs;run++) {",
        [*T_VERTEX, ORACLE_FOUR, ORACLE_FOUR_REFILL],
        "every refill the plan makes is made, the last of a chain included.",
    ),
    _mutation(
        "four-constants-refill-at-the-wrong-cursor",
        VERTEX,
        "        if (d3d8_pushbuffer_refill_at(plan.run[run].begin)!=plan.run[run+1u].begin)",
        "        if (d3d8_pushbuffer_refill_at(plan.run[run].begin+4u)!=plan.run[run+1u].begin)",
        [*T_VERTEX, ORACLE_FOUR, ORACLE_FOUR_REFILL],
        "the refill is called with the cursor the call found, nothing having been written before it.",
    ),
    _mutation(
        "four-constants-packet-overlap-allowed",
        VERTEX,
        "        overlap(data,source_bytes,cursor,packet_bytes))",
        "        (overlap(data,source_bytes,cursor,packet_bytes) && false))",
        [*T_VERTEX, ORACLE_FOUR, ORACLE_FOUR_REFILL],
        "a source inside the packet's own bytes stays refused: the port does not take the original's load-then-store order apart.",
    ),
    _mutation(
        "four-constants-cursor-published-short",
        VERTEX,
        "    d3d8_pushbuffer_end(cursor+packet_bytes);",
        "    d3d8_pushbuffer_end(cursor+packet_bytes-4u);",
        [*T_VERTEX, ORACLE_FOUR, ORACLE_FOUR_REFILL],
        "0x003D5734 stores the cursor plus 0x4c.",
    ),
    # --- T734: 0x003D57D0, the same emitter without the shadow and without the flags test ------------------------
    _mutation(
        "plain-constants-write-the-shadow",
        VERTEX,
        "const bool writes_shadow=shadowed && (control[2]&0x10u)==0u;",
        "const bool writes_shadow=(control[2]&0x10u)==0u;",
        [*T_VERTEX, ORACLE_VERTEX, ORACLE_VERTEX_REFILL],
        "0x003D57D0 never writes the CPU shadow (that is the point of the variant): the whole D3D region is compared.",
    ),
    _mutation(
        "plain-constants-write-the-shadow-even-flagged",
        VERTEX,
        "const bool writes_shadow=shadowed && (control[2]&0x10u)==0u;",
        "const bool writes_shadow=shadowed || (control[2]&0x10u)==0u;",
        [*T_VERTEX, ORACLE_VERTEX, ORACLE_VERTEX_REFILL],
        "the shadowed 0x003D58B0 skips the shadow under device flag 0x10, and the plain one writes none, flag or not.",
    ),
    _mutation(
        "plain-constants-shadow-source-refused",
        VERTEX,
        "    if((source_bytes!=0u && data>UINT32_MAX-source_bytes) ||\n"
        "       (shadowed && overlap(data,source_bytes,D3D8_CONSTANT_SHADOW,MAX_WORDS*4u)) ||",
        "    if((source_bytes!=0u && data>UINT32_MAX-source_bytes) ||\n"
        "       overlap(data,source_bytes,D3D8_CONSTANT_SHADOW,MAX_WORDS*4u) ||",
        [*T_VERTEX, ORACLE_VERTEX],
        "the original only reads a source inside the shadow when it writes none, so the plain variant takes it.",
    ),
    _mutation(
        "plain-constants-handler-is-the-shadowed-one",
        VERTEX,
        "    return upload_vertex_constants(ENTRY_PLAIN,false,index,data,count);",
        "    return upload_vertex_constants(ENTRY_PLAIN,true,index,data,count);",
        [*T_VERTEX, ORACLE_VERTEX, ORACLE_VERTEX_REFILL],
        "the plain entry point must be the plain emitter.",
    ),
    _mutation(
        "plain-constants-not-registered",
        VERTEX,
        "           (size_t)d3d8_hle_register(ENTRY_PLAIN,plain_handler);",
        "           (size_t)(false && d3d8_hle_register(ENTRY_PLAIN,plain_handler));",
        [*T_VERTEX],
        "the boot stops at 0x003D57D0 (XDK function with no implementation) without the registration.",
    ),
    _mutation(
        "plain-constants-refusal-names-the-wrong-entry",
        VERTEX,
        "    return upload_vertex_constants(ENTRY_PLAIN,false,index,data,count);",
        "    return upload_vertex_constants(ENTRY,false,index,data,count);",
        [*T_VERTEX],
        "a refusal names the address of the function that was called.",
    ),
    _mutation(
        "plain-constants-handler-reads-the-wrong-count",
        VERTEX,
        "    return d3d8_upload_vertex_constants_unshadowed(index,data,count);",
        "    return d3d8_upload_vertex_constants_unshadowed(index,data,count+1u);",
        [*T_VERTEX],
        "the count is the one stack dword of the call.",
    ),
]
