# ruff: noqa: E501
"""Mutations for T743 and T764: asynchronous (overlapped) NtReadFile completion on the virtual clock.

The module (`src/xbox/kernel_async_io.c`) decides WHEN a queued read becomes visible to the title, and the title's
file service only advances on the PENDING shape (tests/test_file_service_pump_oracle.py). A wrong eligibility rule, a
completion that is early, out of order or half written, a lost Event, or a third stream Pause caller admitted without the
completion model each changes what the title sees without any crash, so every entry below is a defect a suite must notice.
`tsfp_host` is not a ctest binary: the main.c wiring (flag, announce, hook install) is covered by
tests/test_async_file_io_boot.py instead (its `async-io-file-object` wiring was mutated by hand: dropping
`kernel_async_io_set_file_object_enabled` fails `test_event_less_reads_signal_the_file_object...`).

T764 adds the blocking waits, the file object signal of an Event-less read and the by-name APC refusal. A wait that
advances the clock one tick too far, completes the wrong request, forgets a timeout, or an object signalled by the wrong
read changes what the title sees without a crash, so those entries are checked by `tests/c/test_kernel_async_io.c`, and
the retail wrapper contract they serve is pinned by `tests/test_overlapped_waits_oracle.py`.
"""

MUTATIONS: list[dict] = [
    {
        "id": "async-io-sync-success-does-not-set-event",
        "file": "src/xbox/kernel_io.c",
        "old": "    if (event_handle != 0u) {\n        const nt_status event_status = kernel_object_event_set(event_handle, NULL);",
        "new": "    if (false && event_handle != 0u) {\n        const nt_status event_status = kernel_object_event_set(event_handle, NULL);",
        "targets": ["test_kernel_async_io"],
        "why": "T763 observes a buffered asynchronous STATUS_SUCCESS with its Event signalled; the native test keeps the neighbouring handle clear.",
    },
    {
        "id": "async-io-eligible-ignores-the-flag",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    return kernel_async_io_enabled() &&\n           (event_handle != 0u ||",
        "new": "    return (kernel_async_io_enabled() || true) &&\n           (event_handle != 0u ||",
        "targets": ["test_kernel_async_io"],
        "why": "the flag is the opt-in: ignoring it queues reads in every default boot and changes their byte identity.",
    },
    {
        "id": "async-io-eligible-ignores-the-event",
        "file": "src/xbox/kernel_async_io.c",
        "old": "(event_handle != 0u || kernel_async_io_file_object_enabled());",
        "new": "(event_handle != 0u || true);",
        "targets": ["test_kernel_async_io"],
        "why": "a read with no Event is only queued under --async-file-io-file-object: otherwise the title would wait on a file object nothing signals.",
    },
    {
        "id": "async-io-eligible-ignores-buffering",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    if ((open_options & KERNEL_ASYNC_IO_NO_BUFFERING_OPTION) == 0u) {\n        return false;\n    }\n",
        "new": "",
        "targets": ["test_kernel_async_io"],
        "why": "xemu completes a buffered asynchronous read inside NtReadFile (T763): PENDING needs FILE_NO_INTERMEDIATE_BUFFERING.",
    },
    {
        "id": "async-io-eligible-ignores-synchronous-handles",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    if ((open_options & KERNEL_ASYNC_IO_SYNCHRONOUS_OPTIONS) != 0u) {\n        return false;\n    }\n    if ((open_options & KERNEL_ASYNC_IO_NO_BUFFERING_OPTION) == 0u) {",
        "new": "    if ((open_options & KERNEL_ASYNC_IO_NO_BUFFERING_OPTION) == 0u) {",
        "targets": ["test_kernel_async_io"],
        "why": "a synchronous handle completes inside NtReadFile on the original: returning PENDING breaks every blocking read.",
    },
    {
        "id": "async-io-ticks-drop-the-access-time",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    return access + transfer;",
        "new": "    return (access & 0u) + transfer;",
        "targets": ["test_kernel_async_io"],
        "why": "the access time is part of the stated INFERRED timing, a request of zero bytes would complete at once.",
    },
    {
        "id": "async-io-ticks-drop-the-transfer-time",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    return access + transfer;",
        "new": "    return access + (transfer & 0u);",
        "targets": ["test_kernel_async_io"],
        "why": "a large read would complete as fast as a small one.",
    },
    {
        "id": "async-io-ticks-round-the-transfer-down",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    const uint64_t transfer = ((uint64_t)bytes * frequency + rate - 1u) / rate;",
        "new": "    const uint64_t transfer = ((uint64_t)bytes * frequency) / rate;",
        "targets": ["test_kernel_async_io"],
        "why": "rounded down a request can complete a tick early, which the title could observe as a completion before its time.",
    },
    {
        "id": "async-io-ticks-ignore-the-volume",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    const bool hdd = volume == KERNEL_ASYNC_IO_VOLUME_HDD;",
        "new": "    const bool hdd = volume == KERNEL_ASYNC_IO_VOLUME_HDD || volume == KERNEL_ASYNC_IO_VOLUME_DISC;",
        "targets": ["test_kernel_async_io"],
        "why": "T763: the disc and the HDD were measured separately, a request on the disc must take the disc's time.",
    },
    {
        "id": "async-io-ticks-swap-the-volumes",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    const bool hdd = volume == KERNEL_ASYNC_IO_VOLUME_HDD;",
        "new": "    const bool hdd = volume != KERNEL_ASYNC_IO_VOLUME_HDD;",
        "targets": ["test_kernel_async_io"],
        "why": "T763: a swapped volume gives the disc's constants to the HDD and the reverse.",
    },
    {
        "id": "async-io-request-volume-always-disc",
        "file": "src/xbox/kernel_io.c",
        "old": "        .volume = kernel_async_io_volume_of_path(file->path),",
        "new": "        .volume = KERNEL_ASYNC_IO_VOLUME_DISC,",
        "targets": ["test_kernel_async_io"],
        "why": "T763: the volume must come from the file the title opened, not a fixed drive.",
    },
    {
        "id": "async-io-volume-of-path-drops-the-harddisk-device",
        "file": "src/xbox/kernel_async_io.c",
        "old": '    if (path_has_prefix(path, "\\\\Device\\\\Harddisk")) {',
        "new": '    if (false && path_has_prefix(path, "\\\\Device\\\\Harddisk")) {',
        "targets": ["test_kernel_async_io"],
        "why": "T763: \\Device\\Harddisk0\\Partition1 is the HDD, classifying it as the disc gives it the disc's time.",
    },
    {
        "id": "async-io-volume-of-path-drops-the-case-fold",
        "file": "src/xbox/kernel_async_io.c",
        "old": "        const char a = (*path >= 'a' && *path <= 'z') ? (char)(*path - 'a' + 'A') : *path;",
        "new": "        const char a = *path;",
        "targets": ["test_kernel_async_io"],
        "why": "T763: NT paths are case-insensitive, \\DEVICE\\HARDDISK0 is the same drive.",
    },
    {
        "id": "async-io-volume-of-path-drops-the-drive-letters",
        "file": "src/xbox/kernel_async_io.c",
        "old": '        if (strchr("CEFXYZ", letter) != NULL) {',
        "new": '        if (strchr("", letter) != NULL) {',
        "targets": ["test_kernel_async_io"],
        "why": "T763: E: is the HDD, only D: is the disc.",
    },
    {
        "id": "async-io-drive-is-parallel",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    const uint64_t start = drive_free_ticks > now ? drive_free_ticks : now;",
        "new": "    const uint64_t start = now;",
        "targets": ["test_kernel_async_io"],
        "why": "one drive serves one request at a time: a parallel drive completes two reads together.",
    },
    {
        "id": "async-io-queue-refusal-not-counted",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    if (slot == NULL) {\n        stats.refused++;\n",
        "new": "    if (slot == NULL) {\n",
        "targets": ["test_kernel_async_io"],
        "why": "a refusal that is not counted reads as a title that never asked.",
    },
    {
        "id": "async-io-completion-skips-the-copy",
        "file": "src/xbox/kernel_async_io.c",
        "old": "            memcpy(destination, read->data, read->length);",
        "new": "            (void)destination;",
        "targets": ["test_kernel_async_io"],
        "why": "the title would read a buffer the read never filled.",
    },
    {
        "id": "async-io-completion-reports-the-requested-length",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    uint32_t information = read->length;",
        "new": "    uint32_t information = read->requested;",
        "targets": ["test_kernel_async_io"],
        "why": "the title compares InternalHigh with the length it asked for: an end of file read would look complete.",
    },
    {
        "id": "async-io-completion-skips-the-io-status",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    write_result(read, status, information);\n",
        "new": "    (void)write_result;\n    (void)status;\n    (void)information;\n",
        "targets": ["test_kernel_async_io"],
        "why": "GetOverlappedResult polls this word: without it the request stays pending forever.",
    },
    {
        "id": "async-io-completion-skips-the-event",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    const nt_status set = kernel_object_event_set(read->event_handle, &previous);",
        "new": "    const nt_status set = STATUS_SUCCESS;\n    (void)previous;",
        "targets": ["test_kernel_async_io"],
        "why": "a title that waits on the OVERLAPPED's event (GetOverlappedResult with wait) would hang.",
    },
    {
        "id": "async-io-completion-newest-first",
        "file": "src/xbox/kernel_async_io.c",
        "old": "queue[i].due_ticks < oldest->due_ticks",
        "new": "queue[i].due_ticks > oldest->due_ticks",
        "targets": ["test_kernel_async_io"],
        "why": "the drive completes in issue order: a later request blocking an earlier one reorders what the title sees.",
    },
    {
        "id": "async-io-clock-frame-hook-not-called",
        "file": "src/xbox/kernel_clock.c",
        "old": "    if (hook != NULL) {\n        hook();\n    }",
        "new": "    (void)hook;",
        "targets": ["test_kernel_async_io"],
        "why": "the virtual vblank is the title's per frame service point: without it a pending read waits for the next NtReadFile.",
    },
    {
        "id": "async-io-read-does-not-service-first",
        "file": "src/xbox/kernel_io.c",
        "old": "    if (kernel_async_io_enabled()) {\n        (void)kernel_async_io_service();\n    }",
        "new": "    (void)0;",
        "targets": ["test_kernel_async_io"],
        "why": "the second service point: a clock that moved past a due request completes it at the next read.",
    },
    {
        "id": "async-io-read-returns-success",
        "file": "src/xbox/kernel_io.c",
        "old": "    return STATUS_PENDING;\n}",
        "new": "    return STATUS_SUCCESS;\n}",
        "targets": ["test_kernel_async_io"],
        "why": "SUCCESS makes the title's ReadFile wrapper return TRUE and the pump re-issue the read forever (the T743 wait).",
    },
    {
        "id": "async-io-read-oversize-queued",
        "file": "src/xbox/kernel_io.c",
        "old": "    const bool queued = length != 0u && length <= KERNEL_ASYNC_IO_MAX_BYTES &&\n                        ",
        "new": "    const bool queued = ",
        "targets": ["test_kernel_async_io"],
        "why": "the byte bound keeps the host copy small and zero-length reads complete synchronously; dropping either condition changes a tested boundary.",
    },
    {
        "id": "async-io-read-implicit-offset-not-advanced",
        "file": "src/xbox/kernel_io.c",
        "old": "        (void)kernel_file_open_set_offset(file_handle, offset + got);\n    }\n    lock();\n    read_count++;",
        "new": "    }\n    lock();\n    read_count++;",
        "targets": ["test_kernel_async_io"],
        "why": "the position moves at issue: a second implicit read would return the first one's data.",
    },
    {
        "id": "async-io-read-unmapped-destination-queued",
        "file": "src/xbox/kernel_io.c",
        "old": "    if (got != 0u && kernel_guest_at(buffer, got) == NULL) {",
        "new": "    if (got != 0u && kernel_guest_at(buffer, got) == NULL && false) {",
        "targets": ["test_kernel_async_io"],
        "why": "a bad destination must be refused at issue, not discovered at completion where nobody can be told.",
    },
    {
        "id": "async-io-open-options-not-recorded",
        "file": "src/xbox/kernel_file.c",
        "old": "    slot->state.open_options = open_options;",
        "new": "    slot->state.open_options = open_options & 0u;",
        "targets": ["test_kernel_async_io"],
        "why": "every handle would look asynchronous, including the synchronous ones the title blocks on.",
    },
    {
        "id": "stream-pause-start-caller-admitted-without-the-model",
        "file": "src/audio/dsound_stream.c",
        "old": "(!third_admitted || third==0u || actual!=third)",
        "new": "(!(third_admitted || true) || third==0u || actual!=third)",
        "targets": ["test_dsound_stream_start_caller"],
        "why": "with the completion model off the start caller is as unmeasured as any other: default boots must keep refusing it.",
    },
    {
        "id": "stream-pause-start-caller-not-admitted",
        "file": "src/audio/dsound_stream.c",
        "old": "(!third_admitted || third==0u || actual!=third)",
        "new": "(true || third_admitted || third)",
        "targets": ["test_dsound_stream_start_caller"],
        "why": "the title's stream start (sub_00029EE0, return 0x29F13) is the next call after the first packet.",
    },
    {
        "id": "stream-pause-refusal-drops-the-caller",
        "file": "src/audio/dsound_stream.c",
        "old": 'static char reason[96];\n        const bool have=frame!=NULL && kernel_guest_read_u32(frame->stack_ptr,&actual);\n        (void)snprintf(reason,sizeof reason,"only measured startup caller is supported, got caller %#x",have?actual:0u);',
        "new": 'static char reason[96];\n        const bool have=frame!=NULL && kernel_guest_read_u32(frame->stack_ptr,&actual);\n        (void)snprintf(reason,sizeof reason,"only measured startup caller is supported, got caller %#x",have?actual&0u:0u);',
        "targets": ["test_dsound_stream_start_caller"],
        "why": "the refusal must name the actual return address, as the Play refusal of T722 does.",
    },
    {
        "id": "async-io-option-never-sets-the-flag",
        "file": "src/host/host_options.c",
        "old": '--async-file-io") == 0) {\n            out->async_file_io = true;',
        "new": '--async-file-io") == 0) {\n            out->async_file_io = false;',
        "targets": ["test_host_options"],
        "why": "the opt-in must reach the host: a flag that parses and does nothing reads as a model that failed.",
    },
    # ---- T764: file object, eligibility ----
    {
        "id": "async-io-file-object-eligible-without-the-base-flag",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    return kernel_async_io_enabled() &&\n           (event_handle != 0u ||",
        "new": "    return (kernel_async_io_enabled() || kernel_async_io_file_object_enabled()) &&\n           (event_handle != 0u ||",
        "targets": ["test_kernel_async_io"],
        "why": "--async-file-io-file-object needs --async-file-io: a lone sub-flag must not queue reads.",
    },
    {
        "id": "async-io-apc-refusal-ignores-the-flag",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    const bool refused = enabled;",
        "new": "    const bool refused = true;",
        "targets": ["test_kernel_async_io"],
        "why": "with the flag off an ApcRoutine keeps its old reported-not-called completion, byte identical.",
    },
    {
        "id": "async-io-apc-refusal-ignores-the-handle-kind",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    if (apc_routine == 0u || (open_options & KERNEL_ASYNC_IO_SYNCHRONOUS_OPTIONS) != 0u) {",
        "new": "    if (apc_routine == 0u || (open_options & 0u) != 0u) {",
        "targets": ["test_kernel_async_io"],
        "why": "a synchronous handle is not the model's: refusing its APC read changes a read that always worked.",
    },
    {
        "id": "async-io-apc-refusal-not-counted",
        "file": "src/xbox/kernel_async_io.c",
        "old": "        stats.apc_refused++;\n",
        "new": "",
        "targets": ["test_kernel_async_io"],
        "why": "a refusal that is not counted reads as a title that never passed an ApcRoutine.",
    },
    {
        "id": "async-io-read-apc-refusal-not-applied",
        "file": "src/xbox/kernel_io.c",
        "old": "    if (kernel_async_io_apc_refused(file.open_options, apc_routine)) {",
        "new": "    if (false && kernel_async_io_apc_refused(file.open_options, apc_routine)) {",
        "targets": ["test_kernel_async_io"],
        "why": "an ApcRoutine the host cannot deliver must not be completed behind the title's back under the model.",
    },
    {
        "id": "async-io-read-apc-refusal-returns-success",
        "file": "src/xbox/kernel_io.c",
        "old": '        (void)write_io_status(io_status, STATUS_NOT_IMPLEMENTED, 0u, "NtReadFile");\n        return STATUS_NOT_IMPLEMENTED;',
        "new": '        (void)write_io_status(io_status, STATUS_SUCCESS, 0u, "NtReadFile");\n        return STATUS_SUCCESS;',
        "targets": ["test_kernel_async_io"],
        "why": "a refusal that says SUCCESS is a read that never happened reported as done.",
    },
    {
        "id": "async-io-file-object-signal-set-at-issue",
        "file": "src/xbox/kernel_async_io.c",
        "old": "        object->signalled = false;\n        stats.file_object_reads++;",
        "new": "        object->signalled = true;\n        stats.file_object_reads++;",
        "targets": ["test_kernel_async_io"],
        "why": "a file object signalled at issue lets a waiter run before the data is there.",
    },
    {
        "id": "async-io-file-object-signal-not-cleared-at-issue",
        "file": "src/xbox/kernel_async_io.c",
        "old": "        object->signalled = false;\n        stats.file_object_reads++;",
        "new": "        stats.file_object_reads++;",
        "targets": ["test_kernel_async_io"],
        "why": "the NT I/O manager clears the file object when a request is issued: a stale signal lets the next wait return early.",
    },
    {
        "id": "async-io-file-object-signal-never-set",
        "file": "src/xbox/kernel_async_io.c",
        "old": "            object->signalled = true;",
        "new": "            object->signalled = false;",
        "targets": ["test_kernel_async_io"],
        "why": "the retail wrappers wait on the file handle: a file object nothing signals hangs them.",
    },
    {
        "id": "async-io-file-object-keyed-by-raw-handle",
        "file": "src/xbox/kernel_async_io.c",
        "old": "        identity = kernel_object_file_identity(request->file_handle);",
        "new": "        identity = request->file_handle;",
        "targets": ["test_kernel_async_io"],
        "why": "a duplicate handle is the same file object: keyed by handle, a wait through the duplicate never ends.",
    },
    {
        "id": "async-io-file-object-table-never-reuses-a-dead-file",
        "file": "src/xbox/kernel_async_io.c",
        "old": "        if (reusable == NULL && !kernel_object_file_identity_live(entry->identity)) {",
        "new": "        if (false && reusable == NULL && !kernel_object_file_identity_live(entry->identity)) {",
        "targets": ["test_kernel_async_io"],
        "why": "files come and go: a table that never reclaims a closed file's entry refuses every read after the 64th open.",
    },
    {
        "id": "async-io-file-object-table-reuses-a-live-file",
        "file": "src/xbox/kernel_async_io.c",
        "old": "        if (reusable == NULL && !kernel_object_file_identity_live(entry->identity)) {",
        "new": "        if (reusable == NULL) {",
        "targets": ["test_kernel_async_io"],
        "why": "reusing a live file's entry loses its signal: its next wait would block for a read that completed.",
    },
    {
        "id": "async-io-file-object-table-reuses-a-busy-file",
        "file": "src/xbox/kernel_async_io.c",
        "old": "            if (!busy) {\n                reusable = entry;\n            }",
        "new": "            reusable = entry;",
        "targets": ["test_kernel_async_io"],
        "why": "an entry with a request still pending is the one its completion signals: reusing it signals another file's object.",
    },
    {
        "id": "async-io-file-object-table-too-small",
        "file": "src/xbox/kernel_async_io.c",
        "old": "#define FILE_OBJECT_TABLE 64u",
        "new": "#define FILE_OBJECT_TABLE 63u",
        "targets": ["test_kernel_async_io"],
        "why": "kernel_file allows 64 open files: a smaller table refuses a read the title can legitimately issue.",
    },
    {
        "id": "async-io-file-object-table-refusal-not-counted",
        "file": "src/xbox/kernel_async_io.c",
        "old": "        if (object == NULL) {\n            stats.refused++;\n",
        "new": "        if (object == NULL) {\n",
        "targets": ["test_kernel_async_io"],
        "why": "a read refused for want of a file object slot must be counted like a full queue.",
    },
    {
        "id": "thread-file-wait-would-block-filed-as-unsupported-scope",
        "file": "src/xbox/kernel_thread.c",
        "old": "    refuse_wait(handle, KERNEL_THREAD_WAIT_WOULD_BLOCK, callback);\n}\n\nstatic uint32_t wait_single_object",
        "new": "    refuse_wait(handle, KERNEL_THREAD_WAIT_UNSUPPORTED_SCOPE, callback);\n}\n\nstatic uint32_t wait_single_object",
        "targets": ["test_kernel_async_io"],
        "why": "WOULD_BLOCK names the missing scheduler: a file wait nothing pending ends is that gap, not an unsupported scope.",
    },
    # ---- T764: blocking waits ----
    {
        "id": "async-io-wait-ignores-the-flag",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    if (!kernel_async_io_enabled()) {\n        return KERNEL_ASYNC_WAIT_NONE;\n    }\n    const uint64_t start",
        "new": "    const uint64_t start",
        "targets": ["test_kernel_async_io"],
        "why": "the wait is part of the opt-in model: off, a wait must keep its old named refusal and move no clock.",
    },
    {
        "id": "async-io-wait-advances-one-tick-past-the-due-time",
        "file": "src/xbox/kernel_async_io.c",
        "old": "        (void)kernel_clock_advance_to(due);\n        advanced = true;",
        "new": "        (void)kernel_clock_advance_to(due + 1u);\n        advanced = true;",
        "targets": ["test_kernel_async_io"],
        "why": "NEVER past the due time: a title that reads the clock around its wait sees time that did not pass.",
    },
    {
        "id": "async-io-wait-advances-to-the-last-due-time",
        "file": "src/xbox/kernel_async_io.c",
        "old": "(found == NULL || queue[i].due_ticks < found->due_ticks)",
        "new": "(found == NULL || queue[i].due_ticks > found->due_ticks)",
        "targets": ["test_kernel_async_io"],
        "why": "the wait ends at the FIRST request that signals the object, not the last one queued behind it.",
    },
    {
        "id": "async-io-wait-matches-any-pending-request",
        "file": "src/xbox/kernel_async_io.c",
        "old": "        const bool match = by_event ? queue[i].read.event_handle == key",
        "new": "        const bool match = by_event ? true",
        "targets": ["test_kernel_async_io"],
        "why": "a wait on one Event advancing the clock for another Event's request completes work nobody awaited.",
    },
    {
        "id": "async-io-wait-file-matches-event-requests",
        "file": "src/xbox/kernel_async_io.c",
        "old": "                                    : queue[i].read.event_handle == 0u &&\n                                          queue[i].file_identity == key;",
        "new": "                                    : queue[i].file_identity == key;",
        "targets": ["test_kernel_async_io"],
        "why": "an Event read signals its Event, never the file object: matching it hangs or wakes the wrong waiter.",
    },
    {
        "id": "async-io-wait-deadline-rounded-down",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    return (timeout_100ns * frequency + 9999999u) / 10000000u;",
        "new": "    return (timeout_100ns * frequency) / 10000000u;",
        "targets": ["test_kernel_async_io"],
        "why": "a timeout that ends a tick early is a wait that returns before the time the title asked for.",
    },
    {
        "id": "async-io-wait-ignores-the-timeout",
        "file": "src/xbox/kernel_async_io.c",
        "old": "        if (due > deadline) {",
        "new": "        if (due > deadline && false) {",
        "targets": ["test_kernel_async_io"],
        "why": "a finite wait that outlasts its timeout hides a read the title decided to give up on.",
    },
    {
        "id": "async-io-wait-timeout-advances-to-the-due-time",
        "file": "src/xbox/kernel_async_io.c",
        "old": "            (void)kernel_clock_advance_to(deadline);",
        "new": "            (void)kernel_clock_advance_to(due);",
        "targets": ["test_kernel_async_io"],
        "why": "a timed out wait must stop at its deadline: advancing to the request completes it and returns a timeout.",
    },
    {
        "id": "async-io-wait-timeout-does-not-service",
        "file": "src/xbox/kernel_async_io.c",
        "old": "            (void)kernel_async_io_service();\n            result = KERNEL_ASYNC_WAIT_TIMED_OUT;",
        "new": "            result = KERNEL_ASYNC_WAIT_TIMED_OUT;",
        "targets": ["test_kernel_async_io"],
        "why": "requests due before the deadline (other waiters' reads) complete while the clock passes them.",
    },
    {
        "id": "async-io-wait-timeout-not-counted",
        "file": "src/xbox/kernel_async_io.c",
        "old": "        stats.wait_timeouts++;",
        "new": "        (void)stats;",
        "targets": ["test_kernel_async_io"],
        "why": "a counter that misses timeouts reads as waits that all succeeded.",
    },
    {
        "id": "async-io-wait-counts-a-wait-that-did-not-advance",
        "file": "src/xbox/kernel_async_io.c",
        "old": "    bool advanced = false;",
        "new": "    bool advanced = true;",
        "targets": ["test_kernel_async_io"],
        "why": "`blocking waits` counts the waits that moved the clock, not an object already signalled.",
    },
    {
        "id": "async-io-wait-never-reports-signalled",
        "file": "src/xbox/kernel_async_io.c",
        "old": "        if (signalled) {\n            result = KERNEL_ASYNC_WAIT_SATISFIED;",
        "new": "        if (signalled && false) {\n            result = KERNEL_ASYNC_WAIT_SATISFIED;",
        "targets": ["test_kernel_async_io"],
        "why": "an object already signalled satisfies a wait at once, with no clock movement.",
    },
    # ---- T764: the clock primitive ----
    {
        "id": "clock-advance-to-goes-backwards",
        "file": "src/xbox/kernel_clock.c",
        "old": "    if (now_ticks < ticks) {\n        now_ticks = ticks;\n    }",
        "new": "    now_ticks = ticks;",
        "targets": ["test_kernel_async_io"],
        "why": "the counter is strictly monotone: a wait must never put a time earlier than one the title has read.",
    },
    {
        "id": "clock-advance-to-ignores-the-frame-floor",
        "file": "src/xbox/kernel_clock.c",
        "old": "uint64_t kernel_clock_advance_to(uint64_t ticks)\n{\n    pthread_mutex_lock(&clock_lock);\n    if (now_ticks < floor_ticks) {\n        now_ticks = floor_ticks;\n    }\n",
        "new": "uint64_t kernel_clock_advance_to(uint64_t ticks)\n{\n    pthread_mutex_lock(&clock_lock);\n",
        "targets": ["test_kernel_async_io"],
        "why": "the counter never reads below the frame floor: advancing from below it loses the frames already passed.",
    },
    # ---- T764: the kernel_thread wait paths ----
    {
        "id": "thread-event-wait-poll-skips-the-model",
        "file": "src/xbox/kernel_thread.c",
        "old": "    if (kind == KERNEL_OBJECT_EVENT && (timeout_pointer == 0u || (int64_t)timeout <= 0)) {",
        "new": "    if (kind == KERNEL_OBJECT_EVENT && (timeout_pointer == 0u || (int64_t)timeout < 0)) {",
        "targets": ["test_kernel_async_io"],
        "why": "a poll must still complete a read that is already due, or the title polls a request that finished.",
    },
    {
        "id": "thread-event-wait-timeout-reports-success",
        "file": "src/xbox/kernel_thread.c",
        "old": "        if (waited == KERNEL_ASYNC_WAIT_TIMED_OUT) {\n            return THREAD_WAIT_TIMEOUT;\n        }\n        if (waited == KERNEL_ASYNC_WAIT_SATISFIED) {",
        "new": "        if (waited == KERNEL_ASYNC_WAIT_TIMED_OUT) {\n            return STATUS_SUCCESS;\n        }\n        if (waited == KERNEL_ASYNC_WAIT_SATISFIED) {",
        "targets": ["test_kernel_async_io"],
        "why": "a timed out wait that says SUCCESS makes the title read an IoStatusBlock that is still pending.",
    },
    {
        "id": "thread-event-wait-does-not-consume-the-event",
        "file": "src/xbox/kernel_thread.c",
        "old": "            (void)kernel_object_event_try_wait(handle, &acquired_now);\n            if (acquired_now) {\n                return STATUS_SUCCESS;\n            }",
        "new": "            (void)acquired_now;\n            return STATUS_SUCCESS;",
        "targets": ["test_kernel_async_io"],
        "why": "an auto-reset Event satisfies exactly one wait: a still signalled Event wakes the next waiter wrongly.",
    },
    {
        "id": "thread-file-wait-served-with-the-flag-off",
        "file": "src/xbox/kernel_thread.c",
        "old": "    if (live && object.kind == KERNEL_OBJECT_FILE && kernel_async_io_enabled()) {",
        "new": "    if (live && object.kind == KERNEL_OBJECT_FILE) {",
        "targets": ["test_kernel_async_io"],
        "why": "with the flag off a wait on a file handle keeps its original named scope refusal.",
    },
    {
        "id": "thread-file-wait-refuses-a-poll",
        "file": "src/xbox/kernel_thread.c",
        "old": "    if (waited == KERNEL_ASYNC_WAIT_TIMED_OUT || (timeout_pointer != 0u && timeout == 0u)) {",
        "new": "    if (waited == KERNEL_ASYNC_WAIT_TIMED_OUT) {",
        "targets": ["test_kernel_async_io"],
        "why": "a poll of an unsignalled file object is STATUS_TIMEOUT, never a refusal.",
    },
    {
        "id": "thread-file-wait-serves-an-absolute-timeout",
        "file": "src/xbox/kernel_thread.c",
        "old": "    if (timeout_pointer != 0u && (int64_t)timeout > 0) {\n        refuse_wait(handle, KERNEL_THREAD_WAIT_UNSUPPORTED_SCOPE, callback);",
        "new": "    if (timeout_pointer != 0u && (int64_t)timeout > 0 && false) {\n        refuse_wait(handle, KERNEL_THREAD_WAIT_UNSUPPORTED_SCOPE, callback);",
        "targets": ["test_kernel_async_io"],
        "why": "an absolute timeout is host wall time, not the virtual clock: it stays refused by name.",
    },
    {
        "id": "thread-file-wait-satisfied-reports-timeout",
        "file": "src/xbox/kernel_thread.c",
        "old": "    if (waited == KERNEL_ASYNC_WAIT_SATISFIED) {\n        return STATUS_SUCCESS;\n    }\n    if (waited == KERNEL_ASYNC_WAIT_TIMED_OUT ||",
        "new": "    if (waited == KERNEL_ASYNC_WAIT_SATISFIED) {\n        return THREAD_WAIT_TIMEOUT;\n    }\n    if (waited == KERNEL_ASYNC_WAIT_TIMED_OUT ||",
        "targets": ["test_kernel_async_io"],
        "why": "the retail wrapper reads the IoStatusBlock only after a non-negative wait status: a timeout here means not done.",
    },
    # ---- T764: host options ----
    {
        "id": "async-io-file-object-option-never-sets-the-flag",
        "file": "src/host/host_options.c",
        "old": "            out->async_file_io_file_object = true;",
        "new": "            out->async_file_io_file_object = false;",
        "targets": ["test_host_options"],
        "why": "the sub-flag must reach the host: a flag that parses and does nothing reads as a model that failed.",
    },
    {
        "id": "async-io-file-object-option-needs-no-base-flag",
        "file": "src/host/host_options.c",
        "old": "        (!out->async_file_io_file_object || out->async_file_io) &&\n",
        "new": "",
        "targets": ["test_host_options"],
        "why": "the file object reads are a refinement of --async-file-io, not a second way to turn the model on.",
    },
]
