# ruff: noqa: E501
"""Mutations for the live texture module (T792): `src/gpu/live_texture.c`, checked by `test_live_texture`.

Grouped by what a survivor would let through: plan (format word fields, size ranges, the INFERRED gate), swizzle (Morton
interleave and the long side tail), decode (565, DXT1 transparent mode, DXT3 nibbles, DXT5 ramps, uncompressed channel
order and alpha), cache (range overlap edges, invalidation, generation and upload flags), target (T510 exact, alias and
ambiguous rules) and census (dedupe key and counts). `plan.swizzled` in the target layout check is subsumed by the pitch check (a swizzled plan has pitch 0), so no mutant is
listed for it. The decode oracle is the replay decoder frozen verbatim inside the test.
"""

MUTATIONS: list[dict] = [
    {
        "id": "live-texture-plan-measured-dxt1",
        "file": "src/gpu/live_texture.c",
        "old": "        if (exponent_u > 11u",
        "new": "        if (exponent_u > 12u",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the plan-measured-dxt1 rule",
    },
    {
        "id": "live-texture-dxt-min-exponent",
        "file": "src/gpu/live_texture.c",
        "old": "exponent_u < (plan->compressed ? 2u : 0u)",
        "new": "exponent_u < (plan->compressed ? 1u : 0u)",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the dxt-min-exponent rule",
    },
    {
        "id": "live-texture-levels-one",
        "file": "src/gpu/live_texture.c",
        "old": "if (levels != 1u) {",
        "new": "if (levels > 1u) {",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the levels-one rule",
    },
    {
        "id": "live-texture-cube-bit",
        "file": "src/gpu/live_texture.c",
        "old": "const bool cube = ((format >> 2) & 1u) != 0u;",
        "new": "const bool cube = ((format >> 2) & 1u) != 1u;",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the cube-bit rule",
    },
    {
        "id": "live-texture-dims-two",
        "file": "src/gpu/live_texture.c",
        "old": "((format >> 4) & 0xFu) != 2u",
        "new": "((format >> 4) & 0xFu) != 1u",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the dims-two rule",
    },
    {
        "id": "live-texture-inferred-gate",
        "file": "src/gpu/live_texture.c",
        "old": "if (!row->measured && !allow_inferred) {",
        "new": "if (!row->measured && allow_inferred) {",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the inferred-gate rule",
    },
    {
        "id": "live-texture-linear-pitch-shift",
        "file": "src/gpu/live_texture.c",
        "old": "(((binding->size_word >> 24) & 0xFFu) + 1u) << 6",
        "new": "(((binding->size_word >> 24) & 0xFFu) + 1u) << 5",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the linear-pitch-shift rule",
    },
    {
        "id": "live-texture-linear-pitch-check",
        "file": "src/gpu/live_texture.c",
        "old": "plan->pitch < plan->width * row->bytes",
        "new": "plan->pitch <= plan->width * row->bytes",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the linear-pitch-check rule",
    },
    {
        "id": "live-texture-swizzle-y-bit",
        "file": "src/gpu/live_texture.c",
        "old": "offset |= ((y >> bit) & 1u) << (2u * bit + 1u);",
        "new": "offset |= ((y >> bit) & 1u) << (2u * bit);",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the swizzle-y-bit rule",
    },
    {
        "id": "live-texture-swizzle-tail-x",
        "file": "src/gpu/live_texture.c",
        "old": "offset |= (x >> shared) << (2u * shared);",
        "new": "offset |= (x >> shared) << (2u * shared + 1u);",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the swizzle-tail-x rule",
    },
    {
        "id": "live-texture-swizzle-tail-y",
        "file": "src/gpu/live_texture.c",
        "old": "offset |= (y >> shared) << (2u * shared);",
        "new": "offset |= (y >> shared) << (2u * shared + 1u);",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the swizzle-tail-y rule",
    },
    {
        "id": "live-texture-dxt1-three-colour",
        "file": "src/gpu/live_texture.c",
        "old": "const bool four = !dxt1 || color0 > color1;",
        "new": "const bool four = color0 > color1;",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the dxt1-three-colour rule",
    },
    {
        "id": "live-texture-dxt1-transparent",
        "file": "src/gpu/live_texture.c",
        "old": "palette[3][3] = four ? 255u : 0u;",
        "new": "palette[3][3] = 255u;",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the dxt1-transparent rule",
    },
    {
        "id": "live-texture-dxt-interp-2",
        "file": "src/gpu/live_texture.c",
        "old": "(2u * palette[0][channel] + palette[1][channel]) / 3u",
        "new": "(palette[0][channel] + 2u * palette[1][channel]) / 3u",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the dxt-interp-2 rule",
    },
    {
        "id": "live-texture-dxt3-nibble",
        "file": "src/gpu/live_texture.c",
        "old": "alpha[texel] = (uint8_t)(nibble * 17u);",
        "new": "alpha[texel] = (uint8_t)(nibble * 16u);",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the dxt3-nibble rule",
    },
    {
        "id": "live-texture-dxt3-nibble-order",
        "file": "src/gpu/live_texture.c",
        "old": "(block[texel / 2u] >> (4u * (texel & 1u))) & 15u",
        "new": "(block[texel / 2u] >> (4u * (1u - (texel & 1u)))) & 15u",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the dxt3-nibble-order rule",
    },
    {
        "id": "live-texture-dxt5-ramp8",
        "file": "src/gpu/live_texture.c",
        "old": "ramp[1u + step] = ((7u - step) * ramp[0] + step * ramp[1]) / 7u;",
        "new": "ramp[1u + step] = ((6u - step) * ramp[0] + step * ramp[1]) / 6u;",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the dxt5-ramp8 rule",
    },
    {
        "id": "live-texture-dxt5-ramp6-end",
        "file": "src/gpu/live_texture.c",
        "old": "ramp[7] = 255u;",
        "new": "ramp[7] = 254u;",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the dxt5-ramp6-end rule",
    },
    {
        "id": "live-texture-dxt5-mode",
        "file": "src/gpu/live_texture.c",
        "old": "if (ramp[0] > ramp[1]) {",
        "new": "if (ramp[0] >= ramp[1] + 1000u) {",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the dxt5-mode rule",
    },
    {
        "id": "live-texture-dxt5-bits",
        "file": "src/gpu/live_texture.c",
        "old": "bits |= (uint64_t)block[2u + byte] << (8u * byte);",
        "new": "bits |= (uint64_t)block[2u + byte] << (7u * byte);",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the dxt5-bits rule",
    },
    {
        "id": "live-texture-dxt-colour-offset",
        "file": "src/gpu/live_texture.c",
        "old": "plan->kind == LIVE_TEXTURE_DXT1 ? block : block + 8",
        "new": "plan->kind == LIVE_TEXTURE_DXT1 ? block : block + 0",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the dxt-colour-offset rule",
    },
    {
        "id": "live-texture-565-green",
        "file": "src/gpu/live_texture.c",
        "old": "out[1] = (uint8_t)((green << 2) | (green >> 4));",
        "new": "out[1] = (uint8_t)((green << 2) | (green >> 5));",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the 565-green rule",
    },
    {
        "id": "live-texture-argb-order",
        "file": "src/gpu/live_texture.c",
        "old": "out[0] = (uint8_t)(word >> 16);",
        "new": "out[0] = (uint8_t)(word);",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the argb-order rule",
    },
    {
        "id": "live-texture-x8-alpha",
        "file": "src/gpu/live_texture.c",
        "old": "out[3] = kind == LIVE_TEXTURE_A8R8G8B8 ? (uint8_t)(word >> 24) : 255u;",
        "new": "out[3] = (uint8_t)(word >> 24);",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the x8-alpha rule",
    },
    {
        "id": "live-texture-a1-alpha",
        "file": "src/gpu/live_texture.c",
        "old": "(word & 0x8000u) == 0u ? 0u : 255u",
        "new": "(word & 0x8000u) == 0u ? 255u : 0u",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the a1-alpha rule",
    },
    {
        "id": "live-texture-a4-scale",
        "file": "src/gpu/live_texture.c",
        "old": "(((word >> 12) & 15u) * 17u)",
        "new": "(((word >> 12) & 15u) * 16u)",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the a4-scale rule",
    },
    {
        "id": "live-texture-ay8-alpha",
        "file": "src/gpu/live_texture.c",
        "old": "out[0] = out[1] = out[2] = out[3] = (uint8_t)word;",
        "new": "out[0] = out[1] = out[2] = (uint8_t)word; out[3] = 255u;",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the ay8-alpha rule",
    },
    {
        "id": "live-texture-linear-row-pitch",
        "file": "src/gpu/live_texture.c",
        "old": "(size_t)y * plan->pitch + (size_t)x * bytes",
        "new": "(size_t)y * plan->width * bytes + (size_t)x * bytes",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the linear-row-pitch rule",
    },
    {
        "id": "live-texture-decode-short",
        "file": "src/gpu/live_texture.c",
        "old": "source_length < plan->source_bytes",
        "new": "source_length + 1u < plan->source_bytes",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the decode-short rule",
    },
    {
        "id": "live-texture-write-overlap-end",
        "file": "src/gpu/live_texture.c",
        "old": "(uint64_t)address < (uint64_t)entry->read_address + entry->plan.source_bytes",
        "new": "(uint64_t)address <= (uint64_t)entry->read_address + entry->plan.source_bytes",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the write-overlap-end rule",
    },
    {
        "id": "live-texture-write-overlap-start",
        "file": "src/gpu/live_texture.c",
        "old": "(uint64_t)entry->read_address < (uint64_t)address + bytes) ||",
        "new": "(uint64_t)entry->read_address <= (uint64_t)address + bytes) ||",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the write-overlap-start rule",
    },
    {
        "id": "live-texture-write-no-invalidate",
        "file": "src/gpu/live_texture.c",
        "old": "            entry->valid = false;\n            stale++;",
        "new": "            stale++;",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the write-no-invalidate rule",
    },
    {
        "id": "live-texture-hit-skip",
        "file": "src/gpu/live_texture.c",
        "old": "    if (entry->valid) {\n        cache->hits++;",
        "new": "    if (false && entry->valid) {\n        cache->hits++;",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the hit-skip rule",
    },
    {
        "id": "live-texture-generation-bump",
        "file": "src/gpu/live_texture.c",
        "old": "        entry->generation++;\n",
        "new": "        entry->generation += 0u;\n",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the generation-bump rule",
    },
    {
        "id": "live-texture-upload-flag",
        "file": "src/gpu/live_texture.c",
        "old": "result->needs_upload = entry->uploaded_generation != entry->generation;",
        "new": "result->needs_upload = entry->uploaded_generation == 0u;",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the upload-flag rule",
    },
    {
        "id": "live-texture-upload-bytes",
        "file": "src/gpu/live_texture.c",
        "old": "result->upload_bytes = result->needs_upload ? entry->plan.rgba_bytes : 0u;",
        "new": "result->upload_bytes = entry->plan.rgba_bytes;",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the upload-bytes rule",
    },
    {
        "id": "live-texture-mark-uploaded",
        "file": "src/gpu/live_texture.c",
        "old": "cache->entries[entry].uploaded_generation = generation;",
        "new": "cache->entries[entry].uploaded_generation = 0u;",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the mark-uploaded rule",
    },
    {
        "id": "live-texture-target-ambiguous",
        "file": "src/gpu/live_texture.c",
        "old": "if (matches > 1u) {",
        "new": "if (matches > 2u) {",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the target-ambiguous rule",
    },
    {
        "id": "live-texture-target-layout-pitch",
        "file": "src/gpu/live_texture.c",
        "old": "plan.height != target->height || (!target->swizzled && plan.pitch != target->pitch)",
        "new": "plan.height != target->height",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the target-layout-pitch rule",
    },
    {
        "id": "live-texture-alias-detect",
        "file": "src/gpu/live_texture.c",
        "old": "(uint64_t)target->data < (uint64_t)binding->data + plan.source_bytes) {",
        "new": "(uint64_t)target->data < (uint64_t)binding->data) {",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the alias-detect rule",
    },
    {
        "id": "live-texture-target-count",
        "file": "src/gpu/live_texture.c",
        "old": "cache->target_samples++;",
        "new": "cache->target_samples += 0u;",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the target-count rule",
    },
    {
        "id": "live-texture-census-dedupe",
        "file": "src/gpu/live_texture.c",
        "old": "entry->data == binding->data) {\n            entry->count++;",
        "new": "entry->data == binding->data + 1u) {\n            entry->count++;",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the census-dedupe rule",
    },
    {
        "id": "live-texture-census-count",
        "file": "src/gpu/live_texture.c",
        "old": "    cache->refusals++;\n",
        "new": "    cache->refusals += 0u;\n",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the census-count rule",
    },
    {
        "id": "live-texture-unreadable",
        "file": "src/gpu/live_texture.c",
        "old": "!reader(context, read_address, source, plan.source_bytes)",
        "new": "!reader(context, read_address, source, plan.source_bytes - 1u)",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the unreadable rule",
    },
    {
        "id": "live-texture-key-format",
        "file": "src/gpu/live_texture.c",
        "old": "candidate->binding.format == binding->format &&",
        "new": "candidate->binding.format != binding->format + 1u &&",
        "targets": ["test_live_texture"],
        "why": "a survivor means the live_texture test does not pin the key-format rule",
    },
]
