# SPDX-License-Identifier: GPL-3.0-or-later
# ruff: noqa: E501
"""Mutation set for T793 live Vulkan render targets (src/gpu/live_vk_target.c, tests/c/test_live_vk_target.c).

The suite needs a Vulkan device (llvmpipe works, VK_DRIVER_FILES=/usr/share/vulkan/icd.d/lvp_icd.json) and exits 77
without one, which the harness would read as a pass: run this set only where the suite really runs.
The swapchain half (tests/c/test_live_vk_present.c) skips under the dummy driver and is not a target here.
"""

MUTATIONS: list[dict] = [
    {
        "id": "live-vk-target-copy-route-always-staged",
        "file": "src/gpu/live_vk_target.c",
        "old": "    if (use->copy_image_ok) {\n        if (!run_copy_image(",
        "new": "    if (false) {\n        if (!run_copy_image(",
        "targets": ["test_live_vk_target"],
        "why": "The plain vkCmdCopyImage must be the route when the plan allows it (the staged path is byte identical, only the route counters tell them apart).",
    },
    {
        "id": "live-vk-target-copy-source-row",
        "file": "src/gpu/live_vk_target.c",
        "old": "        .srcOffset = {(int32_t)((plan->source_offset % plan->source_pitch) / bytes),\n                      (int32_t)(plan->source_offset / plan->source_pitch), 0},",
        "new": "        .srcOffset = {(int32_t)((plan->source_offset % plan->source_pitch) / bytes),\n                      (int32_t)(plan->destination_offset / plan->destination_pitch), 0},",
        "targets": ["test_live_vk_target"],
        "why": "The source row is the plan's source offset over the source pitch.",
    },
    {
        "id": "live-vk-target-copy-destination-column-bytes",
        "file": "src/gpu/live_vk_target.c",
        "old": "        .dstOffset = {(int32_t)((plan->destination_offset % plan->destination_pitch) / bytes),",
        "new": "        .dstOffset = {(int32_t)((plan->destination_offset % plan->destination_pitch)),",
        "targets": ["test_live_vk_target"],
        "why": "The destination column is in texels, a byte column would land four times too far right.",
    },
    {
        "id": "live-vk-target-copy-rows",
        "file": "src/gpu/live_vk_target.c",
        "old": "        .extent = {plan->row_bytes / bytes, plan->rows, 1u}};",
        "new": "        .extent = {plan->row_bytes / bytes, 1u, 1u}};",
        "targets": ["test_live_vk_target"],
        "why": "The region is the plan's row count, not one row.",
    },
    {
        "id": "live-vk-target-image-width-from-width",
        "file": "src/gpu/live_vk_target.c",
        "old": "    slot->texels = slot->desc.pitch / slot->desc.bytes_per_pixel;",
        "new": "    slot->texels = slot->desc.width;",
        "targets": ["test_live_vk_target"],
        "why": "The image is as wide as the pitch so a clamped row (HQ58) fits, a pitch wider than the width loses the tail.",
    },
    {
        "id": "live-vk-target-blit-generation-not-bumped",
        "file": "src/gpu/live_vk_target.c",
        "old": "    live_target_note_written(set->registry, blit->destination_data);\n    return LIVE_VK_OK;",
        "new": "    return LIVE_VK_OK;",
        "targets": ["test_live_vk_target"],
        "why": "A blit changes the destination, so the shared generation (T792 invalidation) must move.",
    },
    {
        "id": "live-vk-target-empty-blit-runs",
        "file": "src/gpu/live_vk_target.c",
        "old": "    if (use->empty) {\n        set->stats.empty_blits++;",
        "new": "    if (false) {\n        set->stats.empty_blits++;",
        "targets": ["test_live_vk_target"],
        "why": "A zero width or height moves nothing (HQ58), it must not reach the device as a zero extent copy.",
    },
    {
        "id": "live-vk-target-staged-same-surface-destination",
        "file": "src/gpu/live_vk_target.c",
        "old": "        live_target_execute_plan(plan, source_buffer.mapped, same ? source_buffer.mapped : destination_buffer.mapped);",
        "new": "        live_target_execute_plan(plan, source_buffer.mapped, destination_buffer.mapped);",
        "targets": ["test_live_vk_target"],
        "why": "A blit inside one surface must run in place over the one readback, so the smear of ascending rows is the reference's.",
    },
    {
        "id": "live-vk-target-staged-same-surface-writeback",
        "file": "src/gpu/live_vk_target.c",
        "old": "        ok = buffer_to_image(set, destination, same ? &source_buffer : &destination_buffer);",
        "new": "        ok = buffer_to_image(set, destination, &destination_buffer);",
        "targets": ["test_live_vk_target"],
        "why": "The in place result lives in the source buffer when the surfaces are the same.",
    },
    {
        "id": "live-vk-target-front-cache-ignores-generation",
        "file": "src/gpu/live_vk_target.c",
        "old": "    if (set->front_valid && set->front_data == data && set->front_generation == generation) {",
        "new": "    if (set->front_valid && set->front_data == data) {",
        "targets": ["test_live_vk_target"],
        "why": "A blit or draw into the front must show at the next vblank, a stale cache would hold the old picture.",
    },
    {
        "id": "live-vk-target-front-cache-ignores-target",
        "file": "src/gpu/live_vk_target.c",
        "old": "    if (set->front_valid && set->front_data == data && set->front_generation == generation) {",
        "new": "    if (set->front_valid && set->front_generation == generation) {",
        "targets": ["test_live_vk_target"],
        "why": "A different front buffer with the same generation count is a different picture.",
    },
    {
        "id": "live-vk-target-compose-front-channel-order",
        "file": "src/gpu/live_vk_target.c",
        "old": "                pixel[0] = source[2];",
        "new": "                pixel[0] = source[0];",
        "targets": ["test_live_vk_target"],
        "why": "A8R8G8B8 is B, G, R, A in memory and the swapchain handoff is RGBA.",
    },
    {
        "id": "live-vk-target-compose-front-alpha",
        "file": "src/gpu/live_vk_target.c",
        "old": "            pixel[3] = 0xFFu;\n        }\n    }\n    if (overlay_rgb == NULL",
        "new": "            pixel[3] = front_bgra != NULL ? front_bgra[(size_t)y * front_stride + (size_t)x * 4u + 3u] : 0xFFu;\n        }\n    }\n    if (overlay_rgb == NULL",
        "targets": ["test_live_vk_target"],
        "why": "The scanout ignores the surface alpha (INFERRED), the frame must be opaque.",
    },
    {
        "id": "live-vk-target-compose-letterbox-centre",
        "file": "src/gpu/live_vk_target.c",
        "old": "    const uint32_t left = (out_width - fit_width) / 2u;",
        "new": "    const uint32_t left = (out_width - fit_width) / 3u;",
        "targets": ["test_live_vk_target"],
        "why": "The picture is centred in the bars.",
    },
    {
        "id": "live-vk-target-compose-letterbox-top",
        "file": "src/gpu/live_vk_target.c",
        "old": "    const uint32_t top = (out_height - fit_height) / 2u;",
        "new": "    const uint32_t top = 0u;",
        "targets": ["test_live_vk_target"],
        "why": "The picture is centred vertically.",
    },
    {
        "id": "live-vk-target-vblank-drops-overlay",
        "file": "src/gpu/live_vk_target.c",
        "old": "                           has_overlay ? set->overlay_rgb : NULL, set->overlay_width, set->overlay_height, *width, *height,",
        "new": "                           NULL, set->overlay_width, set->overlay_height, *width, *height,",
        "targets": ["test_live_vk_target"],
        "why": "The overlay layer must be composed above the front when the schedule lists it.",
    },
    {
        "id": "live-vk-target-vblank-overlay-only-size",
        "file": "src/gpu/live_vk_target.c",
        "old": "        *width = front->width;\n        *height = front->height;\n    } else if (has_overlay) {\n        *width = set->overlay_width;",
        "new": "        *width = front->width;\n        *height = front->height;\n    } else if (has_overlay) {\n        *width = 640u;",
        "targets": ["test_live_vk_target"],
        "why": "With no front the overlay's own size is the canvas.",
    },
    {
        "id": "live-vk-target-present-failure-not-counted",
        "file": "src/gpu/live_vk_target.c",
        "old": "        set->stats.present_callback_failures++;",
        "new": "        (void)0;",
        "targets": ["test_live_vk_target"],
        "why": "A failing present is counted, never hidden.",
    },
    {
        "id": "live-vk-target-frames-presented-not-counted",
        "file": "src/gpu/live_vk_target.c",
        "old": "    set->stats.frames_presented++;",
        "new": "    (void)0;",
        "targets": ["test_live_vk_target"],
        "why": "The presented count is the census of what reached the swapchain.",
    },
    {
        "id": "live-vk-target-observer-bind-ignored",
        "file": "src/gpu/live_vk_target.c",
        "old": "    g_observer_set = set;\n}",
        "new": "    (void)set;\n}",
        "targets": ["test_live_vk_target"],
        "why": "The d3d8_present observer must reach the bound set.",
    },
    {
        "id": "live-vk-target-present-refusal-not-counted",
        "file": "src/gpu/live_vk_target.c",
        "old": "    if (result != LIVE_TARGET_OK) {\n        set->stats.present_refused++;",
        "new": "    if (result != LIVE_TARGET_OK) {\n        (void)0;",
        "targets": ["test_live_vk_target"],
        "why": "A front buffer whose header does not decode is counted, not queued silently.",
    },
    {
        "id": "live-vk-target-overlay-clear-keeps-layer",
        "file": "src/gpu/live_vk_target.c",
        "old": "        set->overlay_active = false;\n        set->overlay_sequence++;",
        "new": "        set->overlay_sequence++;",
        "targets": ["test_live_vk_target"],
        "why": "Clearing the overlay removes its layer.",
    },
    {
        "id": "live-vk-target-apply-copies-continues-after-refusal",
        "file": "src/gpu/live_vk_target.c",
        "old": "            break;\n        }\n        applied++;",
        "new": "            continue;\n        }\n        applied++;",
        "targets": ["test_live_vk_target"],
        "why": "The stream stops at the first refused copy, later events must not run over a state the refusal left unapplied.",
    },
    {
        "id": "live-vk-target-apply-copies-failure-default",
        "file": "src/gpu/live_vk_target.c",
        "old": "        *first_failure = count;\n    }\n    size_t applied = 0u;",
        "new": "        *first_failure = 0u;\n    }\n    size_t applied = 0u;",
        "targets": ["test_live_vk_target"],
        "why": "No failure is reported as `count`.",
    },
    {
        "id": "live-vk-target-copy-event-swaps-source-destination",
        "file": "src/gpu/live_vk_target.c",
        "old": "    return (live_target_blit){.source_data = copy->source_offset,\n                              .destination_data = copy->destination_offset,",
        "new": "    return (live_target_blit){.source_data = copy->destination_offset,\n                              .destination_data = copy->source_offset,",
        "targets": ["test_live_vk_target"],
        "why": "The event's source offset is the blit's source.",
    },
    {
        "id": "live-vk-target-native-queue-dropped",
        "file": "src/gpu/live_vk_target.c",
        "old": "    out->queue = native->queue;",
        "new": "    out->queue = VK_NULL_HANDLE;",
        "targets": ["test_live_vk_target"],
        "why": "The native seam's queue is the device queue.",
    },
    {
        "id": "live-vk-target-native-family",
        "file": "src/gpu/live_vk_target.c",
        "old": "    out->queue_family = native->queue_family;",
        "new": "    out->queue_family = 0u;",
        "targets": ["test_live_vk_target"],
        "why": "The queue family follows the native seam.",
    },
    {
        "id": "live-vk-target-image-format-16bit",
        "file": "src/gpu/live_vk_target.c",
        "old": "    case 2u: *format = VK_FORMAT_R5G6B5_UNORM_PACK16; return true;",
        "new": "    case 2u: *format = VK_FORMAT_R8G8_UNORM; return true;",
        "targets": ["test_live_vk_target"],
        "why": "R5G6B5 is a 16 bit packed byte copy of the guest layout.",
    },
    {
        "id": "live-vk-target-texture-registers-swizzled",
        "file": "src/gpu/live_vk_target.c",
        "old": "            if (set->cache != NULL && slot->desc.swizzled && slot->desc.format == LIVE_TARGET_FORMAT_A8R8G8B8) {",
        "new": "            if (set->cache != NULL && !slot->desc.swizzled && slot->desc.format == LIVE_TARGET_FORMAT_A8R8G8B8) {",
        "targets": ["test_live_vk_target"],
        "why": "A target must be registered with its actual swizzled or linear texture layout.",
    },
    {
        "id": "live-vk-target-texture-registers-x8r8g8b8",
        "file": "src/gpu/live_vk_target.c",
        "old": "            } else if (set->cache != NULL && !slot->desc.swizzled && slot->desc.format == LIVE_TARGET_FORMAT_A8R8G8B8) {",
        "new": "            } else if (set->cache != NULL && !slot->desc.swizzled) {",
        "targets": ["test_live_vk_target"],
        "why": "Only A8R8G8B8 targets match a texture binding of that format.",
    },
    {
        "id": "live-vk-target-texture-target-id",
        "file": "src/gpu/live_vk_target.c",
        "old": "                if (live_texture_register_target(set->cache, (uint32_t)i + 1u, data,",
        "new": "                if (live_texture_register_target(set->cache, (uint32_t)i, data,",
        "targets": ["test_live_vk_target"],
        "why": "The id handed to the cache is slot + 1 so a zero id never names a target.",
    },
    {
        "id": "live-vk-target-upload-length-unchecked",
        "file": "src/gpu/live_vk_target.c",
        "old": "    if (length != image_bytes(slot)) {\n        return LIVE_VK_ARGUMENT;\n    }\n    host_buffer buffer;\n    if (!host_buffer_make(set, &buffer, length)) {\n        return LIVE_VK_DEVICE_FAILED;\n    }\n    memcpy(buffer.mapped, bytes, length);",
        "new": "    host_buffer buffer;\n    if (!host_buffer_make(set, &buffer, length)) {\n        return LIVE_VK_DEVICE_FAILED;\n    }\n    memcpy(buffer.mapped, bytes, length);",
        "targets": ["test_live_vk_target"],
        "why": "A short upload buffer would be read past its end, the length must match the image.",
    },
    {
        "id": "live-vk-target-submit-uses-number-for-vblank",
        "file": "src/gpu/live_vk_target.c",
        "old": ".number = record->number, .interval = record->interval, .vblank = record->vblank,",
        "new": ".number = record->number, .interval = record->interval, .vblank = record->number,",
        "targets": ["test_live_vk_target"],
        "why": "The schedule keys on the modelled vblank of the Swap.",
    },
]
