# SPDX-License-Identifier: GPL-3.0-or-later
# ruff: noqa: E501
"""Mutation set for T793 live render targets (src/gpu/live_target.c, tests/c/test_live_target.c).

The Vulkan integration is not built yet (needs T790), so these cover the device free planner and present schedule.
The interval-0-counts-as-1 rule has no mutant: the test cannot distinguish it at consecutive vblanks (stated, not faked).
"""

MUTATIONS: list[dict] = [
    {
        "id": "live-target-clamp-limit",
        "file": "src/gpu/live_target.c",
        "old": "        row_bytes = narrow_pitch;",
        "new": "        row_bytes = blit->source_pitch;",
        "targets": ["test_live_target"],
        "why": "a row wider than the narrower pitch must stop at that pitch (HQ58 outcome 4), the source pitch would overrun a narrow destination.",
    },
    {
        "id": "live-target-rows-descending",
        "file": "src/gpu/live_target.c",
        "old": "    for (uint32_t row = 0u; row < plan->rows; row++) {",
        "new": "    for (uint32_t row = plan->rows; row-- > 0u;) {",
        "targets": ["test_live_target"],
        "why": "xemu copies rows ascending so a 3 row overlap downwards smears with period 3, a descending order would make it exact.",
    },
    {
        "id": "live-target-alpha-ff-swapped",
        "file": "src/gpu/live_target.c",
        "old": "plan->alpha == LIVE_ALPHA_FORCE_FF ? 0xFFu : 0x00u",
        "new": "plan->alpha == LIVE_ALPHA_FORCE_FF ? 0x00u : 0xFFu",
        "targets": ["test_live_target"],
        "why": "format 7 forces alpha to 0xFF and 6 to 0, swapping them reads as a plausible X8R8G8B8 blit.",
    },
    {
        "id": "live-target-alpha-byte-index",
        "file": "src/gpu/live_target.c",
        "old": "for (uint32_t byte = 3u; byte < plan->row_bytes; byte += 4u) {",
        "new": "for (uint32_t byte = 2u; byte < plan->row_bytes; byte += 4u) {",
        "targets": ["test_live_target"],
        "why": "alpha is byte 3 of a little endian A8R8G8B8 pixel, byte 2 patches red.",
    },
    {
        "id": "live-target-overlap-row-term",
        "file": "src/gpu/live_target.c",
        "old": "blit->out_y < blit->in_y + blit->height;",
        "new": "true;",
        "targets": ["test_live_target"],
        "why": "an overlap needs both the columns and the rows to intersect, without the row test a disjoint-rows copy is reported ordered and loses the vkCmdCopyImage fast path.",
    },
    {
        "id": "live-target-empty-needs-both",
        "file": "src/gpu/live_target.c",
        "old": "if (blit->width == 0u || blit->height == 0u) {",
        "new": "if (blit->width == 0u && blit->height == 0u) {",
        "targets": ["test_live_target"],
        "why": "xemu runs no blit for a zero width OR height (HQ58 outcome 5).",
    },
    {
        "id": "live-target-bounds-destination-inclusive",
        "file": "src/gpu/live_target.c",
        "old": "((uint64_t)blit->out_x * bytes_per_pixel + row_bytes) > destination_row_bytes) {",
        "new": "((uint64_t)blit->out_x * bytes_per_pixel + row_bytes) >= destination_row_bytes) {",
        "targets": ["test_live_target"],
        "why": "a rectangle ending exactly at the surface edge is legal, an off by one refuses the title's own full-surface blit.",
    },
    {
        "id": "live-target-pitch-source-unchecked",
        "file": "src/gpu/live_target.c",
        "old": "if (blit->source_pitch != source->desc.pitch ||",
        "new": "if ((blit->source_pitch != source->desc.pitch && false) ||",
        "targets": ["test_live_target"],
        "why": "a blit pitch that is not the registered pitch would address rows that are not the target's.",
    },
    {
        "id": "live-target-offset-clamp-and",
        "file": "src/gpu/live_target.c",
        "old": "if (blit->in_x != 0u || blit->out_x != 0u) {",
        "new": "if (blit->in_x != 0u && blit->out_x != 0u) {",
        "targets": ["test_live_target"],
        "why": "the clamp is measured only with both offsets zero.",
    },
    {
        "id": "live-target-generation-not-bumped",
        "file": "src/gpu/live_target.c",
        "old": "    destination->generation++;\n    if (source->pixels",
        "new": "    if (source->pixels",
        "targets": ["test_live_target"],
        "why": "T792 invalidates texture uploads by generation, a blit that does not bump it leaves a stale texture.",
    },
    {
        "id": "live-target-redeclare-pitch-unchecked",
        "file": "src/gpu/live_target.c",
        "old": "existing->desc.pitch != desc.pitch ||",
        "new": "false ||",
        "targets": ["test_live_target"],
        "why": "a header re-registered with another pitch must not silently reuse the old geometry.",
    },
    {
        "id": "live-target-linear-pitch-unit",
        "file": "src/gpu/live_target.c",
        "old": "((size_word >> 24) + 1u) * 64u",
        "new": "((size_word >> 24) + 1u) * 32u",
        "targets": ["test_live_target"],
        "why": "the 640x480 header pins pitch 2560 = 40 * 64.",
    },
    {
        "id": "live-target-swizzled-height-exponent",
        "file": "src/gpu/live_target.c",
        "old": "(format_word >> 24) & 0xFu",
        "new": "(format_word >> 25) & 0xFu",
        "targets": ["test_live_target"],
        "why": "the height exponent is bits 24-27 of the Format word.",
    },
    {
        "id": "live-target-present-latency",
        "file": "src/gpu/live_target.c",
        "old": "schedule->queue[i].vblank + schedule->latency <= vblank",
        "new": "schedule->queue[i].vblank + schedule->latency < vblank",
        "targets": ["test_live_target"],
        "why": "a present shows at the vblank after the Swap, not one later.",
    },
    {
        "id": "live-target-present-interval-gate",
        "file": "src/gpu/live_target.c",
        "old": "if (schedule->queue[i].vblank + schedule->latency <= vblank) {\n            chosen = (int)i;\n        }\n    }\n    if (chosen >= 0) {\n        const live_present_event *event = &schedule->queue[chosen];\n        const uint32_t interval = event->interval == 0u ? 1u : event->interval;\n        if (!schedule->shown_any || vblank >= schedule->last_shown_vblank + interval) {",
        "new": "if (schedule->queue[i].vblank + schedule->latency <= vblank) {\n            chosen = (int)i;\n        }\n    }\n    if (chosen >= 0) {\n        const live_present_event *event = &schedule->queue[chosen];\n        const uint32_t interval = event->interval == 0u ? 1u : event->interval;\n        if (!schedule->shown_any || vblank + 1u >= schedule->last_shown_vblank + interval) {",
        "targets": ["test_live_target"],
        "why": "interval 2 must hold the front for two vblanks.",
    },
    {
        "id": "live-target-present-superseded-count",
        "file": "src/gpu/live_target.c",
        "old": "if (schedule->queue[i].vblank + schedule->latency <= vblank) {\n            chosen = (int)i;\n        }\n    }\n    if (chosen >= 0) {\n        const live_present_event *event = &schedule->queue[chosen];\n        const uint32_t interval = event->interval == 0u ? 1u : event->interval;\n        if (!schedule->shown_any || vblank >= schedule->last_shown_vblank + interval) {\n            schedule->superseded += (uint64_t)chosen;",
        "new": "if (schedule->queue[i].vblank + schedule->latency <= vblank) {\n            chosen = (int)i;\n        }\n    }\n    if (chosen >= 0) {\n        const live_present_event *event = &schedule->queue[chosen];\n        const uint32_t interval = event->interval == 0u ? 1u : event->interval;\n        if (!schedule->shown_any || vblank >= schedule->last_shown_vblank + interval) {\n            schedule->superseded += 0u;",
        "targets": ["test_live_target"],
        "why": "dropped presents are counted, never silent.",
    },
    {
        "id": "live-target-present-overlay-order",
        "file": "src/gpu/live_target.c",
        "old": "frame->layers[frame->layer_count++] = LIVE_LAYER_OVERLAY;\n        schedule->overlay_frames++;\n    }\n}\n\nvoid live_present_media_vblank",
        "new": "frame->layers[0] = LIVE_LAYER_OVERLAY; frame->layer_count++;\n        schedule->overlay_frames++;\n    }\n}\n\nvoid live_present_media_vblank",
        "targets": ["test_live_target"],
        "why": "the movie overlay is composed above the front buffer, not instead of it.",
    },
]
