# ruff: noqa: E501  (the anchors are verbatim C source lines)
"""Mutations for the SDL window provider of the host pad sources (T751 follow-up).

Files: the input half of `src/host/present_sink.c` (SDL event to SDL-free event, queue, held keys, focus loss,
gamepad hotplug), the adapter `src/host/pad_sdl_feed.c`, the one-provider rule in `src/host/host_options.c` and
`xinput_pad_source_open_feed` in `src/input/xinput_host_source.c`.

Kill suites: `test_pad_sdl_feed` (SDL3 build, dummy video driver, real SDL events and a real virtual joystick),
`test_host_options`, `test_xinput_host_source`. Needs a build WITH SDL3: without it `test_pad_sdl_feed` skips (77) and
kills nothing, so run the harness on an SDL3 build (`--build build/on`).

Justified equivalents, not mutated: the digit range (a digit outside 1 and 2 has no table name, named or not it reaches the
source as an unknown code and is counted the same), the 8 slot gamepad array bound, the held key capacity guard, and the
`SDL_Quit` and `SDL_CloseGamepad` calls of close (nothing observable survives the sink), the keyboard guard of the focus loss (keys are
tracked only while the keyboard is on and it cannot be turned off again, so the held set is empty otherwise).

Every `old` here occurs exactly once (`tests/test_mutation_anchors.py`).
"""

SINK = "src/host/present_sink.c"
FEED = "src/host/pad_sdl_feed.c"
OPTIONS = "src/host/host_options.c"
SOURCE = "src/input/xinput_host_source.c"
SDL_SUITE = ["test_pad_sdl_feed"]


def _m(
    mutation_id: str,
    file: str,
    old: str,
    new: str,
    why: str,
    suite: list[str] | None = None,
) -> dict:
    return {
        "id": f"pad-sdl-{mutation_id}",
        "file": file,
        "old": old,
        "new": new,
        "targets": list(suite or SDL_SUITE),
        "why": why,
    }


MUTATIONS: list[dict] = [
    _m(
        "key-repeat",
        SINK,
        "if (!sink->input_keyboard || event->key.repeat) return;",
        "if (!sink->input_keyboard) return;",
        "key repeat is dropped",
    ),
    _m(
        "key-needs-keyboard",
        SINK,
        "if (!sink->input_keyboard || event->key.repeat) return;",
        "if (event->key.repeat) return;",
        "keys are queued only when the keyboard is enabled",
    ),
    _m(
        "letter-upper",
        SINK,
        "if (key >= SDLK_A && key <= SDLK_Z) return letter_names[key - SDLK_A];",
        "if (key >= SDLK_A && key < SDLK_Z) return letter_names[key - SDLK_A];",
        "Z is a named letter",
    ),
    _m(
        "letter-lower",
        SINK,
        "if (key >= SDLK_A && key <= SDLK_Z) return letter_names[key - SDLK_A];",
        "if (key > SDLK_A && key <= SDLK_Z) return letter_names[key - SDLK_A];",
        "A is a named letter",
    ),
    _m(
        "digit-1",
        SINK,
        "if (key >= SDLK_0 && key <= SDLK_9) return digit_names[key - SDLK_0];",
        "if (key > SDLK_1 && key <= SDLK_9) return digit_names[key - SDLK_0];",
        "1 is a named digit",
    ),
    _m("key-up", SINK, 'case SDLK_UP: return "UP";', 'case SDLK_UP: return "DOWN";', "UP names UP"),
    _m(
        "key-down",
        SINK,
        'case SDLK_DOWN: return "DOWN";',
        'case SDLK_DOWN: return "UP";',
        "DOWN names DOWN",
    ),
    _m(
        "key-left",
        SINK,
        'case SDLK_LEFT: return "LEFT";',
        'case SDLK_LEFT: return "RIGHT";',
        "LEFT names LEFT",
    ),
    _m(
        "key-right",
        SINK,
        'case SDLK_RIGHT: return "RIGHT";',
        'case SDLK_RIGHT: return "LEFT";',
        "RIGHT names RIGHT",
    ),
    _m("key-return", SINK, "case SDLK_RETURN:\n", "case SDLK_KP_PLUS:\n", "RETURN is ENTER"),
    _m(
        "key-kp-enter",
        SINK,
        'case SDLK_KP_ENTER: return "ENTER";',
        'case SDLK_KP_PLUS: return "ENTER";',
        "the keypad ENTER is ENTER",
    ),
    _m(
        "key-backspace",
        SINK,
        'case SDLK_BACKSPACE: return "BACKSPACE";',
        'case SDLK_BACKSPACE: return "TAB";',
        "BACKSPACE names BACKSPACE",
    ),
    _m(
        "key-space",
        SINK,
        'case SDLK_SPACE: return "SPACE";',
        "case SDLK_SPACE: return NULL;",
        "SPACE is a known unmapped key, not unknown",
    ),
    _m(
        "button-south",
        SINK,
        'case SDL_GAMEPAD_BUTTON_SOUTH: return "A";',
        'case SDL_GAMEPAD_BUTTON_SOUTH: return "B";',
        "SOUTH is A",
    ),
    _m(
        "button-east",
        SINK,
        'case SDL_GAMEPAD_BUTTON_EAST: return "B";',
        'case SDL_GAMEPAD_BUTTON_EAST: return "A";',
        "EAST is B",
    ),
    _m(
        "button-west",
        SINK,
        'case SDL_GAMEPAD_BUTTON_WEST: return "X";',
        'case SDL_GAMEPAD_BUTTON_WEST: return "Y";',
        "WEST is X",
    ),
    _m(
        "button-north",
        SINK,
        'case SDL_GAMEPAD_BUTTON_NORTH: return "Y";',
        'case SDL_GAMEPAD_BUTTON_NORTH: return "X";',
        "NORTH is Y",
    ),
    _m(
        "button-lb",
        SINK,
        'case SDL_GAMEPAD_BUTTON_LEFT_SHOULDER: return "LB";',
        'case SDL_GAMEPAD_BUTTON_LEFT_SHOULDER: return "RB";',
        "left shoulder is LB",
    ),
    _m(
        "button-rb",
        SINK,
        'case SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER: return "RB";',
        'case SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER: return "LB";',
        "right shoulder is RB",
    ),
    _m(
        "button-start",
        SINK,
        'case SDL_GAMEPAD_BUTTON_START: return "START";',
        'case SDL_GAMEPAD_BUTTON_START: return "BACK";',
        "START is START",
    ),
    _m(
        "button-back",
        SINK,
        'case SDL_GAMEPAD_BUTTON_BACK: return "BACK";',
        'case SDL_GAMEPAD_BUTTON_BACK: return "START";',
        "BACK is BACK",
    ),
    _m(
        "button-guide",
        SINK,
        'case SDL_GAMEPAD_BUTTON_GUIDE: return "GUIDE";',
        "case SDL_GAMEPAD_BUTTON_GUIDE: return NULL;",
        "GUIDE is a known unmapped button",
    ),
    _m(
        "button-lstick",
        SINK,
        'case SDL_GAMEPAD_BUTTON_LEFT_STICK: return "LSTICK";',
        'case SDL_GAMEPAD_BUTTON_LEFT_STICK: return "RSTICK";',
        "left stick click is LSTICK",
    ),
    _m(
        "button-rstick",
        SINK,
        'case SDL_GAMEPAD_BUTTON_RIGHT_STICK: return "RSTICK";',
        'case SDL_GAMEPAD_BUTTON_RIGHT_STICK: return "LSTICK";',
        "right stick click is RSTICK",
    ),
    _m(
        "button-dpad-up",
        SINK,
        'case SDL_GAMEPAD_BUTTON_DPAD_UP: return "DPAD_UP";',
        'case SDL_GAMEPAD_BUTTON_DPAD_UP: return "DPAD_DOWN";',
        "dpad up",
    ),
    _m(
        "button-dpad-down",
        SINK,
        'case SDL_GAMEPAD_BUTTON_DPAD_DOWN: return "DPAD_DOWN";',
        'case SDL_GAMEPAD_BUTTON_DPAD_DOWN: return "DPAD_UP";',
        "dpad down",
    ),
    _m(
        "button-dpad-left",
        SINK,
        'case SDL_GAMEPAD_BUTTON_DPAD_LEFT: return "DPAD_LEFT";',
        'case SDL_GAMEPAD_BUTTON_DPAD_LEFT: return "DPAD_RIGHT";',
        "dpad left",
    ),
    _m(
        "button-dpad-right",
        SINK,
        'case SDL_GAMEPAD_BUTTON_DPAD_RIGHT: return "DPAD_RIGHT";',
        'case SDL_GAMEPAD_BUTTON_DPAD_RIGHT: return "DPAD_LEFT";',
        "dpad right",
    ),
    _m(
        "axis-lx",
        SINK,
        'case SDL_GAMEPAD_AXIS_LEFTX: return "LX";',
        'case SDL_GAMEPAD_AXIS_LEFTX: return "RX";',
        "left X is LX",
    ),
    _m(
        "axis-ly-invert",
        SINK,
        'case SDL_GAMEPAD_AXIS_LEFTY: *invert = true; return "LY";',
        'case SDL_GAMEPAD_AXIS_LEFTY: return "LY";',
        "left Y is negated",
    ),
    _m(
        "axis-rx",
        SINK,
        'case SDL_GAMEPAD_AXIS_RIGHTX: return "RX";',
        'case SDL_GAMEPAD_AXIS_RIGHTX: return "LX";',
        "right X is RX",
    ),
    _m(
        "axis-ry-invert",
        SINK,
        'case SDL_GAMEPAD_AXIS_RIGHTY: *invert = true; return "RY";',
        'case SDL_GAMEPAD_AXIS_RIGHTY: return "RY";',
        "right Y is negated",
    ),
    _m(
        "axis-lt",
        SINK,
        'case SDL_GAMEPAD_AXIS_LEFT_TRIGGER: return "LT";',
        'case SDL_GAMEPAD_AXIS_LEFT_TRIGGER: return "RT";',
        "left trigger is LT",
    ),
    _m(
        "axis-rt",
        SINK,
        'case SDL_GAMEPAD_AXIS_RIGHT_TRIGGER: return "RT";',
        'case SDL_GAMEPAD_AXIS_RIGHT_TRIGGER: return "LT";',
        "right trigger is RT",
    ),
    _m(
        "axis-clamp",
        SINK,
        "if (invert) value = value == -32768 ? 32767 : -value;",
        "if (invert) value = value == -32768 ? -32768 : -value;",
        "negating -32768 clamps to 32767",
    ),
    _m(
        "axis-no-invert",
        SINK,
        "if (invert) value = value == -32768 ? 32767 : -value;",
        "if (invert) value = (int32_t)value;",
        "the Y negation is applied",
    ),
    _m(
        "held-add",
        SINK,
        "sink->held_keys[sink->held_count++] = name;",
        "sink->held_count += 0;",
        "a pressed key is remembered for the focus loss",
    ),
    _m(
        "held-remove",
        SINK,
        "sink->held_keys[i] = sink->held_keys[--sink->held_count];",
        "sink->held_keys[i] = sink->held_keys[i];",
        "a released key is forgotten",
    ),
    _m(
        "held-dup",
        SINK,
        "if (sink->held_keys[i] == name) return;\n    if (sink->held_count",
        "if (sink->held_keys[i] == name) {}\n    if (sink->held_count",
        "a key held twice is remembered once",
    ),
    _m(
        "focus-release",
        SINK,
        "while (sink->held_count != 0u) {",
        "while (0) {",
        "losing focus releases the held keys",
    ),
    _m(
        "added-opens",
        SINK,
        "if (sink->input_gamepad) gamepad_open(sink, event->gdevice.which);",
        "(void)0;",
        "an attached pad is opened",
    ),
    _m(
        "removed-closes",
        SINK,
        "if (sink->input_gamepad) gamepad_close(sink, event->gdevice.which);",
        "if (sink->input_gamepad) gamepad_close(sink, 0);",
        "a removed pad is closed",
    ),
    _m(
        "pad-needs-gamepad",
        SINK,
        "if (!sink->input_gamepad) return;\n        input_push(sink, event->type == SDL_EVENT_GAMEPAD_BUTTON_DOWN",
        "input_push(sink, event->type == SDL_EVENT_GAMEPAD_BUTTON_DOWN",
        "pad buttons are queued only when the gamepad is on",
    ),
    _m(
        "axis-needs-gamepad",
        SINK,
        "if (!sink->input_gamepad) return;\n        bool invert;",
        "bool invert;",
        "pad axes are queued only when the gamepad is on",
    ),
    _m(
        "pump-escape",
        SINK,
        "sink->closed_by_user = true;\n            atomic_store(&sink->user_closed, true);\n            continue;",
        "sink->closed_by_user = true;\n            atomic_store(&sink->user_closed, true);",
        "ESCAPE is not queued as a key",
    ),
    _m(
        "queue-full",
        SINK,
        "if (sink->queue_count == PRESENT_INPUT_QUEUE_SIZE) {",
        "if (sink->queue_count > PRESENT_INPUT_QUEUE_SIZE) {",
        "a full queue drops",
    ),
    _m(
        "queue-drop-count",
        SINK,
        "sink->input_dropped++;",
        "sink->input_dropped += 0;",
        "a drop is counted",
    ),
    _m(
        "queue-wrap-push",
        SINK,
        "(sink->queue_head + sink->queue_count) % PRESENT_INPUT_QUEUE_SIZE];",
        "(sink->queue_head + sink->queue_count) % (PRESENT_INPUT_QUEUE_SIZE - 1u)];",
        "the ring wraps at its size",
    ),
    _m(
        "queue-wrap-pop",
        SINK,
        "sink->queue_head = (sink->queue_head + 1u) % PRESENT_INPUT_QUEUE_SIZE;",
        "sink->queue_head = (sink->queue_head + 1u) % (PRESENT_INPUT_QUEUE_SIZE - 1u);",
        "the ring pops at its size",
    ),
    _m(
        "queue-pop-count",
        SINK,
        "sink->queue_count--;",
        "sink->queue_count -= 0u;",
        "a pop shrinks the queue",
    ),
    _m(
        "queue-order",
        SINK,
        "*out = sink->queue[sink->queue_head];",
        "*out = sink->queue[(sink->queue_head + sink->queue_count - 1u) % PRESENT_INPUT_QUEUE_SIZE];",
        "oldest first",
    ),
    _m(
        "axis-value",
        SINK,
        "slot->value = value;",
        "slot->value = value ^ 1;",
        "the axis value is carried",
    ),
    _m(
        "enable-window-only",
        SINK,
        'if (sink == NULL || sink->kind != PRESENT_VIDEO_WINDOW) {\n        *error = "window input needs',
        'if (sink == NULL) {\n        *error = "window input needs',
        "only a window sink takes input",
    ),
    _m(
        "enable-keyboard-latch",
        SINK,
        "sink->input_keyboard = sink->input_keyboard || keyboard;",
        "sink->input_keyboard = keyboard;",
        "enabling the gamepad later keeps the keyboard",
    ),
    _m(
        "enable-gamepad-latch",
        SINK,
        "sink->input_gamepad = sink->input_gamepad || gamepad;",
        "sink->input_gamepad = gamepad;",
        "enabling the keyboard later keeps the gamepad",
    ),
    _m(
        "pad-open-idempotent",
        SINK,
        "SDL_GetGamepadID(sink->gamepads[i]) == id) return; /* ADDED may repeat */",
        "SDL_GetGamepadID(sink->gamepads[i]) == id) {} /* ADDED may repeat */",
        "a repeated ADDED opens one slot",
    ),
    _m(
        "feed-not-due",
        FEED,
        "out->poll = poll_index;",
        "out->poll = poll_index + 1u;",
        "an event is due at the poll that pops it (read by the adapter test, the source itself ignores the field)",
    ),
    _m(
        "feed-device",
        FEED,
        "out->device = keyboard ? XINPUT_HOST_KEYBOARD : XINPUT_HOST_GAMEPAD;",
        "out->device = keyboard ? XINPUT_HOST_GAMEPAD : XINPUT_HOST_KEYBOARD;",
        "key events are keyboard events",
    ),
    _m(
        "feed-down",
        FEED,
        "case PRESENT_INPUT_PAD_DOWN: out->action = XINPUT_HOST_DOWN; break;",
        "case PRESENT_INPUT_PAD_DOWN: out->action = XINPUT_HOST_UP; break;",
        "a press is DOWN",
    ),
    _m(
        "feed-up",
        FEED,
        "case PRESENT_INPUT_PAD_UP: out->action = XINPUT_HOST_UP; break;",
        "case PRESENT_INPUT_PAD_UP: out->action = XINPUT_HOST_DOWN; break;",
        "a release is UP",
    ),
    _m(
        "feed-axis",
        FEED,
        "default: out->action = XINPUT_HOST_AXIS; break;",
        "default: out->action = XINPUT_HOST_DOWN; break;",
        "an axis is AXIS",
    ),
    _m(
        "feed-axis-code",
        FEED,
        "code = out->action == XINPUT_HOST_AXIS ? xinput_host_axis_of(raw.name) : xinput_host_code_of(out->device, raw.name);",
        "code = xinput_host_code_of(out->device, raw.name);",
        "axis names resolve through the axis table",
    ),
    _m(
        "feed-unnamed",
        FEED,
        "out->code = code != UINT32_MAX ? code : UNNAMED_CODE_BASE + ((uint32_t)raw.raw & 0xFFFFFFu);",
        "out->code = code != UINT32_MAX ? code : 0u;",
        "an unnamed host code stays unknown, never UP or A",
    ),
    _m(
        "feed-value",
        FEED,
        "out->value = raw.value;",
        "out->value = 0;",
        "the axis value reaches the source",
    ),
    _m(
        "feed-enable-keyboard",
        FEED,
        "const bool keyboard = device == XINPUT_HOST_KEYBOARD ||",
        "const bool keyboard = device == XINPUT_HOST_GAMEPAD ||",
        "the keyboard source turns the keyboard on",
    ),
    _m(
        "options-feed-window",
        OPTIONS,
        'if (out->pad_feed != NULL && out->present != NULL && strcmp(out->present, "window") == 0) return false;',
        "(void)0;",
        "window and feed together are refused",
        ["test_host_options"],
    ),
    _m(
        "options-feed-any-present",
        OPTIONS,
        'if (out->pad_feed != NULL && out->present != NULL && strcmp(out->present, "window") == 0) return false;',
        "if (out->pad_feed != NULL && out->present != NULL) return false;",
        "a feed with another sink is allowed",
        ["test_host_options"],
    ),
    _m(
        "open-feed-closes-on-refusal",
        SOURCE,
        'snprintf(error, error_size, "not a host device source");\n        if (feed.close != NULL) feed.close(feed.user);',
        'snprintf(error, error_size, "not a host device source");',
        "a refused feed is still closed",
        ["test_xinput_host_source"],
    ),
    _m(
        "open-feed-script-kind",
        SOURCE,
        "xinput_event_feed feed, char *error,\n                                                size_t error_size)\n{\n    if (kind != XINPUT_PAD_SOURCE_KEYBOARD && kind != XINPUT_PAD_SOURCE_GAMEPAD) {",
        "xinput_event_feed feed, char *error,\n                                                size_t error_size)\n{\n    if (false) {",
        "a script kind is not a host device source",
        ["test_xinput_host_source"],
    ),
    _m(
        "open-feed-kind",
        SOURCE,
        "kind == XINPUT_PAD_SOURCE_KEYBOARD ? XINPUT_HOST_KEYBOARD : XINPUT_HOST_GAMEPAD, feed);",
        "kind == XINPUT_PAD_SOURCE_KEYBOARD ? XINPUT_HOST_GAMEPAD : XINPUT_HOST_KEYBOARD, feed);",
        "the kind selects the device",
        ["test_xinput_host_source", "test_pad_sdl_feed"],
    ),
]
