# ruff: noqa: E501  (the anchors are verbatim source lines)
"""Mutations for the closed loop menu navigation (T1640): the `# nav:` line and menu table grammars, the state machine
(direction, wrap shortest path, tie break, lost press detection, retry cap, ready gating, timeout, name matching, activation
press, post-condition, fallback versus strict), the route player (jump to `to`, failure, modes) and the host flag rules.

Kill suite: `test_route_nav` (grammar, a fake menu in fake guest memory driving the machine, the route player with a fake
clock, the record's `# nav:` lines, host_route.c wiring and the flags).

Not mutated, justified: the 5 s progress cadence text and the `describe_seen` name listing (message wording, asserted by
substring only), the buffer size guards (`append`, `snprintf` truncation: a mutant overruns or truncates a log line, not a
verdict), the array bound `*count == ROUTE_NAV_MAX_STEPS` of `parse_navs` in `src/input/xinput_record.c` (a mutant overruns
a fixed array, a crash is not a verdict).

Equivalent (not mutated): the `selectby == name` test on the recorder's name branch and the non empty test of `unique_text` each repeat a guard
that the text loading (`with_text`) and the percent encoder already apply, dropping either one changes nothing observable.

Every `old` here occurs exactly once (`tests/test_mutation_anchors.py`).
"""

NAV = "src/input/xinput_route_nav.c"
SPEC = "src/input/xinput_route_nav_spec.c"
ROUTE = "src/input/xinput_route.c"
OPTIONS = "src/host/host_options.c"
NAVREC = "src/input/xinput_nav_record.c"
RECORD = "src/input/xinput_record.c"
SUITE = ["test_route_nav"]


def _m(mutation_id: str, file: str, old: str, new: str, why: str) -> dict:
    return {
        "id": f"route-nav-{mutation_id}",
        "file": file,
        "old": old,
        "new": new,
        "targets": list(SUITE),
        "why": why,
    }


MUTATIONS: list[dict] = [
    # ---- direction and path ----
    _m(
        "vertical-direction-swapped",
        NAV,
        "(increasing ? XINPUT_BUTTON_DPAD_DOWN : XINPUT_BUTTON_DPAD_UP)",
        "(increasing ? XINPUT_BUTTON_DPAD_UP : XINPUT_BUTTON_DPAD_DOWN)",
        "DOWN no longer increases the cursor on a vertical menu",
    ),
    _m(
        "horizontal-direction-swapped",
        NAV,
        "(increasing ? XINPUT_BUTTON_DPAD_RIGHT : XINPUT_BUTTON_DPAD_LEFT)",
        "(increasing ? XINPUT_BUTTON_DPAD_LEFT : XINPUT_BUTTON_DPAD_RIGHT)",
        "RIGHT no longer increases the cursor on a horizontal menu",
    ),
    _m(
        "axis-ignored",
        NAV,
        "machine->press_bit = menu->vertical ? (",
        "machine->press_bit = !menu->vertical ? (",
        "a horizontal menu is driven with UP/DOWN and a vertical one with LEFT/RIGHT",
    ),
    _m(
        "wrap-ignored",
        NAV,
        "if (!wrap) return to > from;",
        "if (wrap || true) return to > from;",
        "a wrapping menu is walked the long way",
    ),
    _m(
        "wrap-assumed",
        NAV,
        "if (!wrap) return to > from;",
        "if (!wrap && false) return to > from;",
        "a menu without wrap is walked through the wrap",
    ),
    _m(
        "no-wrap-reversed",
        NAV,
        "if (!wrap) return to > from;",
        "if (!wrap) return to < from;",
        "a menu without wrap is driven away from the target",
    ),
    _m(
        "tie-goes-decreasing",
        NAV,
        "return forward <= backward;",
        "return forward < backward;",
        "an equal distance both ways is walked backwards",
    ),
    _m(
        "longest-way-round",
        NAV,
        "return forward <= backward;",
        "return forward >= backward;",
        "the wrap picks the longer way",
    ),
    _m(
        "forward-distance-unwrapped",
        NAV,
        "const uint32_t forward = (to + total - from) % total;",
        "const uint32_t forward = (to + total - from);",
        "the forward distance is not taken modulo the count: a wrap menu always goes increasing",
    ),
    _m(
        "start-on-target-ignored",
        NAV,
        "if (!none && snap.cursor == machine->target) {",
        "if (!none && snap.cursor != machine->target) {",
        "a cursor already on the target is moved, one off is activated",
    ),
    # ---- lost presses, retries, odd menus ----
    _m(
        "lost-detected-at-gap",
        NAV,
        "if (machine->phase_polls < timing->gap + timing->extra) return ROUTE_NAV_RUNNING;",
        "if (machine->phase_polls < timing->gap) return ROUTE_NAV_RUNNING;",
        "a press is declared lost without the extra polls the game gets to react",
    ),
    _m(
        "lost-detected-late",
        NAV,
        "if (machine->phase_polls < timing->gap + timing->extra) return ROUTE_NAV_RUNNING;",
        "if (machine->phase_polls < timing->gap + timing->extra + 1u) return ROUTE_NAV_RUNNING;",
        "a press is declared lost a poll late",
    ),
    _m(
        "retry-off-by-one",
        NAV,
        "if (++machine->consecutive_lost > machine->step->retry)",
        "if (++machine->consecutive_lost >= machine->step->retry)",
        "one retry fewer than retry= is allowed",
    ),
    _m(
        "retry-never-exhausted",
        NAV,
        "if (++machine->consecutive_lost > machine->step->retry)",
        "if (++machine->consecutive_lost > machine->step->retry + 1000u)",
        "a menu that never takes the press is pressed until the step times out",
    ),
    _m(
        "lost-streak-not-reset",
        NAV,
        "machine->consecutive_lost = 0u;",
        "(void)0;",
        "retry= counts all lost presses of the step instead of those in a row",
    ),
    _m(
        "anomaly-undetected",
        NAV,
        "if (machine->moved_to != machine->expected_to) {",
        "if (false) {",
        "a menu that moves two items or the wrong way is replanned forever",
    ),
    _m(
        "anomaly-cap-off-by-one",
        NAV,
        "if (machine->anomalies > machine->step->retry)",
        "if (machine->anomalies >= machine->step->retry)",
        "the unexpected move budget is one short",
    ),
    _m(
        "release-gap-skipped",
        NAV,
        "if (machine->phase_polls < timing->gap) return ROUTE_NAV_RUNNING;",
        "if (false) return ROUTE_NAV_RUNNING;",
        "the next press follows the cursor change at once, without the release gap the game needs for an edge",
    ),
    _m(
        "press-hold-short",
        NAV,
        "case ROUTE_NAV_PRESS:\n        if (machine->phase_polls < machine->timing.hold) {",
        "case ROUTE_NAV_PRESS:\n        if (machine->phase_polls < machine->timing.hold - 1u) {",
        "the d-pad bit is held one poll too short",
    ),
    # ---- ready gating and timeout ----
    _m(
        "ready-ignored",
        NAV,
        "if (!snap.active || !snap.ready) {",
        "if (!snap.active) {",
        "the pad is pressed while the menu is not ready for input",
    ),
    _m(
        "active-ignored",
        NAV,
        "if (!snap.active || !snap.ready) {",
        "if (!snap.ready) {",
        "the pad is pressed while the menu is not the active one",
    ),
    _m(
        "timeout-exclusive",
        NAV,
        "if (spent >= machine->step->timeout_ms) {",
        "if (spent > machine->step->timeout_ms) {",
        "the step lives one poll beyond its timeout",
    ),
    _m(
        "timeout-ignored",
        NAV,
        "if (spent >= machine->step->timeout_ms) {",
        "if (false) {",
        "a menu that never gets ready blocks the route forever",
    ),
    # ---- targets and names ----
    _m(
        "name-left-case-sensitive",
        NAV,
        "if (a >= 'A' && a <= 'Z') a = (char)(a + ('a' - 'A'));",
        "(void)0;",
        "the name read from memory is compared case sensitive",
    ),
    _m(
        "name-right-case-sensitive",
        NAV,
        "if (b >= 'A' && b <= 'Z') b = (char)(b + ('a' - 'A'));",
        "(void)0;",
        "the name of the nav line is compared case sensitive",
    ),
    _m(
        "name-prefix-matches",
        NAV,
        "if (a != b) return false;",
        "if (a != b) return b == '\\0';",
        "a prefix of an item name selects that item",
    ),
    _m(
        "name-ambiguity-allowed",
        NAV,
        "if (matches > 1u) return fail(machine, \"name '%s' is ambiguous",
        "if (matches > 2u) return fail(machine, \"name '%s' is ambiguous",
        "two items with the same name: the first one is taken silently when there are only two",
    ),
    _m(
        "name-not-found-falls-back",
        NAV,
        "if (matches == 0u) return fail(machine, \"name '%s' is not among the menu's %u item(s)\"",
        "if (matches == 0u) return give_up(machine, \"name '%s' is not among the menu's %u item(s)\"",
        "an unknown name replays the recorded presses, which may select the wrong item",
    ),
    _m(
        "index-beyond-count-allowed",
        NAV,
        "if (machine->target >= snap.count)",
        "if (machine->target > snap.count)",
        "index == count is accepted and the cursor is driven to a non-existent item",
    ),
    _m(
        "cursor-beyond-count-allowed",
        NAV,
        "if (!none && snap.cursor >= snap.count) return give_up(",
        "if (!none && snap.cursor > snap.count) return give_up(",
        "a cursor equal to the count is taken as a valid position",
    ),
    # ---- activation and post-condition ----
    _m(
        "activation-weak-press",
        NAV,
        "pad->analog[machine->menu->select_analog] = 255u;",
        "pad->analog[machine->menu->select_analog] = 254u;",
        "the analog select button is not fully pressed",
    ),
    _m(
        "activation-hold-short",
        NAV,
        "case ROUTE_NAV_ACT_PRESS:\n        if (machine->phase_polls < machine->timing.hold) {",
        "case ROUTE_NAV_ACT_PRESS:\n        if (machine->phase_polls < machine->timing.hold - 1u) {",
        "the select button is held one poll too short",
    ),
    _m(
        "activation-release-short",
        NAV,
        "if (machine->phase_polls >= machine->timing.gap) machine->state = ROUTE_NAV_VERIFY;",
        "if (machine->phase_polls > machine->timing.gap) machine->state = ROUTE_NAV_VERIFY;",
        "the verdict comes one poll late after the activation",
    ),
    _m(
        "activation-skipped",
        NAV,
        "machine->dpad_since_ms = 0u;\n        if (!machine->step->activate) return finish(machine, ROUTE_NAV_DONE);",
        "machine->dpad_since_ms = 0u;\n        if (false) return finish(machine, ROUTE_NAV_DONE);",
        "a step without `activate` presses the select button anyway",
    ),
    _m(
        "default-grace-ignored",
        NAV,
        "if (spent < ROUTE_NAV_ACTIVATE_GRACE_MS) return ROUTE_NAV_RUNNING;",
        "if (false) return ROUTE_NAV_RUNNING;",
        "the select button is pressed again at once, without the 3 s grace",
    ),
    _m(
        "default-grace-exclusive",
        NAV,
        "if (spent < ROUTE_NAV_ACTIVATE_GRACE_MS) return ROUTE_NAV_RUNNING;",
        "if (spent <= ROUTE_NAV_ACTIVATE_GRACE_MS) return ROUTE_NAV_RUNNING;",
        "the activation grace is one poll longer than 3 s",
    ),
    _m(
        "default-ignores-menu-closing",
        NAV,
        "const bool changed = !snap.active || !snap.ready ||",
        "const bool changed = !snap.ready ||",
        "a menu that closes after the activation is not seen as a change",
    ),
    _m(
        "expect-always-holds",
        NAV,
        "if (holds) return finish(machine, ROUTE_NAV_DONE);",
        "if (holds || true) return finish(machine, ROUTE_NAV_DONE);",
        "the expect= post-condition is not consulted",
    ),
    _m(
        "expect-max-polls-exclusive",
        NAV,
        "(wait->max_polls != 0u && machine->act_polls >= wait->max_polls)",
        "(wait->max_polls != 0u && machine->act_polls > wait->max_polls)",
        "the expect max= is one poll too generous",
    ),
    # ---- fallback versus strict ----
    _m(
        "fallback-after-press",
        NAV,
        "if (machine->mode != ROUTE_NAV_MODE_STRICT && machine->presses == 0u && !machine->act_started) {",
        "if (machine->mode != ROUTE_NAV_MODE_STRICT && !machine->act_started) {",
        "a step that already pressed falls back and then replays the recorded presses from a moved cursor",
    ),
    _m(
        "strict-falls-back",
        NAV,
        "if (machine->mode != ROUTE_NAV_MODE_STRICT && machine->presses == 0u && !machine->act_started) {",
        "if (machine->presses == 0u && !machine->act_started) {",
        "strict mode falls back like mode on",
    ),
    _m(
        "never-falls-back",
        NAV,
        "if (machine->mode != ROUTE_NAV_MODE_STRICT && machine->presses == 0u && !machine->act_started) {",
        "if (false) {",
        "mode on fails a step that could have fallen back",
    ),
    _m(
        "count-unreadable-ignored",
        NAV,
        "if (!snap.cursor_ok || !snap.count_ok)\n",
        "if (!snap.cursor_ok)\n",
        "an unreadable count is not noticed (the count reads as 0)",
    ),
    _m(
        "default-ignores-child-page",
        NAV,
        "const bool changed = !snap.active || !snap.ready ||",
        "const bool changed = !snap.active ||",
        "a page opened on top of the menu (no longer ready) is not seen as a reaction to the activation",
    ),
    _m(
        "represse-never",
        NAV,
        "if (machine->represses < ROUTE_NAV_ACTIVATE_REPRESS) {",
        "if (false) {",
        "a select press the menu did not react to is never repeated",
    ),
    _m(
        "represse-always",
        NAV,
        "if (machine->represses < ROUTE_NAV_ACTIVATE_REPRESS) {",
        "if (true) {",
        "the select button is pressed again and again",
    ),
    _m(
        "cursorless-treated-as-cursor",
        NAV,
        "if (!menu->has_cursor) { /* a screen that is only waited for and activated */",
        "if (false) { /* a screen that is only waited for and activated */",
        "a menu without a cursor falls back instead of being activated",
    ),
    _m(
        "cursorless-activation-skipped",
        NAV,
        "activated */\n        if (!machine->step->activate) return finish(machine, ROUTE_NAV_DONE);",
        "activated */\n        if (false) return finish(machine, ROUTE_NAV_DONE);",
        "a cursorless step without `activate` presses the select button anyway",
    ),
    # ---- pages, rows, ids ----
    _m(
        "page-closing-state-taken",
        NAV,
        "if (closing) continue;",
        "if (false) continue;",
        "a page that is closing or dead is taken for the menu",
    ),
    _m(
        "page-builder-ignored",
        NAV,
        "&builder) || builder != machine->menu->builder) continue;",
        "&builder) || false) continue;",
        "any live widget is taken for the menu",
    ),
    _m(
        "page-unused-slot-taken",
        NAV,
        "&used) || used == 0u) continue;",
        "&used) || false) continue;",
        "a widget slot that is not in use is taken for the menu",
    ),
    _m(
        "page-highest-slot-lost",
        NAV,
        "if (!found || state >= best_state) {",
        "if (!found || state > best_state) {",
        "of two pages in the same state the lower slot wins",
    ),
    _m(
        "page-lowest-state",
        NAV,
        "if (!found || state >= best_state) {",
        "if (!found || state <= best_state) {",
        "the page that is least open wins",
    ),
    _m(
        "page-last-slot-unseen",
        NAV,
        "for (uint32_t slot = 0u; slot < widgets->count; slot++) {",
        "for (uint32_t slot = 0u; slot + 1u < widgets->count; slot++) {",
        "the last widget slot is never looked at",
    ),
    _m(
        "page-spec-base-lost",
        NAV,
        "*address = page->base + ref->cond.address;",
        "*address = ref->cond.address;",
        "a page spec reads at its offset from address 0, not from the page",
    ),
    _m(
        "row-type-filter-ignored",
        NAV,
        "bool wanted = false;",
        "bool wanted = true;",
        "every node of the chain is a cursor row",
    ),
    _m(
        "skipped-rows-are-stops",
        NAV,
        "if ((machine->row_flags[k] & items->skip_mask) == 0u) machine->stops[machine->stop_count++] = k;",
        "machine->stops[machine->stop_count++] = k;",
        "rows the cursor skips are planned as places the cursor rests on",
    ),
    _m(
        "none-cursor-ignored",
        NAV,
        "const bool none = snap.cursor == ROUTE_NAV_CURSOR_NONE;",
        "const bool none = false;",
        "a cursor that is not on any row yet is taken as an impossible position",
    ),
    _m(
        "none-wakes-the-wrong-end",
        NAV,
        "if (position < 0) return stop_at(machine, increasing ? 0u : total - 1u);",
        "if (position < 0) return stop_at(machine, increasing ? total - 1u : 0u);",
        "the first press from `none` is expected on the last stop",
    ),
    _m(
        "wrap-expectation-lost",
        NAV,
        "if (increasing) return stop_at(machine, at + 1u < total ? at + 1u : (machine->menu->wrap ? 0u : at));",
        "if (increasing) return stop_at(machine, at + 1u < total ? at + 1u : at);",
        "the wrap from the last row to the first is reported as an unexpected move",
    ),
    _m(
        "skipped-target-allowed",
        NAV,
        "if (target_position < 0) {",
        "if (false) {",
        "a title or hint row can be selected",
    ),
    _m(
        "count-row-mismatch-allowed",
        NAV,
        "if (machine->row_count != snap.count) return give_up(",
        "if (false) return give_up(",
        "a count that disagrees with the row list is trusted",
    ),
    _m(
        "grey-ignored",
        NAV,
        "(machine->row_flags[machine->target] & items->grey_mask) != 0u) {",
        "(machine->row_flags[machine->target] & items->grey_mask) == 0u) {",
        "a greyed row is activated and an enabled one is refused",
    ),
    _m(
        "grey-grace-exclusive",
        NAV,
        "if (now + 1u - machine->grey_since_ms >= ROUTE_NAV_GREY_GRACE_MS)",
        "if (now + 1u - machine->grey_since_ms > ROUTE_NAV_GREY_GRACE_MS)",
        "a greyed row is waited for one poll longer than 3 s",
    ),
    _m(
        "grey-fails-at_once",
        NAV,
        "if (now + 1u - machine->grey_since_ms >= ROUTE_NAV_GREY_GRACE_MS)",
        "if (true)",
        "a row that is greyed for a moment fails the step",
    ),
    _m(
        "itemid-mismatch-ignored",
        NAV,
        "snap.itemid_ok && snap.itemid != machine->row_id[machine->target])",
        "snap.itemid_ok && snap.itemid == machine->row_id[machine->target])",
        "the item id under the cursor is checked the wrong way round",
    ),
    _m(
        "id-select-inverted",
        NAV,
        "if (machine->row_id[i] != step->index) continue;",
        "if (machine->row_id[i] == step->index) continue;",
        "select=id: picks the rows with another id",
    ),
    _m(
        "id-ambiguity-allowed",
        NAV,
        'if (matches > 1u) return fail(machine, "the id 0x%X is ambiguous',
        'if (matches > 2u) return fail(machine, "the id 0x%X is ambiguous',
        "a repeated item id selects the first row silently",
    ),
    # ---- the route player ----
    _m(
        "no-jump-to-q",
        ROUTE,
        "route->cursor = step->to;",
        "route->cursor = step->at;",
        "after the step the route replays the recorded presses it was meant to replace",
    ),
    _m(
        "nav-failure-not-fatal",
        ROUTE,
        "        route->failed = true;\n        emit_detail(route, XINPUT_ROUTE_NAV_FAIL,",
        "        emit_detail(route, XINPUT_ROUTE_NAV_FAIL,",
        "a failed nav step does not fail the route",
    ),
    _m(
        "mode-off-still-navigates",
        ROUTE,
        "if (config->mode == ROUTE_NAV_MODE_OFF || config->step_count == 0u) return true;",
        "if (config->step_count == 0u) return true;",
        "--route-nav off keeps driving the menus",
    ),
    _m(
        "strict-accepts-unknown-menu",
        ROUTE,
        "if (config->mode == ROUTE_NAV_MODE_STRICT && route_nav_menu_find(",
        "if (false && route_nav_menu_find(",
        "strict mode does not refuse a step whose menu the table lacks",
    ),
    # ---- grammar limits ----
    _m(
        "steps-limit-off-by-one",
        SPEC,
        "if (count > ROUTE_NAV_MAX_STEPS) {",
        "if (count >= ROUTE_NAV_MAX_STEPS) {",
        "64 nav lines are refused",
    ),
    _m(
        "touching-steps-overlap",
        SPEC,
        "if (i != 0u && step->at < steps[i - 1u].to) {",
        "if (i != 0u && step->at <= steps[i - 1u].to) {",
        "a step starting where the previous one ends is refused",
    ),
    _m(
        "overlap-allowed",
        SPEC,
        "if (i != 0u && step->at < steps[i - 1u].to) {",
        "if (false) {",
        "overlapping steps are accepted",
    ),
    _m(
        "mark-at-start-inside",
        SPEC,
        "if (marks[m] > step->at && marks[m] < step->to) {",
        "if (marks[m] >= step->at && marks[m] < step->to) {",
        "a mark exactly at `at` is refused",
    ),
    _m(
        "mark-at-end-inside",
        SPEC,
        "if (marks[m] > step->at && marks[m] < step->to) {",
        "if (marks[m] > step->at && marks[m] <= step->to) {",
        "a mark exactly at `to` is refused",
    ),
    _m(
        "mark-inside-allowed",
        SPEC,
        "if (marks[m] > step->at && marks[m] < step->to) {",
        "if (false) {",
        "a mark strictly inside the replaced range is accepted",
    ),
    _m(
        "at-above-to-allowed",
        SPEC,
        "if (out->at > out->to) {",
        "if (out->at > out->to + 1000000u) {",
        "at > to is accepted",
    ),
    _m(
        "empty-range-refused",
        SPEC,
        "if (out->at > out->to) {",
        "if (out->at >= out->to) {",
        "at == to is refused",
    ),
    _m(
        "to-past-record-allowed",
        SPEC,
        "if (step->to > total) {",
        "if (step->to > total + 1000000u) {",
        "a step ending after the record is accepted",
    ),
    _m(
        "to-at-record-end-refused",
        SPEC,
        "if (step->to > total) {",
        "if (step->to >= total) {",
        "a step ending exactly at the end of the record is refused",
    ),
    _m(
        "missing-menu-allowed",
        SPEC,
        "if (!seen.menu) {",
        "if (false) {",
        "a nav line without menu= is accepted",
    ),
    _m(
        "missing-select-allowed",
        SPEC,
        "if (!seen.select) {",
        "if (false) {",
        "a nav line without select= is accepted",
    ),
    _m(
        "expect-without-activate-allowed",
        SPEC,
        "if (out->has_expect && !out->activate) {",
        "if (false) {",
        "an expect= without activate is accepted",
    ),
    _m(
        "percent-half-escape-allowed",
        SPEC,
        "if (hi < 0 || lo < 0) {",
        "if (hi < 0) {",
        "a truncated %X escape is decoded",
    ),
    _m(
        "name-length-off-by-one",
        SPEC,
        "if (used + 1u >= out_size) {",
        "if (used + 1u > out_size) {",
        "a 64 byte name overruns the buffer instead of being refused",
    ),
    _m(
        "retry-limit-off-by-one",
        SPEC,
        "if (!parse_u64(value, value_length, ROUTE_NAV_RETRY_LIMIT, &number)) {",
        "if (!parse_u64(value, value_length, ROUTE_NAV_RETRY_LIMIT + 1u, &number)) {",
        "retry=101 is accepted",
    ),
    _m(
        "timeout-zero-allowed",
        SPEC,
        "!parse_u64(value, value_length, XINPUT_ROUTE_TIMEOUT_MS_LIMIT, &number) || number == 0u) {",
        "!parse_u64(value, value_length, XINPUT_ROUTE_TIMEOUT_MS_LIMIT, &number)) {",
        "timeout=0 is accepted and the step times out at once",
    ),
    _m(
        "menu-active-optional",
        SPEC,
        "if (!seen.active) {",
        "if (false) {",
        "a menu line without active= is accepted",
    ),
    _m(
        "menu-cursor-without-count",
        SPEC,
        "if (seen.cursor != seen.count) {",
        "if (false) {",
        "cursor= without count= is accepted",
    ),
    _m(
        "menu-axis-optional",
        SPEC,
        "if (seen.cursor && (!seen.axis || !seen.wrap)) {",
        "if (false) {",
        "a menu with a cursor but no axis= or wrap= is accepted",
    ),
    _m(
        "page-spec-without-page",
        SPEC,
        "if (uses_page && !menu->page_builder) {",
        "if (false) {",
        "a @+OFF spec in a menu without page=builder: is accepted",
    ),
    _m(
        "page-without-widgets",
        SPEC,
        "if (out->menus[i].page_builder && !out->widgets.present) {",
        "if (false) {",
        "page=builder: without a widgets line is accepted",
    ),
    _m(
        "widgets-not-copied",
        SPEC,
        "out->menus[i].widgets = out->widgets;",
        "(void)0;",
        "a menu does not know the widget table to scan",
    ),
    _m(
        "walk-needs-next",
        SPEC,
        "if (!have_next || !have_type ||",
        "if (!have_type ||",
        "an items=walk without next= is accepted",
    ),
    _m(
        "select-id-is-index",
        SPEC,
        "out->kind = ROUTE_NAV_SELECT_ID;",
        "out->kind = ROUTE_NAV_SELECT_INDEX;",
        "select=id:N selects the row with the INDEX N",
    ),
    _m(
        "menu-count-limit-off-by-one",
        SPEC,
        "if (out->count >= ROUTE_NAV_MAX_MENUS) {",
        "if (out->count > ROUTE_NAV_MAX_MENUS) {",
        "a 33rd menu overruns the table",
    ),
    _m(
        "timing-zero-hold-allowed",
        SPEC,
        "!parse_u64(spec, (size_t)(colon - spec), ROUTE_NAV_TIMING_LIMIT, &hold) || hold == 0u ||",
        "!parse_u64(spec, (size_t)(colon - spec), ROUTE_NAV_TIMING_LIMIT, &hold) ||",
        "--route-nav-timing 0:3 would never press",
    ),
    _m(
        "options-nav-needs-replay",
        OPTIONS,
        "(out->replay_input != NULL || (out->route_nav == NULL && out->route_nav_timing == NULL &&",
        "(true || (out->route_nav == NULL && out->route_nav_timing == NULL &&",
        "--route-nav / --route-nav-timing without --replay-input are accepted",
    ),
    _m(
        "options-menus-alone",
        OPTIONS,
        "(out->route_nav_menus == NULL || out->record_input != NULL))) &&",
        "true)) &&",
        "--route-nav-menus without --replay-input or --record-input is accepted",
    ),
    _m(
        "options-record-flag-needs-record",
        OPTIONS,
        "(out->route_nav_record == NULL || out->record_input != NULL) &&",
        "true &&",
        "--route-nav-record without --record-input is accepted",
    ),
    # ---- the recorder side: the sampling, the activation rule, the record lines ----
    _m(
        "rec-gate-ignored",
        NAVREC,
        "if (!allowed) {",
        "if (false) {",
        "the mode word early-out is gone: every poll scans the widget table",
    ),
    _m(
        "rec-scan-all-menus",
        NAVREC,
        "for (unsigned slot = 0u; slot < slots && !present; slot++) present = builders[slot] == menu->builder;",
        "present = true;",
        "every menu of the table is evaluated at every poll instead of those whose page is open",
    ),
    _m(
        "rec-not-ready-activates",
        NAVREC,
        'if (!view.ready) why = "not-ready";',
        'if (false) why = "not-ready";',
        "a select press while the menu is not ready makes a nav line",
    ),
    _m(
        "rec-cursor-at-count-is-a-row",
        NAVREC,
        "view.cursor == ROUTE_NAV_CURSOR_NONE || view.cursor >= view.count))",
        "view.cursor == ROUTE_NAV_CURSOR_NONE || view.cursor > view.count))",
        "a cursor equal to the count is taken for a row",
    ),
    _m(
        "rec-skipped-row-activates",
        NAVREC,
        "else if (row.known && row.skipped) {",
        "else if (false) {",
        "a select press on a row the cursor skips makes a nav line",
    ),
    _m(
        "rec-greyed-row-activates",
        NAVREC,
        "else if (row.known && row.greyed) {",
        "else if (false) {",
        "a select press on a greyed row makes a nav line",
    ),
    _m(
        "rec-duplicate-id-selected-by-id",
        NAVREC,
        "else if (menu->selectby != ROUTE_NAV_BY_INDEX && menu->has_cursor && row.known && row.unique_id)",
        "else if (menu->selectby != ROUTE_NAV_BY_INDEX && menu->has_cursor && row.known)",
        "a row id that repeats in the list (or is 0xFFFFFFFF) is written as select=id:",
    ),
    _m(
        "rec-at-is-the-select-edge",
        NAVREC,
        "recorder->act_at = recorder->have_first_press && !menu->dpad_off ? recorder->first_press : poll_index;",
        "recorder->act_at = poll_index;",
        "the nav range starts at the select press, the d-pad presses stay open loop in front of it",
    ),
    _m(
        "rec-first-press-kept-after-emit",
        NAVREC,
        "                recorder->have_first_press = false;\n            }\n        }\n    }",
        "            }\n        }\n    }",
        "the next activation of the same page starts at the first press of the previous one",
    ),
    _m(
        "rec-instance-not-reset",
        NAVREC,
        "recorder->instance_page = page;\n        recorder->have_first_press = false;",
        "recorder->instance_page = page;",
        "the d-pad presses of an earlier page instance count for the next one",
    ),
    _m(
        "rec-any-button-is-a-press",
        NAVREC,
        "(recorded->digital_buttons & (uint16_t)~before.digital_buttons) & DPAD_MASK) != 0u",
        "(recorded->digital_buttons & (uint16_t)~before.digital_buttons) & 0xFFFFu) != 0u",
        "a START press counts as a d-pad press",
    ),
    _m(
        "rec-to-is-the-edge-poll",
        NAVREC,
        "emit_activation(recorder, poll_index);",
        "emit_activation(recorder, poll_index + 1u);",
        "to is one poll after the first poll with the select button up",
    ),
    _m(
        "rec-held-at-close-lost",
        NAVREC,
        "if (recorder->act_pending) emit_activation(recorder, total_polls);",
        "if (recorder->act_pending && false) emit_activation(recorder, total_polls);",
        "a select press still down when the record closes is dropped",
    ),
    _m(
        "rec-log-ignores-cursor",
        NAVREC,
        "(!cursor_ok || recorder->last_cursor == view->cursor) &&",
        "(!cursor_ok || true) &&",
        "a cursor move is not logged",
    ),
    _m(
        "rec-log-ignores-count",
        NAVREC,
        "(!count_ok || recorder->last_count == view->count) &&",
        "(!count_ok || true) &&",
        "a change of the item count is not logged",
    ),
    _m(
        "rec-log-ignores-id",
        NAVREC,
        "(!itemid_ok || recorder->last_itemid == view->itemid))",
        "(!itemid_ok || true))",
        "a change of the item id is not logged",
    ),
    _m(
        "rec-log-ignores-ready",
        NAVREC,
        "recorder->last_itemid_ok == itemid_ok && recorder->last_ready == ready &&",
        "recorder->last_itemid_ok == itemid_ok && true &&",
        "a change of ready is not logged",
    ),
    _m(
        "rec-log-every-poll",
        NAVREC,
        "if (recorder->seeded && recorder->last_menu == menu_index &&",
        "if (false && recorder->last_menu == menu_index &&",
        "the menu state is logged at every poll, not on change",
    ),
    _m(
        "rec-cursorless-ranked-first",
        NAVREC,
        "const int rank = menu->has_cursor ? (view.ready ? 3 : 2) : 1;",
        "const int rank = menu->has_cursor ? (view.ready ? 3 : 2) : 4;",
        "a cursorless page on screen hides the list that has the cursor",
    ),
    _m(
        "rec-record-mark-inside-low",
        RECORD,
        'if (mark_positions[i] > at && mark_positions[i] < to) reason = "mark-inside";',
        'if (mark_positions[i] >= at && mark_positions[i] < to) reason = "mark-inside";',
        "a mark exactly at `at` drops the nav line",
    ),
    _m(
        "rec-record-mark-inside-high",
        RECORD,
        'if (mark_positions[i] > at && mark_positions[i] < to) reason = "mark-inside";',
        'if (mark_positions[i] > at && mark_positions[i] <= to) reason = "mark-inside";',
        "a mark exactly at `to` drops the nav line",
    ),
    _m(
        "rec-record-mark-inside-ignored",
        RECORD,
        'if (mark_positions[i] > at && mark_positions[i] < to) reason = "mark-inside";',
        'if (false) reason = "mark-inside";',
        "a nav line with a mark inside is written and the whole record is refused at replay",
    ),
    _m(
        "rec-record-limit-off-by-one",
        RECORD,
        'else if (nav_live >= ROUTE_NAV_MAX_STEPS || nav_slots >= NAV_SLOTS) reason = "limit-64";',
        'else if (nav_live > ROUTE_NAV_MAX_STEPS || nav_slots >= NAV_SLOTS) reason = "limit-64";',
        "a 65th nav line is written",
    ),
    _m(
        "rec-record-overlap-unchecked",
        RECORD,
        "if (reason == NULL && at < last_nav_to) at = last_nav_to; /* the previous step ends where this one may begin */",
        "(void)last_nav_to;",
        "a nav line may begin before the previous one ended",
    ),
    _m(
        "rec-record-overlap-reason",
        RECORD,
        'if (reason == NULL && at > to) reason = "overlap";',
        'if (false) reason = "overlap";',
        "a nav line pushed past its end by the previous one is written with at above to",
    ),
    _m(
        "rec-record-suppressed-at-add",
        RECORD,
        '&& !select_is_down(&edge_state, select_analog, select_digital)) reason = "suppressed";',
        '&& false) reason = "suppressed";',
        "a nav line whose select press was cut out by a hotkey chord before the line was made is written",
    ),
    _m(
        "rec-record-revalidate-off",
        RECORD,
        "if (item->nav && state_at_poll(nav_edge[item->number], &state) &&",
        "if (false && state_at_poll(nav_edge[item->number], &state) &&",
        "a nav line whose select press a later hotkey chord cuts out stays in the record",
    ),
    _m(
        "rec-record-position-after-run",
        RECORD,
        "if (!pending[i].mark && pending[i].start + pending[i].frames > at) { index = i; break; }",
        "if (!pending[i].mark && pending[i].start > at) { index = i; break; }",
        "the nav line is written after the run it belongs to",
    ),
    _m(
        "rec-record-observes-raw-state",
        RECORD,
        "recorded = record_last_state;",
        "recorded = state != NULL ? *state : record_last_state;",
        "the recorder side sees the pad before a leaked hotkey key was cut out of it",
    ),
    _m(
        "rec-record-close-hook-lost",
        RECORD,
        "if (closer != NULL) closer(total, closer_user);",
        "if (closer != NULL && false) closer(total, closer_user);",
        "the recorder is not told that the record closed",
    ),
    _m(
        "rec-record-nav-item-is-a-run",
        RECORD,
        "const pending_item item = {true, at, to - at, {0}, slot, true};",
        "const pending_item item = {false, at, to - at, {0}, slot, true};",
        "the nav comment is treated as a run of pad states",
    ),
    # ---- B1 skipped rows in name matching, B2 dpad=0, B5 selectby ----
    _m(
        "skipped-rows-match-names",
        NAV,
        "if (items->present && (machine->row_flags[i] & items->skip_mask) != 0u) continue; /* a row the cursor skips (a title) is not an item */",
        "if (false) continue;",
        "a skipped title row with the same text makes a name ambiguous",
    ),
    _m(
        "skipped-rows-match-names-flag-inverted",
        NAV,
        "if (items->present && (machine->row_flags[i] & items->skip_mask) != 0u) continue; /* a row the cursor skips (a title) is not an item */",
        "if (items->present && (machine->row_flags[i] & items->skip_mask) == 0u) continue;",
        "only the skipped rows take part in name matching",
    ),
    _m(
        "dpad-off-presses",
        NAV,
        "if (menu->dpad_off) {\n        /* the menu does not take the d-pad",
        "if (false) {\n        /* the menu does not take the d-pad",
        "a menu that does not take the d-pad is pressed anyway and fails by lost presses",
    ),
    _m(
        "dpad-off-waits-forever",
        NAV,
        "if (now + 1u - machine->dpad_since_ms >= ROUTE_NAV_DPAD_GRACE_MS) {",
        "if (false) {",
        "a dpad=0 menu whose cursor never arrives is waited for until the step timeout",
    ),
    _m(
        "dpad-off-grace-exclusive",
        NAV,
        "if (now + 1u - machine->dpad_since_ms >= ROUTE_NAV_DPAD_GRACE_MS) {",
        "if (now + 1u - machine->dpad_since_ms > ROUTE_NAV_DPAD_GRACE_MS) {",
        "the dpad=0 grace is one poll longer than 3 s",
    ),
    _m(
        "dpad-off-fails-at-once",
        NAV,
        "if (now + 1u - machine->dpad_since_ms >= ROUTE_NAV_DPAD_GRACE_MS) {",
        "if (true) {",
        "a dpad=0 menu fails before the cursor had time to arrive",
    ),
    _m(
        "dpad-off-names-not-listed",
        NAV,
        '            machine->list_names = true;\n            return fail(machine, "menu %s does not take the d-pad',
        '            return fail(machine, "menu %s does not take the d-pad',
        "the dpad=0 failure does not list the item names",
    ),
    _m(
        "dpad-key-inverted",
        SPEC,
        "menu->dpad_off = value[0] == '0';",
        "menu->dpad_off = value[0] == '1';",
        "dpad=0 is read as dpad=1",
    ),
    _m(
        "dpad-key-value-unchecked",
        SPEC,
        "good = value_length == 1u && (value[0] == '0' || value[0] == '1');\n                menu->dpad_off",
        "good = value_length >= 1u;\n                menu->dpad_off",
        "dpad=2 is accepted",
    ),
    _m(
        "selectby-name-is-id",
        SPEC,
        'else if (value_length == 4u && memcmp(value, "name", 4u) == 0) menu->selectby = ROUTE_NAV_BY_NAME;',
        'else if (value_length == 4u && memcmp(value, "name", 4u) == 0) menu->selectby = ROUTE_NAV_BY_ID;',
        "selectby=name is read as selectby=id",
    ),
    _m(
        "selectby-index-is-id",
        SPEC,
        'else if (value_length == 5u && memcmp(value, "index", 5u) == 0) menu->selectby = ROUTE_NAV_BY_INDEX;',
        'else if (value_length == 5u && memcmp(value, "index", 5u) == 0) menu->selectby = ROUTE_NAV_BY_ID;',
        "selectby=index is read as selectby=id",
    ),
    _m(
        "dpad-needs-no-cursor",
        SPEC,
        "seen.items || seen.names || seen.dpad || seen.selectby)) {",
        "seen.items || seen.names)) {",
        "dpad= or selectby= on a menu without a cursor is accepted",
    ),
    _m(
        "rec-name-never-written",
        NAVREC,
        "if (menu->has_cursor && menu->selectby == ROUTE_NAV_BY_NAME && row.known && row.unique_text)",
        "if (false)",
        "selectby=name still writes the list position",
    ),
    _m(
        "rec-name-not-unique",
        NAVREC,
        "if (menu->has_cursor && menu->selectby == ROUTE_NAV_BY_NAME && row.known && row.unique_text)",
        "if (menu->has_cursor && menu->selectby == ROUTE_NAV_BY_NAME && row.known)",
        "a text that two rows share is written as a name",
    ),
    _m(
        "rec-index-ignores-selectby",
        NAVREC,
        "else if (menu->selectby != ROUTE_NAV_BY_INDEX && menu->has_cursor && row.known && row.unique_id)",
        "else if (menu->has_cursor && row.known && row.unique_id)",
        "selectby=index still writes the id",
    ),
    _m(
        "rec-dpad-off-starts-at-presses",
        NAVREC,
        "recorder->act_at = recorder->have_first_press && !menu->dpad_off ? recorder->first_press : poll_index;",
        "recorder->act_at = recorder->have_first_press ? recorder->first_press : poll_index;",
        "the range of a dpad=0 menu starts at the useless d-pad presses and replaces the recorded stick movement",
    ),
    _m(
        "rec-encode-keeps-space",
        NAVREC,
        "const bool plain = (*c >= 'a' && *c <= 'z') || (*c >= 'A' && *c <= 'Z') || (*c >= '0' && *c <= '9') || *c == '.' || *c == '_' || *c == '-';",
        "const bool plain = (*c >= 'a' && *c <= 'z') || (*c >= 'A' && *c <= 'Z') || (*c >= '0' && *c <= '9') || *c == '.' || *c == '_' || *c == '-' || *c == ' ';",
        "a space is not percent encoded and splits the select= token",
    ),
    _m(
        "rec-encode-keeps-percent",
        NAVREC,
        "const bool plain = (*c >= 'a' && *c <= 'z') || (*c >= 'A' && *c <= 'Z') || (*c >= '0' && *c <= '9') || *c == '.' || *c == '_' || *c == '-';",
        "const bool plain = (*c >= 'a' && *c <= 'z') || (*c >= 'A' && *c <= 'Z') || (*c >= '0' && *c <= '9') || *c == '.' || *c == '_' || *c == '-' || *c == '%';",
        "a percent sign is not encoded",
    ),
    _m(
        "rec-encode-length-limit",
        NAVREC,
        "used + (plain ? 1u : 3u) > ROUTE_NAV_SELECT_TEXT - 1u - 5u) {",
        "used + (plain ? 1u : 3u) > ROUTE_NAV_SELECT_TEXT - 1u - 4u) {",
        "an encoded name one character too long for a select= is written",
    ),
    _m(
        "rec-text-uniqueness-case",
        NAV,
        "if (ascii_equal_blind(scratch->row_text[i], info->text)) info->unique_text = false;",
        "if (strcmp(scratch->row_text[i], info->text) == 0) info->unique_text = false;",
        "texts that differ only in case are taken for different names",
    ),
    _m(
        "rec-text-uniqueness-counts-skipped",
        NAV,
        "if (i == row || (scratch->row_flags[i] & menu->items.skip_mask) != 0u) continue;\n            if (ascii_equal_blind",
        "if (i == row) continue;\n            if (ascii_equal_blind",
        "a skipped title with the same text makes the name not unique",
    ),
    _m(
        "rec-text-not-loaded",
        NAVREC,
        "menu->selectby == ROUTE_NAV_BY_NAME, &row))",
        "false, &row))",
        "the recorder never reads the row texts: selectby=name writes the id",
    ),
]
