# SPDX-License-Identifier: GPL-3.0-or-later
# ruff: noqa: E501
"""Mutations of the T1640 nav tools: the nav line / menu table grammar mirror (`tools/play/route_nav.py`), the converter
(`tools/route_nav.py`: menu pick, cursor read, at/to choice, overlap with marks and nav steps) and the nav handling of
`tools/route_trim.py` (clip and remap). Run with `python tools/mutate/py_mutants.py --set route_nav_py` in a clean worktree.

Every `old` occurs exactly once (tests/test_mutation_anchors.py).
"""

MUTATIONS: list[dict] = []  # c_suites needs a native list, this set has none

_GRAMMAR = "tools/play/route_nav.py"
_CONVERT = "tools/route_nav.py"
_TRIM = "tools/route_trim.py"
_STATE = "tools/route_nav_state.py"
_CLI = "tools/play/cli.py"
_ACTION = "tools/action_profile.py"
_TARGET = [
    "pytest: tests/test_t1640_route_nav.py tests/test_t1640_route_nav_state.py tests/test_t1640_route_nav_record.py"
]


def _mutation(file: str, name: str, old: str, new: str, why: str) -> dict:
    return {
        "id": f"route-nav-py-{name}",
        "file": file,
        "old": old,
        "new": new,
        "targets": _TARGET,
        "why": why,
    }


PYTHON_MUTATIONS: list[dict] = [
    # ---- grammar mirror ----
    _mutation(
        _GRAMMAR,
        "at-equals-to-refused",
        "    if at > to:\n",
        "    if at >= to:\n",
        "an empty range at=to is refused",
    ),
    _mutation(
        _GRAMMAR,
        "expect-without-activate",
        "if expect is not None and not activate:",
        "if False:",
        "expect= without activate is accepted",
    ),
    _mutation(
        _GRAMMAR,
        "duplicate-key",
        "        if key in seen:\n            raise NavError(f\"'{key}' given twice\")",
        "        if key in seen and key != 'at':\n            raise NavError(f\"'{key}' given twice\")",
        "a repeated at= is accepted",
    ),
    _mutation(
        _GRAMMAR,
        "name-length",
        "if len(out) + 1 >= NAME_MAX + 1:",
        "if len(out) + 1 > NAME_MAX + 1:",
        "a 64 byte name is accepted",
    ),
    _mutation(
        _GRAMMAR,
        "name-space",
        "if not 0x20 <= code <= 0x7E:",
        "if not 0x21 <= code <= 0x7E:",
        "%20 (space) in a name is refused",
    ),
    _mutation(
        _GRAMMAR,
        "retry-limit",
        '_number(seen["retry"], RETRY_MAX, "retry")',
        '_number(seen["retry"], RETRY_MAX + 1, "retry")',
        "retry=101 is accepted",
    ),
    _mutation(
        _GRAMMAR,
        "timeout-minimum",
        '_number(seen["timeout"], route_wait.TIMEOUT_MS_LIMIT, "timeout", 1)',
        '_number(seen["timeout"], route_wait.TIMEOUT_MS_LIMIT, "timeout", 0)',
        "timeout=0 is accepted",
    ),
    _mutation(
        _GRAMMAR,
        "index-limit",
        'index = _number(select[6:], INDEX_MAX, "select index")',
        'index = _number(select[6:], INDEX_MAX + 1, "select index")',
        "index:0x1000000 is accepted",
    ),
    _mutation(
        _GRAMMAR,
        "marks-inside-inclusive",
        "inside = [mark for mark in found.marks if step.at < mark < step.to]",
        "inside = [mark for mark in found.marks if step.at <= mark <= step.to]",
        "a mark exactly at P or Q is called inside",
    ),
    _mutation(
        _GRAMMAR,
        "adjacent-steps-overlap",
        "if previous is not None and step.at < previous[1].to:",
        "if previous is not None and step.at <= previous[1].to:",
        "a step starting where the previous one ends is called overlapping",
    ),
    _mutation(
        _GRAMMAR,
        "to-past-record",
        "if step.to > found.polls:",
        "if step.to >= found.polls:",
        "to= equal to the record's poll count is refused",
    ),
    _mutation(
        _GRAMMAR,
        "line-count",
        "if total > MAX_NAV_LINES:",
        "if total >= MAX_NAV_LINES:",
        "the 64th nav line is refused",
    ),
    _mutation(
        _GRAMMAR,
        "cond-less-than",
        '"<": masked < cond.value,',
        '"<": masked <= cond.value,',
        "a < condition holds at equality",
    ),
    _mutation(
        _GRAMMAR,
        "cond-mask",
        "masked = value & cond.mask",
        "masked = value",
        "the mask of a condition is not applied",
    ),
    _mutation(
        _GRAMMAR,
        "encode-percent",
        "byte not in (0x25, 0x3D)",
        "byte not in (0x3D,)",
        "a percent sign is written raw by encode_name",
    ),
    _mutation(
        _GRAMMAR,
        "fold-range",
        "if 0x41 <= byte <= 0x5A else byte",
        "if 0x41 <= byte <= 0x5B else byte",
        "'[' folds to '{' in the case blind name match",
    ),
    _mutation(
        _GRAMMAR,
        "names-stride-limit",
        "route_wait.c_number(parts[1], 4096)",
        "route_wait.c_number(parts[1], 4097)",
        "a names stride of 4097 is accepted",
    ),
    _mutation(
        _GRAMMAR,
        "timing-limit",
        "route_wait.c_number(hold_text, TIMING_LIMIT)",
        "route_wait.c_number(hold_text, TIMING_LIMIT + 1)",
        "a hold of 121 polls is accepted",
    ),
    _mutation(
        _GRAMMAR,
        "flags-without-mode",
        "if mode is None and not has_nav_lines(record_text):",
        "if mode is None:",
        "a record with nav steps and no explicit mode gets no host flags",
    ),
    _mutation(
        _GRAMMAR,
        "strip-timing",
        '"--route-nav-timing": 1,',
        '"--route-nav-timing": 0,',
        "the value of the timing flag is left behind on a host that predates T1640",
    ),
    # ---- converter ----
    _mutation(
        _CONVERT,
        "mark-inside-press",
        "if any(edge < mark < release for mark in marks):",
        "if any(edge < mark <= release for mark in marks):",
        "a mark at the poll after the A release blocks the conversion",
    ),
    _mutation(
        _CONVERT,
        "bound-mark-edge",
        "+ [mark for mark in marks if mark <= edge]",
        "+ [mark for mark in marks if mark < edge]",
        "a mark exactly at the A press does not limit the run",
    ),
    _mutation(
        _CONVERT,
        "bound-nav-end",
        "+ [end for _, end in occupied if end <= edge]",
        "+ [end for _, end in occupied if end < edge]",
        "an existing step ending at the A press does not limit the run",
    ),
    _mutation(
        _CONVERT,
        "run-ignores-bound",
        "or press.edge < bound",
        "or False",
        "the run of presses reaches back over marks and existing steps",
    ),
    _mutation(
        _CONVERT,
        "run-ignores-axis",
        "or not press.dirs <= axis",
        "or False",
        "a press on the other axis joins the run",
    ),
    _mutation(
        _CONVERT,
        "run-gap",
        "if cursor_position - press.release > options.max_gap:",
        "if cursor_position - press.release >= options.max_gap:",
        "a pause of exactly max-gap polls ends the run",
    ),
    _mutation(
        _CONVERT,
        "run-other-input",
        "if any(not pad.quiet[poll] for poll in range(press.release, cursor_position)):",
        "if False:",
        "another button or a stick push between two presses does not end the run",
    ),
    _mutation(
        _CONVERT,
        "range-start",
        "start = run[-1].edge if run else edge",
        "start = run[0].edge if run else edge",
        "the range starts at the LAST press of the run instead of the first",
    ),
    _mutation(
        _CONVERT,
        "covered-start",
        "step.at <= edge < max(step.to, step.at + 1)",
        "step.at < edge < max(step.to, step.at + 1)",
        "an existing step starting at the A press does not cover it",
    ),
    _mutation(
        _CONVERT,
        "line-limit",
        "        if count >= grammar.MAX_NAV_LINES:\n            outcomes.append(",
        "        if count > grammar.MAX_NAV_LINES:\n            outcomes.append(",
        "a 65th nav line is written",
    ),
    _mutation(
        _CONVERT,
        "promote-line-limit",
        "    if count >= grammar.MAX_NAV_LINES:\n        return Outcome(",
        "    if count > grammar.MAX_NAV_LINES:\n        return Outcome(",
        "a 65th promoted nav line is written",
    ),
    _mutation(
        _CONVERT,
        "insert-boundary",
        "flush(position + frames)",
        "flush(position + frames + 1)",
        "a line for a run boundary poll lands before the previous run",
    ),
    _mutation(
        _CONVERT,
        "insert-order",
        "pending[0].at < limit",
        "pending[0].at <= limit",
        "a line for the first poll of the next run lands before this run",
    ),
    _mutation(
        _CONVERT,
        "memlog-group",
        "specs[index : index + per_run]",
        "specs[index : index + per_run + 1]",
        "memlog groups hold one address too many",
    ),
    _mutation(
        _CONVERT,
        "dry-run-existing",
        "if out.exists() and not args.force and not args.dry_run:",
        "if out.exists() and not args.force:",
        "a dry run refuses an existing output",
    ),
    _mutation(
        _CONVERT,
        "nothing-to-add",
        "if not conversion.converted:",
        "if False:",
        "a conversion with nothing to add writes a copy",
    ),
    _mutation(
        _CONVERT,
        "check-added-lines",
        "if number not in drop",
        "if number not in set()",
        "the internal check does not drop the added lines before comparing",
    ),
    # ---- grammar: widgets, page menus, items, ids ----
    _mutation(
        _GRAMMAR,
        "menu-duplicate",
        "if entry.id in menus:",
        "if False:",
        "a menu defined twice is accepted",
    ),
    _mutation(
        _GRAMMAR,
        "menu-count",
        "if len(menus) >= MAX_MENUS and not",
        "if len(menus) > MAX_MENUS and not",
        "a 33rd menu is accepted",
    ),
    _mutation(
        _GRAMMAR,
        "select-default",
        'if "select" in seen else "A",',
        'if "select" in seen else "B",',
        "the default select button is B",
    ),
    _mutation(
        _GRAMMAR,
        "cursor-count-together",
        'if ("cursor" in seen) != ("count" in seen):',
        'if ("cursor" in seen) and ("count" not in seen):',
        "count= without cursor= is accepted",
    ),
    _mutation(
        _GRAMMAR,
        "rows-need-a-cursor",
        'if "cursor" not in seen and any(',
        "if False and any(",
        "itemid=, items= or names= without a cursor is accepted",
    ),
    _mutation(
        _GRAMMAR,
        "stride-minimum",
        "stride < WIDGET_STRIDE_MIN",
        "stride <= WIDGET_STRIDE_MIN",
        "a stride of exactly 0x1B4 is refused",
    ),
    _mutation(
        _GRAMMAR,
        "skip-needs-flags",
        'if (masks["skip"] or masks["grey"]) and offsets["flags"] is None:',
        "if False:",
        "skip= or grey= without flags= is accepted",
    ),
    _mutation(
        _GRAMMAR,
        "type-count",
        "if len(types) >= MAX_TYPES or number is None:",
        "if len(types) > MAX_TYPES or number is None:",
        "five row types are accepted",
    ),
    _mutation(
        _GRAMMAR,
        "page-offset-pointer",
        'if text[2:3] in ("*", ""):',
        'if text[2:3] in ("",):',
        "an indirect page offset @+*ADDR is accepted",
    ),
    _mutation(
        _GRAMMAR,
        "default-lost-extra",
        "DEFAULT_LOST_EXTRA = 2",
        "DEFAULT_LOST_EXTRA = 3",
        "the default lost press allowance is 3 polls",
    ),
    _mutation(
        _GRAMMAR,
        "id-limit",
        '_number(select[3:], 0xFFFFFFFF, "select id")',
        '_number(select[3:], 0xFFFFFFFF + 1, "select id")',
        "id:0x100000000 is accepted",
    ),
    # ---- state sources ----
    _mutation(
        _STATE,
        "cond-false-ignored",
        "elif value is None or not grammar.eval_cond(cond, value):",
        "elif value is None:",
        "an active condition that does not hold is ignored: every menu looks active",
    ),
    _mutation(
        _STATE,
        "unknown-is-true",
        'return "unknown" if unknown else "true"',
        'return "true"',
        "a missing sample counts as a held condition",
    ),
    _mutation(
        _STATE,
        "sample-at-edge",
        "bisect.bisect_right([sample[0] for sample in samples], poll)",
        "bisect.bisect_left([sample[0] for sample in samples], poll)",
        "a sample logged AT the activation poll is not used",
    ),
    _mutation(
        _STATE,
        "cursor-mask",
        "MenuState(picked, menu.cursor.read(cursor), item_id=item_id)",
        "MenuState(picked, cursor, item_id=item_id)",
        "the mask of the cursor reference is not applied",
    ),
    _mutation(
        _STATE,
        "pick-cursor-first",
        "with_cursor = [menu_id for menu_id in true if menus[menu_id].has_cursor]",
        "with_cursor = []",
        "a container page without a cursor competes with its list",
    ),
    _mutation(
        _STATE,
        "pick-ready",
        "if ready.get(menu_id) is not False]",
        "if ready.get(menu_id) is not True]",
        "a menu whose ready conditions are unknown loses against none",
    ),
    _mutation(
        _STATE,
        "locate-state-first",
        "if best is None or (state, slot) > best:",
        "if best is None or slot > best[1]:",
        "the highest slot wins whatever the page state",
    ),
    _mutation(
        _STATE,
        "locate-closing",
        "or state in widgets.closing:",
        "or state in ():",
        "a closing page is taken as the menu",
    ),
    _mutation(
        _STATE,
        "locate-used",
        "if not used or found != builder",
        "if found != builder",
        "a free slot with leftover bytes is taken as the page",
    ),
    _mutation(
        _STATE,
        "snapshot-gap",
        "if offset == len(data):",
        "if True:",
        "a dump row that does not continue the block is appended",
    ),
    _mutation(
        _STATE,
        "walk-types",
        "if node_type in items.types:",
        "if True:",
        "dividers count as cursor rows",
    ),
    _mutation(
        _STATE,
        "ids-unique",
        "sum(1 for other in rows if other.item_id == row.item_id) == 1",
        "sum(1 for other in rows if other.item_id == row.item_id) >= 1",
        "a repeated item id counts as unique",
    ),
    _mutation(
        _STATE,
        "label-unique",
        "sum(1 for other in rows if other.label == row.label and not other.skipped) == 1",
        "sum(1 for other in rows if other.label == row.label and not other.skipped) >= 1",
        "a repeated label counts as unique",
    ),
    _mutation(
        _STATE,
        "no-cursor-row",
        "if cursor == NO_ROW:",
        "if False:",
        "a cursor with no row yet (0xFFFFFFFF) is converted",
    ),
    _mutation(
        _STATE,
        "nav-line-poll",
        "index = bisect.bisect_right(self.polls, poll)",
        "index = bisect.bisect_left(self.polls, poll)",
        "a nav line logged AT the press poll is not used",
    ),
    _mutation(
        _STATE,
        "nav-id-evidence",
        "return None if len(seen) < 2 else True",
        "return None if len(seen) < 2 else False",
        "an id seen on two different rows is called repeated",
    ),
    # ---- converter: the choice ----
    _mutation(
        _CONVERT,
        "choice-id-forced",
        'if wanted == "id" and id_problem is not None:',
        "if False:",
        "--select-by id converts a row without a usable id",
    ),
    _mutation(
        _CONVERT,
        "choice-id-unique",
        "if state.ids_unique is False:",
        "if False:",
        "an id shared by two rows is selected by id",
    ),
    _mutation(
        _CONVERT,
        "choice-avoid",
        "if menu.id in options.avoid_id:",
        "if False:",
        "a menu with repeated ids is selected by id",
    ),
    _mutation(
        _CONVERT,
        "choice-label-unique",
        "if state.label_unique is False:",
        "if False:",
        "a label shared by two rows is selected by name",
    ),
    _mutation(
        _CONVERT,
        "choice-no-id",
        "if state.item_id is None or state.item_id == NO_ROW:",
        "if state.item_id is None:",
        "the item id 0xFFFFFFFF (no id) is selected by id",
    ),
    _mutation(
        _CONVERT,
        "repeated-menus",
        'REPEATED_ID_MENUS = frozenset({"editor-map-settings", "editor-tools"})',
        'REPEATED_ID_MENUS = frozenset({"editor-map-settings"})',
        "editor-tools is selected by id although its ids repeat",
    ),
    _mutation(
        _CONVERT,
        "chain-reason",
        "if len(sources) == 1:",
        "if len(sources) >= 1:",
        "the reasons of several sources are not all reported",
    ),
    _mutation(
        _CONVERT,
        "dump-pointer",
        'add(f"0x{ref.address:X}:4")',
        'add(f"0x{ref.address:X}:8")',
        "the pointer dword of an indirect reference is dumped with the wrong width",
    ),
    _mutation(
        _CONVERT,
        "memlog-plain",
        "plain = [menu for menu in menus.values() if menu.has_cursor and not menu.uses_page()]",
        "plain = [menu for menu in menus.values() if menu.has_cursor]",
        "page based menus are offered to --route-log-mem",
    ),
    _mutation(
        _CONVERT,
        "range-end",
        "start, release, menu.id, kind,",
        "start, edge, menu.id, kind,",
        "the range ends at the A press instead of after its release",
    ),
    _mutation(
        _GRAMMAR,
        "record-flag-added",
        'if "--route-nav-record" not in passthrough:',
        "if False:",
        "a recording never gets --route-nav-record on",
    ),
    _mutation(
        _GRAMMAR,
        "record-explicit-off",
        'if explicit == "off":',
        "if False:",
        "an explicit --route-nav-record off is overridden",
    ),
    _mutation(
        _GRAMMAR,
        "record-opt-out",
        "    if opt_out:\n        return [], []",
        "    if False:\n        return [], []",
        "--no-route-nav does not stop the recording flags",
    ),
    _mutation(
        _GRAMMAR,
        "strip-record-value",
        '"--route-nav-record": 1,',
        '"--route-nav-record": 0,',
        "the value of --route-nav-record is left behind when the flags are stripped",
    ),
    _mutation(
        _GRAMMAR,
        "has-nav-flags",
        "return any(token in NAV_HOST_FLAGS for token in command)",
        'return "--route-nav" in command',
        "a recording command is not recognised as carrying nav flags",
    ),
    _mutation(
        _CLI,
        "record-flags-not-added",
        "    extra += nav_record_flags(args)\n",
        "    extra += []\n",
        "tools.play never adds the nav recording flags",
    ),
    _mutation(
        _CLI,
        "record-opt-out-refused",
        "if args.replay_input is None and args.record_input is None and args.no_route_nav:",
        "if args.replay_input is None and args.no_route_nav:",
        "--no-route-nav is refused for a recording",
    ),
    _mutation(
        _CONVERT,
        "promote-activation",
        "if not step.at <= edge <= step.to or not step.activate:",
        "if not step.activate:",
        "a host nav-line that does not hold the press is promoted",
    ),
    _mutation(
        _CONVERT,
        "promote-mark",
        "if any(step.at < mark < step.to for mark in marks):",
        "if any(step.at < mark <= step.to for mark in marks):",
        "a mark at the end of a promoted range blocks it",
    ),
    _mutation(
        _CONVERT,
        "promote-overlap",
        "if any(start < step.to and end > step.at for start, end in occupied):",
        "if any(start < step.to and end >= step.at for start, end in occupied):",
        "a promoted line that touches the previous one is called overlapping",
    ),
    _mutation(
        _CONVERT,
        "compare-key",
        "return (step.at, step.to, step.menu, step.select_text, step.activate)",
        "return (step.at, step.to, step.menu, step.activate)",
        "a changed select is not a mismatch",
    ),
    _mutation(
        _CONVERT,
        "compare-reason",
        'skip.reason == "suppressed"',
        "True",
        "any nav-skip explains a missing record line",
    ),
    _mutation(
        _CONVERT,
        "compare-range",
        'and skip.fields.get("to") == str(line.step.to)',
        "and True",
        "a suppression of another range explains a missing record line",
    ),
    _mutation(
        _CONVERT,
        "compare-exit",
        "return 0 if result.equal and not events.bad_lines else 2",
        "return 0 if result.equal else 2",
        "a malformed nav-line in the log does not fail the comparison",
    ),
    _mutation(
        _STATE,
        "host-line-edge",
        "events.lines.append(HostNavLine(poll, step.at if edge is None else edge, step))",
        "events.lines.append(HostNavLine(poll, step.at, step))",
        "the select edge of a host nav-line is ignored",
    ),
    _mutation(
        _STATE,
        "unreadable-cursor",
        "        if sample.cursor is None:\n            return Lookup(",
        "        if False:\n            return Lookup(",
        "an unreadable cursor (?) is converted",
    ),
    _mutation(
        _STATE,
        "snapshot-smallest",
        "(best is None or len(data) < len(best[1]))",
        "best is None",
        "the first enclosing segment answers instead of the smallest",
    ),
    _mutation(
        _STATE,
        "align-no-going-back",
        "if offset <= poll - edge <= offset + self.slack",
        "if 0 <= poll - edge <= offset + self.slack",
        "the stall offset may go down between mark segments",
    ),
    _mutation(
        _STATE,
        "align-tie",
        "                        -shift,\n",
        "                        shift,\n",
        "the largest offset wins a tie",
    ),
    _mutation(
        _STATE,
        "exact-stall-mark",
        "marks[ordinal - 1] <= edge",
        "marks[ordinal - 1] < edge",
        "a press exactly at the stalled mark is not shifted",
    ),
    _mutation(
        _STATE,
        "skipped-flag",
        "skipped = flags is not None and bool(flags & items.skip_mask)",
        "skipped = False",
        "skipped rows count against a label",
    ),
    _mutation(
        _STATE,
        "skipped-unique",
        "if other.label == row.label and not other.skipped",
        "if other.label == row.label",
        "a skipped title with the same text makes a label look repeated",
    ),
    _mutation(
        _CONVERT,
        "selectby-name",
        'tried_name = wanted == "name" or (auto and menu.selectby in ("id", "name"))',
        'tried_name = wanted == "name" or (auto and menu.selectby in ("id",))',
        "selectby=name menus are written by index",
    ),
    _mutation(
        _CONVERT,
        "selectby-id",
        'tried_id = wanted == "id" or (auto and menu.selectby == "id")',
        'tried_id = wanted == "id" or (auto and menu.selectby != "index")',
        "selectby=name menus are written by id",
    ),
    _mutation(
        _GRAMMAR,
        "dpad-flag",
        'dpad=seen.get("dpad") != "0",',
        'dpad=seen.get("dpad") == "0",',
        "dpad=0 is read as dpad=1",
    ),
    _mutation(
        _GRAMMAR,
        "selectby-default",
        'selectby=seen.get("selectby", "id"),',
        'selectby=seen.get("selectby", "name"),',
        "the default selectby is name",
    ),
    _mutation(
        _GRAMMAR,
        "dpad-needs-cursor",
        'key in seen for key in ("itemid", "items", "names", "dpad", "selectby")',
        'key in seen for key in ("itemid", "items", "names")',
        "dpad= or selectby= without a cursor is accepted",
    ),
    # ---- trim ----
    _mutation(
        _TRIM,
        "clip-left-piece",
        "shrunk.append((start, at))",
        "shrunk.append((start, at - 1))",
        "the part of a cut before a nav range loses a poll",
    ),
    _mutation(
        _TRIM,
        "clip-right-piece",
        "shrunk.append((to, end))",
        "shrunk.append((to + 1, end))",
        "the part of a cut after a nav range loses a poll",
    ),
    _mutation(
        _TRIM,
        "clip-longest",
        "best = max(pieces,",
        "best = min(pieces,",
        "the shortest remaining piece of a clipped cut is kept",
    ),
    _mutation(
        _TRIM,
        "clip-unchanged",
        "if pieces == [cut]:",
        "if False:",
        "a cut that touches no nav range is reported as clipped",
    ),
    _mutation(
        _TRIM,
        "remap-keys",
        'key in ("at", "to")',
        'key in ("at",)',
        "to= of a nav line is not remapped",
    ),
    _mutation(
        _TRIM,
        "remap-value",
        'parts[index] = f"{key}={new_position(int(value), cuts)}"',
        'parts[index] = f"{key}={int(value)}"',
        "at= and to= of a nav line are not moved by the cuts",
    ),
    _mutation(
        _TRIM,
        "verify-enter-end",
        "if any(start < to and end > at for start, end in cuts):",
        "if any(start <= to and end > at for start, end in cuts):",
        "a cut starting at the end of a nav range is called entering it",
    ),
    # ---- launch glue ----
    _mutation(
        _CLI,
        "flags-not-added",
        "        extra += nav_flags(args)\n",
        "        extra += []\n",
        "tools.play never passes the nav flags to the host",
    ),
    _mutation(
        _CLI,
        "nav-check-skipped",
        "    navs = nav_refusal(args)\n    if navs is not None:",
        "    navs = None\n    if navs is not None:",
        "--check-route and the launch never validate the nav lines",
    ),
    _mutation(
        _CLI,
        "marker-not-checked",
        "if route_nav.has_nav_flags(command) and not route_nav.host_supports_nav(ROOT / host):",
        "if False:",
        "a host that predates T1640 gets flags it refuses",
    ),
    _mutation(
        _CLI,
        "opt-out-ignored",
        "text, args.route_nav, nav_menus_file(args), args.route_nav_timing, args.no_route_nav",
        "text, args.route_nav, nav_menus_file(args), args.route_nav_timing, False",
        "--no-route-nav does nothing",
    ),
    _mutation(
        _ACTION,
        "opt-out-not-forwarded",
        'if getattr(args, "no_route_nav", False) and replays:',
        "if False:",
        "tools.action_profile drops --no-route-nav",
    ),
]
