# SPDX-License-Identifier: GPL-3.0-or-later
# ruff: noqa: E501
"""Mutations of tools/route_trim.py (T1636): the idle test, the settle guard rule, the cut placement, the mark remap, the run
formatting and the file safety. Run with `python tools/mutate/py_mutants.py --set route_trim` in a clean worktree.

Every `old` occurs exactly once (tests/test_mutation_anchors.py).
"""

MUTATIONS: list[dict] = []  # c_suites needs a native list, this set has none

_FILE = "tools/route_trim.py"
_TARGET = ["pytest: tests/test_t1636_route_trim.py"]

PYTHON_MUTATIONS: list[dict] = [
    {
        "id": "route-trim-quiet-ignores-digital",
        "file": _FILE,
        "old": "        if name in DIGITAL:\n            return False",
        "new": "        if False:\n            return False",
        "targets": _TARGET,
        "why": "a held digital button counts as idle, an input would be cut",
    },
    {
        "id": "route-trim-quiet-analog-threshold",
        "file": _FILE,
        "old": "value > analog_quiet",
        "new": "value > 255",
        "targets": _TARGET,
        "why": "a pressed analog button (A=255 is not above 255) counts as idle",
    },
    {
        "id": "route-trim-quiet-stick-limit",
        "file": _FILE,
        "old": "abs(value) > (STICKS[name] if stick_quiet is None else stick_quiet)",
        "new": "abs(value) > 32767",
        "targets": _TARGET,
        "why": "a full stick deflection counts as idle",
    },
    {
        "id": "route-trim-guard-min-counts",
        "file": _FILE,
        "old": "return bool(keys - NON_GUARD_FIELDS)",
        "new": "return bool(keys)",
        "targets": _TARGET,
        "why": "a min= only wait is taken as a settle guard, a load could be cut",
    },
    {
        "id": "route-trim-guard-ignored",
        "file": _FILE,
        "old": "if spec is not None and is_guard(spec):",
        "new": "if spec is not None:",
        "targets": _TARGET,
        "why": "any wait, even min only, unlocks the pre-mark cut",
    },
    {
        "id": "route-trim-pre-mark-keep-ignored",
        "file": _FILE,
        "old": '    if options.pre_mark == "keep":',
        "new": "    if False:",
        "targets": _TARGET,
        "why": "--pre-mark keep still cuts guarded gaps",
    },
    {
        "id": "route-trim-evidence-ms-as-polls",
        "file": _FILE,
        "old": "proven = int(quiet_ms[mark] * EVIDENCE_POLL_RATE / 1000.0)",
        "new": "proven = int(quiet_ms[mark])",
        "targets": _TARGET,
        "why": "ms are read as polls, far more than the quiet time",
    },
    {
        "id": "route-trim-evidence-no-margin",
        "file": _FILE,
        "old": "max(0, proven - options.margin)",
        "new": "max(0, proven)",
        "targets": _TARGET,
        "why": "the proven quiet time is cut down to zero margin",
    },
    {
        "id": "route-trim-pre-mark-min-gap",
        "file": _FILE,
        "old": "if allowed > 0 and length >= (options.nav_min_gap if nav_post else options.min_gap):",
        "new": "if allowed > 0:",
        "targets": _TARGET,
        "why": "a short pre-mark gap is cut",
    },
    {
        "id": "route-trim-post-mark-margin",
        "file": _FILE,
        "old": "                            right - margin,\n                        )  # keep the polls right before the next input",
        "new": "                            right,\n                        )  # keep the polls right before the next input",
        "targets": _TARGET,
        "why": "no margin is kept before the next input",
    },
    {
        "id": "route-trim-tail-margin",
        "file": _FILE,
        "old": "                            left + margin,\n                            right,",
        "new": "                            left,\n                            right,",
        "targets": _TARGET,
        "why": "no margin is kept next to the last mark",
    },
    {
        "id": "route-trim-remap-marks",
        "file": _FILE,
        "old": "    return position - removed",
        "new": "    return position",
        "targets": _TARGET,
        "why": "marks keep their old position after a cut",
    },
    {
        "id": "route-trim-remap-overlap",
        "file": _FILE,
        "old": "removed += max(0, min(end, position) - start)",
        "new": "removed += max(0, end - start)",
        "targets": _TARGET,
        "why": "a cut after the mark moves it as well",
    },
    {
        "id": "route-trim-merge-different-states",
        "file": _FILE,
        "old": "pending[0] == item.state",
        "new": "pending[0] != item.state",
        "targets": _TARGET,
        "why": "runs of different states are merged",
    },
    {
        "id": "route-trim-run-cap",
        "file": _FILE,
        "old": "piece = min(frames, RUN_LIMIT)",
        "new": "piece = frames",
        "targets": _TARGET,
        "why": "a run above the script grammar cap is written",
    },
    {
        "id": "route-trim-overwrite-original",
        "file": _FILE,
        "old": "    if out.resolve() == route_path.resolve():",
        "new": "    if False:",
        "targets": _TARGET,
        "why": "the original can be the output",
    },
    {
        "id": "route-trim-mark-position-unchecked",
        "file": _FILE,
        "old": "            if at != position:",
        "new": "            if False:",
        "targets": _TARGET,
        "why": "a mark that is not at its poll position is accepted",
    },
    {
        "id": "route-trim-trailer-unchecked",
        "file": _FILE,
        "old": "    if route.polls != position:",
        "new": "    if False:",
        "targets": _TARGET,
        "why": "a trailer that disagrees with the body is accepted",
    },
    {
        "id": "route-trim-stick-drift-off",
        "file": _FILE,
        "old": "stick_spread(route, left, right) > options.stick_drift",
        "new": "stick_spread(route, left, right) > 10**9",
        "targets": _TARGET,
        "why": "a deliberate sub-dead-zone stick move is cut",
    },
    {
        "id": "route-trim-region-marks-exclusive",
        "file": _FILE,
        "old": "if start <= at <= end]",
        "new": "if start < at < end]",
        "targets": _TARGET,
        "why": "a mark on the edge of an idle region is not attributed",
    },
    {
        "id": "route-trim-verify-idle-check",
        "file": _FILE,
        "old": "quiet_cut = [index for index in removed if not is_quiet(old_states[index])]",
        "new": "quiet_cut = []",
        "targets": _TARGET,
        "why": "the self check no longer sees a cut input",
    },
    {
        "id": "route-trim-waits-name",
        "file": _FILE,
        "old": "line.replace(route_path.name, out.name) if",
        "new": "line if",
        "targets": _TARGET,
        "why": "the copied waits file keeps naming the original route",
    },
    {
        "id": "route-trim-lead-in-always",
        "file": _FILE,
        "old": 'options.lead_in == "trim"',
        "new": "True",
        "targets": _TARGET,
        "why": "the guest boot lead-in is cut without --lead-in trim",
    },
    {
        "id": "route-trim-default-out-name",
        "file": _FILE,
        "old": 'route_path.stem + ".trim" + route_path.suffix',
        "new": "route_path.stem + route_path.suffix",
        "targets": _TARGET,
        "why": "the default output is the input name",
    },
    {
        "id": "route-trim-dry-run-writes",
        "file": _FILE,
        "old": '    if args.dry_run:\n        print("dry run: nothing written")',
        "new": '    if False:\n        print("dry run: nothing written")',
        "targets": _TARGET,
        "why": "--dry-run writes the files",
    },
]
