# SPDX-License-Identifier: GPL-3.0-or-later
# ruff: noqa: E501
"""Mutants of tools.tracegaps.addresstaking (T603), fields in the order of `mutate.Mutation`:
(identifier, file, old, new, why, real, suite)."""

SUITE = "tests/test_addresstaking.py"
FILE = "addresstaking.py"

MUTANTS: list[tuple[str, str, str, str, str, bool, str]] = [
    # ---- jump_table: the compiler pattern and its conditions
    (
        "taking-jump-table-accepts-jae-as-the-bound",
        FILE,
        'if previous.mnemonic == "ja" and previous.operands[0].type == cs_x86.X86_OP_IMM:',
        'if previous.mnemonic in ("ja", "jae") and previous.operands[0].type == cs_x86.X86_OP_IMM:',
        "a jae (index may equal the bound) bounds the table like ja does",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-ignores-branch-targets",
        FILE,
        'if cursor.address in targets or cursor.address in taken:\n            return "a branch target lies between the bound and the jmp"',
        'if cursor.address in taken:\n            return "a branch target lies between the bound and the jmp"',
        "a direct branch into the middle of the bound pattern no longer refuses the table",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-ignores-taken-addresses",
        FILE,
        'if cursor.address in targets or cursor.address in taken:\n            return "a branch target lies between the bound and the jmp"',
        'if cursor.address in targets:\n            return "a branch target lies between the bound and the jmp"',
        "an address taken inside the bound pattern (an indirect entry) no longer refuses the table",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-allows-flag-writes-before-the-ja",
        FILE,
        'if flags:\n                return "the flags are rewritten between the cmp and the ja"',
        'if False:\n                return "the flags are rewritten between the cmp and the ja"',
        "an instruction that clobbers the flags between the cmp and the ja leaves the bound standing",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-allows-index-rewrite-after-the-ja",
        FILE,
        'elif register in written:\n                return "index register rewritten after the bound"',
        'elif False:\n                return "index register rewritten after the bound"',
        "the index register may change between the ja and the jmp",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-allows-index-rewrite-before-the-ja",
        FILE,
        'if register in written:\n                return "index register rewritten between the cmp and the ja"',
        'if False:\n                return "index register rewritten between the cmp and the ja"',
        "the index register may change between the cmp and the ja",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-allows-a-transfer-between-ja-and-jmp",
        FILE,
        'elif _is_transfer(previous):\n                return "a transfer between the bound and the jmp"',
        'elif False:\n                return "a transfer between the bound and the jmp"',
        "a call or another jump between the ja and the jmp is skipped over",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-allows-a-transfer-between-cmp-and-ja",
        FILE,
        'if _is_transfer(previous):\n                return "a transfer between the cmp and the ja"',
        'if False:\n                return "a transfer between the cmp and the ja"',
        "a call or another jump between the cmp and the ja is skipped over",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-bound-off-by-one",
        FILE,
        "entries = bound + 1",
        "entries = bound",
        "the table loses its last slot",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-byte-maximum-off-by-one",
        FILE,
        "entries = max(data) + 1",
        "entries = max(data)",
        "the two level table loses the slot of the largest byte",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-accepts-an-unaligned-base",
        FILE,
        'if base % 4:\n        return "table base is not 4-aligned"',
        'if False:\n        return "table base is not 4-aligned"',
        "a table whose slots are not dwords of the run is accepted",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-accepts-a-slot-in-another-section",
        FILE,
        "value is None or code.insn_at(value) is None or image.section_at(value) is not section",
        "value is None or code.insn_at(value) is None",
        "a slot may point out of the jump's section",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-accepts-a-slot-that-is-no-instruction",
        FILE,
        "value is None or code.insn_at(value) is None or image.section_at(value) is not section",
        "value is None or image.section_at(value) is not section",
        "a slot may point into the middle of an instruction or at data",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-accepts-a-huge-bound",
        FILE,
        "if bound >= MAX_ENTRIES:",
        "if bound > MAX_ENTRIES:",
        "a bound of exactly MAX_ENTRIES is not refused as not small",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-window-too-short",
        FILE,
        "BOUND_WINDOW = 16",
        "BOUND_WINDOW = 4",
        "a bound with a few instructions between the cmp and the jmp is no longer found",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-bound-constant-ignores-branch-targets",
        FILE,
        'if cursor.address in targets or cursor.address in taken:\n            return "a branch target lies between the bound constant and the cmp"',
        'if False:\n            return "a branch target lies between the bound constant and the cmp"',
        "a jump past the mov that sets the bound register leaves the bound standing",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-bound-register-set-by-any-write",
        FILE,
        'previous.mnemonic == "mov"\n                and source is not None',
        "source is not None",
        "an add or sub of a constant counts as setting the bound register",
        False,
        SUITE,
    ),
    (
        "taking-jump-table-byte-read-accepts-wider-moves",
        FILE,
        "if source.type != cs_x86.X86_OP_MEM or source.size != 1:",
        "if source.type != cs_x86.X86_OP_MEM:",
        "a word read of the run counts as a byte read",
        False,
        SUITE,
    ),
    # ---- the runs and the rules
    (
        "taking-run-does-not-extend-backward",
        FILE,
        "while code_word(low - 4):",
        "while False:",
        "a run starts at the slot asked about, not at its first dword",
        False,
        SUITE,
    ),
    (
        "taking-run-references-skip-the-first-dword",
        FILE,
        "for address in range(low, high):\n            for hit in self._hits.get(address, ()):\n                if hit.kind not in TAKING_KINDS:",
        "for address in range(low + 4, high):\n            for hit in self._hits.get(address, ()):\n                if hit.kind not in TAKING_KINDS:",
        "an immediate that names the table base is no reference",
        False,
        SUITE,
    ),
    (
        "taking-run-references-skip-the-last-dword",
        FILE,
        "for address in range(low, high):\n            for hit in self._hits.get(address, ()):\n                if hit.kind not in TAKING_KINDS:",
        "for address in range(low, high - 4):\n            for hit in self._hits.get(address, ()):\n                if hit.kind not in TAKING_KINDS:",
        "a reference to the last dword of a run is not seen",
        False,
        SUITE,
    ),
    (
        "taking-run-is-never-indexed-on-demand",
        FILE,
        "            self._index(range(low, high))\n",
        "            pass\n",
        "a run `prepare` did not cover has no references and is called unreferenced",
        False,
        SUITE,
    ),
    (
        "taking-explanation-ignores-an-open-run",
        FILE,
        "        if not run.closed:\n            return None\n        if run.unreferenced:",
        "        if run.unreferenced:",
        "a table another instruction also reads is still explained",
        False,
        SUITE,
    ),
    (
        "taking-unreferenced-ignores-refusals",
        FILE,
        "return self.closed and not self.jumps and not self.byte_readers",
        "return not self.jumps and not self.byte_readers",
        "a run with a refused reference counts as unreferenced",
        False,
        SUITE,
    ),
    (
        "taking-byte-readers-are-refused",
        FILE,
        "if insn is not None and _byte_read(insn) is not None:",
        "if False:",
        "a byte read of the byte table closes no run",
        False,
        SUITE,
    ),
    (
        "taking-explanation-skips-the-body-check",
        FILE,
        "if not owners or any(address not in self.graph.body(owner) for owner in owners):",
        "if not owners:",
        "a target outside the body of the jump's function is explained",
        False,
        SUITE,
    ),
    (
        "taking-explanation-needs-only-one-owner",
        FILE,
        "any(address not in self.graph.body(owner) for owner in owners)",
        "all(address not in self.graph.body(owner) for owner in owners)",
        "a target in the body of only one of two owners of the jump is explained",
        False,
        SUITE,
    ),
    (
        "taking-table-reads-one-slot-too-many",
        FILE,
        "return self.base <= slot < self.end and (slot - self.base) % 4 == 0",
        "return self.base <= slot <= self.end and (slot - self.base) % 4 == 0",
        "the slot after the bound counts as read by the jump",
        False,
        SUITE,
    ),
    (
        "taking-operand-rule-ignores-the-base",
        FILE,
        "if hit.where in run.jumps and run.jumps[hit.where].base == address:",
        "if hit.where in run.jumps:",
        "any address of the run named by the jump is its own table operand",
        False,
        SUITE,
    ),
    # ---- part (b)
    (
        "taking-roles-exclude-a-push-like-a-compare",
        FILE,
        'if mnemonic in ("cmp", "test"):',
        'if mnemonic in ("cmp", "test", "push"):',
        "a pushed code address is excluded as a compare",
        False,
        SUITE,
    ),
    (
        "taking-excluding-roles-widened",
        FILE,
        "EXCLUDING_ROLES = frozenset({ROLE_COMPARE})",
        "EXCLUDING_ROLES = frozenset({ROLE_COMPARE, ROLE_ARGUMENT})",
        "every pushed argument is excluded",
        False,
        SUITE,
    ),
    (
        "taking-data-run-needs-both-neighbours",
        FILE,
        "kind = ROLE_DATA_TABLE if any(near) else ROLE_DATA_SLOT",
        "kind = ROLE_DATA_TABLE if all(near) else ROLE_DATA_SLOT",
        "a pointer with one code neighbour is called a lone slot",
        False,
        SUITE,
    ),
    (
        "taking-data-in-code-is-not-told-apart",
        FILE,
        "if name not in DATA_SECTIONS:",
        "if False:",
        "a dword stored in an executable section is called a data pointer",
        False,
        SUITE,
    ),
    (
        "taking-entry-flag-inverted",
        FILE,
        "target = taken_entries if role.entry else taken_interiors",
        "target = taken_interiors if role.entry else taken_entries",
        "function entries and interior addresses swap",
        False,
        SUITE,
    ),
    (
        "taking-classify-miscounts-roles",
        FILE,
        "roles[role.kind] = roles.get(role.kind, 0) + 1",
        "roles[role.kind] = roles.get(role.kind, 0) + 2",
        "the role counts no longer add up to the occurrences",
        False,
        SUITE,
    ),
    # ---- the retail image
    (
        "taking-real-small-tables-only",
        FILE,
        "MAX_ENTRIES = 4096",
        "MAX_ENTRIES = 24",
        "the larger switch tables of the retail image are no longer verified",
        True,
        SUITE,
    ),
    (
        "taking-real-short-bound-window",
        FILE,
        "BOUND_WINDOW = 16",
        "BOUND_WINDOW = 6",
        "bounds the compiler put more than six instructions before the jmp are lost",
        True,
        SUITE,
    ),
    (
        "taking-real-register-bounds-refused",
        FILE,
        "if second.type != cs_x86.X86_OP_REG or second.size != 4:",
        "if True:",
        "a cmp against a register set by a mov no longer bounds a table",
        True,
        SUITE,
    ),
    (
        "taking-real-unreferenced-runs-count-as-unread",
        FILE,
        "        if run.unreferenced:\n            return Explanation(RULE_UNREFERENCED, run.low)\n",
        "",
        "the 446 runs nothing names are reported as slots a closed table never reads",
        True,
        SUITE,
    ),
    (
        "taking-real-consumer-window-short",
        FILE,
        "CONSUMER_WINDOW = 14",
        "CONSUMER_WINDOW = 3",
        "pushed addresses whose call is more than three instructions away are not attributed",
        True,
        SUITE,
    ),
]
