# SPDX-License-Identifier: GPL-3.0-or-later
# ruff: noqa: E501
"""Mutants of tools.tracegaps.pools (T606, mutation-tested by T678), fields in the order of `mutate.Mutation`:
(identifier, file, old, new, why, real, suite).

Logic mutants (`real` False) are killed by the synthetic tests of tests/test_pools.py (stub graph,
real capstone instructions), the image-bound ones by its `_real_image` tests only (they change a
number or a pool the retail image pins). Anchors are checked by `mutate.run_one` (exactly one
occurrence) so a drifted anchor is reported ANCHOR-DRIFT, never counted killed."""

SUITE = "tests/test_pools.py"
FILE = "pools.py"

MUTANTS: list[tuple[str, str, str, str, str, bool, str]] = [
    (
        "pools-ret-operand-ignored",
        FILE,
        "insn.operands[0].imm if insn.operands else 0",
        "0",
        "a `ret 8` counts as `ret 0`",
        False,
        SUITE,
    ),
    (
        "pools-ret-without-operand-dropped",
        FILE,
        "insn.operands[0].imm if insn.operands else 0",
        "insn.operands[0].imm",
        "a bare `ret` is not read as `ret 0`",
        False,
        SUITE,
    ),
    (
        "pools-ret-mnemonic-wrong",
        FILE,
        'insn.mnemonic in ("ret", "retn")',
        'insn.mnemonic in ("retn",)',
        "a `ret` instruction is not a return",
        False,
        SUITE,
    ),
    (
        "pools-return-sizes-keep-last",
        FILE,
        "            sizes.add(insn.operands[0].imm if insn.operands else 0)",
        "            sizes = {insn.operands[0].imm if insn.operands else 0}",
        "only the last `ret` of a body counts",
        False,
        SUITE,
    ),
    (
        "pools-run-slots-take-every-hit-kind",
        FILE,
        'if hit.kind != "data":',
        "if False:",
        "an immediate or table hit is a slot of a run",
        False,
        SUITE,
    ),
    (
        "pools-run-slots-only-non-data-hits",
        FILE,
        'if hit.kind != "data":',
        'if hit.kind == "data":',
        "only the hits that are no pointer slot are runs",
        False,
        SUITE,
    ),
    (
        "pools-run-never-extends",
        FILE,
        "            while graph.is_code(image.u32(start - 4) or 0):",
        "            while False:",
        "every slot starts its own run",
        False,
        SUITE,
    ),
    (
        "pools-run-extends-by-two-dwords",
        FILE,
        "                start -= 4\n",
        "                start -= 8\n",
        "a run skips a dword while it walks back to its start",
        False,
        SUITE,
    ),
    (
        "pools-run-slot-index-halved",
        FILE,
        "runs[start].append((hit.where - start) // 4)",
        "runs[start].append((hit.where - start) // 2)",
        "the slot index is the byte offset over two",
        False,
        SUITE,
    ),
    (
        "pools-run-slot-index-from-where",
        FILE,
        "runs[start].append((hit.where - start) // 4)",
        "runs[start].append(hit.where // 4)",
        "the slot index is the address, not the offset in the run",
        False,
        SUITE,
    ),
    (
        "pools-shape-jump-ignored",
        FILE,
        '    if site.kind == "jump":\n',
        "    if False:\n",
        "a `jmp [reg + disp]` is classed as a vtable site",
        False,
        SUITE,
    ),
    (
        "pools-shape-register-kind-ignored",
        FILE,
        'if site.kind == "register" or insn is None or',
        "if insn is None or",
        "a register site with a memory instruction is classed by its operand",
        False,
        SUITE,
    ),
    (
        "pools-shape-missing-insn-crashes",
        FILE,
        'if site.kind == "register" or insn is None or insn.operands[0].type != cs_x86.X86_OP_MEM:',
        'if site.kind == "register" or insn.operands[0].type != cs_x86.X86_OP_MEM:',
        "a site without an instruction is not a register site",
        False,
        SUITE,
    ),
    (
        "pools-shape-memory-test-inverted",
        FILE,
        "insn.operands[0].type != cs_x86.X86_OP_MEM:",
        "insn.operands[0].type == cs_x86.X86_OP_MEM:",
        "a register operand is read as memory and a memory one as a register",
        False,
        SUITE,
    ),
    (
        "pools-shape-ebp-frame-dropped",
        FILE,
        "if mem.base in (cs_x86.X86_REG_ESP, cs_x86.X86_REG_EBP):",
        "if mem.base in (cs_x86.X86_REG_ESP,):",
        "an `[ebp + d]` call is bounded by a slot index",
        False,
        SUITE,
    ),
    (
        "pools-shape-esp-frame-dropped",
        FILE,
        "if mem.base in (cs_x86.X86_REG_ESP, cs_x86.X86_REG_EBP):",
        "if mem.base in (cs_x86.X86_REG_EBP,):",
        "an `[esp + d]` call is bounded by a slot index",
        False,
        SUITE,
    ),
    (
        "pools-shape-indexed-as-vtable",
        FILE,
        "    if mem.index != 0:\n",
        "    if False:\n",
        "a `call [reg*4 + base]` is bounded by its base displacement",
        False,
        SUITE,
    ),
    (
        "pools-shape-disp-not-masked",
        FILE,
        'return "vtable", mem.disp & 0xFFFFFFFF',
        'return "vtable", mem.disp',
        "a negative displacement keeps its sign",
        False,
        SUITE,
    ),
    (
        "pools-open-ignores-the-pool",
        FILE,
        'if verdict.pool or verdict.shape != "vtable"',
        'if verdict.shape != "vtable"',
        "a site with a candidate at its slot is not open",
        False,
        SUITE,
    ),
    (
        "pools-open-ignores-the-shape",
        FILE,
        'if verdict.pool or verdict.shape != "vtable"',
        "if verdict.pool",
        "a site with no displacement to bound is not open",
        False,
        SUITE,
    ),
    (
        "pools-open-needs-both",
        FILE,
        'if verdict.pool or verdict.shape != "vtable"',
        'if verdict.pool and verdict.shape != "vtable"',
        "a site is open only when it has a pool and no displacement",
        False,
        SUITE,
    ),
    (
        "pools-closable-needs-one-start",
        FILE,
        "return all(not self.open_sites(name) for name in self.starts)",
        "return any(not self.open_sites(name) for name in self.starts)",
        "one closed start closes the report",
        False,
        SUITE,
    ),
    (
        "pools-closable-always",
        FILE,
        "return all(not self.open_sites(name) for name in self.starts)",
        "return True",
        "the verdict is closable whatever the sites",
        False,
        SUITE,
    ),
    (
        "pools-closable-first-start-only",
        FILE,
        "return all(not self.open_sites(name) for name in self.starts)",
        "return all(not self.open_sites(name) for name in list(self.starts)[:1])",
        "only the first start is checked",
        False,
        SUITE,
    ),
    (
        "pools-closable-inverted",
        FILE,
        "return all(not self.open_sites(name) for name in self.starts)",
        "return all(self.open_sites(name) for name in self.starts)",
        "the verdict reads open for closed",
        False,
        SUITE,
    ),
    (
        "pools-render-closable-inverted",
        FILE,
        'f"CLOSABLE: {report.closable}"',
        'f"CLOSABLE: {not report.closable}"',
        "the printed verdict is the opposite of the report's",
        False,
        SUITE,
    ),
    (
        "pools-render-counts-sites-without-a-pool",
        FILE,
        "with_pool = sum(1 for verdict in verdicts if verdict.pool)",
        "with_pool = sum(1 for verdict in verdicts if not verdict.pool)",
        "the pooled site count is the unpooled one",
        False,
        SUITE,
    ),
    (
        "pools-render-runs-count-wrong",
        FILE,
        'f"  runs holding a candidate entry: {len(report.runs)}"',
        'f"  runs holding a candidate entry: {report.entries}"',
        "the printed run count is the entry count",
        False,
        SUITE,
    ),
    (
        "pools-real-pool-ignores-the-slot",
        FILE,
        "if disp // 4 in slots",
        "if True",
        "every run is in the pool of every vtable site",
        True,
        SUITE,
    ),
    (
        "pools-real-pool-address-is-the-run",
        FILE,
        "start_of_run + 4 * (disp // 4)",
        "start_of_run",
        "a pool lists the run start, not the slot",
        True,
        SUITE,
    ),
    (
        "pools-real-runs-from-interiors",
        FILE,
        "runs = _run_slots(graph, classification.entries)",
        "runs = _run_slots(graph, classification.interiors)",
        "the runs hold interiors, not member entries",
        True,
        SUITE,
    ),
    (
        "pools-real-runs-from-every-candidate",
        FILE,
        "runs = _run_slots(graph, classification.entries)",
        "runs = _run_slots(graph, candidates)",
        "the runs hold interiors as well as entries",
        True,
        SUITE,
    ),
    (
        "pools-real-arity-of-the-interiors",
        FILE,
        "for sizes in (_return_sizes(graph, entry) for entry in classification.entries)",
        "for sizes in (_return_sizes(graph, entry) for entry in classification.interiors)",
        "the arity is read over the interiors",
        True,
        SUITE,
    ),
    (
        "pools-real-arity-label-inverted",
        FILE,
        'if sizes else "no ret"',
        'if not sizes else "no ret"',
        "a function with a `ret` is `no ret`",
        True,
        SUITE,
    ),
    (
        "pools-real-members-off-by-one",
        FILE,
        "members=len(running.backward.members),",
        "members=len(running.backward.members) + 1,",
        "the callers closure size is off",
        True,
        SUITE,
    ),
    (
        "pools-real-classify-ignores-the-unexplained",
        FILE,
        "classification = addresstaking.classify(graph, running.backward.members, running.unexplained)",
        "classification = addresstaking.classify(graph, running.backward.members, [])",
        "the candidates are classified without the running flag's unexplained hits",
        True,
        SUITE,
    ),
    (
        "pools-real-claims-dropped",
        FILE,
        'claims = {"network poll": threadreach.poll_claims(graph)}',
        "claims = {}",
        "the poll thread's registrations are not claimed",
        True,
        SUITE,
    ),
]

# SURVIVORS, kept out of MUTANTS so the sweep stays green: measured equivalent on the retail image
# (T678). The retail run reads 80 vtable sites that all have a 4-aligned displacement (no `% 4`
# case exists), and the running flag has exactly two writer functions, 0x155550 and 0x156d80, each
# the only owner of its instruction and the same set under `access & 1`. No image test can tell
# them apart and the inline expressions are not reachable synthetically without refactoring
# `pools.analyse` (T680 edits that file), so they are recorded, not killed.
SURVIVORS: list[tuple[str, str, str, str, str, bool, str]] = [
    (
        "pools-real-pool-for-unaligned-displacement",
        FILE,
        "if disp is not None and disp % 4 == 0:",
        "if disp is not None:",
        "a displacement that is no slot index gets a pool",
        True,
        SUITE,
    ),
    (
        "pools-real-writers-read-as-reads",
        FILE,
        "op.access & 2",
        "op.access & 1",
        "the running flag readers are taken for its writers",
        True,
        SUITE,
    ),
    (
        "pools-real-writer-owner-last",
        FILE,
        "writers.add(owners[0])",
        "writers.add(owners[-1])",
        "a writer is attributed to its last owner",
        True,
        SUITE,
    ),
]
