# SPDX-License-Identifier: GPL-3.0-or-later
# ruff: noqa: E501
"""Mutants of tools.tracegaps.saturate (T603), fields in the order of `mutate.Mutation`:
(identifier, file, old, new, why, real, suite).

Logic mutants (`real` False) are killed by the synthetic tests of tests/test_saturate.py, the real
ones by the `_real_image` tests only (they change a number the retail image pins)."""

SUITE = "tests/test_saturate.py"
FILE = "saturate.py"

MUTANTS: list[tuple[str, str, str, str, str, bool, str]] = [
    (
        "saturate-import-ignores-slot-writers",
        FILE,
        "                if self._writers_of(slot):\n",
        "                if False:\n",
        "an import slot some instruction writes is still trusted as a kernel entry",
        False,
        SUITE,
    ),
    (
        "saturate-slot-pool-ignores-immediate-hits",
        FILE,
        'if hit.kind in ("immediate", "data", "table"):',
        'if hit.kind in ("data", "table"):',
        "a slot whose address is pushed or loaded as an immediate stays closed",
        False,
        SUITE,
    ),
    (
        "saturate-slot-pool-ignores-data-hits",
        FILE,
        'if hit.kind in ("immediate", "data", "table"):',
        'if hit.kind in ("immediate", "table"):',
        "a slot whose address is stored in a data dword stays closed",
        False,
        SUITE,
    ),
    (
        "saturate-slot-pool-ignores-table-hits",
        FILE,
        'if hit.kind in ("immediate", "data", "table"):',
        'if hit.kind in ("immediate", "data"):',
        "a slot whose address sits in a pointer table stays closed",
        False,
        SUITE,
    ),
    (
        "saturate-slot-pool-allows-indexed-writes",
        FILE,
        '            if shape != "absolute":\n',
        "            if False:\n",
        "an indexed operand that writes the slot does not open it",
        False,
        SUITE,
    ),
    (
        "saturate-slot-shape-test-inverted",
        FILE,
        'shape = "absolute" if mem.base == 0 and mem.index == 0 else "indexed"',
        'shape = "absolute" if mem.base == 0 or mem.index == 0 else "indexed"',
        "an operand with only an index register counts as a plain global access",
        False,
        SUITE,
    ),
    (
        "saturate-slot-pool-allows-non-mov-writes",
        FILE,
        'if insn is None or insn.mnemonic != "mov" or len(insn.operands) != 2:',
        "if insn is None or len(insn.operands) != 2:",
        "an add to the slot is read as a store of its operand",
        False,
        SUITE,
    ),
    (
        "saturate-slot-pool-accepts-unbounded-stores",
        FILE,
        "if store is None or not store.bounded:",
        "if store is None:",
        "a store of a value Flow cannot bound adds nothing to the pool and does not open it",
        False,
        SUITE,
    ),
    (
        "saturate-slot-pool-ignores-narrow-stores",
        FILE,
        "        if destination.size != 4:\n",
        "        if False:\n",
        "a word store into the slot is read as a pointer store",
        False,
        SUITE,
    ),
    (
        "saturate-slot-pool-drops-non-code-filter",
        FILE,
        "return ValueSet(frozenset(v for v in values if self.graph.is_code(v)))",
        "return ValueSet(frozenset(values))",
        "an initial value that is no instruction stays in the pool",
        False,
        SUITE,
    ),
    (
        "saturate-slot-pool-drops-the-initial-value",
        FILE,
        "            values.add(initial)",
        "            pass",
        "the initial dword of the slot is not part of its pool",
        False,
        SUITE,
    ),
    (
        "saturate-slot-pool-drops-literal-stores",
        FILE,
        "return ValueSet(frozenset({source.imm & 0xFFFFFFFF}))",
        "return ValueSet(frozenset())",
        "a `mov [slot], imm` adds no target",
        False,
        SUITE,
    ),
    (
        "saturate-slot-pool-reads-count-as-stores",
        FILE,
        "            if not writes:\n",
        "            if writes:\n",
        "reads of the slot are checked as stores and the stores are skipped",
        False,
        SUITE,
    ),
    (
        "saturate-import-name-ignored",
        FILE,
        "            if name is not None:\n",
        "            if False:\n",
        "an import slot is treated as a global slot with an empty pool",
        False,
        SUITE,
    ),
    (
        "saturate-every-reason-is-a-slot-load",
        FILE,
        "            if match is None:\n",
        "            if False:\n",
        "a reason that is no load of a global dword no longer refuses the site",
        False,
        SUITE,
    ),
    (
        "saturate-refused-slot-resolves-empty",
        FILE,
        "            return None if pool is None else pool",
        "            return pool if pool is not None else ValueSet()",
        "a call through a slot that is not closed resolves to no target",
        False,
        SUITE,
    ),
    (
        "saturate-loaded-slot-refusal-ignored",
        FILE,
        "            if pool is None:\n                return None\n            targets |= pool.values",
        "            targets |= (pool or ValueSet()).values",
        "a register loaded from a slot that is not closed resolves to the rest of its targets",
        False,
        SUITE,
    ),
    (
        "saturate-targets-keep-non-code",
        FILE,
        "tuple(sorted(target for target in targets if self.graph.is_code(target))),",
        "tuple(sorted(targets)),",
        "a literal that is no instruction becomes a target",
        False,
        SUITE,
    ),
    (
        "saturate-import-rule-label-too-wide",
        FILE,
        "rule = RULE_IMPORT if kernels and len(kernels) == len(slots) else RULE_SLOT",
        "rule = RULE_IMPORT if kernels else RULE_SLOT",
        "a register that may hold an import or a global slot is labelled an import",
        False,
        SUITE,
    ),
    (
        "saturate-direct-slot-site-labelled-literal",
        FILE,
        "            operand.type == cs_x86.X86_OP_MEM and operand.mem.base == 0 and operand.mem.index == 0\n        )",
        "            False\n        )",
        "a call through a plain global dword is no longer named a slot site",
        False,
        SUITE,
    ),
    (
        "saturate-jump-sites-skip-the-table-rule",
        FILE,
        '        if site.kind == "jump":',
        "        if False:",
        "a verified jump table is not resolved",
        False,
        SUITE,
    ),
    (
        "saturate-jump-table-refusal-not-checked",
        FILE,
        "            if isinstance(table, addresstaking.JumpTable):",
        "            if True:",
        "an unverified jump is resolved by its refusal text",
        False,
        SUITE,
    ),
    (
        "saturate-null-routine-ignores-the-value",
        FILE,
        "return value.bounded and value.values == frozenset({0})",
        "return value.bounded",
        "any bounded routine argument counts as null",
        False,
        SUITE,
    ),
    (
        "saturate-closed-ignores-unresolved",
        FILE,
        "return not self.unresolved and not self.callback_imports and not self.reaches(writers)",
        "return not self.callback_imports and not self.reaches(writers)",
        "a start with an unresolved site counts as closed",
        False,
        SUITE,
    ),
    (
        "saturate-closed-ignores-callbacks",
        FILE,
        "return not self.unresolved and not self.callback_imports and not self.reaches(writers)",
        "return not self.unresolved and not self.reaches(writers)",
        "a start with an unexplained callback service counts as closed",
        False,
        SUITE,
    ),
    (
        "saturate-closed-ignores-writers",
        FILE,
        "return not self.unresolved and not self.callback_imports and not self.reaches(writers)",
        "return not self.unresolved and not self.callback_imports",
        "a start that reaches a writer counts as closed",
        False,
        SUITE,
    ),
    (
        "saturate-reaches-inverted",
        FILE,
        "if function in self.closure.parent]",
        "if function not in self.closure.parent]",
        "the writers a closure holds are the ones it lacks",
        False,
        SUITE,
    ),
    (
        "saturate-by-rule-counts-distinct-rules",
        FILE,
        "return Counter(resolution.rule for resolution in self.resolutions.values())",
        "return Counter({resolution.rule for resolution in self.resolutions.values()})",
        "the rule histogram counts a rule once however many sites it resolved",
        False,
        SUITE,
    ),
    (
        "saturate-stops-after-one-round",
        FILE,
        "        if not added:\n            break\n",
        "        break\n",
        "the sites the resolved targets bring in are never resolved",
        False,
        SUITE,
    ),
    (
        "saturate-resolved-targets-not-fed-back",
        FILE,
        "            [start], {address: resolution.targets for address, resolution in resolutions.items()}\n",
        "            [start], {}\n",
        "the closure never follows a resolved site",
        False,
        SUITE,
    ),
    (
        "saturate-claims-dropped",
        FILE,
        "for address, targets in (claims or {}).items():",
        "for address, targets in {}.items():",
        "the caller's registrations are not used",
        False,
        SUITE,
    ),
    (
        "saturate-register-callbacks-not-counted",
        FILE,
        "        if name in CALLBACK_IMPORTS\n",
        "        if False\n",
        "a callback service entered through a register is no callback",
        False,
        SUITE,
    ),
    (
        "saturate-register-callbacks-left-out-of-the-list",
        FILE,
        "callbacks = [*closure.callback_imports, *entered]",
        "callbacks = [*closure.callback_imports]",
        "the callbacks entered through a register are not in the list that opens the start",
        False,
        SUITE,
    ),
    (
        "saturate-nulls-stay-in-the-open-list",
        FILE,
        "rest = [site for site in callbacks if site not in nulls]",
        "rest = list(callbacks)",
        "a callback with a proven null routine still keeps the start open",
        False,
        SUITE,
    ),
    # ---- image-bound: each moves a number the retail image pins
    (
        "saturate-real-import-label-dropped",
        FILE,
        "rule = RULE_IMPORT if kernels and len(kernels) == len(slots) else RULE_SLOT",
        "rule = RULE_SLOT",
        "the retail register calls through kernel imports are labelled global slots",
        True,
        SUITE,
    ),
    (
        "saturate-real-direct-slot-sites-labelled-literal",
        FILE,
        "            operand.type == cs_x86.X86_OP_MEM and operand.mem.base == 0 and operand.mem.index == 0\n        )",
        "            False\n        )",
        "the retail calls through plain global dwords lose their rule",
        True,
        SUITE,
    ),
    (
        "saturate-real-one-round-only",
        FILE,
        "        if not added:\n            break\n",
        "        break\n",
        "the retail closures stop growing after the first round of resolutions",
        True,
        SUITE,
    ),
    (
        "saturate-real-claims-dropped",
        FILE,
        "for address, targets in (claims or {}).items():",
        "for address, targets in {}.items():",
        "the poll thread's T424 registrations are not claimed",
        True,
        SUITE,
    ),
    (
        "saturate-real-null-routine-never-null",
        FILE,
        "return value.bounded and value.values == frozenset({0})",
        "return False",
        "the retail APC arguments of NtReadFile and NtWriteFile are never null",
        True,
        SUITE,
    ),
]
