# SPDX-License-Identifier: GPL-3.0-or-later
"""Whole-image call reachability with explicit indirect-site resolution (T424).

THE QUESTION. Can a thread started at address S ever execute function G? The answer is a
closure over (a) direct `call rel32`, (b) direct tail `jmp rel32` to another function entry,
(c) the targets of each INDIRECT site, which are resolved one site at a time from the image
and recorded with the reason. A site that is not resolved is never guessed: it is returned
in `Closure.unresolved`, so "unreachable" is only ever claimed when that list is empty or
each member is argued closed by the caller.

WHY NOT THE LIFTED TREE. `tools.vblank_probe.parse_call_graph` reads `generated/lifted`. That
tree is regenerated by other work, and its text scan once credited each function with a call
to the NEXT function in the file, because the slice for a body ran up to the next `void`
line and so included that function's doc comment. Reading the retail image directly removes
both problems. Everything here is an image address.

SITE KINDS (`Site.kind`).
  import     `call [slot]` through a kernel thunk slot. No guest code runs from the call
             itself. `Site.kernel` names it and `CALLBACK_IMPORTS` lists the kernel services
             that take a guest routine, which `Closure.callback_imports` reports separately.
  slot       `call [absolute]` through a non-import address (a global function pointer).
  memory     `call [reg + disp]` (a vtable slot or a record field).
  register   `call reg`.
  jump       an indirect `jmp` that `Flow` could not turn into an in-function switch table.
A scaled `jmp [reg*4 + table]` that `Flow` resolves is in-function control flow, not a site.

FUNCTION BOUNDARIES. There is no function table. Entries are the targets of direct calls, the
`known_entries` the caller names (thread starts, the XBE entry point) and one pseudo entry per
stretch of code none of those floods. A body is the forward flood from an entry (`body`): both
arms of a conditional branch, a `jmp` that is not to another call target, and every arm of a
`jmp [reg*4 + table]` read greedily. A `jmp` to a call target is a tail call (an edge). Both
choices only ADD edges or members when wrong, so a closure is an over-approximation of
reachability. It cannot lose a path through a mis-sized body.
`tools.tracegaps.flow.Flow` is used only to resolve call arguments (`call_arguments`).
"""

from __future__ import annotations

import collections
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass, field

import capstone
from capstone import x86 as cs_x86

from tools.kernel_ordinals import KERNEL_ORDINALS
from tools.tracegaps.code import Code
from tools.tracegaps.flow import FlowCache, ValueSet

#: Kernel services that accept a guest routine. A guest routine passed to one runs later, on
#: another thread, in a DPC or as an APC, so reaching the call does not by itself reach the
#: routine, and each use must be read from its arguments.
CALLBACK_IMPORTS = frozenset(
    {
        "PsCreateSystemThreadEx",
        "KeInitializeDpc",
        "KeInitializeApc",
        "KeInitializeTimerEx",
        "KeInitializeInterrupt",
        "KeConnectInterrupt",
        "KeInsertQueueApc",
        "NtQueueApcThread",
        "NtReadFile",
        "NtWriteFile",
        "NtDeviceIoControlFile",
        "NtFsControlFile",
        "NtSetTimerEx",
        "NtCreateTimer",
        "ExQueueWorkItem",
        "IoCreateFile",
        "IoStartPacket",
        "MmSetAddressProtect",
    }
)


#: Sections that hold data. A hit there is a stored value even where the sweep decoded bytes.
DATA_SECTIONS = frozenset({".rdata", ".data", ".data1", ".XTLID"})
#: Data sections the title never executes through: the XDK library identification table
#: (`tools/xtlid.py`) lists function addresses for tools, nothing at run time calls them.
METADATA_SECTIONS = frozenset({".XTLID"})
#: `Hit.kind` values that count as taking the address.
TAKING_KINDS = frozenset({"immediate", "displacement", "data", "table"})


@dataclass(frozen=True)
class Site:
    """One indirect `call` or `jmp` inside a function."""

    address: int
    function: int
    kind: str
    mnemonic: str
    operand: str
    #: Kernel export name when `kind` is "import".
    kernel: str | None = None
    #: The memory slot for `import` and `slot`.
    slot: int | None = None


@dataclass
class Summary:
    """What one function can transfer control to, read from its flood."""

    entry: int
    direct: set[int] = field(default_factory=set)
    tail: set[int] = field(default_factory=set)
    sites: list[Site] = field(default_factory=list)
    instructions: int = 0


@dataclass(frozen=True)
class Hit:
    """One occurrence of an address's four bytes (see `ReachGraph.address_hits`)."""

    section: str
    #: the instruction address for code hits, the byte address for data hits
    where: int
    kind: str
    aligned: bool
    #: the byte address of the four bytes when `where` is the covering instruction (code hits)
    location: int | None = None


@dataclass
class Backward:
    """The result of `ReachGraph.callers_closure`."""

    #: function -> the callee through which it joined (None for a target)
    members: dict[int, int | None]
    #: caller instructions no candidate function body contains
    unattributed: list[int]


@dataclass
class Closure:
    """The result of `ReachGraph.closure`."""

    roots: tuple[int, ...]
    #: function -> the function through which it was first reached (None for a root)
    parent: dict[int, int | None]
    #: indirect sites in the closure that nobody resolved
    unresolved: list[Site]
    #: indirect sites resolved by the caller, address -> targets
    resolved: dict[int, tuple[int, ...]]
    #: kernel services called from the closure, name -> number of call sites
    kernel: collections.Counter[str]
    #: calls to the services in CALLBACK_IMPORTS, as sites
    callback_imports: list[Site]

    def path(self, target: int) -> list[int]:
        """First-found call path from a root to `target`, or [] when it is not reached."""
        if target not in self.parent:
            return []
        chain: list[int] = []
        cursor: int | None = target
        while cursor is not None:
            chain.append(cursor)
            cursor = self.parent[cursor]
        return chain[::-1]


class ReachGraph:
    """Per-function summaries over one decoded image, and closures over them."""

    def __init__(
        self, code: Code, flows: FlowCache | None = None, known_entries: Iterable[int] = ()
    ) -> None:
        self.code = code
        self.flows = flows or FlowCache(code)
        xbe = code.image.xbe
        #: kernel thunk slot address -> export name
        self.imports: dict[int, str] = {
            xbe.kernel_thunk_addr + 4 * index: KERNEL_ORDINALS.get(
                ordinal & 0xFFFF, f"ordinal{ordinal & 0xFFFF}"
            )
            for index, ordinal in enumerate(xbe.kernel_import_ordinals)
        }
        self._summaries: dict[int, Summary] = {}
        self._bodies: dict[int, frozenset[int]] = {}
        self._owners: dict[int, list[int]] | None = None
        self._orphans: set[int] = set()
        #: entries that are not direct call targets (thread starts, callbacks) and so are not
        #: found by `Code.entry_candidates`
        self.known_entries: frozenset[int] = frozenset(known_entries)

    # ------------------------------------------------------------------ one function

    def is_code(self, address: int) -> bool:
        return self.code.insn_at(address) is not None

    def summary(self, entry: int) -> Summary:
        if entry not in self._summaries:
            self._summaries[entry] = self._summarise(entry)
        return self._summaries[entry]

    def _summarise(self, entry: int) -> Summary:
        """Read the flood `body(entry)`: its direct calls, tail jumps and indirect sites."""
        body = self.body(entry)
        targets = self.code.call_targets()
        result = Summary(entry=entry, instructions=len(body))
        for address in sorted(body):
            insn = self.code.insn_at(address)
            if insn is None or insn.mnemonic not in ("call", "jmp"):
                continue
            operand = insn.operands[0]
            if operand.type == cs_x86.X86_OP_IMM:
                target = operand.imm & 0xFFFFFFFF
                if insn.mnemonic == "call":
                    result.direct.add(target)
                elif target in targets and target != entry:
                    result.tail.add(target)
            elif insn.mnemonic == "call":
                result.sites.append(self._site(entry, insn))
            elif not self._table_targets(insn):
                result.sites.append(self._site(entry, insn, kind="jump"))
        return result

    def _site(self, entry: int, insn: capstone.CsInsn, kind: str | None = None) -> Site:
        operand = insn.operands[0]
        slot: int | None = None
        kernel: str | None = None
        if operand.type == cs_x86.X86_OP_MEM:
            mem = operand.mem
            if mem.base == 0 and mem.index == 0:
                slot = mem.disp & 0xFFFFFFFF
                kernel = self.imports.get(slot)
                found = "import" if kernel else "slot"
            else:
                found = "memory"
        else:
            found = "register"
        return Site(
            address=insn.address,
            function=entry,
            kind=kind if kind and found not in ("import", "slot") else found,
            mnemonic=insn.mnemonic,
            operand=insn.op_str,
            kernel=kernel,
            slot=slot,
        )

    # ------------------------------------------------------------------ closure

    def closure(
        self,
        roots: Iterable[int],
        resolutions: Mapping[int, Sequence[int]] | None = None,
        extra_edges: Mapping[int, Sequence[int]] | None = None,
    ) -> Closure:
        """Everything reachable from `roots`.

        `resolutions` maps an indirect site address to its targets, `extra_edges` maps a
        function to callees added by hand (used for a function whose body the flood cannot
        see whole). Both are the caller's argued claims, they are reported back.
        """
        resolutions = resolutions or {}
        extra_edges = extra_edges or {}
        roots = tuple(roots)
        parent: dict[int, int | None] = {root: None for root in roots}
        queue = collections.deque(roots)
        unresolved: list[Site] = []
        resolved: dict[int, tuple[int, ...]] = {}
        kernel: collections.Counter[str] = collections.Counter()
        callbacks: list[Site] = []
        while queue:
            function = queue.popleft()
            summary = self.summary(function)
            callees = set(summary.direct) | set(summary.tail) | set(extra_edges.get(function, ()))
            for site in summary.sites:
                if site.kind == "import":
                    assert site.kernel is not None
                    kernel[site.kernel] += 1
                    if site.kernel in CALLBACK_IMPORTS:
                        callbacks.append(site)
                elif site.address in resolutions:
                    resolved[site.address] = tuple(resolutions[site.address])
                    callees.update(resolutions[site.address])
                else:
                    unresolved.append(site)
            for callee in sorted(callees):
                if callee not in parent and self.is_code(callee):
                    parent[callee] = function
                    queue.append(callee)
        return Closure(roots, parent, unresolved, resolved, kernel, callbacks)

    # ------------------------------------------------------------------ callback registries

    def literal_arguments(self, registrar: int, position: int) -> list[tuple[int, ValueSet]]:
        """For every direct caller of `registrar`, the value set of stack argument `position`.

        `position` is 1-based, argument 1 is the first one the callee reads. The caller's
        function is the first of `enclosing_entries`. Returns `(call address, value set)`.
        """
        return [
            (transfer.address, self.call_arguments(transfer.address, position)[position - 1])
            for transfer in self.code.callers(registrar)
        ]

    def call_arguments(self, call_address: int, count: int) -> list[ValueSet]:
        """`Flow.call_arguments` for a function that holds the call at `call_address`.

        The owners are tried nearest entry first, the first whose `Flow` contains the call
        and has a usable stack model answers.
        """
        owners = sorted(self.enclosing_entries(call_address), reverse=True)
        for owner in owners:
            try:
                flow = self.flows.at_entry(owner)
            except KeyError:
                continue
            if call_address in flow.insns:
                return flow.call_arguments(call_address, count)
        raise LookupError(f"no function with a stack model contains the call at {call_address:#x}")

    # ------------------------------------------------------------------ backward closure

    def enclosing_entries(self, address: int) -> list[int]:
        """Every function entry whose flood contains the instruction at `address`.

        Entries are the direct call targets, the `known_entries`, and one pseudo entry per
        stretch of decoded code no call target floods (code reached only through a pointer,
        or dead, or a body the flood cannot enter). Every decoded instruction of an
        executable section therefore has an owner, and a function that shares code with a
        neighbour is listed under both. Over-listing only ADDS members to a backward
        closure, which is the safe direction for an "unreachable" proof.
        """
        owners = self._owner_index()
        return owners.get(address, [])

    def real_owners(self, address: int) -> list[int]:
        """The owners of `address` that are real entries (call targets, known entries)."""
        self._owner_index()
        return [owner for owner in self.enclosing_entries(address) if owner not in self._orphans]

    def orphan_entries(self) -> list[int]:
        """The pseudo entries `enclosing_entries` added for code no call target floods."""
        self._owner_index()
        return sorted(self._orphans)

    def _owner_index(self) -> dict[int, list[int]]:
        if self._owners is not None:
            return self._owners
        owners: dict[int, list[int]] = collections.defaultdict(list)
        entries = {a for a in self.code.call_targets() if self.is_code(a)} | self.known_entries
        for entry in sorted(entries):
            for address in self.body(entry):
                owners[address].append(entry)
        data_ranges = [
            (section.virtual_addr, section.virtual_addr + section.virtual_size)
            for section in self.code.sections
            if section.name in DATA_SECTIONS
        ]
        for insn in self.code.insns:
            if insn.address in owners or insn.mnemonic in ("int3", "nop"):
                continue
            if any(low <= insn.address < high for low, high in data_ranges):
                continue
            self._orphans.add(insn.address)
            for address in self.body(insn.address):
                owners[address].append(insn.address)
        self._owners = owners
        return owners

    def body(self, entry: int) -> frozenset[int]:
        """Instruction addresses of the function flood at `entry`.

        Unlike `Flow` this reads a `jmp [reg*4 + table]` switch table greedily (every
        consecutive dword that is a decoded instruction of the same section) so that case
        arms are part of the body. A table read too long only adds code, never removes it.
        """
        if entry not in self._bodies:
            self._bodies[entry] = self._flood_addresses(entry)
        return self._bodies[entry]

    def _table_targets(self, insn: capstone.CsInsn) -> list[int]:
        operand = insn.operands[0]
        if operand.type != cs_x86.X86_OP_MEM:
            return []
        mem = operand.mem
        if mem.base != 0 or mem.index == 0 or mem.scale != 4:
            return []
        section = self.code.image.section_at(insn.address)
        targets: list[int] = []
        for slot in range(4096):
            value = self.code.image.u32((mem.disp & 0xFFFFFFFF) + 4 * slot)
            if value is None or self.code.insn_at(value) is None:
                break
            if section is None or self.code.image.section_at(value) is not section:
                break
            targets.append(value)
        # An `and reg, 2^k - 1` mask sizes the table even when the greedy read stops early at an
        # unused slot (T607): add the slots that are decoded instructions of the section.
        masked = self.code.masked_table(insn)
        if masked is not None and not masked[1]:
            targets.extend(value for value in masked[0] if value not in targets)
        borrow = self.code.borrow_range(insn)
        if borrow is not None:
            for slot in range(-borrow, 0):
                value = self.code.image.u32((mem.disp & 0xFFFFFFFF) + 4 * slot)
                if value is None or value in targets or self.code.insn_at(value) is None:
                    continue
                if section is not None and self.code.image.section_at(value) is section:
                    targets.append(value)
        return targets

    def _flood_addresses(self, entry: int) -> frozenset[int]:
        targets = self.code.call_targets()
        seen: set[int] = set()
        pending = [entry]
        while pending:
            address = pending.pop()
            insn = self.code.insn_at(address)
            if insn is None or address in seen:
                continue
            seen.add(address)
            if insn.mnemonic in ("ret", "retn", "retf", "int3", "hlt", "ud2"):
                continue
            operand = insn.operands[0] if insn.operands else None
            direct = operand is not None and operand.type == cs_x86.X86_OP_IMM
            if insn.mnemonic == "jmp":
                if direct and ((operand.imm & 0xFFFFFFFF) not in targets or operand.imm == entry):
                    pending.append(operand.imm & 0xFFFFFFFF)
                elif not direct:
                    pending.extend(self._table_targets(insn))
                continue
            if capstone.CS_GRP_JUMP in insn.groups and direct:
                pending.append(operand.imm & 0xFFFFFFFF)
            pending.append(address + insn.size)
        return frozenset(seen)

    def callers_closure(self, targets: Iterable[int]) -> Backward:
        """Every function that can reach one of `targets` through DIRECT calls and tail jumps.

        A transfer to ANY instruction of a member's body counts, not only to its entry, so a
        `jmp` into shared code or the middle of a function is an edge too. A caller
        instruction no function owns is listed in `unattributed` (see `enclosing_entries`),
        so it is never silently dropped.
        """
        members: dict[int, int | None] = {target: None for target in targets}
        unattributed: list[int] = []
        queue = collections.deque(members)
        transfers = self.code.transfers()
        while queue:
            callee = queue.popleft()
            for address in sorted(self.body(callee) | {callee}):
                for transfer in transfers.get(address, []):
                    owners = self.enclosing_entries(transfer.address)
                    if not owners:
                        unattributed.append(transfer.address)
                    for owner in owners:
                        if owner not in members:
                            members[owner] = callee
                            queue.append(owner)
        return Backward(members, sorted(set(unattributed)))

    def address_hits(self, addresses: Iterable[int]) -> dict[int, list[Hit]]:
        """Every 4-byte occurrence of each address in the image, classified by `Hit.kind`.

        `immediate` and `displacement`: the four bytes are exactly the instruction's own imm32
        or disp32 field, which is how a code address is taken or a table is indexed.
        `branch`: a relative `call`/`jmp` displacement (a distance, not an address).
        `straddle`: neighbouring bytes happen to spell the value, in a decoded instruction or
        in a data section at an address that is not 4-aligned (no pointer slot is unaligned).
        `table`: an aligned dword in executable bytes next to another code address, a pointer
        table (a `switch` table) the sweep decoded as instructions, counted as address-taking.
        `data`: an aligned stored dword in a data section, a pointer slot.
        `metadata`: a stored dword in `METADATA_SECTIONS`, not a pointer anything calls.
        `orphan`: a `branch` or `straddle` in code only a pseudo entry (see `enclosing_entries`)
        covers, no pointer run around it. Dismissed like those two, but kept apart so the
        number of dismissals that rest on unattributed code is visible.
        """
        wanted = list(dict.fromkeys(addresses))
        return self._classify_hits(wanted, self.code.dword_hits_many(wanted).get)

    def address_hits_reference(self, addresses: Iterable[int]) -> dict[int, list[Hit]]:
        """`address_hits` through one image scan PER address, the T424 original (quadratic).

        Kept as the oracle the indexed `address_hits` is tested against (T599). Same result.
        """
        return self._classify_hits(dict.fromkeys(addresses), self.code.dword_hits)

    def _classify_hits(
        self,
        addresses: Iterable[int],
        find: Callable[[int], list[tuple[str, int, bool]] | None],
    ) -> dict[int, list[Hit]]:
        out: dict[int, list[Hit]] = {}
        for address in addresses:
            hits: list[Hit] = []
            for section, location, inside in find(address) or ():
                aligned = location % 4 == 0
                insn = self.code._covering(location) if inside else None
                if section in METADATA_SECTIONS:
                    hits.append(Hit(section, location, "metadata", aligned))
                    continue
                if section in DATA_SECTIONS or insn is None:
                    hits.append(Hit(section, location, "data" if aligned else "straddle", aligned))
                    continue
                encoding = insn.encoding
                imm_at = insn.address + encoding.imm_offset if encoding.imm_size == 4 else None
                disp_at = insn.address + encoding.disp_offset if encoding.disp_size == 4 else None
                if capstone.CS_GRP_BRANCH_RELATIVE in insn.groups:
                    kind = "branch"
                elif location == imm_at:
                    kind = "immediate"
                elif location == disp_at:
                    kind = "displacement"
                else:
                    kind = "straddle"
                if kind in ("branch", "straddle"):
                    if self._in_pointer_run(location):
                        kind = "table"
                    elif not self.real_owners(insn.address):
                        kind = "orphan"
                hits.append(Hit(section, insn.address, kind, aligned, location))
            if hits:
                out[address] = hits
        return out

    def _in_pointer_run(self, location: int) -> bool:
        """True when the dword at `location` is aligned and a neighbouring aligned dword is also a
        decoded instruction address, which is what a pointer table (a `switch` table, a callback
        list) looks like and what a distance or constant that happens to spell an address does
        not."""
        if location % 4:
            return False
        image = self.code.image
        return any(
            (value := image.u32(location + delta)) is not None and self.is_code(value)
            for delta in (-4, 4)
        )

    @staticmethod
    def address_taking(hits: Iterable[Hit]) -> list[Hit]:
        """The hits that can put the address in a register or a slot, see `address_hits`."""
        return [hit for hit in hits if hit.kind in TAKING_KINDS]

    # ------------------------------------------------------------------ data references

    def memory_operand_refs(self, low: int, high: int) -> list[int]:
        """Instructions with a memory operand whose displacement lies in `[low, high)`.

        Any base and index count, so a scaled table access (`[esi*8 + table]`) is found,
        which `Code.absolute_operand_refs` does not report.
        """
        found: list[int] = []
        for insn in self.code.insns:
            for operand in insn.operands:
                disp = operand.mem.disp & 0xFFFFFFFF
                if operand.type == cs_x86.X86_OP_MEM and low <= disp < high:
                    found.append(insn.address)
                    break
        return found

    def header_u32(self, address: int) -> int | None:
        """A dword of the XBE header, which is mapped at the base address but is no section."""
        xbe = self.code.image.xbe
        offset = address - xbe.base_address
        if 0 <= offset <= xbe.size_of_headers - 4:
            return int.from_bytes(self.code.image.raw[offset : offset + 4], "little")
        return None
