# SPDX-License-Identifier: GPL-3.0-or-later
"""Switch jump table recovery for the retail XBE.

An indirect `jmp` with no resolved target set is a function the static recompiler cannot
emit correct control flow for, and MSVC compiled 687 switch statements in `.text` into
`jmp dword ptr [idx*4 + imm]` against a table it placed inline in `.text` rather than in
`.rdata`. This package reads those tables, using the compiler's own `cmp`/`ja` range
check as the length, and reports the indirect jumps that remain unresolvable with the
reason for each. See `tools/jumptables/recover.py` for why the decode is anchored at
known function entries instead of swept linearly.
"""

from tools.jumptables.recover import (
    CAUSE_ABSOLUTE_SLOT,
    CAUSE_BIASED_TABLE_BASE,
    CAUSE_INDEX_TABLE_UNREADABLE,
    CAUSE_NO_PLAUSIBLE_ENTRIES,
    CAUSE_POINTER_BASE,
    CAUSE_REGISTER_BASE,
    CAUSE_REGISTER_TARGET,
    CAUSE_STACK_SLOT,
    CAUSE_TABLE_OUTSIDE_IMAGE,
    CAUSE_UNSUPPORTED_SCALE,
    DEFAULT_BOUND_WINDOW,
    DEFAULT_CODE_SECTIONS,
    DEFAULT_MIN_ENTRIES,
    DEFAULT_SCAN_LIMIT,
    ENTRY_SIZE,
    FORM_DIRECT,
    FORM_INDEX_INDIRECTION,
    LENGTH_FROM_BOUND,
    LENGTH_FROM_SCAN,
    SUSPECT_BOUND_OVERRUNS,
    SUSPECT_INDEX_SPAN_OVERLAPS_TABLE,
    SUSPECT_NO_BOUND,
    SUSPECT_TABLE_BASE_SHIFTED,
    SUSPECT_TARGET_MISALIGNED,
    SUSPECT_TARGET_OUTSIDE_CODE,
    SUSPECT_TARGET_OUTSIDE_FUNCTION,
    SUSPECT_TARGET_UNVERIFIED,
    Bound,
    Image,
    JumpTable,
    NullResult,
    Recovery,
    Region,
    UnresolvedSite,
    false_positive_null,
    image_from_regions,
    image_from_xbe,
    recover_function,
    recover_image,
    scan_targets,
)

__all__ = [
    "CAUSE_ABSOLUTE_SLOT",
    "CAUSE_BIASED_TABLE_BASE",
    "CAUSE_INDEX_TABLE_UNREADABLE",
    "CAUSE_NO_PLAUSIBLE_ENTRIES",
    "CAUSE_POINTER_BASE",
    "CAUSE_REGISTER_BASE",
    "CAUSE_REGISTER_TARGET",
    "CAUSE_STACK_SLOT",
    "CAUSE_TABLE_OUTSIDE_IMAGE",
    "CAUSE_UNSUPPORTED_SCALE",
    "DEFAULT_BOUND_WINDOW",
    "DEFAULT_CODE_SECTIONS",
    "DEFAULT_MIN_ENTRIES",
    "DEFAULT_SCAN_LIMIT",
    "ENTRY_SIZE",
    "FORM_DIRECT",
    "FORM_INDEX_INDIRECTION",
    "LENGTH_FROM_BOUND",
    "LENGTH_FROM_SCAN",
    "SUSPECT_BOUND_OVERRUNS",
    "SUSPECT_INDEX_SPAN_OVERLAPS_TABLE",
    "SUSPECT_NO_BOUND",
    "SUSPECT_TABLE_BASE_SHIFTED",
    "SUSPECT_TARGET_MISALIGNED",
    "SUSPECT_TARGET_OUTSIDE_CODE",
    "SUSPECT_TARGET_OUTSIDE_FUNCTION",
    "SUSPECT_TARGET_UNVERIFIED",
    "Bound",
    "Image",
    "JumpTable",
    "NullResult",
    "Recovery",
    "Region",
    "UnresolvedSite",
    "false_positive_null",
    "image_from_regions",
    "image_from_xbe",
    "recover_function",
    "recover_image",
    "scan_targets",
]
