# SPDX-License-Identifier: GPL-3.0-or-later
"""Make the lifted definition of each replaced function weak, without editing the lift.

THE MECHANISM
-------------
The lifted chunks define `void sub_0003C330(void)` as an ordinary external function and
call each other by that symbol. To let a hand-written strong definition win at link time
the lifted one must be WEAK. `#pragma weak sub_0003C330`, placed before the definition by
force-including a header into the chunk that defines it, does that, and nothing else
changes: callers anywhere (same chunk or another) and the dispatch table all name the
symbol, and the linker resolves every one of them to the strong definition.

ONE HEADER PER DEFINING CHUNK, NOT ONE FOR ALL
----------------------------------------------
A `#pragma weak` on a symbol a translation unit only REFERENCES makes that reference a
weak undefined symbol, which an unresolved link would then turn into a call through
address zero instead of an error. Each header is therefore included only into the single
chunk that defines the symbols it names, found here by reading the lifted tree. The
chunk is also the unit that recompiles when a replacement is added.

This module is stdlib only so CMake can run it with the system python3.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from .scan import Registration

#: A lifted definition. Matched at the start of a line followed by the opening brace on
#: the next line, which is how every generated function begins. A prototype ends in `;`
#: on the same line and never matches.
DEFINITION = re.compile(r"^void (sub_[0-9A-F]{8})\(void\)\s*$", re.MULTILINE)
CHUNK_GLOB = "recomp_*.c"
TRAMPOLINE_CHUNK = "recomp_xdk_manual.c"


class WiringError(ValueError):
    """A replacement cannot be wired against this lifted tree."""


@dataclass(frozen=True)
class Wiring:
    #: chunk file name -> symbols to weaken in it, sorted
    by_chunk: dict[str, tuple[str, ...]]

    @property
    def symbols(self) -> tuple[str, ...]:
        return tuple(sorted(symbol for group in self.by_chunk.values() for symbol in group))


def find_definitions(gen_dir: Path, wanted: set[str]) -> dict[str, list[str]]:
    """symbol -> the chunk files that DEFINE it, for the wanted symbols only."""
    found: dict[str, list[str]] = {}
    for chunk in sorted(gen_dir.glob(CHUNK_GLOB)):
        text = chunk.read_text(encoding="utf-8", errors="replace")
        for match in DEFINITION.finditer(text):
            symbol = match.group(1)
            if symbol in wanted:
                found.setdefault(symbol, []).append(chunk.name)
    return found


def plan_wiring(gen_dir: Path, registrations: list[Registration]) -> Wiring:
    """Work out which chunk defines each replaced symbol, refusing anything unsound."""
    if not gen_dir.is_dir():
        raise WiringError(f"no lifted tree at {gen_dir}")
    wanted = {registration.symbol for registration in registrations}
    found = find_definitions(gen_dir, wanted)
    missing = sorted(wanted - set(found))
    if missing:
        raise WiringError(
            "no lifted definition to replace for "
            + ", ".join(missing)
            + f" in {gen_dir}. Either the address is not a function entry, or it is one "
            "of the addresses the --manual-functions lift suppresses (an XDK surface "
            "address), whose body is a dispatcher trampoline rather than lifted code."
        )
    duplicated = sorted(symbol for symbol, chunks in found.items() if len(chunks) > 1)
    if duplicated:
        raise WiringError("defined in more than one chunk: " + ", ".join(duplicated))
    in_trampoline = sorted(s for s, chunks in found.items() if chunks == [TRAMPOLINE_CHUNK])
    if in_trampoline:
        raise WiringError("defined only by the XDK trampoline file: " + ", ".join(in_trampoline))
    by_chunk: dict[str, list[str]] = {}
    for symbol, chunks in found.items():
        by_chunk.setdefault(chunks[0], []).append(symbol)
    return Wiring({chunk: tuple(sorted(symbols)) for chunk, symbols in sorted(by_chunk.items())})


def header_name(chunk: str) -> str:
    return f"weak_{Path(chunk).stem}.h"


def render_header(chunk: str, symbols: tuple[str, ...]) -> str:
    lines = [
        "/* Generated by tools/replace. Do not edit. */",
        f"/* Makes the lifted definitions in {chunk} weak so that src/game can replace them. */",
        *(f"#pragma weak {symbol}" for symbol in symbols),
        "",
    ]
    return "\n".join(lines)


def write_wiring(wiring: Wiring, out_dir: Path) -> list[Path]:
    """Write one header per affected chunk and a manifest, removing stale headers.

    A header is rewritten only when its content changes, so an unchanged chunk keeps its
    timestamp and is not recompiled. Headers for chunks that no longer have a replacement
    are deleted: a stale `#pragma weak` would leave a lifted definition weak with nothing
    to override it, which is harmless to the link but misleads whoever reads the tree.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    keep = set()
    for chunk, symbols in wiring.by_chunk.items():
        path = out_dir / header_name(chunk)
        keep.add(path.name)
        content = render_header(chunk, symbols)
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
        written.append(path)
    for stale in out_dir.glob("weak_recomp_*.h"):
        if stale.name not in keep:
            stale.unlink()
    index = {
        chunk: {"header": header_name(chunk), "symbols": list(symbols)}
        for chunk, symbols in wiring.by_chunk.items()
    }
    index_path = out_dir / "wiring.json"
    text = json.dumps(index, indent=2, sort_keys=True) + "\n"
    if not index_path.exists() or index_path.read_text(encoding="utf-8") != text:
        index_path.write_text(text, encoding="utf-8")
    return written
