# SPDX-License-Identifier: GPL-3.0-or-later
"""A deterministic corpus of valid and malformed `XGAssembleShader` binary inputs.

Every input is synthetic: tokens we encode ourselves with `tools.nv2a.d3dtokens` and then
damage on purpose, so nothing here is derived from the disc and the corpus can be committed
and re-generated by anyone. Expected behaviour is NOT stored here. What the original does
with each input is measured by running the original bytes (`tools.shaderscan.assemble`) and
recorded in `docs/shader-assembler-limits.md`, because an expectation written from a
reading of the decoder would be exactly the fabricated original value T202 forbids.

`group` records the INTENT of a case, not its outcome. A `control` is a well-formed program
and a `malformed` case is damaged in one named way. The measured outcome may contradict the
intent, which is itself a finding.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass

from tools.nv2a import d3dtokens

#: Flags the title passes with its vertex token streams (measured at the call site).
VERTEX_FLAGS = 0x120

VERSION = d3dtokens.VERSION
END = d3dtokens.END
#: A `mov r0, v0` as three tokens, used as a well-formed body to damage.
MOV_R0_V0 = d3dtokens.instruction("mov r0, v0")


@dataclass(frozen=True)
class Case:
    name: str
    #: "control" (well formed) or "malformed" (damaged in the way `note` says).
    group: str
    source: bytes
    flags: int
    note: str
    #: Instruction budget for this case when the default is too small (T385). The original
    #: only needs more for a long valid-looking program, it is not a runaway.
    budget: int | None = None


def words(*tokens: int) -> bytes:
    """Little-endian dwords."""
    return b"".join(struct.pack("<I", token & 0xFFFFFFFF) for token in tokens)


def _program(lines: list[str]) -> bytes:
    return d3dtokens.program(lines)


def _controls() -> list[Case]:
    programs = {
        "mov_opos": ["mov oPos, v0"],
        "mov_via_temp": ["mov r0, v0", "mov oPos, r0"],
        "mad": ["mov r1, v1", "mad r0, v0, c1, r1", "mov oPos, r0"],
        "dp4_four": [f"dp4 oPos.{axis}, v0, c{index}" for index, axis in enumerate("xyzw")],
        "m4x4": ["m4x4 r0, v0, c0", "mov oPos, r0"],
        "two_outputs": ["mov oD0, v1", "mov oPos, v0"],
        "relative_constant": ["mov a0.x, v0.x", "mov r0, c[a0.x+3]", "mov oPos, r0"],
    }
    cases = [
        Case(f"control_{name}", "control", _program(lines), VERTEX_FLAGS, "well-formed program")
        for name, lines in programs.items()
    ]
    cases.append(
        Case(
            "control_tokens_after_end",
            "control",
            _program(["mov oPos, v0"]) + words(*MOV_R0_V0, END),
            VERTEX_FLAGS,
            "valid program then more tokens, source length covers both",
        )
    )
    return cases


def _sizes() -> list[Case]:
    good = _program(["mov oPos, v0"])
    cases = [Case("size_empty", "malformed", b"", VERTEX_FLAGS, "zero-length source")]
    for length in (1, 2, 3):
        cases.append(
            Case(
                f"size_{length}_bytes",
                "malformed",
                good[:length],
                VERTEX_FLAGS,
                f"first {length} byte of the version token",
            )
        )
    cases.append(Case("size_version_only", "malformed", good[:4], VERTEX_FLAGS, "version, no END"))
    cases.append(
        Case("size_version_end", "malformed", words(VERSION, END), VERTEX_FLAGS, "no code")
    )
    for extra in (1, 2, 3):
        cases.append(
            Case(
                f"size_version_plus_{extra}",
                "malformed",
                good[: 4 + extra],
                VERTEX_FLAGS,
                f"version and {extra} bytes of the next token",
            )
        )
    cases.append(
        Case("size_cut_mid_end", "malformed", good[:-2], VERTEX_FLAGS, "END token half present")
    )
    cases.append(
        Case("size_no_end", "malformed", good[:-4], VERTEX_FLAGS, "valid body, END missing")
    )
    return cases


def _headers() -> list[Case]:
    body = words(*d3dtokens.instruction("mov oPos, v0"), END)
    versions = {
        "vs10": 0xFFFE0100,
        "vs20": 0xFFFE0200,
        "ps11": 0xFFFF0101,
        "swapped": 0x0101FFFE,
        "zero": 0,
        "all_ones": 0xFFFFFFFF,
    }
    cases = [
        Case(
            f"header_version_{name}",
            "malformed",
            words(token) + body,
            VERTEX_FLAGS,
            f"version token {token:#010x} then a valid body",
        )
        for name, token in versions.items()
    ]
    cases.append(Case("header_no_version", "malformed", body, VERTEX_FLAGS, "body without version"))
    cases += [
        Case("filler_zeros_64", "malformed", bytes(64), VERTEX_FLAGS, "64 zero bytes"),
        Case("filler_ones_64", "malformed", b"\xff" * 64, VERTEX_FLAGS, "64 0xFF bytes"),
        Case(
            "filler_deadbeef_64",
            "malformed",
            words(*([0xDEADBEEF] * 16)),
            VERTEX_FLAGS,
            "16 DEADBEEF dwords",
        ),
        Case(
            "filler_ascending_64",
            "malformed",
            words(*range(16)),
            VERTEX_FLAGS,
            "dwords 0..15, no version",
        ),
        Case(
            "filler_version_then_deadbeef",
            "malformed",
            words(VERSION, *([0xDEADBEEF] * 15)),
            VERTEX_FLAGS,
            "valid version then DEADBEEF filler",
        ),
        Case(
            "filler_version_then_zeros",
            "malformed",
            words(VERSION, *([0] * 15)),
            VERTEX_FLAGS,
            "valid version then 15 NOP opcodes, no END",
        ),
    ]
    return cases


def _instructions() -> list[Case]:
    dest_opos = d3dtokens.encode_destination(d3dtokens.parse_operand("oPos"))
    source_v0 = d3dtokens.encode_source(d3dtokens.parse_operand("v0"))
    dest_r0 = d3dtokens.encode_destination(d3dtokens.parse_operand("r0"))

    def one(name: str, tokens: list[int], note: str) -> Case:
        return Case(name, "malformed", words(VERSION, *tokens, END), VERTEX_FLAGS, note)

    return [
        one("opcode_unknown_25", [25, dest_opos, source_v0], "opcode just past m3x2"),
        one("opcode_unknown_0x7777", [0x7777, dest_opos, source_v0], "opcode far outside the set"),
        one("opcode_0xfffd", [0xFFFD, dest_opos, source_v0], "opcode next to comment/END"),
        one("opcode_pixel_texkill", [0x41, dest_opos, source_v0], "pixel-shader opcode in vs"),
        one("mov_missing_source", [1, dest_r0], "mov with destination only, END is the source"),
        one("mov_missing_all", [1], "mov opcode alone, END is the destination"),
        one("mov_extra_source", [1, dest_opos, source_v0, source_v0], "mov with two sources"),
        one(
            "dest_type_7",
            [1, dest_r0 | 7 << 28, source_v0],
            "destination register type 7 does not exist",
        ),
        one(
            "dest_temp_99",
            [1, (dest_r0 & ~0x7FF) | 99, source_v0],
            "temporary register 99 of 12",
        ),
        one(
            "dest_constant_register",
            [1, (dest_r0 & ~(7 << 28)) | 2 << 28, source_v0],
            "constant register as destination",
        ),
        one(
            "dest_mask_zero",
            [1, dest_opos & ~(0xF << 16), source_v0],
            "write mask 0",
        ),
        one(
            "source_type_7",
            [1, dest_opos, source_v0 | 7 << 28],
            "source register type 7 does not exist",
        ),
        one(
            "source_input_99",
            [1, dest_opos, (source_v0 & ~0x7FF) | 99],
            "input register v99 of 16",
        ),
        one(
            "source_constant_9999",
            [1, dest_opos, (source_v0 & ~(7 << 28) & ~0x7FF) | 2 << 28 | 0x7FF],
            "constant register 2047 of 96",
        ),
        one(
            "source_no_high_bit",
            [1, dest_opos, source_v0 & 0x7FFFFFFF],
            "source token without its mandatory top bit",
        ),
        one(
            "source_reads_oPos",
            [1, dest_r0, d3dtokens.encode_source(d3dtokens.parse_operand("oPos"))],
            "an output register used as a source",
        ),
        one(
            "dest_reads_uninitialised",
            [2, dest_opos, source_v0, d3dtokens.encode_source(d3dtokens.parse_operand("r5"))],
            "add reading a temporary nothing wrote",
        ),
        one(
            "relative_without_a0",
            [1, dest_opos, d3dtokens.encode_source(d3dtokens.parse_operand("c3[a0.x]"))],
            "relative constant with no a0 load",
        ),
    ]


def _comments() -> list[Case]:
    mov = _program(["mov oPos, v0"])
    payload = words(VERSION)
    return [
        Case(
            "comment_empty",
            "malformed",
            words(VERSION, 0xFFFE) + mov[4:],
            VERTEX_FLAGS,
            "comment token with size 0, then a valid body",
        ),
        Case(
            "comment_one_dword",
            "malformed",
            words(VERSION, 0xFFFE | 1 << 16, 0x12345678) + mov[4:],
            VERTEX_FLAGS,
            "comment of 1 dword, then a valid body",
        ),
        Case(
            "comment_oversize_32767",
            "malformed",
            words(VERSION, 0xFFFE | 0x7FFF << 16) + mov[4:],
            VERTEX_FLAGS,
            "comment claims 32767 dwords, source holds 5",
        ),
        Case(
            "comment_oversize_by_one",
            "malformed",
            words(VERSION, 0xFFFE | 6 << 16) + mov[4:],
            VERTEX_FLAGS,
            "comment claims one dword more than remains",
        ),
        Case(
            "comment_truncated",
            "malformed",
            words(VERSION, 0xFFFE | 4 << 16) + payload,
            VERTEX_FLAGS,
            "comment claims 4 dwords, 1 present, no END",
        ),
    ]


def _flags() -> list[Case]:
    good = _program(["mov oPos, v0"])
    return [
        Case(f"flags_{flag:#x}", "malformed", good, flag, f"valid program with flags {flag:#x}")
        for flag in (0, 1, 0x20, 0x100, 0xFFFFFFFF)
    ]


def _text() -> list[Case]:
    text = b"vs.1.1\nmov oPos, v0\n"
    return [
        Case(
            "text_flags_0x120", "malformed", text, VERTEX_FLAGS, "ASCII source on the binary path"
        ),
        Case("text_flags_0", "malformed", text, 0, "ASCII source with no flags"),
    ]


def corpus() -> list[Case]:
    """Every case, in a stable order, with unique names."""
    cases = [
        *_controls(),
        *_sizes(),
        *_headers(),
        *_instructions(),
        *_comments(),
        *_flags(),
        *_text(),
    ]
    names = [case.name for case in cases]
    if len(names) != len(set(names)):
        raise ValueError("duplicate corpus case name")
    return cases
