# SPDX-License-Identifier: GPL-3.0-or-later
"""A deterministic corpus of valid and malformed ASCII `XGAssembleShader` sources (T385).

The T202 corpus (`malformed.py`) is binary vertex tokens with every optional output NULL.
This one is the text path (flags 0): vertex and pixel sources written as assembler text, run
with the constants output and the compilation-errors output supplied, so a failing source
also yields the assembler's own message text, and a `def` yields its constants buffer.

Every source is synthetic, nothing is derived from the disc, so the corpus can be committed
and regenerated by anyone. As in `malformed.py` no expected behaviour is stored: what the
original does is measured by running its bytes (`tools.shaderscan.assemble`) and what the
native route does by `tools.shaderscan.native_corpus`. `group` records the INTENT of a case.
"""

from __future__ import annotations

from tools.shaderscan.malformed import Case

#: Text sources are assembled with no flags (the title's own text call site passes 0).
TEXT_FLAGS = 0

VS = b"vs.1.1\n"
PS = b"ps.1.1\n"
MOV = b"mov oPos, v0\n"


def _case(name: str, group: str, source: bytes, note: str, flags: int = TEXT_FLAGS) -> Case:
    return Case(name, group, source, flags, note)


def _controls() -> list[Case]:
    sources = {
        "vs_mov": (VS + MOV, "one instruction"),
        "vs_crlf": (b"vs.1.1\r\nmov oPos, v0\r\n", "CR LF line ends"),
        "vs_cr_only": (b"vs.1.1\rmov oPos, v0\r", "CR line ends"),
        "vs_no_final_newline": (b"vs.1.1\nmov oPos, v0", "no newline after the last line"),
        "vs_comments": (
            b"vs.1.1\n; semicolon comment\n// slash comment\nmov oPos, v0 ; trailing\n",
            "both comment styles",
        ),
        "vs_block_comment": (b"vs.1.1\n/* block */\nmov oPos, v0\n", "C style block comment"),
        "vs_uppercase": (b"VS.1.1\nMOV OPOS, V0\n", "upper case mnemonics and registers"),
        "vs_tabs": (b"vs.1.1\n\tmov\toPos,\tv0\n", "tab separators"),
        "vs_two": (b"vs.1.1\nmov r0, v0\nmov oPos, r0\n", "through a temporary"),
        "vs_mad": (b"vs.1.1\nmad r0, v0, c1, v1\nmov oPos, r0\n", "three source instruction"),
        "vs_dp4_four": (
            b"vs.1.1\ndp4 oPos.x, v0, c0\ndp4 oPos.y, v0, c1\n"
            b"dp4 oPos.z, v0, c2\ndp4 oPos.w, v0, c3\n",
            "four dot products with write masks",
        ),
        "xvs_mov": (b"xvs.1.1\nmov oPos, v0\n", "xvs version statement"),
        "vs_def_one": (
            b"vs.1.1\ndef c0, 1.0, 2.0, 3.0, 4.0\nmov oPos, c0\n",
            "one def, the constants output is non-empty",
        ),
        "vs_def_two": (
            b"vs.1.1\ndef c0, 1.0, 2.0, 3.0, 4.0\ndef c5, 0.5, 0.5, 0.5, 0.5\n"
            b"mov r0, c0\nadd oPos, r0, c5\n",
            "two defs",
        ),
        "vs_def_negative": (
            b"vs.1.1\ndef c0, -1.5, 0.0, 1e3, -0.25\nmov oPos, c0\n",
            "negative, zero and exponent literals",
        ),
        "vs_chain_10": (
            VS + b"mov r0, v0\n" + b"add r0, r0, c0\n" * 8 + b"mov oPos, r0\n",
            "ten live instructions, output grows with the program",
        ),
        "vs_chain_20": (
            VS + b"mov r0, v0\n" + b"add r0, r0, c0\n" * 18 + b"mov oPos, r0\n",
            "twenty live instructions",
        ),
        "vs_dead_movs_137": (
            VS + b"mov r0, v0\n" * 136 + b"mov oPos, r0\n",
            "137 instructions, all but the last overwritten, output equals vs_mov",
        ),
        "vs_long_comment": (VS + b"; " + b"x" * 30000 + b"\n" + MOV, "30,000 byte comment line"),
        "ps_mov": (PS + b"mov r0, v0\n", "pixel shader 1.1"),
        "ps_v14": (b"ps.1.4\nmov r0, v0\n", "pixel shader 1.4"),
        "ps_tex": (PS + b"tex t0\nmov r0, t0\n", "texture sample"),
        "ps_xps": (b"xps.1.1\nmov r0, v0\n", "xps version statement"),
        "ps_def": (
            PS + b"def c0, 1.0, 0.5, 0.25, 0.0\nmov r0, c0\n",
            "a pixel shader constant",
        ),
        "ps_empty_body": (PS, "version only, no instructions"),
        "ps_two": (PS + b"mov r0, v0\nmul r0, r0, v1\n", "two instructions"),
        "ps_tex_pair": (PS + b"tex t0\ntex t1\nmul r0, t0, t1\n", "two texture stages"),
        "ps_lrp": (PS + b"tex t0\nlrp r0, v0, t0, v1\n", "three source instruction"),
        "ps_dp3_modifiers": (PS + b"tex t0\ndp3 r0, t0_bx2, v0_bx2\n", "source modifiers"),
        "ps_texbem": (PS + b"tex t0\ntexbem t1, t0\nmov r0, t1\n", "bump mapped stage"),
        "ps_cnd": (PS + b"tex t0\ncnd r0, r0.a, t0, v0\n", "conditional move"),
        "ps_coissue": (
            PS + b"tex t0\nmul r0.rgb, t0, v0\n+ mov r0.a, t0\n",
            "co-issued alpha instruction",
        ),
        "ps_def_many": (
            PS
            + b"".join(b"def c%d, 0.1, 0.2, 0.3, 0.4\n" % index for index in range(8))
            + b"mov r0, c7\n",
            "eight constants, the constants output stays NULL on the pixel path",
        ),
        "ps_def_out_of_range": (
            PS + b"def c0, 5.0, -5.0, 0, 0\nmov r0, c0\n",
            "constant outside [-1, 1], succeeds with a warning in the errors output",
        ),
        "ps_nine_instructions": (PS + b"mov r0, v0\n" * 9, "nine instructions"),
        "ps_fifteen_instructions": (
            PS + b"mul r0, r0, v0\n" * 15,
            "fifteen instructions, the longest program that stays inside the 240 byte output",
        ),
        "ps_crlf": (b"ps.1.1\r\nmov r0, v0\r\n", "CR LF line ends"),
        "ps_no_final_newline": (b"ps.1.1\nmov r0, v0", "no newline after the last line"),
        "ps_version_only_no_newline": (b"ps.1.1", "version statement alone"),
        "ps_comments": (b"ps.1.1\n// c\n; d\nmov r0, v0\n", "both comment styles"),
        "ps_uppercase": (b"PS.1.1\nMOV R0, V0\n", "upper case"),
        "ps_v20": (b"ps.2.0\nmov r0, v0\n", "a version the Xbox has no hardware for"),
    }
    return [
        _case(f"control_{name}", "control", source, note)
        for name, (source, note) in sources.items()
    ]


def _syntax() -> list[Case]:
    sources = {
        "empty": (b"", "zero length"),
        "whitespace_only": (b"   \n\n\t\n", "blank lines"),
        "junk": (b"@@@@ !!!\n", "no version statement"),
        "zeros_16": (bytes(16), "NUL bytes"),
        "no_version": (MOV, "instruction without a version statement"),
        "late_version": (MOV + b"vs.1.1\n", "version after an instruction"),
        "two_versions": (b"vs.1.1\nvs.1.1\n" + MOV, "version twice"),
        "bad_version_vs": (b"vs.9.9\n" + MOV, "vertex version 9.9"),
        "bad_version_ps": (b"ps.9.9\nmov r0, v0\n", "pixel version 9.9"),
        "no_position_output": (VS + b"mov r0, v0\n", "temporary written, no oPos"),
        "unknown_opcode": (VS + b"bogus oPos, v0\n", "unknown mnemonic"),
        "missing_source": (VS + b"mov oPos\n", "mov with one operand"),
        "missing_all": (VS + b"mov\n", "mnemonic alone"),
        "extra_operand": (VS + b"mov oPos, v0, v1\n", "mov with two sources"),
        "bad_input_register": (VS + b"mov oPos, v99\n", "input register 99 of 16"),
        "bad_temp_register": (VS + b"mov r99, v0\n", "temporary register 99 of 12"),
        "bad_constant_register": (VS + b"mov oPos, c999\n", "constant register 999 of 96"),
        "bad_output_register": (VS + b"mov oT9, v0\n", "texture output 9 of 4"),
        "constant_as_destination": (VS + b"mov c0, v0\n", "constant register written"),
        "bad_swizzle": (VS + b"mov oPos, v0.q\n", "swizzle letter q"),
        "bad_write_mask": (VS + b"mov oPos.xx, v0\n", "repeated write mask letter"),
        "relative_without_a0": (VS + b"mov oPos, c3[a0.x]\n", "relative address, a0 never loaded"),
        "unterminated_block_comment": (VS + b"/* open\n" + MOV, "block comment never closed"),
        "nul_inside": (b"vs.1.1\nmov oPos,\x00 v0\n", "NUL byte inside an instruction"),
        "high_bytes": (b"vs.1.1\nmov oPos, v0 \xff\xfe\n", "non ASCII bytes after an instruction"),
        "long_identifier": (VS + b"q" * 3000 + b" oPos, v0\n", "3,000 character mnemonic"),
        "error_on_line_5": (
            VS + b"mov r0, v0\nmov r1, v0\nmov r2, v0\nbogus r3, v0\n",
            "the message names the line",
        ),
        "two_errors": (VS + b"bogus r0, v0\nbogus r1, v0\n", "does it stop at the first"),
        "def_bad_float": (VS + b"def c0, 1.0, x, 3.0, 4.0\nmov oPos, c0\n", "literal x"),
        "def_short": (VS + b"def c0, 1.0\nmov oPos, c0\n", "def with one value"),
        "def_bad_register": (VS + b"def c999, 1.0, 2.0, 3.0, 4.0\n" + MOV, "def c999"),
        "def_temp_register": (VS + b"def r0, 1.0, 2.0, 3.0, 4.0\n" + MOV, "def of a temporary"),
        "ps_unknown_opcode": (PS + b"bogus r0, v0\n", "pixel shader unknown mnemonic"),
        "ps_xps_stage_syntax": (b"xps.1.1\nstage 0\ncolor\nmov r0, v0\n", "stage block syntax"),
        "ps_bad_register": (PS + b"mov r9, v0\n", "pixel temporary r9"),
        "ps_tex_bad_stage": (PS + b"tex t9\n", "texture stage 9"),
        "ps_v14_instruction": (b"ps.1.4\ntexld r0, t0\nmov r0, r0\n", "1.4 only mnemonic"),
        "ps_modifier_suffix": (PS + b"mov_sat r0, v0\n", "instruction modifier suffix"),
        "ps_def_bad_float": (PS + b"def c0, 1.0, x, 0, 0\nmov r0, c0\n", "literal x"),
        "ps_no_version": (b"mov r0, v0\n", "pixel instruction without a version statement"),
        "ps_missing_operand": (PS + b"mov r0\n", "pixel mov with one operand"),
    }
    return [
        _case(f"syntax_{name}", "malformed", source, note)
        for name, (source, note) in sources.items()
    ]


#: Instruction budget for a long program. The original needs about 40 million instructions for
#: 92 live instructions, its work grows faster than the program, and the 20 million default
#: would stop it first (a slow run, not a runaway).
SLOW_BUDGET = 400_000_000


def _slow() -> list[Case]:
    source = VS + b"mov r0, v0\n" + b"add r0, r0, c0\n" * 90 + b"mov oPos, r0\n"
    note = "92 instructions expand to 138 microcode words, the limit is 136 (error V600)"
    return [
        Case("syntax_vs_microcode_over_limit", "malformed", source, TEXT_FLAGS, note, SLOW_BUDGET)
    ]


def _overruns() -> list[Case]:
    """Sources the original compiles by writing past the end of its 240 byte output block.

    Instruction index 15 and above store a combiner word at `output + 0xB4 + 4 * index`, with
    no bound check (T485), so from the 16th instruction on the store lands on whatever follows
    the block. The reference heap has spare bytes there, so the original returns, and the
    reference measures the overrun (`verify.Measurement.heap_overrun`) and does not compare.
    """
    sources = {
        "ps_sixteen_instructions": (
            PS + b"mul r0, r0, v0\n" * 16,
            "the first count that overruns the output block by one word",
        ),
        "ps_twenty_instructions": (
            PS + b"mul r0, r0, v0\n" * 20,
            "five words past the output block, the native compiler returns once then faults",
        ),
    }
    return [
        _case(f"overrun_{name}", "malformed", source, note)
        for name, (source, note) in sources.items()
    ]


def _throws() -> list[Case]:
    return [
        _case("throw_version_only", "malformed", b"vs.1.1\n", "vertex version, no instructions"),
        _case("throw_version_no_newline", "malformed", b"vs.1.1", "version without a newline"),
    ]


def _flags() -> list[Case]:
    source = VS + MOV
    return [
        _case(f"flags_{flag:#x}", "malformed", source, f"text source with flags {flag:#x}", flag)
        for flag in (0x1, 0x2, 0x4, 0x8, 0x10, 0x20, 0x100, 0x120, 0xFFFFFFFF)
    ]


def corpus() -> list[Case]:
    """Every case, in a stable order, with unique names."""
    cases = [*_controls(), *_syntax(), *_slow(), *_overruns(), *_throws(), *_flags()]
    names = [case.name for case in cases]
    if len(names) != len(set(names)):
        raise ValueError("duplicate text corpus case name")
    return cases
