# SPDX-License-Identifier: GPL-3.0-or-later
"""Write a copy of the lifted tree that reports every function it enters, once.

Nothing in the real tree is edited. Every file is a symlink back to the original except
the chunks that hold function bodies, which are rewritten with one marker statement as
the first line of each body. A marker is a byte test on the hot path and one `write(2)`
the first time the function runs:

    T59-HIT <sequence> 0x<entry>

It is written straight to stderr, not at exit, because the host leaves with `_exit` when
a guest thread is still running and skips atexit handlers.

Build the host against the copy with `-DTSFP_LIFTED_DIR=<out>`: CMake globs
`recomp_*.c` from that directory, so `recomp_t59_mark.c` is compiled without any edit to
CMakeLists.txt.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

from tools.initmap.liftparse import index_directory

#: Guest code starts here. The seen-table is indexed by `entry - CODE_BASE`.
CODE_BASE = 0x10000
CODE_SPAN = 0x800000

HEADER = f"""/* GENERATED by tools/mmio_reach/instrument.py. Not part of the lifted tree. */
#ifndef T59_MARK_H
#define T59_MARK_H
#include <stdint.h>
extern volatile uint8_t t59_seen[{CODE_SPAN:#x}];
void t59_first(uint32_t entry);
#define T59_MARK(va) do {{ if (!t59_seen[(va) - {CODE_BASE:#x}u]) t59_first(va); }} while (0)
#endif
"""

RUNTIME = f"""/* GENERATED by tools/mmio_reach/instrument.py. Not part of the lifted tree. */
#include <stdint.h>
#include <stdio.h>
#include <unistd.h>
#include "t59_mark.h"

volatile uint8_t t59_seen[{CODE_SPAN:#x}];
static uint32_t t59_sequence;

void t59_first(uint32_t entry)
{{
    if (__atomic_exchange_n(&t59_seen[entry - {CODE_BASE:#x}u], 1u, __ATOMIC_SEQ_CST)) {{
        return;
    }}
    char line[48];
    uint32_t number = __atomic_add_fetch(&t59_sequence, 1u, __ATOMIC_SEQ_CST);
    int length = snprintf(line, sizeof line, "T59-HIT %u 0x%08X\\n", number, entry);
    if (length > 0 && write(2, line, (size_t)length) < 0) {{
        return;
    }}
}}
"""

_MARKER = "    T59_MARK(0x{entry:08X}u);\n"
_INCLUDE = '#include "t59_mark.h"\n'


def instrument(source: Path, out: Path) -> int:
    """Write the marked copy of `source` into `out`. Returns the marker count."""
    index = index_directory(source)
    if not index.spans:
        raise ValueError(f"no lifted functions under {source}")
    if out.resolve() == source.resolve():
        raise ValueError("output must not be the lifted tree itself")
    out.mkdir(parents=True, exist_ok=True)
    insertions: dict[str, list[tuple[int, int]]] = {}
    for entry, (chunk, start, _end) in index.spans.items():
        if not CODE_BASE <= entry < CODE_BASE + CODE_SPAN:
            raise ValueError(f"function {entry:#010x} is outside the mark table")
        insertions.setdefault(chunk, []).append((start, entry))
    for path in sorted(source.iterdir()):
        target = out / path.name
        if target.is_symlink() or target.exists():
            target.unlink()
        if path.name not in insertions:
            os.symlink(path.resolve(), target)
            continue
        text = index.texts[path.name]
        for start, entry in sorted(insertions[path.name], reverse=True):
            text = text[:start] + _MARKER.format(entry=entry) + text[start:]
        target.write_text(_INCLUDE + text, encoding="utf-8")
    (out / "t59_mark.h").write_text(HEADER, encoding="utf-8")
    (out / "recomp_t59_mark.c").write_text(RUNTIME, encoding="utf-8")
    return len(index.spans)


_HIT = re.compile(r"^T59-HIT (\d+) 0x([0-9A-Fa-f]{8})$", re.MULTILINE)


def parse_hits(text: str) -> list[int]:
    """Entry addresses in first-execution (sequence) order. A repeated entry is an error."""
    ordered = sorted((int(m.group(1)), int(m.group(2), 16)) for m in _HIT.finditer(text))
    entries = [entry for _number, entry in ordered]
    if len(set(entries)) != len(entries):
        raise ValueError("a function reported its first entry twice")
    return entries
