# SPDX-License-Identifier: GPL-3.0-or-later
"""Hand-built combiner configurations of the replay tests, and the generator of their C header.

Nothing here comes from the user's executable. The fields follow `docs/combiner-translator.md`
section 3 (the byte layout of an operand, the output word, the control word) and the worked
`pass_through_block` of `tests/nv2a_combiner_support.py`. The four configurations are chosen so a
device pixel pins one thing each:

  pass       mov r0, v0, final D = r0, G = r0.a        oD0 reaches the target through the combiner
  multiply   r0 = c0 * c1 per channel (factor0[0], factor1[0], different in every channel)
                                                       the ARGB byte order of a factor word
  final      the final combiner alone, D = c0 * c1 of the FINAL constants (words 43, 44) and
             G = final c0 alpha                        the final constants, final E * F product
  twovary    r0 = v0 * v1                              a fragment that reads oD1: the ctest's
                                                       vertex module writes oD0 only, so the
                                                       replay refuses it

    python -m tools.nv2a_combiner.replay_fixtures --header tests/c/gpu_combiner_words.h
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from collections.abc import Sequence
from pathlib import Path

from tools.nv2a_combiner import config as cfg
from tools.nv2a_combiner import replay_modules

STATE = cfg.STATE_DWORDS

# idx 34 colour ICW0 A=v0 (signed identity 6: 0xC4) B=ZERO inverted (0x20); idx 0 alpha ICW0 the
# same with the alpha bit (0xD4, 0x30); output words AB_DST = spare0 (0xC0); control 1 stage |
# mux msb | each-stage factors = 0x11101; final D = spare0 (0x0C), G = spare0 alpha (0x1C) | clamp
# (0x80).
PASS = {34: 0xC4200000, 0: 0xD4300000, 45: 0xC0, 26: 0xC0, 53: 0x11101, 8: 0x0C, 9: 0x1C80}

MULTIPLY = dict(PASS)
MULTIPLY.update({34: 0x01020000, 10: 0x00FF8040, 18: 0x0080C0FF})  # A = c0, B = c1; ARGB words

FINAL = {53: 0x11101, 8: 0x0000000F, 9: 0x01021180, 43: 0x80FF4020, 44: 0x00808080}

TWOVARY = dict(PASS)
TWOVARY.update({34: 0x04050000})  # A = v0, B = v1

FIXTURES = {"pass": PASS, "multiply": MULTIPLY, "final": FINAL, "twovary": TWOVARY}
#: T860: the fixtures that also get the `_alpha` module (the alpha test runs in the combiner module)
ALPHA_FIXTURES = ("pass",)

TEX_PROBE = """\
#version 450
layout(set = 0, binding = 1, std140) uniform Constants { vec4 values[20]; } constants;
layout(set = 0, binding = 2) uniform sampler2D probe;
layout(location = 0) out vec4 frag_color;
void main() {
    // a: the right texel of row 0 by CLAMPING (1.3 is past the edge). b: texel (1, 1) by a NEAREST
    // lookup, a linear one mixes the left and right texels of row 1 (x = 0.55 is 0.6 of the way).
    vec4 a = texture(probe, vec2(1.3, 0.25));
    vec4 b = texture(probe, vec2(0.55, 0.75));
    frag_color = vec4(a.r, a.g, b.b, a.a) * constants.values[0];
}
"""


def words_of(fixture: dict[int, int]) -> list[int]:
    dwords = [0] * STATE
    for index, value in fixture.items():
        dwords[index] = value
    return dwords


def key_of(fixture: dict[int, int]) -> tuple[int, ...]:
    """The structure key of a fixture as `gpu_combiner_plan_build` computes it (no textures)."""
    return replay_modules.structure_key(words_of(fixture), 0)


def name_of(fixture: dict[int, int]) -> str:
    return replay_modules.module_name(key_of(fixture))


def compile_glsl(source: str, stage: str, directory: Path) -> list[int]:
    path = directory / f"module.{stage}"
    path.write_text(source)
    output = directory / f"module.{stage}.spv"
    done = subprocess.run(
        [
            "glslangValidator",
            "-V",
            "--target-env",
            "vulkan1.1",
            "-S",
            stage,
            "-o",
            str(output),
            str(path),
        ],
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    if done.returncode != 0:
        raise RuntimeError(done.stdout + done.stderr)
    raw = output.read_bytes()
    return [int.from_bytes(raw[i : i + 4], "little") for i in range(0, len(raw), 4)]


def render_array(name: str, words: Sequence[int]) -> str:
    lines = [f"__attribute__((unused)) static const uint32_t {name}[] = {{"]
    for start in range(0, len(words), 6):
        lines.append("    " + " ".join(f"0x{word:08x}u," for word in words[start : start + 6]))
    lines.append("};")
    return "\n".join(lines)


def render_header() -> str:
    parts = [
        "/* SPDX-License-Identifier: GPL-3.0-or-later",
        " *",
        " * GENERATED by tools/nv2a_combiner/replay_fixtures.py, regenerate with",
        " *   python -m tools.nv2a_combiner.replay_fixtures --header tests/c/gpu_combiner_words.h",
        " * The SPIR-V of the four hand-built combiner configurations (their words are in",
        " * tests/c/test_gpu_combiner.c and tests/test_gpu_combiner_replay.py, the NAME macros",
        " * prove all three agree) and of the texture probe. Nothing here comes from the user's",
        " * executable.",
        " */",
        "#ifndef TSFP_TESTS_GPU_COMBINER_WORDS_H",
        "#define TSFP_TESTS_GPU_COMBINER_WORDS_H",
        "",
        "#include <stdint.h>",
        "",
    ]
    with tempfile.TemporaryDirectory() as scratch:
        directory = Path(scratch)
        for label, fixture in FIXTURES.items():
            name = name_of(fixture)
            key = key_of(fixture)
            module = replay_modules.module_source(key)
            parts.append(f'#define COMBINER_NAME_{label.upper()} "{name}"')
            parts.append(
                render_array(f"combiner_words_{label}", compile_glsl(module, "frag", directory))
            )
            parts.append("")
            if label in ALPHA_FIXTURES:
                alpha_module = replay_modules.module_source(key, alpha_test=True)
                alpha_name = f"{name}{replay_modules.ALPHA_SUFFIX}"
                parts.append(f'#define COMBINER_NAME_{label.upper()}_ALPHA "{alpha_name}"')
                parts.append(
                    render_array(
                        f"combiner_words_{label}_alpha",
                        compile_glsl(alpha_module, "frag", directory),
                    )
                )
                parts.append("")
        parts.append(render_array("tex_probe_words", compile_glsl(TEX_PROBE, "frag", directory)))
    parts += ["", "#endif", ""]
    return "\n".join(parts)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Write the C header of the combiner replay fixtures."
    )
    parser.add_argument("--header", type=Path, required=True)
    args = parser.parse_args(argv)
    args.header.write_text(render_header())
    print(f"wrote {args.header}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
