# SPDX-License-Identifier: GPL-3.0-or-later
"""The textured combiner and the oT0 vertex shaders of the texture tests (T497 stand-in, T510).

Also the generator of their C header. Nothing here comes from the user's executable.
`--gpu-replay-standin-texture` (T497) feeds the swap replay one stand-in texture at stage 0. To pin
it on a device the ctest needs a combiner that READS texture register t0 and a vertex module that
WRITES oT0 (location 3):

  textured  r0 = t0 (colour), alpha = t0.a, final D = r0, G = r0.a: the stand-in reaches the
            target through the combiner, all four channels of it. The test stream writes the
            stage program (word 54, method 0x1E70) as 1, as the title's stream does (MEASURED), so
            the module is the one keyed with an effective word 54 of 1.
  vertex    gl_Position = v1, oD0 = v2.zyxw + c[3] (the synthetic program of the replay suites)
            and oT0 = (v1.x + 1, v1.y + 1, 0, 1): the texture coordinate follows the position and
            spans both texels of a 2x2 texture over the replay suite's triangles (clip x and y
            from -0.9 to -0.1, and 0.1 to 0.9), and a draw through it is not refused for a
            coordinate nobody wrote.

    python -m tools.nv2a_combiner.standin_fixtures --header tests/c/gpu_standin_words.h
"""

from __future__ import annotations

import argparse
import sys
import tempfile
from collections.abc import Sequence
from pathlib import Path

from tools.nv2a_combiner import replay_fixtures, replay_modules

# Stage 0 samples a 2D texture (mode 1), the value the title's stream writes for t0 draws.
STAGE_PROGRAM_MODE = 1
# PASS with the colour A input reading t0 (register 8, unsigned identity) and the alpha A input
# reading t0's alpha (0x18: register 8, alpha channel) instead of oD0, so the whole RGBA of the
# stand-in reaches the target.
TEXTURED = dict(replay_fixtures.PASS)
TEXTURED.update({34: 0x08200000, 0: 0x18300000})

VERTEX_T0 = """\
#version 450
layout(location = 1) in vec4 v1;
layout(location = 2) in vec4 v2;
layout(std140, set = 0, binding = 0) uniform Constants { vec4 c[192]; };
layout(location = 0) out vec4 oD0;
layout(location = 3) out vec4 oT0;
void main() {
    gl_Position = v1;
    oD0 = v2.zyxw + c[3];
    oT0 = vec4(v1.x + 1.0, v1.y + 1.0, 0.0, 1.0);
}
"""


# T510: the texture coordinate in TEXELS of a 128x64 render target texture (a hardware linear
# texture takes its coordinate in texels): oT0 is the window position of a pixel centre when the
# draw covers a 128x64 target, so a 1:1 draw reads texel (x, y) at pixel (x, y). Row 0 is the top
# row, as clip y = -1 is the top of the replay's image.
VERTEX_TEXEL = VERTEX_T0.replace(
    "oT0 = vec4(v1.x + 1.0, v1.y + 1.0, 0.0, 1.0);",
    "oT0 = vec4((v1.x + 1.0) * 64.0, (v1.y + 1.0) * 32.0, 0.0, 1.0);",
)
# The same, half a texel to the right: bilinear lands between two texels, nearest on a single one.
VERTEX_TEXEL_HALF = VERTEX_T0.replace(
    "oT0 = vec4(v1.x + 1.0, v1.y + 1.0, 0.0, 1.0);",
    "oT0 = vec4((v1.x + 1.0) * 64.0 + 0.5, (v1.y + 1.0) * 32.0, 0.0, 1.0);",
)


def textured_key() -> tuple[int, ...]:
    """The structure key of the textured configuration with stage 0 a 2D texture."""
    return replay_modules.structure_key(replay_fixtures.words_of(TEXTURED), STAGE_PROGRAM_MODE)


def textured_name() -> str:
    return replay_modules.module_name(textured_key())


def render_header() -> str:
    parts = [
        "/* SPDX-License-Identifier: GPL-3.0-or-later",
        " *",
        " * GENERATED by tools/nv2a_combiner/standin_fixtures.py, regenerate with",
        " *   python -m tools.nv2a_combiner.standin_fixtures --header tests/c/gpu_standin_words.h",
        " * The SPIR-V of the textured combiner (reads t0) and of the vertex shader that",
        " * writes oT0, for the stand-in texture tests of the swap replay (T497). Nothing",
        " * here comes from the user's executable.",
        " */",
        "#ifndef TSFP_TESTS_GPU_STANDIN_WORDS_H",
        "#define TSFP_TESTS_GPU_STANDIN_WORDS_H",
        "",
        "#include <stdint.h>",
        "",
        f'#define COMBINER_NAME_TEXTURED "{textured_name()}"',
    ]
    with tempfile.TemporaryDirectory() as scratch:
        directory = Path(scratch)
        fragment = replay_modules.module_source(textured_key())
        parts.append(
            replay_fixtures.render_array(
                "combiner_words_textured",
                replay_fixtures.compile_glsl(fragment, "frag", directory),
            )
        )
        parts.append("")
        parts.append(
            replay_fixtures.render_array(
                "draw_vertex_t0_words", replay_fixtures.compile_glsl(VERTEX_T0, "vert", directory)
            )
        )
        for name, source in (
            ("draw_vertex_texel_words", VERTEX_TEXEL),
            ("draw_vertex_texel_half_words", VERTEX_TEXEL_HALF),
        ):
            parts.append("")
            parts.append(
                replay_fixtures.render_array(
                    name, replay_fixtures.compile_glsl(source, "vert", directory)
                )
            )
    parts += ["", "#endif", ""]
    return "\n".join(parts)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Write the C header of the stand-in texture fixtures."
    )
    parser.add_argument("--header", type=Path, required=True)
    args = parser.parse_args(argv)
    args.header.write_text(render_header())
    print(f"wrote {args.header}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
