# SPDX-License-Identifier: GPL-3.0-or-later
"""Build-time generator: vertex-program corpus -> SPIR-V modules + the runtime selection table.

Reads a corpus written by `tools/nv2a/corpus.py` (default `generated/shaders/corpus`: `static/`,
`generated/`, `manifest.json`) and writes into a GITIGNORED directory (default
`generated/shaders/vsh`):

  * `spv/<kind>_<digest>.spv`  one vertex-stage SPIR-V module per distinct program;
  * `vsh_table.inc`            C initialisers for `struct gpu_vsh_table` (src/gpu/gpu_vsh_select.h):
                               the key mask, the sorted (key -> module) pairs, the sorted static
                               (guest address -> module) pairs and the module file names.

Nothing derived from the user's executable is committed. `--no-spirv` writes only the table.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path

from tools.nv2a import translate

STATIC = "static"
GENERATED = "generated"
REGENERATE = (
    "python -m tools.nv2a.corpus <default.xbe> --out generated/shaders/corpus (about 15 min)"
)


class TableError(Exception):
    pass


def module_name(kind: str, digest: str) -> str:
    return f"{kind}_{digest}"


def stale_manifest_reason(manifest: dict[str, object]) -> str | None:
    """Pure: why the manifest cannot select any generated program, or None when it can.

    A manifest from before T95 has `generated_distinct` programs but no `generated_keys`, so
    only the static modules would be built and the replay would refuse the first generated
    program. `tools/steady_replay.py` derives its own keys and is unaffected.
    """
    distinct = manifest.get("generated_distinct", 0)
    if not isinstance(distinct, int) or distinct <= 0:
        return None
    if manifest.get("generated_keys"):
        return None
    state = "empty" if "generated_keys" in manifest else "missing"
    return (
        f"the corpus manifest lists generated_distinct={distinct} generated programs but its "
        f"generated_keys is {state} (it predates T95), so only the static modules are built "
        "and the replay will refuse the first generated program. Regenerate the corpus "
        f"manifest: {REGENERATE}"
    )


def build_table(manifest: dict[str, object]) -> dict[str, object]:
    """Pure: manifest -> `{mask, modules, keys, statics}`; raises TableError on any ambiguity."""
    static = manifest.get("static", {})
    generated_keys = manifest.get("generated_keys", {})
    assert isinstance(static, dict) and isinstance(generated_keys, dict)
    mask = int(manifest.get("key_mask", 0))  # type: ignore[call-overload]
    modules: list[str] = []
    index: dict[str, int] = {}

    def module(kind: str, digest: str) -> int:
        name = module_name(kind, digest)
        if name not in index:
            index[name] = len(modules)
            modules.append(name)
        return index[name]

    statics: dict[int, int] = {}
    for digest, addresses in sorted(static.items()):
        for address in addresses:
            value = int(address, 16)
            if value in statics:
                raise TableError(f"static address {value:#x} appears twice")
            statics[value] = module(STATIC, digest)
    keys: dict[int, int] = {}
    for text, digest in sorted(generated_keys.items(), key=lambda item: int(item[0], 16)):
        value = int(text, 16)
        if value & ~mask:
            raise TableError(f"key {value:#x} has bits outside the mask {mask:#x}")
        keys[value] = module(GENERATED, digest)
    return {"mask": mask, "modules": modules, "keys": keys, "statics": statics}


def render_inc(table: dict[str, object]) -> str:
    modules: list[str] = table["modules"]  # type: ignore[assignment]
    keys: dict[int, int] = table["keys"]  # type: ignore[assignment]
    statics: dict[int, int] = table["statics"]  # type: ignore[assignment]
    lines = ["/* GENERATED by tools/nv2a/vsh_modules.py, do not edit, do not commit. */"]
    lines.append("static const char *const vsh_module_names[] = {")
    lines += [f'    "{name}",' for name in modules] or ["    0"]
    lines.append("};")
    lines.append("static const struct gpu_vsh_entry vsh_key_entries[] = {")
    lines += [f"    {{0x{k:08x}u, {m}u}}," for k, m in sorted(keys.items())] or ["    {0u, 0u}"]
    lines.append("};")
    lines.append("static const struct gpu_vsh_entry vsh_static_entries[] = {")
    lines += [f"    {{0x{k:08x}u, {m}u}}," for k, m in sorted(statics.items())] or ["    {0u, 0u}"]
    lines.append("};")
    lines.append("static const struct gpu_vsh_table vsh_table = {")
    lines.append(f"    0x{table['mask']:08x}u,")
    lines.append(f"    {len(keys)}u, vsh_key_entries,")
    lines.append(f"    {len(statics)}u, vsh_static_entries,")
    lines.append(f"    {len(modules)}u, vsh_module_names,")
    lines.append("};")
    return "\n".join(lines) + "\n"


def compile_vertex(glsl: Path, spirv: Path, glslang: str) -> None:
    done = subprocess.run(
        [glslang, "-V", "--target-env", "vulkan1.1", "-S", "vert", "-o", str(spirv), str(glsl)],
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    if done.returncode != 0:
        raise TableError(f"glslang failed on {glsl.name}: {(done.stdout + done.stderr)[:500]}")


def make_program_module(
    program: bytes,
    spv_directory: Path,
    *,
    kind: str = GENERATED,
    glslang: str = "glslangValidator",
    undo_viewport: bool = False,
    window_to_clip: bool = False,
    output_init: str = translate.DEFAULT_OUTPUT_INIT,
    live_raster: bool = False,
    live_fog: bool = False,
) -> Path:
    """T847: one `<kind>_<sha256>.spv` module for one program given as its bytes (the header, the
    instruction count and the instructions, the form the replay digests), written into
    `spv_directory` through a temporary name so a reader never sees half a module. The digest in
    the name is the program's own, so the replay finds the module by name. An existing module is
    kept (the digest names its content, the options are the caller's)."""
    if shutil.which(glslang) is None:
        raise TableError(f"{glslang} not found (sudo apt-get install -y glslang-tools)")
    name = module_name(kind, hashlib.sha256(program).hexdigest())
    spv_directory.mkdir(parents=True, exist_ok=True)
    final = spv_directory / f"{name}.spv"
    if final.exists():
        return final
    translation = translate.translate(program, name=name)
    source_text = translate.vertex_shader_source(
        translation,
        undo_viewport=undo_viewport,
        window_to_clip=window_to_clip,
        output_init=output_init,
        live_raster=live_raster,
        live_fog=live_fog,
    )
    stem = f"{name}.{os.getpid()}"
    glsl = spv_directory / f"{stem}.vert"
    partial = spv_directory / f"{stem}.partial"
    try:
        glsl.write_text(source_text)
        compile_vertex(glsl, partial, glslang)
        partial.replace(final)
    finally:
        glsl.unlink(missing_ok=True)
        partial.unlink(missing_ok=True)
    return final


def generate(
    corpus: Path,
    out: Path,
    *,
    spirv: bool = True,
    glslang: str = "glslangValidator",
    undo_viewport: bool = False,
    strict_manifest: bool = False,
    window_to_clip: bool = False,
    output_init: str = translate.DEFAULT_OUTPUT_INIT,
) -> dict[str, object]:
    manifest = json.loads((corpus / "manifest.json").read_text())
    stale = stale_manifest_reason(manifest)
    if stale is not None:
        if strict_manifest:
            raise TableError(stale)
        print(f"vsh_modules: WARNING: {stale}", file=sys.stderr)
    table = build_table(manifest)
    out.mkdir(parents=True, exist_ok=True)
    if spirv:
        if shutil.which(glslang) is None:
            raise TableError(f"{glslang} not found (use --no-spirv for the table only)")
        (out / "spv").mkdir(exist_ok=True)
        for name in table["modules"]:  # type: ignore[attr-defined]
            kind, digest = name.split("_", 1)
            source = corpus / kind / f"{digest}.bin"
            glsl = out / "spv" / f"{name}.vert"
            translation = translate.translate(source.read_bytes(), name=name)
            source_text = translate.vertex_shader_source(
                translation,
                undo_viewport=undo_viewport,
                window_to_clip=window_to_clip,
                output_init=output_init,
            )
            glsl.write_text(source_text)
            compile_vertex(glsl, out / "spv" / f"{name}.spv", glslang)
            glsl.unlink()
    (out / "vsh_table.inc").write_text(render_inc(table))
    return table


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--corpus", type=Path, default=Path("generated/shaders/corpus"))
    parser.add_argument("--out", type=Path, default=Path("generated/shaders/vsh"))
    parser.add_argument(
        "--program",
        type=Path,
        help="T847: translate ONE program file (header, count, instructions: the form the replay "
        "digests) into --out as generated_<sha256>.spv and exit, no corpus. --out is the module "
        "directory itself",
    )
    parser.add_argument("--no-spirv", action="store_true", help="write only vsh_table.inc")
    parser.add_argument("--glslang", default="glslangValidator")
    parser.add_argument(
        "--undo-viewport",
        action="store_true",
        help="modules invert the program's c58/c59 viewport transform (T96, INFERRED), default raw",
    )
    parser.add_argument(
        "--window-to-clip",
        action="store_true",
        help="modules also convert x and y of window coordinate programs (the none and z-only "
        "classes) with c58/c59 (T560, INFERRED), default raw. Combine with --undo-viewport",
    )
    parser.add_argument(
        "--output-init",
        choices=sorted(translate.OUTPUT_INITS),
        default=translate.DEFAULT_OUTPUT_INIT,
        help="initial value of every vertex output (T561/T713): zero (default) or nv, "
        "(0, 0, 0, 1), INFERRED until HQ20, so a program that writes only oT0.xy leaves w at 1",
    )
    parser.add_argument(
        "--strict-manifest",
        action="store_true",
        help="exit 1 when the manifest has generated programs but no generated_keys "
        "(default: warn on stderr and build the static modules only)",
    )
    args = parser.parse_args(argv)
    if args.program is not None:
        try:
            options = {
                "undo_viewport": args.undo_viewport,
                "window_to_clip": args.window_to_clip,
                "output_init": args.output_init,
            }
            made = make_program_module(
                args.program.read_bytes(), args.out, glslang=args.glslang, **options
            )
        except (TableError, OSError, translate.Unsupported) as error:
            print(f"vsh_modules: {error}", file=sys.stderr)
            return 1
        print(made)
        return 0
    try:
        table = generate(
            args.corpus,
            args.out,
            spirv=not args.no_spirv,
            glslang=args.glslang,
            undo_viewport=args.undo_viewport,
            window_to_clip=args.window_to_clip,
            output_init=args.output_init,
            strict_manifest=args.strict_manifest,
        )
    except (TableError, OSError, translate.Unsupported) as error:
        print(f"vsh_modules: {error}", file=sys.stderr)
        return 1
    print(
        f"{len(table['modules'])} modules, {len(table['keys'])} keys, "  # type: ignore[arg-type]
        f"{len(table['statics'])} static addresses"  # type: ignore[arg-type]
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
