/* SPDX-License-Identifier: GPL-3.0-or-later
 *
 * GENERATED by tools/gen_kernel_header.py from tools/kernel_ordinals.py.
 * Do not edit: regenerate instead.
 *
 * Xbox kernel export ordinal -> name. An XBE imports kernel functions by
 * ordinal only, with no name strings, so this table is the only way to know what
 * a guest is calling.
 *
 * Ordinal tables are factual interface documentation, published independently on
 * xboxdevwiki. This data is from sp00nznet/xboxrecomp (MIT, Copyright (c) 2026
 * sp00nz).
 */

#ifndef TSFP_XBOX_KERNEL_ORDINALS_H
#define TSFP_XBOX_KERNEL_ORDINALS_H

#include <stddef.h>

/* Highest ordinal in the table, inclusive. Ordinals are not contiguous. */
#define XBOX_KERNEL_ORDINAL_MAX 378

/** Name for a kernel ordinal, or NULL if the ordinal is unknown. */
const char *xbox_kernel_ordinal_name(unsigned ordinal);

/** Count of known ordinals. */
size_t xbox_kernel_ordinal_count(void);

#endif /* TSFP_XBOX_KERNEL_ORDINALS_H */
