# SPDX-License-Identifier: GPL-3.0-or-later
"""Build docs/game-glossary.md from the public TimeSplitters fandom wiki category listings.

Only page TITLES (facts: mission, character, weapon, map and mode names) are collected through the
wiki's public MediaWiki API, never page text, so the glossary is a vocabulary list for naming game
functions, not a copy of the wiki. Network access is required; output is deterministic for a given
wiki state.
"""

import argparse
import json
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

API = "https://timesplitters.fandom.com/api.php"
USER_AGENT = "Mozilla/5.0 (research; tsfp-decomp glossary)"

SECTIONS = [
    ("Story missions", ["Story missions in TSFP"]),
    ("Characters", ["Characters - TimeSplitters Future Perfect"]),
    ("Weapons", ["Weapons - TimeSplitters Future Perfect"]),
    (
        "Weapon classes (all games, intersect with the Weapons section above)",
        [
            "Weapons - Automatic",
            "Weapons - Explosive",
            "Weapons - Handgun",
            "Weapons - Melee",
            "Weapons - Other",
            "Weapons - Pistol",
            "Weapons - Shotgun",
            "Weapons - Sniper",
        ],
    ),
    ("Maps", ["Maps - TimeSplitters: Future Perfect"]),
    ("Levels", ["Levels - TimeSplitters Future Perfect"]),
    ("Challenges", ["Challenges - TimeSplitters: Future Perfect", "TimeSplitters FP Challenges"]),
    ("Arcade leagues", ["Arcade Leagues - TimeSplitters Future Perfect"]),
    (
        "League series and matches",
        [
            "League Series - TimeSplitters: Future Perfect",
            "League Matches - TimeSplitters: Future Perfect",
        ],
    ),
    ("Modes", ["Modes"]),
    ("Vehicles", ["Vehicles"]),
    ("Map Maker", ["Mapmaker", "Mapmaker - Assault", "Mapmaker - Story", "Items - Mapmaker"]),
]


def members(category: str, delay: float) -> list[str]:
    titles: list[str] = []
    cont: dict[str, str] = {}
    while True:
        query = {
            "action": "query",
            "list": "categorymembers",
            "cmtitle": f"Category:{category.replace(' ', '_')}",
            "cmlimit": "500",
            "format": "json",
            **cont,
        }
        request = urllib.request.Request(
            f"{API}?{urllib.parse.urlencode(query)}", headers={"User-Agent": USER_AGENT}
        )
        with urllib.request.urlopen(request, timeout=40) as response:
            data = json.load(response)
        titles += [m["title"] for m in data.get("query", {}).get("categorymembers", [])]
        if "continue" not in data:
            return titles
        cont = {k: v for k, v in data["continue"].items()}
        time.sleep(delay)


def page_column(page: str, column_from_end: int, delay: float) -> list[str]:
    """Titles from one column of a series table (the TSFP column), keeping the list nesting.

    The wiki's Challenge and Arcade League pages are three-column tables (one column per game);
    the Future Perfect column is the last one. Output lines are 'depth|title' with depth 0 for a
    league heading or series, 1 for a series inside a league, and so on.
    """
    query = {"action": "parse", "page": page, "prop": "wikitext", "format": "json"}
    request = urllib.request.Request(
        f"{API}?{urllib.parse.urlencode(query)}", headers={"User-Agent": USER_AGENT}
    )
    with urllib.request.urlopen(request, timeout=40) as response:
        text = json.load(response)["parse"]["wikitext"]["*"]
    time.sleep(delay)
    columns = re.split(r'\n\|\s*valign="top"\s*\|', text)
    column = re.sub(r"\n\|\}.*", "", columns[len(columns) - column_from_end], flags=re.S)
    rows: list[str] = []
    for raw in column.splitlines():
        line = raw.strip()
        heading = re.fullmatch(r"'''(.+?)'''", line)
        if heading:
            rows.append(f"0|{heading.group(1)}")
            continue
        item = re.match(r"(\*+)\s*(.*)", line)
        if item:
            title = re.sub(r"\[\[(?:[^\]|]*\|)?([^\]]*)\]\]", r"\1", item.group(2))
            title = title.replace("''", "").strip()
            if title:
                rows.append(f"{len(item.group(1))}|{title}")
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("docs/game-glossary.md"))
    parser.add_argument("--delay", type=float, default=0.5, help="seconds between API requests")
    args = parser.parse_args()
    lines = [
        "# TimeSplitters: Future Perfect vocabulary (for naming game functions)",
        "",
        "Generated by `python -m tools.fetch_game_glossary` from the page titles in the public",
        "TimeSplitters fandom wiki categories "
        "(https://timesplitters.fandom.com, community content under",
        "CC BY-SA). Titles only, no page text. Use it as naming vocabulary and "
        "a source of context;",
        "a wiki name is NOT evidence that a function does something, only the code and traces are.",
        "Facts from Wikipedia "
        "(https://en.wikipedia.org/wiki/TimeSplitters:_Future_Perfect): developer",
        "Free Radical Design, publisher Electronic Arts, platforms GameCube, "
        "PlayStation 2 and Xbox",
        "(Xbox release 2005-03-22 NA, 2005-03-24 EU), modes Story (co-op), Arcade, Challenge,",
        "multiplayer including online on Xbox Live (disabled) and Map Maker (basic and advanced),",
        "protagonist Sergeant Cortez, Anya the Chief Science Officer, the "
        "General, antagonist Dr. Jacob Crow.",
        "See also [game-menus.md](game-menus.md), the owner-described menu tree.",
        "",
    ]
    for heading, categories in SECTIONS:
        names: list[str] = []
        for category in categories:
            names += members(category, args.delay)
            time.sleep(args.delay)
        names = sorted({n for n in names if not n.startswith(("Template:", "Category:", "File:"))})
        lines += [
            f"## {heading} ({len(names)})",
            "",
            "Source categories: " + ", ".join(categories),
            "",
        ]
        lines += [f"- {n}" for n in names] or ["- (none returned)"]
        lines.append("")
        print(f"{heading}: {len(names)}", file=sys.stderr)
    for heading, page in (
        ("Challenge structure (series, then levels)", "Challenge"),
        ("Arcade League structure (league, then series, then levels)", "Arcade_League"),
    ):
        rows = page_column(page, 1, args.delay)
        lines += [
            f"## {heading} ({sum(1 for r in rows if r[0] == '3' or r.startswith('2|'))} levels)",
            "",
            f"Source page: {page} (Future Perfect column)",
            "",
        ]
        for row in rows:
            depth, title = row.split("|", 1)
            lines.append(("  " * int(depth)) + f"- {title}")
        lines.append("")
        print(f"{heading}: {len(rows)} rows", file=sys.stderr)
    args.out.write_text("\n".join(lines).rstrip("\n") + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
