# SPDX-License-Identifier: GPL-3.0-or-later
"""Emit a Ghidra-parseable C header from the donor type extraction.

Ghidra parses C source into its data type manager, so a clean header is the
lowest-friction way to get the donor's struct layouts in. A binary `.gdt` would be
version-pinned and opaque by comparison.

THE CONSTRAINT THAT MATTERS. The donor is TimeSplitters 2 on MIPS EE; the target
is TimeSplitters: Future Perfect on x86. Field *names and order* transfer as
hypotheses. Byte *offsets* do not: `prop_s` embeds two EE-specific 0x40-byte
matrix unions, and array sizes like `gunsheld[40]` are version-stamped by content.
So donor sizes are emitted as comments and never as `static_assert`, because
asserting a donor size against a TSFP build would be asserting a falsehood.
"""

from __future__ import annotations

import argparse
from collections.abc import Iterable
from datetime import UTC, datetime
from pathlib import Path

from tools.stabs import StructDef, parse_types

# Donor base types, as Free Radical and the Sony SDK defined them, mapped to
# fixed-width C so the header parses without the donor's own headers.
BASE_TYPE_MAP = {
    "u8": "uint8_t",
    "s8": "int8_t",
    "u16": "uint16_t",
    "s16": "int16_t",
    "u32": "uint32_t",
    "s32": "int32_t",
    "u64": "uint64_t",
    "s64": "int64_t",
    "u128": "donor_u128",
    "boolean": "uint32_t",
    "fix_t": "int32_t",
    "vindex": "uint8_t",
}

HEADER_PROLOGUE = """\
/* SPDX-License-Identifier: GPL-3.0-or-later
 *
 * GENERATED by tools/gen_donor_header.py. Do not edit; regenerate instead.
 *
 * Free Radical engine types recovered from the TimeSplitters 2 US OPM Demo 53
 * build (TS2/SLUS_999.99, %(donor_date)s), which shipped unstripped with a
 * populated .mdebug stabs section.
 *
 * Generated %(generated)s from %(struct_count)d struct/union definitions.
 *
 * ============================== READ THIS ==============================
 *
 * This is a DONOR, not the target. TimeSplitters 2 is the previous game, built
 * for MIPS EE; TimeSplitters: Future Perfect is ours, built for x86.
 *
 *   * Field NAMES and ORDER transfer as hypotheses and are usually right.
 *   * Byte OFFSETS DO NOT TRANSFER. Donor sizes appear in comments only.
 *
 * `prop_s` embeds two EE-specific 0x40-byte matrix unions, so everything after
 * them shifts. Array sizes are version-stamped by content: TSFP has more weapons
 * and characters than TS2, so `gunsheld`, `ammo` and `kills` will have grown, and
 * each growth shifts every field after it.
 *
 * Recover each struct's real TSFP size from its allocation call site, then walk
 * offsets outward from high-confidence anchors. Assuming a donor offset produces
 * subtly wrong code that passes tests.
 * =======================================================================
 */

#ifndef TSFP_DONOR_TYPES_H
#define TSFP_DONOR_TYPES_H

#include <stdint.h>

"""


def map_base_types(type_name: str) -> str:
    """Rewrite donor base types to fixed-width C, preserving pointers and spacing."""
    out: list[str] = []
    for token in type_name.replace("*", " * ").split():
        out.append(BASE_TYPE_MAP.get(token, token))
    rendered = " ".join(out)
    # Re-tighten pointer spacing: "int *" rather than "int * ".
    return rendered.replace(" *", " *").replace("* ", "*").replace("*", " *", 1).strip()


def is_emittable(struct: StructDef) -> bool:
    """Only emit aggregates that parsed completely and carry a known size.

    A partially-parsed struct entering the type manager is worse than none: it
    looks authoritative while being wrong about where its later fields sit.
    """
    return bool(struct.name) and bool(struct.fields) and struct.size is not None


def by_value_dependencies(struct: StructDef, known: set[str]) -> set[str]:
    """Aggregates this struct embeds by value or as an array, so needs defined first.

    Pointer members do not count: a pointer to an incomplete type is legal, which
    is what the forward declarations cover. By-value and array members are not,
    and that distinction is the whole reason an ordering is needed.
    """
    deps: set[str] = set()
    for item in struct.fields:
        if "*" in item.type_name:
            continue
        for token in item.type_name.split():
            if token in known and token != struct.name:
                deps.add(token)
    return deps


def order_definitions(structs: Iterable[StructDef]) -> list[StructDef]:
    """Topologically order definitions so each is defined before it is embedded.

    Forward declarations are not sufficient on their own: a struct that embeds
    another BY VALUE or as an ARRAY needs the embedded type complete at that point.
    An earlier version of this sorted alphabetically on the theory that pointers
    were the only cross-reference, and the compile check produced 20 errors of the
    form "array has incomplete element type 'mtx_u'". Hence a real sort.

    Ties break alphabetically so regeneration diffs stay readable, and a cycle
    (which would mean a struct embedding itself by value, i.e. impossible in valid
    C) degrades to alphabetical rather than looping.
    """
    emittable = sorted((s for s in structs if is_emittable(s)), key=lambda s: s.name)
    known = {s.name for s in emittable}
    by_name = {s.name: s for s in emittable}
    deps = {s.name: by_value_dependencies(s, known) for s in emittable}

    ordered: list[StructDef] = []
    placed: set[str] = set()
    visiting: set[str] = set()

    def visit(name: str) -> None:
        if name in placed or name in visiting:
            return
        visiting.add(name)
        for dependency in sorted(deps.get(name, ())):
            if dependency in by_name:
                visit(dependency)
        visiting.discard(name)
        if name not in placed:
            placed.add(name)
            ordered.append(by_name[name])

    for struct in emittable:
        visit(struct.name)
    return ordered


#: C keywords and builtin type words that are never undefined type names.
_NOT_A_TYPE_NAME = {
    "struct",
    "union",
    "enum",
    "const",
    "volatile",
    "unsigned",
    "signed",
    "char",
    "short",
    "int",
    "long",
    "float",
    "double",
    "void",
    "_Bool",
}


#: Compiler and libc internals that collide with system headers if redefined.
_SYSTEM_TYPE_MAP = {
    "__int8_t": "int8_t",
    "__uint8_t": "uint8_t",
    "__int16_t": "int16_t",
    "__uint16_t": "uint16_t",
    "__int32_t": "int32_t",
    "__uint32_t": "uint32_t",
    "__int64_t": "int64_t",
    "__uint64_t": "uint64_t",
    "SItype": "int32_t",  # GCC internal: a single-integer-word type, 32-bit on EE.
    "USItype": "uint32_t",
    "DItype": "int64_t",  # GCC internal: a double-integer-word type.
    "UDItype": "uint64_t",
}

#: Intentionally empty.
#:
#: This header is written to be parsed IN ISOLATION, which is how Ghidra consumes
#: C source, so it defines every name it references and includes only <stdint.h>.
#: An earlier attempt to defer standard types to the system headers turned into
#: whack-a-mole: every POSIX type not enumerated (size_t, then va_list, then
#: nlink_t...) collided. Isolated parsing has no such conflicts, and the test
#: compiles the header standalone to match the real use case rather than
#: alongside <stdio.h>, which nothing actually requires.
_SYSTEM_PROVIDED: set[str] = set()

#: Default stand-in size when a by-value field's type cannot be sized at all.
_FALLBACK_OPAQUE_SIZE = 4


def referenced_type_names(structs: Iterable[StructDef]) -> set[str]:
    """Every bare identifier a field's type refers to."""
    names: set[str] = set()
    for struct in structs:
        for item in struct.fields:
            for token in item.type_name.replace("*", " ").split():
                if token not in _NOT_A_TYPE_NAME and token.isidentifier():
                    names.add(token)
    return names


def by_value_type_names(structs: Iterable[StructDef]) -> set[str]:
    """Identifiers used as a field's type WITHOUT a pointer.

    A pointer to an incomplete type is legal C; a by-value member is not. Only the
    latter needs a sized stand-in, so distinguishing them keeps the invented sizes
    to the minimum.
    """
    names: set[str] = set()
    for struct in structs:
        for item in struct.fields:
            if "*" in item.type_name:
                continue
            for token in item.type_name.split():
                if token not in _NOT_A_TYPE_NAME and token.isidentifier():
                    names.add(token)
    return names


def infer_type_sizes(structs: Iterable[StructDef]) -> dict[str, int]:
    """Infer sizes for unknown types from the spacing between donor field offsets.

    If two consecutive fields of the same unknown type sit 4 bytes apart, that type
    is 4 bytes. This recovers a real size from data we already have rather than
    inventing one, and it is exact whenever the evidence exists.
    """
    sizes: dict[str, int] = {}
    for struct in structs:
        fields = struct.fields
        for index, item in enumerate(fields):
            if "*" in item.type_name or item.array_suffix:
                continue
            bare = item.type_name.strip()
            if not bare.isidentifier() or bare in _NOT_A_TYPE_NAME:
                continue
            # Distance to the next field, or to the end of the struct.
            if index + 1 < len(fields):
                span = fields[index + 1].offset - item.offset
            elif struct.size is not None:
                span = struct.size - item.offset
            else:
                continue
            if span > 0 and (bare not in sizes or span < sizes[bare]):
                sizes[bare] = span
    return sizes


def render_header(structs: Iterable[StructDef], *, donor_date: str = "2001-10-05") -> str:
    """Render the full header text.

    The header is made self-contained deliberately. The donor's own code relied on
    typedefs we do not have, so without this a consumer gets a cascade of
    'unknown type name' and silently imports nothing. Three things make it parse:
    a typedef per aggregate so bare tag references resolve, the mapped base types,
    and an explicit fallback typedef for every name that is still unresolved,
    marked as such rather than quietly invented.
    """
    emit = order_definitions(structs)
    defined = {s.name for s in emit}
    unresolved = sorted(
        name
        for name in referenced_type_names(emit)
        if name not in defined
        and name not in BASE_TYPE_MAP.values()
        and name not in _SYSTEM_TYPE_MAP
    )
    needs_size = by_value_type_names(emit)
    inferred = infer_type_sizes(emit)

    parts = [
        HEADER_PROLOGUE
        % {
            "donor_date": donor_date,
            "generated": datetime.now(UTC).strftime("%Y-%m-%d"),
            "struct_count": len(emit),
        }
    ]

    parts.append("/* Forward declarations, so pointer members resolve in one pass. */\n")
    for struct in emit:
        parts.append(f"{struct.kind} {struct.name};\n")
    parts.append("\n")

    parts.append(
        "/* A typedef per aggregate: the donor's code referred to these by bare\n"
        " * name, which C only permits via a typedef. */\n"
    )
    for struct in emit:
        parts.append(f"typedef {struct.kind} {struct.name} {struct.name};\n")
    parts.append("\n")

    parts.append(
        "/* The PS2's 128-bit type. Emitted as a sized struct rather than a compiler\n"
        " * extension so a C parser without __int128 still accepts the header. */\n"
        "typedef struct { uint64_t lo; uint64_t hi; } donor_u128;\n\n"
    )
    parts.append(
        "/* Compiler and libc internal types, mapped to fixed-width equivalents so\n"
        " * they neither collide with system headers nor stay incomplete. */\n"
    )
    for name, mapped in sorted(_SYSTEM_TYPE_MAP.items()):
        parts.append(f"typedef {mapped} {name};\n")
    parts.append("\n")

    if unresolved:
        parts.append(
            "/* Types referenced by a field but never defined in the donor's symbol\n"
            " * table. Those used only through a pointer stay incomplete, which is\n"
            " * legal and honest. Those used BY VALUE need a size, so one is taken\n"
            " * from the spacing between donor field offsets where that evidence\n"
            " * exists, and marked GUESSED where it does not -- a guessed size makes\n"
            " * any enclosing struct's later offsets unreliable even in donor terms.\n"
            f" * {len(unresolved)} unresolved. */\n"
        )
        for name in unresolved:
            if name not in needs_size:
                parts.append(f"{'struct'} {name};  /* UNRESOLVED, pointer use only */\n")
                parts.append(f"typedef struct {name} {name};\n")
                continue
            size = inferred.get(name)
            note = "size inferred from donor field spacing" if size else "size GUESSED"
            width = size or _FALLBACK_OPAQUE_SIZE
            parts.append(
                f"typedef struct {{ unsigned char opaque[{width}]; }} {name};"
                f"  /* UNRESOLVED, {note} */\n"
            )
        parts.append("\n")

    for struct in emit:
        parts.append(f"/* donor size {struct.size:#x} ({struct.size} bytes) */\n")
        parts.append(f"{struct.kind} {struct.name} {{\n")
        for item in struct.fields:
            mapped = map_base_types(item.type_name)
            parts.append(
                f"    /* donor {item.offset:#05x} */ {mapped} {item.name}{item.array_suffix};\n"
            )
        parts.append("};\n\n")

    parts.append("#endif /* TSFP_DONOR_TYPES_H */\n")
    return "".join(parts)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate a Ghidra-parseable header from donor types.",
        epilog="Produce the input with: stdump types SLUS_999.99 > types.log",
    )
    parser.add_argument("--types", type=Path, required=True, help="stdump types output")
    parser.add_argument("--out", type=Path, required=True, help="header to write")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    text = args.types.read_text(encoding="utf-8", errors="replace")
    structs = parse_types(text.splitlines())
    emittable = order_definitions(structs)
    skipped = len([s for s in structs if not is_emittable(s)])

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_header(structs), encoding="utf-8")
    fields = sum(len(s.fields) for s in emittable)
    print(
        f"{len(emittable)} definitions ({fields} fields) written to {args.out}; "
        f"{skipped} skipped as incomplete"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
