# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate src/xbox/kernel_ordinals.h from tools/kernel_ordinals.py.

The Python table is the single source of truth. This keeps the C build free of a
Python dependency while avoiding two hand-maintained copies that can drift.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from tools.kernel_ordinals import KERNEL_ORDINALS

BANNER = """\
/* SPDX-License-Identifier: GPL-3.0-or-later
 *
 * GENERATED by tools/gen_kernel_header.py from tools/kernel_ordinals.py.
 * Do not edit: regenerate instead.
 *
 * Xbox kernel export ordinal -> name. An XBE imports kernel functions by
 * ordinal only, with no name strings, so this table is the only way to know what
 * a guest is calling.
 *
 * Ordinal tables are factual interface documentation, published independently on
 * xboxdevwiki. This data is from sp00nznet/xboxrecomp (MIT, Copyright (c) 2026
 * sp00nz).
 */

#ifndef TSFP_XBOX_KERNEL_ORDINALS_H
#define TSFP_XBOX_KERNEL_ORDINALS_H

#include <stddef.h>

/* Highest ordinal in the table, inclusive. Ordinals are not contiguous. */
#define XBOX_KERNEL_ORDINAL_MAX %(maximum)d

/** Name for a kernel ordinal, or NULL if the ordinal is unknown. */
const char *xbox_kernel_ordinal_name(unsigned ordinal);

/** Count of known ordinals. */
size_t xbox_kernel_ordinal_count(void);

#endif /* TSFP_XBOX_KERNEL_ORDINALS_H */
"""

SOURCE_BANNER = """\
/* SPDX-License-Identifier: GPL-3.0-or-later
 *
 * GENERATED by tools/gen_kernel_header.py. Do not edit; regenerate instead.
 */

#include "kernel_ordinals.h"

#include <stdio.h>

/* Sparse table indexed by ordinal; gaps are NULL. Ordinals %(gaps)s are absent
 * from the real kernel export table, so a guest importing one is malformed. */
static const char *const names[XBOX_KERNEL_ORDINAL_MAX + 1] = {
%(entries)s};

const char *xbox_kernel_ordinal_name(unsigned ordinal)
{
    if (ordinal > XBOX_KERNEL_ORDINAL_MAX) {
        return NULL;
    }
    return names[ordinal];
}

size_t xbox_kernel_ordinal_count(void)
{
    size_t count = 0;
    for (unsigned i = 0; i <= XBOX_KERNEL_ORDINAL_MAX; i++) {
        if (names[i]) {
            count++;
        }
    }
    return count;
}
"""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate the kernel ordinal C table.")
    parser.add_argument("--out-dir", type=Path, default=Path("src/xbox"), help="where to write")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    maximum = max(KERNEL_ORDINALS)
    gaps = [i for i in range(1, maximum + 1) if i not in KERNEL_ORDINALS]

    entries = "".join(
        f'    [{ordinal}] = "{KERNEL_ORDINALS[ordinal]}",\n' for ordinal in sorted(KERNEL_ORDINALS)
    )

    header = args.out_dir / "kernel_ordinals.h"
    source = args.out_dir / "kernel_ordinals.c"
    header.write_text(BANNER % {"maximum": maximum}, encoding="utf-8")
    source.write_text(
        SOURCE_BANNER
        % {
            "entries": entries,
            "gaps": ", ".join(str(g) for g in gaps) if gaps else "(none)",
        },
        encoding="utf-8",
    )
    print(f"wrote {header} and {source}: {len(KERNEL_ORDINALS)} ordinals, max {maximum}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
