# SPDX-License-Identifier: GPL-3.0-or-later
"""Whole-table consistency review of the function-name overlay (T1473).

    python -m tools.name_consistency report [--names tools/data/function_names.csv] [--json OUT]
    python -m tools.name_consistency plan --out tmp/t1473/plan.csv
    python -m tools.name_consistency apply PLAN.csv [--renames docs/data/t1473-renames.csv]

Read-only analysis (report, plan). `apply` rewrites names in place keeping the VA, appends
'renamed T1473 from <old>: <reason>' to the evidence and logs entry_va,old,new,reason_class
to the rename table. Seed rows (evidence regenerated by tools.seed_function_names) are never
touched. Reports: (1) prefix families and synonym families with band provenance and
glossary/doc support, (2) verb inconsistencies between sibling names, (3) address-shaped
names, (4) numeric/letter suffix schemes, (5) over-specific names with thin evidence.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

from tools.seed_function_names import SEED_EVIDENCE

NAMES = Path("tools/data/function_names.csv")
RENAMES = Path("docs/data/t1473-renames.csv")
IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# (group label, canonical word, variants that name the same concept).
SYNONYMS = [
    ("menu/ui/screen", "menu", ["ui", "screen"]),
    ("hud/overlay", "hud", ["overlay"]),
    ("particle/effect/fx", "particle", ["effect", "fx"]),
    ("collision/physics/sweep", "collision", ["physics", "sweep"]),
    ("net/online/session/fesl", "net", ["online", "session", "fesl"]),
    ("mapedit/mapmaker/editor", "mapedit", ["mapmaker", "editor"]),
    ("weapon/gun", "weapon", ["gun"]),
    ("player/pawn/character/char/actor", "player", ["pawn", "character", "char", "actor"]),
    ("object/obj", "object", ["obj"]),
    ("sound/audio/sfx", "sound", ["audio", "sfx"]),
    ("anim/animation", "anim", ["animation"]),
    ("cutscene/cinematic/movie", "cutscene", ["cinematic", "movie"]),
]
VERB_GROUPS = [
    ("get/read/fetch", "get", ["read", "fetch"]),
    ("set/write/store", "set", ["write", "store"]),
    ("init/reset/clear", "init", ["reset", "clear"]),
    ("update/tick/step", "update", ["tick", "step"]),
    ("alloc/acquire/create/allocate", "alloc", ["acquire", "create", "allocate"]),
    ("free/release/destroy", "free", ["release", "destroy"]),
]
BAND_DOC = re.compile(r"docs/t\d+[a-z0-9-]*\.md")
ADDRESS = re.compile(r"(?<=_)(?:0x)?([0-9a-f]{6})(?=_|$)")
SUFFIX = re.compile(r"_(?:([a-z])|(\d+)|(one|two|three|four))$")
GENERIC_OWNERS = {
    "global",
    "globals",
    "table",
    "static",
    "get",
    "set",
    "call",
    "thunk",
    "wrapper",
    "find",
    "is",
    "clear",
    "copy",
    "array",
    "list",
    "shared",
    "current",
}


def load(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def is_seed(row: dict[str, str]) -> bool:
    return SEED_EVIDENCE.search(row["evidence"]) is not None


def tokens(name: str) -> list[str]:
    return name.split("_")[1:]


def band_of(row: dict[str, str]) -> str:
    docs = BAND_DOC.findall(row["evidence"])
    return docs[-1].removeprefix("docs/").removesuffix(".md") if docs else "(none)"


def glossary_support(words: list[str]) -> dict[str, int]:
    text = ""
    for doc in ("docs/game-glossary.md", "docs/game-menus.md"):
        if Path(doc).is_file():
            text += Path(doc).read_text(encoding="utf-8", errors="replace").lower()
    return {word: len(re.findall(r"\b" + re.escape(word), text)) for word in words}


def prefix_families(rows: list[dict[str, str]]) -> dict[str, dict]:
    counts: dict[str, Counter] = defaultdict(Counter)
    for row in rows:
        parts = tokens(row["name"])
        if parts:
            counts[parts[0]][band_of(row)] += 1
    return {k: {"count": sum(v.values()), "bands": v.most_common(3)} for k, v in counts.items()}


def synonym_report(rows: list[dict[str, str]]) -> list[dict]:
    out = []
    for label, canon, variants in SYNONYMS:
        words = [canon, *variants]
        word_rows = {w: [r for r in rows if w in tokens(r["name"])] for w in words}
        prefix = {w: sum(1 for r in rows if tokens(r["name"])[:1] == [w]) for w in words}
        out.append(
            {
                "group": label,
                "token_count": {w: len(word_rows[w]) for w in words},
                "prefix_count": prefix,
                "glossary_mentions": glossary_support(words),
                "evidence_mentions": {
                    w: sum(1 for r in word_rows[w] if re.search(r"'[^']*" + w, r["evidence"]))
                    for w in words
                },
            }
        )
    return out


def verb_report(rows: list[dict[str, str]]) -> list[dict]:
    """Sibling names equal after masking a verb token of one group, with differing verbs."""
    out = []
    for label, canon, variants in VERB_GROUPS:
        words = {canon, *variants}
        stems: dict[tuple, dict[str, list[str]]] = defaultdict(lambda: defaultdict(list))
        for row in rows:
            parts = tokens(row["name"])
            for index, part in enumerate(parts):
                if part in words:
                    stems[(tuple(parts[:index]), tuple(parts[index + 1 :]))][part].append(
                        row["name"]
                    )
        pairs = [
            {"stem": "_".join(prefix) + "_*_" + "_".join(rest), "verbs": dict(verbs)}
            for (prefix, rest), verbs in stems.items()
            if len(verbs) > 1 and rest
        ]
        out.append({"group": label, "sibling_pairs": len(pairs), "examples": pairs[:8]})
    return out


def address_report(rows: list[dict[str, str]]) -> dict:
    by_addr: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        for match in set(ADDRESS.findall(row["name"])):
            if re.search(r"\d", match):
                by_addr[match].append(row)
    families = []
    for addr, users in by_addr.items():
        owners = Counter(tokens(u["name"])[0] for u in users if tokens(u["name"]))
        named = [o for o in owners if o not in GENERIC_OWNERS]
        families.append((addr, len(users), owners.most_common(3), bool(named)))
    families.sort(key=lambda item: -item[1])
    return {
        "names_with_address": sum(len(u) for u in by_addr.values()),
        "distinct_addresses": len(by_addr),
        "largest_families": families[:15],
    }


def trailing_address_candidates(rows: list[dict[str, str]]) -> list[tuple[str, str, str]]:
    """Rows ending in a data address where dropping it keeps a unique, owned name."""
    taken = Counter(r["name"] for r in rows)
    candidates = []
    for row in rows:
        if is_seed(row):
            continue
        match = re.search(r"_(?:0x)?([0-9a-f]{6})$", row["name"])
        if not match or not re.search(r"\d", match.group(1)):
            continue
        new = row["name"][: match.start()]
        parts = tokens(new)
        if len(parts) < 3 or parts[0] in GENERIC_OWNERS or new in taken or not IDENT.match(new):
            continue
        candidates.append((row["entry_va"], row["name"], new))
    counts = Counter(new for _, _, new in candidates)
    return [c for c in candidates if counts[c[2]] == 1]


def suffix_report(rows: list[dict[str, str]]) -> list[dict]:
    stems: dict[str, dict[str, list[str]]] = defaultdict(lambda: defaultdict(list))
    for row in rows:
        match = SUFFIX.search(row["name"])
        if match:
            scheme = "letter" if match.group(1) else "digit" if match.group(2) else "word"
            stems[row["name"][: match.start()]][scheme].append(row["name"])
    return [
        {"stem": s, "schemes": {k: len(v) for k, v in d.items()}}
        for s, d in stems.items()
        if len(d) > 1
    ]


def overspecific_report(rows: list[dict[str, str]]) -> list[dict]:
    """Names asserting a game entity that occurs in one row only, with short evidence."""
    entities: set[str] = set()
    for doc in ("docs/game-glossary.md", "docs/game-menus.md"):
        if Path(doc).is_file():
            text = Path(doc).read_text(encoding="utf-8", errors="replace").lower()
            entities |= {w for w in re.findall(r"[a-z]{5,20}", text)}
    common = {t for r in rows for t in tokens(r["name"])}
    counts = Counter(t for r in rows for t in set(tokens(r["name"])))
    entities = {w for w in entities if w in common and counts[w] == 1}
    seen: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        for part in set(tokens(row["name"])):
            if part in entities:
                seen[part].append(row)
    out = []
    for word, users in seen.items():
        if len(users) == 1 and len(users[0]["evidence"]) < 160:
            out.append(
                {
                    "entity": word,
                    "va": users[0]["entry_va"],
                    "name": users[0]["name"],
                    "evidence": users[0]["evidence"],
                }
            )
    return out


def build_report(rows: list[dict[str, str]]) -> dict:
    return {
        "rows": len(rows),
        "seed_rows": sum(1 for r in rows if is_seed(r)),
        "prefix_families": dict(
            sorted(prefix_families(rows).items(), key=lambda kv: -kv[1]["count"])[:60]
        ),
        "synonym_families": synonym_report(rows),
        "verbs": verb_report(rows),
        "addresses": address_report(rows),
        "trailing_address_candidates": len(trailing_address_candidates(rows)),
        "mixed_suffix_stems": suffix_report(rows)[:40],
        "overspecific": overspecific_report(rows)[:60],
    }


def print_report(report: dict) -> None:
    print(f"rows {report['rows']} (seed {report['seed_rows']})")
    print("== prefix families (top, with bands) ==")
    for key, value in list(report["prefix_families"].items())[:40]:
        print(f"  {key:14} {value['count']:5}  {value['bands']}")
    print("== synonym families ==")
    for fam in report["synonym_families"]:
        print(
            f"  {fam['group']}: tokens {fam['token_count']} prefix {fam['prefix_count']} "
            f"glossary {fam['glossary_mentions']}"
        )
    print("== verb sibling inconsistencies ==")
    for verb in report["verbs"]:
        print(f"  {verb['group']}: {verb['sibling_pairs']} sibling stems")
        for ex in verb["examples"][:3]:
            print(f"     {ex['stem']} {ex['verbs']}")
    addr = report["addresses"]
    print(
        f"== addresses == {addr['names_with_address']} names, "
        f"{addr['distinct_addresses']} addresses, "
        f"{report['trailing_address_candidates']} safe trailing-address drops"
    )
    for item in addr["largest_families"][:10]:
        print("  ", item)
    print(
        f"== mixed suffix schemes == {len(report['mixed_suffix_stems'])} stems (first 40 in json)"
    )
    print(f"== over-specific, thin evidence == {len(report['overspecific'])} (first 60)")
    for item in report["overspecific"][:15]:
        print(f"  {item['va']} {item['name']}: {item['evidence'][:100]}")


def plan_rows(rows: list[dict[str, str]]) -> list[tuple[str, str, str, str]]:
    """Mechanical normalisations: (va, old, new, reason_class)."""
    names = {r["name"] for r in rows}
    plan: list[tuple[str, str, str, str]] = []
    reserved: set[str] = set()

    def add(row: dict[str, str], new: str, cls: str) -> None:
        if any(item[0] == row["entry_va"] for item in plan):
            return
        if new != row["name"] and new not in names and new not in reserved and IDENT.match(new):
            reserved.add(new)
            plan.append((row["entry_va"], row["name"], new, cls))

    for row in rows:
        if is_seed(row):
            continue
        name = row["name"]
        parts = name.split("_")
        for old, new, cls in (
            ("obj", "object", "vocab_obj_to_object"),
            ("character", "char", "vocab_character_to_char"),
            ("animation", "anim", "vocab_animation_to_anim"),
        ):
            if len(parts) > 2 and parts[1] == old:
                add(row, "_".join([parts[0], new, *parts[2:]]), cls)
    for va, _old, new in trailing_address_candidates(rows):
        row = next(r for r in rows if r["entry_va"] == va)
        add(row, new, "address_suffix_dropped")
    return plan


REASONS = {
    "vocab_obj_to_object": (
        "same concept as game_object_ (538 prefix rows, obj is its abbreviation)"
    ),
    "vocab_character_to_char": "same concept as game_char_ (153 prefix rows)",
    "vocab_animation_to_anim": (
        "same concept as game_anim_ (53 prefix rows, anim is the majority spelling)"
    ),
    "address_suffix_dropped": "owning subsystem is the name prefix, data address stays in evidence",
}


def apply(plan_path: Path, names_path: Path, renames_path: Path) -> int:
    rows = load(names_path)
    by_va = {r["entry_va"]: r for r in rows}
    taken = {r["name"] for r in rows}
    done = []
    with plan_path.open(newline="", encoding="utf-8") as handle:
        for va, old, new, cls in csv.reader(handle):
            row = by_va.get(va)
            if (
                row is None
                or row["name"] != old
                or new in taken
                or is_seed(row)
                or not IDENT.match(new)
            ):
                print(f"skip {va} {old} -> {new}", file=sys.stderr)
                continue
            taken.discard(old)
            taken.add(new)
            row["name"] = new
            row["evidence"] += f"; renamed T1473 from {old}: {REASONS.get(cls, cls)}"
            done.append((va, old, new, cls))
    with names_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=["entry_va", "name", "confidence", "evidence"], lineterminator="\n"
        )
        writer.writeheader()
        writer.writerows(rows)
    fresh = not renames_path.is_file()
    with renames_path.open("a", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        if fresh:
            writer.writerow(["entry_va", "old", "new", "reason_class"])
        writer.writerows(done)
    print(f"applied {len(done)} renames")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("command", choices=["report", "plan", "apply"])
    parser.add_argument("plan", nargs="?", type=Path)
    parser.add_argument("--names", type=Path, default=NAMES)
    parser.add_argument("--json", type=Path)
    parser.add_argument("--out", type=Path)
    parser.add_argument("--renames", type=Path, default=RENAMES)
    parser.add_argument("--limit", type=int, default=300, help="max rows in a plan")
    args = parser.parse_args(argv)
    rows = load(args.names)
    if args.command == "report":
        report = build_report(rows)
        print_report(report)
        if args.json:
            args.json.parent.mkdir(parents=True, exist_ok=True)
            args.json.write_text(json.dumps(report, indent=1, default=list), encoding="utf-8")
        return 0
    if args.command == "plan":
        plan = plan_rows(rows)[: args.limit]
        out = args.out or Path("/dev/stdout")
        with out.open("w", newline="", encoding="utf-8") as handle:
            csv.writer(handle, lineterminator="\n").writerows(plan)
        print(f"{len(plan)} planned renames", file=sys.stderr)
        return 0
    if args.plan is None:
        parser.error("apply needs PLAN.csv")
    return apply(args.plan, args.names, args.renames)


if __name__ == "__main__":
    raise SystemExit(main())
