# SPDX-License-Identifier: GPL-3.0-or-later
"""Resolve `.XTLID` records to real XDK library function names.

The `.XTLID` section of an Xbox executable is a table of (library function id,
address) pairs the linker emitted. Mapping those ids to names yields **exact**
symbol names with no false positives, which is strictly better than any pattern
matching. For TimeSplitters: Future Perfect it names 297 XDK library functions.

Name data comes from `XboxDev/xtlid`, an independently-built open database. It is
fetched rather than vendored, so this repository carries no third-party data; see
`docs/provenance.md` for why that distinction matters.

The database keys functions by a combined id, `(lib_id << 16) | func_id`, which is
exactly how the two 16-bit fields sit in an `.XTLID` record.
"""

from __future__ import annotations

import re
from collections.abc import Iterable
from dataclasses import dataclass

from tools.xbe.model import XtlidEntry

XTLID_DB_URL = "https://github.com/XboxDev/xtlid/releases/download/v0.1.2/xtlid.xml"

_LIB_RE = re.compile(r'<lib\s+name="([^"]+)"(?:\s+libnames="([^"]*)")?\s*>')
_FUNC_RE = re.compile(r'<func\s+id="(0[xX][0-9a-fA-F]+|\d+)"\s+name="([^"]+)"\s*/?>')


@dataclass(frozen=True)
class XtlidName:
    """One named XDK library function."""

    combined_id: int
    library: str
    name: str

    @property
    def lib_id(self) -> int:
        return self.combined_id >> 16

    @property
    def func_id(self) -> int:
        return self.combined_id & 0xFFFF


def combined_id(entry: XtlidEntry) -> int:
    """The database key for an `.XTLID` record."""
    return (entry.lib_id << 16) | entry.func_id


def parse_xtlid_db(text: str) -> dict[int, XtlidName]:
    """Parse the xtlid.xml database into combined_id -> XtlidName.

    Parsed with regexes rather than an XML parser deliberately: the file is a flat
    machine-generated shape, and this avoids depending on how well-formed a
    third-party download happens to be.
    """
    database: dict[int, XtlidName] = {}
    library = "?"
    for line in text.splitlines():
        lib_match = _LIB_RE.search(line)
        if lib_match:
            library = lib_match.group(1)
            continue
        func_match = _FUNC_RE.search(line)
        if func_match:
            key = int(func_match.group(1), 0)
            database[key] = XtlidName(combined_id=key, library=library, name=func_match.group(2))
    return database


def resolve_xtlid(
    entries: Iterable[XtlidEntry], database: dict[int, XtlidName]
) -> tuple[dict[int, XtlidName], list[XtlidEntry]]:
    """Map each record's address to its name.

    Returns (address -> XtlidName, unresolved records). Addresses are used as the
    key because that is what a disassembler needs.
    """
    resolved: dict[int, XtlidName] = {}
    unresolved: list[XtlidEntry] = []
    for entry in entries:
        found = database.get(combined_id(entry))
        if found is None:
            unresolved.append(entry)
        else:
            resolved[entry.address] = found
    return resolved, unresolved


def to_ghidra_symbols(resolved: dict[int, XtlidName]) -> str:
    """Render resolved names as a two-column `address name` table.

    This is the plainest interchange format a disassembler script can consume, and
    it keeps the naming step independent of any particular tool's project format.
    """
    lines = [
        "# address name  -- generated by tools/xtlid.py from XboxDev/xtlid",
        "# These are exact XDK library names from the executable's own .XTLID",
        "# section. Zero false positives; safe to apply without review.",
    ]
    for address in sorted(resolved):
        entry = resolved[address]
        lines.append(f"{address:#010x} {entry.name}  # {entry.library}")
    return "\n".join(lines) + "\n"
