# SPDX-License-Identifier: GPL-3.0-or-later
"""Merge a task branch into main while holding the shared merge lock (T453).

The lock (`<repo top>/tmp/merge.lock`, resolved from the git common dir) is held for the
whole operation: merge, conflict resolution, audit snapshot, verify and push.

Linked worktrees (T1564). Run from a linked worktree, the helper finds the primary checkout
through the git common dir and runs every step with `git -C <primary>`. The primary must be on
the target branch, clean and without MERGE_HEAD, else exit 2. The branch defaults to the
worktree's own branch, `--branch` names it explicitly (needed for a non task/ name). The merge
event records `via=worktree`, the primary and the worktree path. Nothing is stashed or reset.

Exit codes: 0 ok, 1 usage or git failure, 2 refused (lock timeout, dirty tree, MERGE_HEAD,
wrong branch), 3 unresolvable conflict (merge aborted), 4 verify failed (merge commit left
local and unpushed), 5 push failed, 6 audit snapshot could not be generated or committed
after a real merge (merge commit left local and unpushed, tree restored, same revert hint
as 4).

Audit trail (T1047, design in docs/t1047-merge-audit-findings.md). The task id comes from
the branch (`task/t1047-...` is T1047) and `--release T<n>`, which wins on disagreement. With
one, the helper logs `coord event` records (kind `merge` and `publish`, detail is
space separated key=value tokens) and, right after the merge commit and before verify and
push, commits `docs/audit/T<n>.md` generated from the event log as its own commit
`Audit snapshot T<n> (generated by merge_task)`. Event logging is telemetry: a failure warns
on stderr and never changes the merge outcome. A failed snapshot is different, it is part
of the published tree, so it stops the push with exit 6. `--dry-run` writes and logs nothing.
"""

import argparse
import fcntl
import json
import os
import re
import shlex
import subprocess
import sys
import time
from pathlib import Path
from typing import TextIO

AUTO_RESOLVE_FILES = {"docs/tasks.md", "context.md"}
OPEN_STUB = re.compile(r"^- \[ \] \*\*(T\d+)\.")
DONE_ENTRY = re.compile(r"^- \[x\] \*\*(T\d+)\.")
BRANCH_TASK = re.compile(r"task/t(\d+)(?:[-_/].*)?", re.IGNORECASE)
TASK_ID = re.compile(r"T\d+")
COORD_PYTHON = sys.executable
COORD_MODULE = "tools.agents.coord"
EVENT_TIMEOUT = 30
DEFAULT_EVENT_OWNER = "merge_task"
AUDIT_DIR = Path("docs/audit")
STALE_CAVEAT = (
    "Stale time is a lower bound: heartbeats are not logged, so a worker that went quiet and "
    "then released, without anyone liberating its claim, shows no stale time "
    "(docs/t1044-coord-audit-findings.md)."
)


def say(message: str) -> None:
    print(f"merge_task: {message}", flush=True)


# Set by main() when the helper runs inside a linked worktree (T1564). Every git call then
# targets the primary checkout with `git -C`, so the main-branch steps never touch the worktree.
PRIMARY: Path | None = None


def git(*args: str, check: bool = False) -> subprocess.CompletedProcess:
    prefix = ["-C", str(PRIMARY)] if PRIMARY else []
    return subprocess.run(["git", *prefix, *args], capture_output=True, text=True, check=check)


def linked_worktree_primary() -> Path | None:
    """Primary checkout when the cwd is in a linked worktree, None in the primary checkout.

    A linked worktree has a private git dir (`<common>/worktrees/<name>`) apart from the
    common dir. The primary checkout is the parent of the common dir.
    """
    own = subprocess.run(
        ["git", "rev-parse", "--path-format=absolute", "--git-dir", "--git-common-dir"],
        capture_output=True,
        text=True,
    )
    if own.returncode != 0:
        return None
    git_dir, common = (Path(line).resolve() for line in own.stdout.split("\n")[:2])
    if git_dir == common:
        return None
    return common.parent


def common_dir() -> Path:
    return Path(
        git("rev-parse", "--path-format=absolute", "--git-common-dir", check=True).stdout.strip()
    )


def lock_path() -> Path:
    return common_dir().parent / "tmp" / "merge.lock"


def acquire_lock(path: Path, timeout: float) -> TextIO | None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle = open(path, "a+")
    deadline = time.monotonic() + timeout
    while True:
        try:
            fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
            return handle
        except OSError:
            if time.monotonic() >= deadline:
                handle.close()
                return None
            time.sleep(0.1)


def merge_head_exists() -> bool:
    return git("rev-parse", "-q", "--verify", "MERGE_HEAD").returncode == 0


def split_entries(lines: list[str]) -> list[list[str]]:
    """Group lines into entries: a top-level `- ` line plus its indented continuation."""
    entries: list[list[str]] = []
    for line in lines:
        if entries and line.startswith((" ", "\t")) and line.strip():
            entries[-1].append(line)
        else:
            entries.append([line])
    return entries


def drop_stale_stubs(mine: list[str], theirs: list[str]) -> tuple[list[str], list[str]]:
    def done_ids(lines: list[str]) -> set[str]:
        return {m.group(1) for line in lines if (m := DONE_ENTRY.match(line))}

    def filtered(lines: list[str], other_done: set[str]) -> list[str]:
        kept: list[str] = []
        for entry in split_entries(lines):
            stub = OPEN_STUB.match(entry[0])
            if stub and stub.group(1) in other_done:
                continue
            kept.extend(entry)
        return kept

    return filtered(mine, done_ids(theirs)), filtered(theirs, done_ids(mine))


def resolve_text(text: str) -> str | None:
    """Resolve diff3 conflict hunks that are pure both-sides adds. None if any is not."""
    out: list[str] = []
    state = "text"
    mine: list[str] = []
    base: list[str] = []
    theirs: list[str] = []
    for line in text.splitlines(keepends=True):
        if state == "text":
            if line.startswith("<<<<<<< "):
                state, mine, base, theirs = "mine", [], [], []
            else:
                out.append(line)
        elif state == "mine":
            if line.startswith("||||||| "):
                state = "base"
            elif line.startswith("======="):
                return None  # not diff3 style
            else:
                mine.append(line)
        elif state == "base":
            if line.startswith("======="):
                state = "theirs"
            else:
                base.append(line)
        elif line.startswith(">>>>>>> "):
            if any(item.strip() for item in base):
                return None
            for chunk in (mine, theirs):
                if chunk and not chunk[-1].endswith("\n"):
                    chunk[-1] += "\n"
            kept_mine, kept_theirs = drop_stale_stubs(mine, theirs)
            out.extend(kept_mine + kept_theirs)
            state = "text"
        else:
            theirs.append(line)
    if state != "text":
        return None
    result = "".join(out)
    if re.search(r"^(<<<<<<< |=======$|>>>>>>> |\|\|\|\|\|\|\| )", result, re.M):
        return None
    return result


def conflicted_files() -> list[str]:
    return git("diff", "--name-only", "--diff-filter=U").stdout.split()


def try_resolve(files: list[str]) -> bool:
    if not files or any(name not in AUTO_RESOLVE_FILES for name in files):
        return False
    resolved: dict[str, str] = {}
    for name in files:
        # Re-create the diff3 view so the base section is available.
        checkout = git("checkout", "--conflict=diff3", "--", name)
        if checkout.returncode != 0:
            return False
        text = (repository_root() / name).read_text()
        new_text = resolve_text(text)
        if new_text is None:
            return False
        resolved[name] = new_text
    for name, new_text in resolved.items():
        (repository_root() / name).write_text(new_text)
        if git("add", "--", name).returncode != 0:
            return False
    return True


def abort_merge() -> None:
    if merge_head_exists():
        git("merge", "--abort")


def run_release(task: str, owner: str) -> int:
    root = Path(__file__).resolve().parents[2]
    env = {**os.environ, "PYTHONPATH": str(root)}
    result = subprocess.run(
        [sys.executable, "-m", "tools.agents.coord", "release", task, "--owner", owner],
        env=env,
        capture_output=True,
        text=True,
    )
    detail = f"{result.stdout.strip()} {result.stderr.strip()}".strip()
    say(f"release {task}: exit {result.returncode} {detail}")
    return result.returncode


def repository_root() -> Path:
    return Path(git("rev-parse", "--show-toplevel", check=True).stdout.strip())


def required_lint_command() -> str:
    ruff = shlex.quote(str(repository_root() / ".venv" / "bin" / "ruff"))
    return f"{ruff} check . && {ruff} format --check ."


def required_anchors_command() -> str:
    """T887: mutation anchors must match their source once (0.2 s, no build)."""
    python = shlex.quote(str(repository_root() / ".venv" / "bin" / "python"))
    return f"{python} -m pytest -q tests/test_mutation_anchors.py"


def warn(message: str) -> None:
    print(f"merge_task: warning: {message}", file=sys.stderr, flush=True)


def resolve_task(branch: str, release: str | None) -> tuple[str | None, str | None]:
    """Task id from the branch name and `--release`. `--release` is the authority."""
    from_branch = BRANCH_TASK.fullmatch(branch)
    branch_task = f"T{int(from_branch[1])}" if from_branch else None
    release_task = release if release and TASK_ID.fullmatch(release) else None
    if release_task and branch_task and release_task != branch_task:
        return release_task, (
            f"branch {branch} names {branch_task} but --release names {release_task}, "
            f"using {release_task}"
        )
    return release_task or branch_task, None


def detail_text(fields: dict[str, object]) -> str:
    """`key=value` tokens, values shell quoted so `parse_detail` can read them back."""
    return " ".join(f"{key}={shlex.quote(str(value))}" for key, value in fields.items())


def parse_detail(detail: object) -> dict[str, str]:
    if not isinstance(detail, str):
        return {}
    try:
        tokens = shlex.split(detail)
    except ValueError:
        return {}
    return {key: value for key, _, value in (token.partition("=") for token in tokens) if key}


class Trail:
    """Audit telemetry of one merge_task run. Never changes the outcome of the merge."""

    def __init__(self, task: str | None, owner: str | None, enabled: bool) -> None:
        self.task = task
        self.owner = owner or DEFAULT_EVENT_OWNER
        self.enabled = enabled and task is not None

    def event(self, kind: str, **fields: object) -> None:
        """Log one `coord event`. A failure warns on stderr and is otherwise ignored."""
        if not self.enabled:
            return
        root = Path(__file__).resolve().parents[2]
        command = [COORD_PYTHON, "-m", COORD_MODULE, "event", str(self.task)]
        command += ["--owner", self.owner, "--kind", kind, "--detail", detail_text(fields)]
        try:
            result = subprocess.run(
                command,
                env={**os.environ, "PYTHONPATH": str(root)},
                capture_output=True,
                text=True,
                timeout=EVENT_TIMEOUT,
            )
        except (OSError, subprocess.SubprocessError) as error:
            warn(f"audit event {kind} for {self.task} not logged: {error}")
            return
        if result.returncode != 0:
            reason = result.stderr.strip() or result.stdout.strip()
            warn(
                f"audit event {kind} for {self.task} not logged: exit {result.returncode} {reason}"
            )

    def fail(self, code: int, stage: str, **fields: object) -> int:
        """Log the failed attempt as a `merge` event with its exit code and return the code."""
        self.event("merge", stage=stage, result="fail", exit=code, **fields)
        return code


def clock(seconds: int) -> str:
    return f"{seconds // 3600}h{seconds % 3600 // 60:02d}m{seconds % 60:02d}s"


def stamp(ts: float) -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime(ts))


def cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def event_detail(detail: object) -> str:
    if detail is None:
        return ""
    if isinstance(detail, dict):
        return " ".join(f"{key}={json.dumps(value)}" for key, value in detail.items())
    return str(detail)


def task_title(task: str, ledger: str) -> str:
    match = re.search(rf"^- \[.\] \*\*{task}\. (.+?)\*\*", ledger, re.MULTILINE)
    return match[1].rstrip(".") if match else ""


def has_lifecycle_events(events: list[dict], task: str) -> bool:
    """True when the task has any event besides merge_task's own `merge` and `publish`."""
    return any(e.get("task") == task and e["kind"] not in ("merge", "publish") for e in events)


def render_snapshot(task: str, title: str, events: list[dict]) -> str:
    """Deterministic markdown of the important events of `task`. Same events, same bytes.

    Time is audited up to the last recorded event (never the wall clock), so a claim that is
    still open at merge time does not change the file on a rerun.
    """
    from tools.agents import coord

    mine = sorted((e for e in events if e.get("task") == task), key=lambda e: e["ts"])
    audit = coord.audit_task(events, task, int(mine[-1]["ts"]), {})
    important = [e for e in mine if e["kind"] != "progress"]
    owners = [o for o in audit["owners"] if o != DEFAULT_EVENT_OWNER]
    merges = [(e, parse_detail(e.get("detail"))) for e in mine if e["kind"] == "merge"]
    merge_shas = [d["sha"] for _, d in merges if d.get("stage") == "created" and d.get("sha")]
    failed_merges = sum(1 for _, d in merges if d.get("result") == "fail")
    publish_shas = [
        d["sha"]
        for d in (parse_detail(e.get("detail")) for e in mine if e["kind"] == "publish")
        if d.get("sha")
    ]
    progress = audit["progress"]
    blocks = audit["blocks"]
    held = ", ".join(f"{o} {clock(s)}" for o, s in sorted(audit["held_by_owner"].items()))

    def shas(values: list[str]) -> str:
        unique = list(dict.fromkeys(values))
        return ", ".join(f"`{v[:12]}`" for v in unique) or "none yet"

    final = "none reported"
    if progress["last_percent"] is not None:
        final = f"{progress['last_percent']}% ({progress['last_percent_kind'] or 'unspecified'})"
        final += f" {progress['last_status']}" if progress["last_status"] else ""
    blocked = f"{blocks['count']}"
    if blocks["count"]:
        blocked += f" ({clock(blocks['seconds'])}{', still open' if blocks['open'] else ''})"
    lines = [
        f"# Audit {task}" + (f": {title}" if title else ""),
        "",
        "Generated by `python -m tools.agents.merge_task` from the coord event log, do not edit.",
        "The next merge of this task regenerates it. Times are UTC. The state is that of the last",
        "event recorded before this snapshot commit, so the verify and publish result of the merge",
        "that wrote it appear in the next snapshot, and the event log is the full record.",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Milestone | {cell(audit['milestone'] or 'unknown')} |",
        f"| Owners ever | {cell(', '.join(owners) or 'none')} |",
        f"| Claims | {audit['claims']} |",
        f"| Handoffs | {audit['handoffs']} |",
        f"| Replacements (previous holder liberated as stale) | {audit['replacements']} |",
        f"| Stale liberations | {audit['stale_liberations']} |",
        f"| Held | {clock(audit['held_seconds'])} |",
        f"| Active | {clock(audit['active_seconds'])} |",
        f"| Stale (lower bound) | {clock(audit['stale_seconds'])} |",
        f"| Held by owner | {cell(held or 'none')} |",
        f"| Blocks | {blocked} |",
        f"| Final progress | {cell(final)} |",
        f"| Merge SHAs | {shas(merge_shas)} |",
        f"| Failed merge attempts | {failed_merges} |",
        f"| Publish SHAs | {shas(publish_shas)} |",
        f"| Events recorded | {len(mine)} (progress updates not listed: {progress['updates']}) |",
        "",
        STALE_CAVEAT,
        "Held time of a claim still open at the last event ends at that event.",
        "",
        "## Important events (UTC)",
        "",
        "| Time | Owner | Kind | Detail |",
        "|---|---|---|---|",
    ]
    for event in important:
        owner = cell(event.get("owner") or "")
        detail = cell(event_detail(event.get("detail")))
        lines.append(f"| {stamp(event['ts'])} | {owner} | {event['kind']} | {detail} |")
    return "\n".join(lines) + "\n"


def snapshot_relative(task: str) -> str:
    return (AUDIT_DIR / f"{task}.md").as_posix()


def snapshot_plan(task: str) -> str:
    """Dry-run answer: would a snapshot be generated for this task."""
    from tools.agents import coord

    if has_lifecycle_events(coord.read_events(), task):
        return f"would generate {snapshot_relative(task)} as its own commit before verify"
    return f"no audit events for {task}, snapshot would be skipped"


def discard_snapshot(relative: str) -> None:
    """Undo a half written snapshot so the tree stays clean for a retry."""
    git("reset", "-q", "HEAD", "--", relative)
    if git("cat-file", "-e", f"HEAD:{relative}").returncode == 0:
        git("checkout", "HEAD", "--", relative)
    else:
        try:
            (repository_root() / relative).unlink(missing_ok=True)
        except OSError:
            pass  # nothing was written, for example a file stands where the directory belongs


def commit_snapshot(task: str) -> tuple[str, str | None]:
    """Generate and commit docs/audit/T<n>.md. Returns (outcome, commit): written, unchanged
    or skipped. Raises RuntimeError when the snapshot cannot be generated or committed."""
    relative = snapshot_relative(task)
    try:
        from tools.agents import coord

        events = coord.read_events()
        if not has_lifecycle_events(events, task):
            return "skipped", None
        root = repository_root()
        ledger = root / "docs" / "tasks.md"
        title = task_title(task, ledger.read_text() if ledger.exists() else "")
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(render_snapshot(task, title, events).encode())
    except Exception as error:  # generation must never crash the helper, it maps to exit 6
        discard_snapshot(relative)
        raise RuntimeError(f"cannot generate {relative}: {error}") from error
    if not git("status", "--porcelain", "--", relative).stdout.strip():
        return "unchanged", None
    message = f"Audit snapshot {task} (generated by merge_task)"
    added = git("add", "--", relative)
    committed = (
        git("commit", "-q", "-m", message, "--", relative) if added.returncode == 0 else added
    )
    if committed.returncode != 0:
        discard_snapshot(relative)
        raise RuntimeError(f"cannot commit {relative}: {committed.stderr.strip()}")
    return "written", git("rev-parse", "HEAD").stdout.strip()


def revert_hint(head: str, snapshot: str | None) -> str:
    if snapshot:
        return f"git revert --no-edit {snapshot[:12]} && git revert -m 1 {head}"
    return f"git revert -m 1 {head}  (or: git revert -m 1 HEAD)"


def verify_summary(args: argparse.Namespace) -> str:
    summary = "lint,anchors"
    return f"{summary},custom:{args.verify[:60]}" if args.verify else summary


def worktree_fields() -> dict[str, str]:
    if not PRIMARY:
        return {}
    return {"via": "worktree", "primary": str(PRIMARY), "worktree": str(Path.cwd())}


def where() -> str:
    return f"primary checkout {PRIMARY}" if PRIMARY else "checkout"


def run_locked(args: argparse.Namespace, trail: Trail) -> int:
    branch = git("rev-parse", "--abbrev-ref", "HEAD").stdout.strip()
    if branch != args.target:
        reason = f"{where()} is on branch {branch!r}, expected {args.target!r}"
        say(f"refused: {reason}")
        return trail.fail(2, "refused", reason=reason)
    if merge_head_exists():
        say(f"refused: MERGE_HEAD exists in {where()}, a merge is already in progress")
        return trail.fail(2, "refused", reason="MERGE_HEAD exists")
    if git("status", "--porcelain", "--untracked-files=no").stdout.strip():
        say(f"refused: working tree of {where()} is dirty")
        return trail.fail(2, "refused", reason="working tree is dirty")
    if git("rev-parse", "--verify", "-q", args.branch).returncode != 0:
        say(f"branch {args.branch} not found")
        return trail.fail(1, "branch", reason="branch not found")
    say(f"clean tree on {args.target}, merging {args.branch}")

    message = args.message or f"Merge {args.branch}"
    merge_args = ["-c", "merge.conflictStyle=diff3", "merge", "--no-ff", args.branch]
    merge_args += ["--no-commit"] if args.dry_run else ["-m", message]
    merged = git(*merge_args)
    already_merged = merged.returncode == 0 and "Already up to date" in merged.stdout
    if already_merged:
        say("already merged locally; continuing verification and publication")
    if merged.returncode != 0:
        files = conflicted_files()
        if not files and not merge_head_exists():
            reason = merged.stderr.strip() or merged.stdout.strip()
            say(f"git merge failed: {reason}")
            return trail.fail(1, "merge", reason=reason[:200])
        say(f"conflict in: {' '.join(files)}")
        if not try_resolve(files):
            abort_merge()
            say(f"aborted merge, unresolvable conflict files: {' '.join(files)}")
            return trail.fail(3, "conflict", files=" ".join(files))
        say("conflict auto-resolved by keeping both sides")
        if not args.dry_run:
            commit = git("commit", "--no-edit")
            if commit.returncode != 0:
                abort_merge()
                say(f"commit failed: {commit.stderr.strip()}")
                return trail.fail(1, "commit", reason=commit.stderr.strip()[:200])
    if args.dry_run:
        abort_merge()
        say("dry run: merge would succeed, aborted, nothing changed")
        if trail.task:
            try:
                say(f"dry run: audit snapshot for {trail.task}: {snapshot_plan(trail.task)}")
            except Exception as error:  # a plan is advice, never a failure
                say(f"dry run: audit snapshot for {trail.task}: cannot tell ({error})")
        return 0
    head = git("rev-parse", "--short", "HEAD").stdout.strip()
    merge_sha = git("rev-parse", "HEAD").stdout.strip()
    say(f"existing local HEAD {head}" if already_merged else f"merge commit {head} created locally")
    trail.event(
        "merge",
        stage="created",
        sha=merge_sha,
        branch=args.branch,
        verify=verify_summary(args),
        existing="true" if already_merged else "false",
        **worktree_fields(),
    )

    snapshot = None
    if trail.task:
        try:
            outcome, snapshot = commit_snapshot(trail.task)
        except RuntimeError as error:
            say(f"audit snapshot FAILED: {error}, merge commit {head} left local and unpushed")
            say(f"to undo it run: {revert_hint(head, None)}")
            return trail.fail(6, "snapshot", merge=merge_sha, reason=str(error)[:200])
        if outcome == "skipped":
            say(f"no audit events for {trail.task}, snapshot skipped")
        elif outcome == "unchanged":
            say(f"audit snapshot {snapshot_relative(trail.task)} unchanged")
        else:
            say(f"audit snapshot committed {str(snapshot)[:10]}: {snapshot_relative(trail.task)}")

    verify_commands = [required_lint_command(), required_anchors_command()]
    if args.verify:
        verify_commands.append(args.verify)
    for command in verify_commands:
        say(f"verify: {command}")
        if subprocess.run(command, shell=True, cwd=PRIMARY).returncode != 0:
            say(f"verify FAILED, merge commit {head} left local and unpushed")
            say(f"to undo it run: {revert_hint(head, snapshot)}")
            return trail.fail(4, "verify", merge=merge_sha, command=command[:200])
    say("verify passed")
    trail.event("merge", stage="verify", result="pass", merge=merge_sha)

    if args.no_push:
        say(f"merged locally, not pushed (merge commit {head})")
        return 0

    pushed = git("push", "origin", args.target)
    if pushed.returncode != 0:
        say(f"push failed: {pushed.stderr.strip()}")
        return trail.fail(5, "push", merge=merge_sha, reason=pushed.stderr.strip()[:200])
    say(f"pushed {args.target} to origin")
    trail.event(
        "publish",
        stage="push",
        result="pass",
        sha=git("rev-parse", "HEAD").stdout.strip(),
        merge=merge_sha,
    )
    if args.release:
        if not args.owner:
            say("--release needs --owner")
            return trail.fail(1, "release", merge=merge_sha, reason="--release needs --owner")
        if run_release(args.release, args.owner) != 0:
            return trail.fail(1, "release", merge=merge_sha, reason="coord release failed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("branch", nargs="?", help="branch to merge")
    parser.add_argument(
        "--branch",
        dest="branch_option",
        help="branch to merge, explicit form (needed to merge a non task/ branch from a "
        "linked worktree, which otherwise defaults to the worktree's own branch)",
    )
    parser.add_argument(
        "--target", default="main", help="branch that must be checked out (default main)"
    )
    parser.add_argument("-m", "--message", help="merge commit message")
    parser.add_argument("--verify", help="shell command run after merge, before push")
    parser.add_argument("--release", metavar="TASK", help="coord release this task id after push")
    parser.add_argument("--owner", help="coord owner for --release")
    parser.add_argument(
        "--lock-timeout", type=float, default=600, help="seconds to wait for the lock"
    )
    parser.add_argument("--dry-run", action="store_true", help="report only, change nothing")
    parser.add_argument(
        "--no-push",
        action="store_true",
        help="merge and verify under the lock but leave the push to the caller",
    )
    args = parser.parse_args()
    global PRIMARY
    PRIMARY = linked_worktree_primary()
    if args.branch and args.branch_option and args.branch != args.branch_option:
        parser.error("branch given twice and they differ")
    args.branch = args.branch_option or args.branch
    if PRIMARY:
        if not args.branch:
            args.branch = subprocess.run(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"], capture_output=True, text=True
            ).stdout.strip()
        elif not args.branch_option and not BRANCH_TASK.fullmatch(args.branch):
            parser.error("from a linked worktree a non task/ branch needs the explicit --branch")
        say(f"linked worktree {Path.cwd()}: operating on primary checkout {PRIMARY}")
    elif not args.branch:
        parser.error("branch is required")
    if args.no_push and args.release:
        parser.error("--release belongs after a push, drop it when using --no-push")

    task, mismatch = resolve_task(args.branch, args.release)
    if mismatch:
        say(f"task id mismatch: {mismatch}")
    if task is None:
        say("no task id in the branch name or --release, audit events and snapshot skipped")
    trail = Trail(task, args.owner, enabled=not args.dry_run)
    path = lock_path()
    handle = acquire_lock(path, args.lock_timeout)
    if handle is None:
        say(f"refused: could not take {path} within {args.lock_timeout}s")
        return trail.fail(2, "lock", reason=f"no lock within {args.lock_timeout}s")
    say(f"lock held: {path}")
    try:
        return run_locked(args, trail)
    finally:
        handle.close()
        say("lock released")


if __name__ == "__main__":
    sys.exit(main())
