/* SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Translates the generated, whole-executable XDK surface measurement into the
 * d3d8_surface_entry table that d3d8_hle_init expects.
 *
 * d3d8_hle_init takes its table by injection specifically so the dispatch
 * module does not depend on src/xbox/xdk_surface.c, which is generated by
 * tools/gen_d3d8_surface.py and gitignored, so a fresh clone does not have
 * it. Something still has to do the actual translation from the measured
 * surface to the injected shape, and that is this module.
 *
 * The two row shapes are not layout-compatible: xdk_surface_entry carries an
 * extra `section` field that d3d8_surface_entry does not, so casting one
 * array to the other reads every field after `address` out of alignment and
 * corrupts it silently. The measured surface also spans seven sections
 * (D3D, XNET, DSOUND, XONLINE, XGRPH, XPP, XMV), and only D3D belongs to the
 * graphics boundary this module feeds. So this adapter filters by section
 * and copies field by field rather than casting or reinterpreting.
 *
 * The row type below mirrors xdk_surface_entry rather than including
 * src/xbox/xdk_surface.h. Including that header would make this module, and
 * everything that links it, depend on the generated file again, defeating
 * the whole point of the injection in d3d8_hle_init: this module has to
 * build and be fully testable in a fresh clone where that file does not
 * exist yet. Taking the array as a `const d3d8_xdk_row *` parameter means
 * the ONLY place that ever has to name the generated `xdk_surface` symbol is
 * the caller that already has it in scope, not this module.
 */
#ifndef TSFP_GPU_D3D8_SURFACE_ADAPTER_H
#define TSFP_GPU_D3D8_SURFACE_ADAPTER_H

#include <stdbool.h>
#include <stddef.h>

#include "d3d8_hle.h"

/* Mirrors xdk_surface_entry from the generated src/xbox/xdk_surface.c, declared
 * locally so this module compiles in a fresh clone where that file has not been
 * generated. Keep in sync with src/xbox/xdk_surface.h. */
typedef struct {
    uint32_t address;
    const char *section;
    const char *name;
    uint32_t sites;
} d3d8_xdk_row;

/**
 * Translate the rows of `source` whose section matches `section` into freshly
 * allocated d3d8_surface_entry rows.
 *
 * Returns NULL and sets *out_count to 0 on a bad argument or if no row matches.
 * The caller owns the result and frees it with free(). `name` pointers are
 * borrowed from `source`, so `source` must outlive the returned table and
 * whatever is initialised from it.
 */
d3d8_surface_entry *d3d8_surface_select(const d3d8_xdk_row *source, size_t count,
                                        const char *section, size_t *out_count);

/**
 * Translate and hand straight to d3d8_hle_init. Returns false if nothing matched
 * or init failed. Frees its own temporary on every path.
 */
bool d3d8_surface_adopt(const d3d8_xdk_row *source, size_t count, const char *section);

/** The section name for the graphics boundary. */
#define D3D8_SECTION_D3D "D3D"

#endif /* TSFP_GPU_D3D8_SURFACE_ADAPTER_H */
